Repository paritytech/polkadot, pull requests merged in 2018-12, with the labels that each got.

#50 Authorship works again
  Cargo.lock
  availability-store/Cargo.toml
  availability-store/src/lib.rs
  cli/src/lib.rs
  consensus/Cargo.toml
  consensus/src/attestation_service.rs
  consensus/src/dynamic_inclusion.rs
  consensus/src/lib.rs
  consensus/src/service.rs
  primitives/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/Cargo.toml
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
Labels: A8-looksgood

#55 wait less time for parachain candidates before releasing a block
  service/src/lib.rs
Labels: A2-insubstantial

#58 Rename Id to ParaId in decl_{module,storage} (exported metadata type)
  runtime/src/parachains.rs
Labels: A0-pleasereview

#57 Update to latest substrate
  Cargo.lock
  consensus/Cargo.toml
  consensus/src/error.rs
  consensus/src/lib.rs
  network/src/router.rs
  parachain/tests/res/adder.wasm
  runtime/src/parachains.rs
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  service/src/chain_spec.rs
  service/src/lib.rs
  test-parachains/adder/wasm/src/lib.rs
Labels: A8-looksgood

#59 ensure all spawned futures are exit-guarded
  collator/src/lib.rs
  consensus/src/attestation_service.rs
  network/src/consensus.rs
  network/src/router.rs
  service/src/lib.rs
Labels: A8-looksgood
