Repository paritytech/polkadot, pull requests merged in 2018-08, with the labels that each got.

#3 fix interval logic
  Cargo.lock
  consensus/src/service.rs
Labels: A3-inprogress

#6 More generic extrinsic pool
  Cargo.lock
  consensus/src/lib.rs
  consensus/src/service.rs
  network/src/lib.rs
  service/Cargo.toml
  service/src/lib.rs
  transaction-pool/src/error.rs
  transaction-pool/src/lib.rs
Labels: A0-pleasereview

#7 Forward-port of various testnet fixes
  Cargo.lock
  api/Cargo.toml
  api/src/full.rs
  api/src/lib.rs
  consensus/src/offline_tracker.rs
  consensus/src/service.rs
  primitives/src/lib.rs
  runtime/src/lib.rs
  runtime/src/utils.rs
Labels: A8-backport

#11 Upgrade to Substrate#629
  Cargo.lock
  api/src/full.rs
  collator/Cargo.toml
  consensus/src/lib.rs
  consensus/src/service.rs
  parachain/tests/res/adder.wasm
  runtime/Cargo.toml
  runtime/src/checked_block.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/utils.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/Cargo.toml
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  scripts/init.sh
  service/src/chain_spec.rs
Labels: A0-pleasereview
