Repository paritytech/polkadot, pull requests merged in 2019-09, with the labels that each got.

#411 Update substrate master
  Cargo.lock
  executor/src/lib.rs
  runtime/src/claims.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/slots.rs
  service/src/chain_spec.rs
Labels: A0-pleasereview

#415 Backport updates of substrate
  Cargo.lock
  Cargo.toml
  availability-store/src/lib.rs
  cli/src/lib.rs
  collator/Cargo.toml
  collator/src/lib.rs
  erasure-coding/src/lib.rs
  executor/src/lib.rs
  network/Cargo.toml
  network/src/gossip.rs
  network/src/gossip/attestation.rs
  network/src/gossip/message_routing.rs
  network/src/lib.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  primitives/src/parachain.rs
  runtime/src/claims.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/slots.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  src/main.rs
  test-parachains/adder/collator/src/main.rs
  validation/Cargo.toml
  validation/src/attestation_service.rs
  validation/src/collation.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: A0-pleasereview

#412 Disable merge test enable kusama nightly staging test
  .gitlab-ci.yml
  scripts/gitlab/check_merge_conflict.sh
Labels: A0-pleasereview, M1-ci

#418 Forward ported version bump
  runtime/src/lib.rs
  runtime/src/parachains.rs
Labels: A0-pleasereview, A2-insubstantial

#431 Substrate.from()
  Cargo.lock
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  runtime/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/adder/collator/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial

#315 Crowdfund parachain deposit
  runtime/src/crowdfund.rs
  runtime/src/lib.rs
  runtime/src/slots.rs
Labels: A0-pleasereview

#441 Switch to `wasm-builder` 1.0.7
  runtime/Cargo.toml
  runtime/build.rs
  test-parachains/adder/Cargo.toml
  test-parachains/adder/build.rs
  test-parachains/adder/src/lib.rs
  test-parachains/halt/Cargo.toml
  test-parachains/halt/build.rs
  test-parachains/halt/src/lib.rs
Labels: A0-pleasereview

#442 Update substrate
  Cargo.lock
  collator/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/parachains.rs
  service/src/chain_spec.rs
  service/src/lib.rs
  test-parachains/adder/build.rs
  validation/Cargo.toml
Labels: A8-looksgood

#443 Update to lastest Substrate master
  Cargo.lock
  collator/src/lib.rs
  runtime/src/attestations.rs
  runtime/src/claims.rs
  runtime/src/crowdfund.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/slots.rs
  service/src/lib.rs
Labels: A0-pleasereview

#444 Add authority discovery module
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/lib.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
Labels: A0-pleasereview, M4-core

#449 Add kusama CC2 spec
  service/res/kusama.json
Labels: A0-pleasereview, A3-inprogress

#453 Update Readme for CC2
  README.adoc
Labels: A0-pleasereview, A2-insubstantial, F5-documentation

#450 docs: add security policy
  SECURITY.md
Labels: A0-pleasereview, A2-insubstantial, M3-docs
