Repository paritytech/polkadot, pull requests merged in 2019-02, with the labels that each got.

#120 Update to latest substrate
  Cargo.lock
  availability-store/Cargo.toml
  collator/Cargo.toml
  consensus/Cargo.toml
  consensus/src/lib.rs
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  src/main.rs
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/adder/collator/src/main.rs
Labels: A8-looksgood

#122 Use libp2p-kad 0.3.2
  Cargo.lock
Labels: A2-insubstantial

#127 Bump to 0.3.12
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  service/Cargo.toml
Labels: A8-backport

#125 Cleaning up dependencies
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  build.rs
  cli/Cargo.toml
  consensus/Cargo.toml
  network/Cargo.toml
  primitives/Cargo.toml
  runtime/Cargo.toml
  runtime/wasm/Cargo.lock
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  service/Cargo.toml
  src/main.rs
  test-parachains/adder/collator/Cargo.toml
  test-parachains/adder/collator/src/main.rs
Labels: A8-looksgood

#130 update to latest substrate - protocol API update
  Cargo.lock
  collator/src/lib.rs
  network/src/consensus.rs
  network/src/lib.rs
  network/src/router.rs
Labels: A8-looksgood

#136 add a manually curated grandpa module
  runtime/src/curated_grandpa.rs
  runtime/src/lib.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
Labels: A0-pleasereview

#137 Update to latest master
  Cargo.lock
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  service/src/chain_spec.rs
Labels: A0-pleasereview

#141 update to latest substrate
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  service/src/chain_spec.rs
  service/src/lib.rs
Labels: A0-pleasereview

#117 Interchain message-passing
  Cargo.lock
  consensus/src/attestation_service.rs
  consensus/src/collation.rs
  consensus/src/lib.rs
  consensus/src/shared_table/mod.rs
  network/Cargo.toml
  network/src/consensus.rs
  network/src/lib.rs
  network/src/router.rs
  network/src/tests/consensus.rs
  network/src/tests/mod.rs
  parachain/src/lib.rs
  parachain/src/wasm_api.rs
  parachain/tests/adder.rs
  parachain/tests/res/adder.wasm
  primitives/src/parachain.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  service/src/lib.rs
  test-parachains/adder/collator/src/main.rs
  test-parachains/adder/src/lib.rs
  test-parachains/adder/wasm/Cargo.toml
  test-parachains/adder/wasm/src/lib.rs
  test-parachains/build.sh
Labels: A0-pleasereview

#143 some erasure-coding tweaks
  erasure-coding/src/lib.rs
Labels: A0-pleasereview

#144 define Id type in polkadot-parachain and depend on that in primitives.
  Cargo.lock
  consensus/src/collation.rs
  parachain/Cargo.toml
  parachain/src/lib.rs
  parachain/src/wasm_api.rs
  parachain/src/wasm_executor.rs
  parachain/tests/adder.rs
  parachain/tests/res/adder.wasm
  primitives/Cargo.toml
  primitives/src/lib.rs
  primitives/src/parachain.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
Labels: A0-pleasereview

#142 update substrate
  Cargo.lock
  runtime/src/lib.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
Labels: A8-looksgood

#151 Rename polkadot-consensus -> polkadot-validation
  .gitignore
  Cargo.lock
  Cargo.toml
  network/Cargo.toml
  network/src/lib.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  service/Cargo.toml
  service/src/lib.rs
  validation/Cargo.toml
  validation/README.adoc
  validation/src/attestation_service.rs
  validation/src/collation.rs
  validation/src/dynamic_inclusion.rs
  validation/src/error.rs
  validation/src/evaluation.rs
  validation/src/lib.rs
  validation/src/shared_table/includable.rs
  validation/src/shared_table/mod.rs
Labels: A8-looksgood

#154 Remove unused wasm files
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.compact.wasm
  demo/runtime/wasm/target/wasm32-unknown-unknown/release/demo_runtime.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  polkadot/runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
Labels: A2-insubstantial

#155 Egress queue validation in runtime
  .gitignore
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/parachains.rs
Labels: A8-looksgood

#146 updating v0.3 to use substrate v0.10
  Cargo.lock
  availability-store/Cargo.toml
  cli/Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  collator/src/lib.rs
  consensus/Cargo.toml
  consensus/src/attestation_service.rs
  consensus/src/lib.rs
  executor/Cargo.toml
  network/Cargo.toml
  network/src/consensus.rs
  network/src/lib.rs
  network/src/router.rs
  primitives/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/wasm/Cargo.toml
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  src/main.rs
  statement-table/Cargo.toml
  test-parachains/adder/collator/Cargo.toml
  test-parachains/adder/collator/src/main.rs
Labels: A8-looksgood

#153 ci: add check:merge:conflict job
  .gitlab-ci.yml
  scripts/gitlab/check_merge_conflict.sh
Labels: A2-insubstantial, A8-looksgood

#160 Add README Issue Link
  collator/README.adoc
  executor/README.adoc
  network/README.adoc
  parachain/README.adoc
  primitives/README.adoc
  runtime/README.adoc
  service/README.adoc
  src/README.adoc
  statement-table/README.adoc
  validation/README.adoc
Labels: A2-insubstantial, F5-documentation, F5-task

#161 config: fix wrong ip for alexander bootnode
  service/res/alexander.json
Labels: A2-insubstantial, A8-looksgood, B0-patchthis

#162 fix curated-grandpa and rebuild wasm
  runtime/src/curated_grandpa.rs
  runtime/src/lib.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/Cargo.toml
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  service/src/chain_spec.rs
Labels: A0-pleasereview

#164 Correct FIXME/TODO in service module
  service/src/chain_spec.rs
  service/src/lib.rs
Labels: A2-insubstantial
