Repository paritytech/polkadot, pull requests merged in 2019-10, with the labels that each got.

#456 Enable `substrate-session` `std` feature and remove unused traits
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/slots.rs
Labels: A0-pleasereview, A2-insubstantial

#457 Update substrate
  Cargo.lock
  cli/src/lib.rs
  runtime/src/claims.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/slots.rs
  service/src/lib.rs
  test-parachains/adder/Cargo.toml
Labels: A0-pleasereview

#461 polkadot v0.6.1
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  parachain/src/lib.rs
  primitives/Cargo.toml
  runtime/Cargo.toml
  runtime/src/claims.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/slots.rs
  service/Cargo.toml
  service/src/lib.rs
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, M4-core

#464 polkadot v0.6.2
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, M4-core

#462 Update latest substrate master
  Cargo.lock
  runtime/src/lib.rs
  runtime/src/parachains.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#465 Polkadot-parachain fix compilation in wasm
  parachain/src/wasm_executor/mod.rs
Labels: A0-pleasereview, A2-insubstantial

#458 Make `ParachainContext` take self as mutable
  collator/src/lib.rs
  test-parachains/adder/collator/src/main.rs
Labels: A0-pleasereview, A2-insubstantial

#466 Changes for substrate#3699
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/slots.rs
Labels: B0-patchthis, M4-core

#473 update branch name in Cargo.lock
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#341 Introduce Parathreads (runtime)
  Cargo.lock
  network/src/gossip.rs
  network/src/tests/validation.rs
  parachain/Cargo.toml
  parachain/src/lib.rs
  primitives/src/parachain.rs
  runtime/Cargo.toml
  runtime/src/crowdfund.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/registrar.rs
  runtime/src/slots.rs
  runtime/src/testing.rs
  service/src/chain_spec.rs
  test-parachains/adder/wasm/Cargo.toml
  validation/src/evaluation.rs
  validation/src/lib.rs
Labels: A8-looksgood

#472 Update to latest Substrate master
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/claims.rs
  runtime/src/crowdfund.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/registrar.rs
  runtime/src/slots.rs
Labels: A0-pleasereview

#476 change versioning and tagging of releases
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#481 ci: backport gitlab-ci.yml from master branch
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#483 Make `ParaId` constructible from a const context
  parachain/src/lib.rs
  parachain/src/wasm_api.rs
  runtime/src/crowdfund.rs
  runtime/src/registrar.rs
  runtime/src/slots.rs
Labels: A0-pleasereview

#484 Pass `client` and `task_executor` to `BuildParachainContext`
  Cargo.lock
  collator/src/lib.rs
  test-parachains/adder/collator/Cargo.toml
  test-parachains/adder/collator/src/main.rs
Labels: A0-pleasereview

#482 integrate minor weight/fee changes
  Cargo.lock
  cli/Cargo.toml
  cli/src/lib.rs
  runtime/Cargo.toml
  runtime/src/claims.rs
  runtime/src/crowdfund.rs
  runtime/src/impls.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/registrar.rs
  runtime/src/slots.rs
Labels: A0-pleasereview

#486 Update to latest Substrate master
  Cargo.lock
  service/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#485 Fixes required for Cumulus
  runtime/src/parachains.rs
  runtime/src/registrar.rs
  service/src/lib.rs
Labels: A0-pleasereview

#487 Only register one gossip validator for full nodes
  network/src/gossip.rs
  service/src/lib.rs
Labels: A0-pleasereview

#489 ci: backport #488 - fix publishing of ci builds
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#488 ci: fix publishing of ci builds
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#460 Support `account_nextIndex` RPC.
  Cargo.lock
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  service/Cargo.toml
  service/src/lib.rs
Labels: A0-pleasereview

#492 Switch elections to Phragmen, enable them in PoA
  Cargo.lock
  primitives/src/lib.rs
  runtime/Cargo.toml
  runtime/src/impls.rs
  runtime/src/lib.rs
  service/src/chain_spec.rs
  service/src/lib.rs
Labels: A0-pleasereview

#495 service: cleanup task spawning
  service/src/lib.rs
Labels: A7-looksgoodcantmerge

#496 Update to latest substrate polkadot-master
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#498 service: don't use the grandpa observer (#494)
  service/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#497 v0.6: merge master branch
  Cargo.lock
  Cargo.toml
  README.adoc
  SECURITY.md
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  collator/src/lib.rs
  docker/Dockerfile
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  network/src/gossip.rs
  network/src/tests/validation.rs
  parachain/Cargo.toml
  parachain/src/lib.rs
  parachain/src/wasm_api.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
  primitives/src/parachain.rs
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/crowdfund.rs
  runtime/src/impls.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/registrar.rs
  runtime/src/slots.rs
  runtime/src/testing.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/adder/collator/Cargo.toml
  test-parachains/adder/collator/src/main.rs
  test-parachains/adder/wasm/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
  validation/src/evaluation.rs
  validation/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#500 Enable nicknaming for accounts
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: A2-insubstantial

#501 Enable nicknaming for accounts (#500)
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: A8-backport

#502 Update substrate to bring in forced nicks
  Cargo.lock
  runtime/src/lib.rs
Labels: A2-insubstantial

#507 Backport fix lock
  Cargo.lock
  runtime/src/crowdfund.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/slots.rs
Labels: A8-backport

#511 Integrate fee RPC (#508)
  Cargo.lock
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  service/src/chain_spec.rs
Labels: A8-backport

#514 Update Substrate
  Cargo.lock
  cli/src/lib.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/registrar.rs
  service/src/lib.rs
Labels: A2-insubstantial

#515 Backport of Substrate update
  Cargo.lock
  cli/src/lib.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/registrar.rs
  service/src/lib.rs
Labels: A8-backport

#516 bump version to 0.6.6
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview

#521 retry on gitlab system failures
  .gitlab-ci.yml
Labels: M1-ci

#522 Bump Substrate master
  Cargo.lock
  network/src/tests/validation.rs
  runtime/src/lib.rs
  service/src/lib.rs
Labels: A2-insubstantial

#525 Backports from master
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  network/src/tests/validation.rs
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  service/Cargo.toml
  service/src/lib.rs
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A8-backport
