Repository paritytech/polkadot, pull requests merged in 2019-06, with the labels that each got.

#274 Allow parachains to send messages
  Cargo.lock
  collator/src/lib.rs
  network/src/collator_pool.rs
  network/src/gossip.rs
  network/src/lib.rs
  network/src/tests/mod.rs
  parachain/src/lib.rs
  parachain/src/wasm_api.rs
  parachain/src/wasm_executor.rs
  parachain/tests/adder.rs
  primitives/src/parachain.rs
  runtime/src/claims.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/wasm/Cargo.lock
  validation/src/collation.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: A0-pleasereview

#280 ci: fix indentation
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#277 Remove dependency on error_chain
  Cargo.lock
  parachain/Cargo.toml
  parachain/src/lib.rs
  parachain/src/wasm_executor.rs
  service/Cargo.toml
  validation/Cargo.toml
  validation/src/collation.rs
  validation/src/error.rs
  validation/src/evaluation.rs
  validation/src/lib.rs
Labels: A8-looksgood, M4-core

#284 Update to latest substrate master
  Cargo.lock
  network/src/tests/validation.rs
  network/src/validation.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/wasm/Cargo.lock
  service/src/chain_spec.rs
Labels: A0-pleasereview

#285 Require --locked on CI for WASM runtime locks
  .gitlab-ci.yml
  ci/script.sh
  runtime/wasm/Cargo.lock
  runtime/wasm/build.sh
  scripts/build.sh
  test-parachains/build.sh
Labels: A2-insubstantial

#289 Fix typo
  network/src/validation.rs
Labels: A2-insubstantial

#290 allow asynchronous collation
  collator/src/lib.rs
  test-parachains/adder/collator/src/main.rs
Labels: A0-pleasereview

#287 Track and accumulate ingress roots in runtime
  network/src/lib.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  primitives/src/parachain.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  validation/src/collation.rs
Labels: A0-pleasereview

#295 Make `validation::NetworkService` strongly typed
  network/Cargo.toml
  network/src/gossip.rs
  network/src/lib.rs
  network/src/router.rs
  network/src/tests/validation.rs
  network/src/validation.rs
Labels: A0-pleasereview

#299 Store `PeerId`s in collator pool
  network/src/collator_pool.rs
  network/src/lib.rs
Labels: A0-pleasereview

#300 Pass `relay_parent` hash to `produce_candidate`
  collator/src/lib.rs
  test-parachains/adder/collator/src/main.rs
Labels: A0-pleasereview

#297 Make `polkadot-parachain` call `validate_block` instead of `validate`
  Cargo.lock
  parachain/Cargo.toml
  parachain/src/lib.rs
  parachain/src/wasm_api.rs
  parachain/src/wasm_executor.rs
  parachain/tests/adder.rs
  parachain/tests/res/adder.wasm
  runtime/wasm/Cargo.lock
  test-parachains/adder/wasm/Cargo.toml
  test-parachains/adder/wasm/src/lib.rs
  test-parachains/build.sh
Labels: A0-pleasereview

#293 Charge fees for parachain execution
  collator/src/lib.rs
  network/src/tests/validation.rs
  primitives/src/parachain.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  test-parachains/adder/collator/src/main.rs
  validation/src/collation.rs
Labels: A0-pleasereview

#301 `ValidationNetwork` expose more functionality
  network/src/collator_pool.rs
  network/src/lib.rs
  network/src/router.rs
  network/src/validation.rs
Labels: A0-pleasereview

#302 Introduce `BuildParachainContext` trait
  Cargo.lock
  collator/Cargo.toml
  collator/src/lib.rs
  network/src/validation.rs
  test-parachains/adder/collator/src/main.rs
Labels: A0-pleasereview
