Repository paritytech/polkadot, pull requests merged in 2019-08, with the labels that each got.

#318 Pass indices in serialized form
  Cargo.lock
  primitives/Cargo.toml
  primitives/src/parachain.rs
  runtime/Cargo.toml
  runtime/src/parachains.rs
  test-parachains/adder/Cargo.toml
  validation/Cargo.toml
  validation/src/shared_table/mod.rs
Labels: A0-pleasereview

#350 Make polkadot-parachain compile for WASM
  parachain/Cargo.toml
  parachain/src/wasm_executor.rs
  parachain/src/wasm_executor/validation_host.rs
Labels: A0-pleasereview

#351 Remove tokio dependency from networking and service
  Cargo.lock
  network/Cargo.toml
  network/src/tests/validation.rs
  service/Cargo.toml
Labels: A2-insubstantial

#354 sanity check on validity-votes length
  runtime/src/parachains.rs
Labels: A0-pleasereview

#337 Track received attestations from recent blocks
  network/src/gossip/message_routing.rs
  primitives/src/lib.rs
  runtime/src/attestations.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  validation/src/lib.rs
Labels: A0-pleasereview

#358 Expose claims module signing Prefix
  runtime/src/claims.rs
Labels: A0-pleasereview

#355 Integrate the claims module
  Cargo.lock
  availability-store/Cargo.toml
  network/Cargo.toml
  runtime/src/claims.rs
  runtime/src/lib.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  test-parachains/adder/collator/Cargo.toml
  validation/Cargo.toml
Labels: A8-looksgood

#353 Update to latest Substrate master.
  Cargo.lock
  availability-store/Cargo.toml
  availability-store/src/lib.rs
  cli/src/chain_spec.rs
  collator/Cargo.toml
  collator/src/lib.rs
  erasure-coding/Cargo.toml
  erasure-coding/src/lib.rs
  network/Cargo.toml
  network/src/collator_pool.rs
  network/src/gossip.rs
  network/src/gossip/message_routing.rs
  network/src/lib.rs
  network/src/local_collations.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  parachain/Cargo.toml
  parachain/src/lib.rs
  parachain/src/wasm_executor.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/tests/adder/mod.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
  primitives/src/parachain.rs
  runtime/Cargo.toml
  runtime/src/attestations.rs
  runtime/src/claims.rs
  runtime/src/constants.rs
  runtime/src/curated_grandpa.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/slot_range.rs
  runtime/src/slots.rs
  service/Cargo.toml
  service/res/kusama.json
  service/src/chain_spec.rs
  service/src/lib.rs
  statement-table/Cargo.toml
  statement-table/src/generic.rs
  test-parachains/adder/Cargo.toml
  test-parachains/adder/collator/src/main.rs
  test-parachains/adder/src/lib.rs
  validation/Cargo.toml
  validation/src/attestation_service.rs
  validation/src/collation.rs
  validation/src/error.rs
  validation/src/evaluation.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: A0-pleasereview

#362 Prepare stuff for Kusama (i.e. disable most things)
  Cargo.lock
  cli/src/lib.rs
  runtime/Cargo.toml
  runtime/src/constants.rs
  runtime/src/curated_grandpa.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  service/Cargo.toml
  service/src/chain_spec.rs
Labels: A0-pleasereview

#356 Reward validity statements from validators
  runtime/src/attestations.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
Labels: A0-pleasereview

#371 Claims module uses a hex representation of the address not raw
  runtime/src/claims.rs
Labels: A0-pleasereview

#368 Replace parse_and_execute with parse_and_prepare
  cli/src/lib.rs
Labels: A8-looksgood

#375 Add provides tag to claims transactions.
  runtime/src/claims.rs
Labels: A0-pleasereview, M4-core

#372 Config genesis json with children (fix polkadot build-spec)
  service/res/kusama.json
Labels: A0-pleasereview

#373 Update Claims EcdsaSignature Codec
  runtime/src/claims.rs
Labels: A0-pleasereview

#369 non-root user for running node in Dockerfile
  docker/Dockerfile
Labels: A0-pleasereview

#377 Update to latest Substrate
  Cargo.lock
  runtime/src/lib.rs
  runtime/src/parachains.rs
  service/src/chain_spec.rs
  service/src/lib.rs
Labels: A0-pleasereview

#378 Fix service setup for non-validator nodes
  network/src/gossip.rs
  service/src/lib.rs
Labels: A8-looksgood

#379 Blocktime and epoch length tweaks.
  runtime/src/constants.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
Labels: A0-pleasereview

#380 Enable session module during PoA
  runtime/src/lib.rs
Labels: A2-insubstantial

#381 Move sudo to the last module
  runtime/src/lib.rs
Labels: A2-insubstantial, A8-looksgood

#383 error variant for failed deadline compute in validation worker
  validation/src/error.rs
  validation/src/lib.rs
Labels: A8-looksgood

#384 Runtime version affinity enabled in transactions.
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/attestations.rs
  runtime/src/claims.rs
  runtime/src/constants.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/slots.rs
  service/src/chain_spec.rs
Labels: A0-pleasereview

#389 Bump multistream-select to fix a debug_assert!
  Cargo.lock
Labels: A2-insubstantial

#391 pay out slashes to the treasury
  runtime/src/lib.rs
Labels: A9-buythatmanabeer

#392 Tweak treasury params
  runtime/src/lib.rs
Labels: A2-insubstantial

#393 Add networkId to Kusama chain spec
  service/res/kusama.json
Labels: A0-pleasereview

#395 Kusama CC1 chain spec(!)
  service/res/kusama.json
Labels: A2-insubstantial

#370 Allow parallel parachain validation
  parachain/src/wasm_executor.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/tests/wasm_executor/mod.rs
Labels: A0-pleasereview

#396 Fix up bonding period.
  runtime/src/lib.rs
  runtime/src/parachains.rs
Labels: A2-insubstantial

#397 Bump all versions to 0.6.0
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  runtime/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial

#400 Backports and a version bump to v0.5.1
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  parachain/src/wasm_executor.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/tests/wasm_executor/mod.rs
  primitives/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/parachains.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, A8-backport

#401 Backports and message tweak
  Cargo.lock
  cli/src/lib.rs
Labels: A2-insubstantial

#402 Spelling and update Substrate
  Cargo.lock
  cli/src/lib.rs
Labels: A2-insubstantial

#404 Update substrate
  Cargo.lock
Labels: A2-insubstantial

#403 Update substrate
  Cargo.lock
Labels: A2-insubstantial

#405 Better .dockerignore
  .dockerignore
Labels: A0-pleasereview, enhancement

#407 Update to latest Substrate
  Cargo.lock
  Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  collator/src/lib.rs
  service/Cargo.toml
  service/src/lib.rs
  src/main.rs
Labels: A0-pleasereview

#304 ICMP message-routing gossip
  availability-store/src/lib.rs
  collator/src/lib.rs
  erasure-coding/src/lib.rs
  network/Cargo.toml
  network/src/gossip.rs
  network/src/gossip/attestation.rs
  network/src/gossip/message_routing.rs
  network/src/lib.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  primitives/src/parachain.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  service/src/lib.rs
  test-parachains/adder/collator/src/main.rs
  validation/Cargo.toml
  validation/src/attestation_service.rs
  validation/src/collation.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: A0-pleasereview
