Repository paritytech/polkadot, pull requests merged in 2019-05, with the labels that each got.

#236 WIP: ci uses new docker image
  .gitlab-ci.yml
  scripts/init.sh
Labels: M1-ci

#244 update substrate reference
  Cargo.lock
  cli/src/lib.rs
  network/src/gossip.rs
  network/src/lib.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  service/src/lib.rs
  validation/src/collation.rs
  validation/src/error.rs
  validation/src/evaluation.rs
  validation/src/lib.rs
Labels: A8-looksgood

#248 Use authorities from Authorities runtime API, not Core
  Cargo.lock
  collator/Cargo.toml
  collator/src/lib.rs
  validation/Cargo.toml
  validation/src/attestation_service.rs
  validation/src/lib.rs
Labels: A8-looksgood

#247 [poc-4] update substrate reference
  Cargo.lock
  network/src/lib.rs
  network/src/tests.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/wasm/Cargo.lock
Labels: A0-pleasereview

#249 update substrate reference
  Cargo.lock
  network/src/lib.rs
  network/src/tests/mod.rs
  runtime/src/curated_grandpa.rs
  runtime/src/parachains.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
Labels: A0-pleasereview

#186 Don't pass validators' public keys with attestations
  network/src/gossip.rs
  network/src/router.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  primitives/src/parachain.rs
  runtime/src/parachains.rs
  statement-table/src/generic.rs
  statement-table/src/lib.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: A8-looksgood

#262 Bump version to v0.5
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  runtime/src/lib.rs
  service/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#256 strip out all ICMP network code and begin gossip refactor for attestations
  Cargo.lock
  collator/src/lib.rs
  network/Cargo.toml
  network/src/gossip.rs
  network/src/lib.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  service/src/lib.rs
  statement-table/src/generic.rs
  validation/src/lib.rs
Labels: A0-pleasereview

#265 ci: fix docker file for debian binary
  .gitlab-ci.yml
  scripts/docker/Dockerfile
Labels: A0-pleasereview, M1-ci

#230 Add block data size check
  network/src/tests/validation.rs
  service/src/lib.rs
  validation/src/attestation_service.rs
  validation/src/collation.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: A0-pleasereview

#239 Parachain auctions
  Cargo.lock
  parachain/Cargo.toml
  parachain/src/lib.rs
  primitives/src/parachain.rs
  runtime/src/claims.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/slot_range.rs
  runtime/src/slots.rs
  runtime/wasm/Cargo.lock
  test-parachains/adder/Cargo.toml
Labels: A0-pleasereview

#269 show rust version
  .gitlab-ci.yml
  scripts/docker/Dockerfile
Labels: A8-backport, M1-ci

#266 Allow claim to be not signed by receiver account
  runtime/src/claims.rs
Labels: A0-pleasereview

#271 Update to Substrate master
  Cargo.lock
  Cargo.toml
  service/src/lib.rs
  src/main.rs
  validation/src/error.rs
Labels: A0-pleasereview

#273 Migrate to the 2018 edition
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  availability-store/src/lib.rs
  cli/Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  collator/src/lib.rs
  erasure-coding/Cargo.toml
  erasure-coding/src/lib.rs
  executor/Cargo.toml
  executor/src/lib.rs
  network/Cargo.toml
  network/src/collator_pool.rs
  network/src/gossip.rs
  network/src/lib.rs
  network/src/local_collations.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
  primitives/src/parachain.rs
  runtime/Cargo.toml
  runtime/src/claims.rs
  runtime/src/curated_grandpa.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/slot_range.rs
  runtime/src/slots.rs
  runtime/wasm/Cargo.toml
  runtime/wasm/src/lib.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  src/main.rs
  statement-table/Cargo.toml
  statement-table/src/generic.rs
  statement-table/src/lib.rs
  test-parachains/adder/Cargo.toml
  test-parachains/adder/collator/Cargo.toml
  test-parachains/adder/collator/src/main.rs
  test-parachains/adder/src/lib.rs
  test-parachains/adder/wasm/Cargo.toml
  test-parachains/adder/wasm/src/lib.rs
  validation/Cargo.toml
  validation/src/attestation_service.rs
  validation/src/collation.rs
  validation/src/error.rs
  validation/src/evaluation.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: A8-looksgood
