Repository paritytech/polkadot, pull requests merged in 2019-12, with the labels that each got.

#636 Bump Substrate
  Cargo.lock
  runtime/src/lib.rs
Labels: A2-insubstantial, B2-breaksapi

#639 docs: update readme for cc3
  README.md
Labels: A2-insubstantial, M3-docs

#641 fix for latest substrate crate renaming
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  collator/src/lib.rs
  erasure-coding/Cargo.toml
  erasure-coding/src/lib.rs
  executor/Cargo.toml
  executor/src/lib.rs
  network/Cargo.toml
  network/src/collator_pool.rs
  network/src/gossip.rs
  network/src/gossip/attestation.rs
  network/src/gossip/message_routing.rs
  network/src/lib.rs
  network/src/local_collations.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  parachain/Cargo.toml
  parachain/src/lib.rs
  primitives/Cargo.toml
  primitives/src/parachain.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/Cargo.toml
  runtime/src/attestations.rs
  runtime/src/claims.rs
  runtime/src/constants.rs
  runtime/src/crowdfund.rs
  runtime/src/impls.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/registrar.rs
  runtime/src/slot_range.rs
  runtime/src/slots.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/adder/collator/Cargo.toml
  test-parachains/adder/collator/src/main.rs
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
  validation/src/attestation_service.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: B2-breaksapi

#638 CI check polkadot runtime
  .gitlab-ci.yml
  scripts/gitlab/check_line_width.sh
  scripts/gitlab/check_runtime.sh
Labels: A0-pleasereview, M1-ci

#642 interruptible test and build jobs
  .gitlab-ci.yml
Labels: M1-ci

#637 Adding vesting logic to claims
  runtime/src/claims.rs
  runtime/src/lib.rs
  service/src/chain_spec.rs
Labels: A8-looksgood, B2-breaksapi

#645 Bump Substrate and version
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial

#644 Update for new peerset API
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  network/src/gossip.rs
  network/src/gossip/attestation.rs
  network/src/gossip/message_routing.rs
  network/src/lib.rs
  network/src/tests/mod.rs
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview

#647 Make Kusama decentralised and permissionless
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview

#345 Erasure encoding availability
  .gitlab-ci.yml
  Cargo.lock
  availability-store/Cargo.toml
  availability-store/src/lib.rs
  availability-store/src/store.rs
  availability-store/src/worker.rs
  cli/Cargo.toml
  collator/src/lib.rs
  erasure-coding/Cargo.toml
  erasure-coding/src/lib.rs
  network/Cargo.toml
  network/src/collator_pool.rs
  network/src/gossip.rs
  network/src/lib.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  primitives/Cargo.toml
  primitives/src/parachain.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/registrar.rs
  service/src/lib.rs
  validation/Cargo.toml
  validation/src/attestation_service.rs
  validation/src/collation.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: A0-pleasereview, B2-breaksapi

#649 Update Substrate
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial

#652 Add versioning to `ParachainHost` runtime API
  availability-store/src/worker.rs
  primitives/src/parachain.rs
Labels: A0-pleasereview

#655 Bump versions
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial

#657 Fix checking that `get_heads` exists
  availability-store/src/worker.rs
Labels: A0-pleasereview

#659 Tweak some Kusama params
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial

#663 Increase nick deposit (10 KSM) and require 2 councillors to slash
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial

#664 Bump Substrate
  Cargo.lock
Labels: A2-insubstantial

#674 Replace Substrate mentions in license headers with Polkadot
  executor/src/lib.rs
  runtime/build.rs
  runtime/src/claims.rs
  test-parachains/adder/build.rs
  test-parachains/halt/build.rs
Labels: A2-insubstantial

#676 Bump Substrate, add Identity module
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: A2-insubstantial

#673 Update futures and tokio for browser light client
  Cargo.lock
  availability-store/Cargo.toml
  availability-store/src/lib.rs
  availability-store/src/store.rs
  availability-store/src/worker.rs
  cli/Cargo.toml
  cli/browser-demo/.gitignore
  cli/browser-demo/README.md
  cli/browser-demo/build.sh
  cli/browser-demo/favicon.png
  cli/browser-demo/index.html
  cli/browser-demo/ws.js
  cli/src/browser.rs
  cli/src/lib.rs
  collator/Cargo.toml
  collator/src/lib.rs
  network/Cargo.toml
  network/src/collator_pool.rs
  network/src/lib.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  service/Cargo.toml
  service/src/lib.rs
  src/main.rs
  test-parachains/adder/collator/src/main.rs
  validation/Cargo.toml
  validation/src/attestation_service.rs
  validation/src/collation.rs
  validation/src/error.rs
  validation/src/lib.rs
  validation/src/shared_table/includable.rs
  validation/src/shared_table/mod.rs
Labels: A0-pleasereview

#681 Add the /ws bootnode to the chain specs
  service/res/kusama.json
Labels: A2-insubstantial

#683 Fix bootnodes PeerIds
  service/res/kusama.json
Labels: A2-insubstantial

#675 Fixes a flaky test
  availability-store/src/worker.rs
Labels: A0-pleasereview

#686 Bump Substrate
  Cargo.lock
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  service/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial

#687 Merge some things from `ashley-compile-to-wasm`
  Cargo.lock
  cli/Cargo.toml
  cli/browser-demo/index.html
  cli/src/browser.rs
Labels: A8-looksgood

#688 Add matrix release alert script and gitlab job
  .gitlab-ci.yml
  scripts/gitlab/alert_pending_release.sh
Labels: A8-looksgood

#679 Rewrite some Future structs as async functions
  collator/src/lib.rs
  network/src/lib.rs
  network/src/router.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  validation/Cargo.toml
  validation/src/collation.rs
  validation/src/lib.rs
  validation/src/shared_table/includable.rs
  validation/src/shared_table/mod.rs
Labels: A8-looksgood

#695 Supercede 'Propagate Substrate#4284 to Polkadot'
  Cargo.lock
  collator/src/lib.rs
  network/Cargo.toml
  network/src/gossip.rs
  network/src/gossip/attestation.rs
  network/src/lib.rs
  network/src/router.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  runtime/src/crowdfund.rs
  service/src/lib.rs
Labels: A0-pleasereview

#701 Increase the minimum treasury bond to reduce silly proposals
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial

#703 Update to latest Substrate master
  Cargo.lock
  runtime/src/attestations.rs
  runtime/src/claims.rs
  runtime/src/crowdfund.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/registrar.rs
  runtime/src/slots.rs
Labels: A0-pleasereview

#702 Introduce an event for when transaction fees are paid
  runtime/src/impls.rs
Labels: A0-pleasereview

#706 Bump to latest Substrate
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/crowdfund.rs
  runtime/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A7-looksgoodtestsfail

#707 ci: increase git cloning depth to 100
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#708 ci: fetch master branch for runtime diff
  scripts/gitlab/check_runtime.sh
Labels: A0-pleasereview, M1-ci
