Repository paritytech/polkadot, pull requests merged in 2019-11, with the labels that each got.

#527 im-online module should report offences
  runtime/src/lib.rs
Labels: A2-insubstantial

#528 Backports
  Cargo.lock
  runtime/src/lib.rs
  service/src/lib.rs
Labels: A2-insubstantial, A8-backport

#531 Bump Substrate and versions
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial

#537 Bump rpc deps
  Cargo.lock
  cli/src/lib.rs
  rpc/Cargo.toml
  runtime/src/claims.rs
Labels: A2-insubstantial

#542 Bump Substrate, versions.
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/parachains.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial

#544 Bump Substrate
  Cargo.lock
  runtime/src/crowdfund.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
Labels: A2-insubstantial

#545 Enable Wasmtime building
  Cargo.lock
  cli/Cargo.toml
  cli/src/lib.rs
Labels: A2-insubstantial

#547 Bump Substrate
  Cargo.lock
  service/src/lib.rs
Labels: A2-insubstantial

#549 Enable grandpa migration.
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: A2-insubstantial

#552 Backport all v0.6 changes to master...
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/crowdfund.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  service/Cargo.toml
  service/src/lib.rs
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A8-backport

#553 Remove deprecated methods from NetworkSpecialization
  network/src/lib.rs
Labels: A2-insubstantial

#554 Bump versions & Substrate
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  network/src/gossip.rs
  network/src/tests/mod.rs
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial

#555 ci: add runtime version check
  .gitlab-ci.yml
  scripts/gitlab/check_line_width.sh
  scripts/gitlab/check_runtime.sh
Labels: A0-pleasereview, M1-ci

#557 Bump substrate/version
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial

#560 Bump version and Substrate
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial

#568 cli: fix node shutdown
  cli/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-patchthis

#570 Update to latest Substrate master
  Cargo.lock
  network/Cargo.toml
  network/src/gossip.rs
  network/src/router.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  primitives/Cargo.toml
  primitives/src/parachain.rs
  runtime/Cargo.toml
  runtime/src/attestations.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  service/Cargo.toml
  service/src/lib.rs
  validation/Cargo.toml
  validation/src/attestation_service.rs
  validation/src/collation.rs
  validation/src/error.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: A0-pleasereview

#571 Master backports
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  network/src/gossip.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  parachain/Cargo.toml
  primitives/Cargo.toml
  primitives/src/parachain.rs
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/attestations.rs
  runtime/src/claims.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  service/Cargo.toml
  service/src/lib.rs
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
  validation/src/attestation_service.rs
  validation/src/collation.rs
  validation/src/error.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: A2-insubstantial, B2-breaksapi

#574 Bump Substrate & version
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/impls.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial

#576 Bump Substrate
  Cargo.lock
Labels: A2-insubstantial

#578 Bump Substrate
  Cargo.lock
Labels: A2-insubstantial

#587 Update Substrate after repository reorganisation
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  collator/src/lib.rs
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/Cargo.toml
  runtime/build.rs
  runtime/src/attestations.rs
  runtime/src/claims.rs
  runtime/src/crowdfund.rs
  runtime/src/impls.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/registrar.rs
  runtime/src/slots.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/adder/collator/Cargo.toml
  test-parachains/adder/collator/src/main.rs
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview

#598 Update Substrate after repository reorganisation (#587)
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  collator/src/lib.rs
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/Cargo.toml
  runtime/build.rs
  runtime/src/attestations.rs
  runtime/src/claims.rs
  runtime/src/crowdfund.rs
  runtime/src/impls.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/registrar.rs
  runtime/src/slots.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/adder/collator/Cargo.toml
  test-parachains/adder/collator/src/main.rs
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A8-backport

#603 Fix `run_to_block` for Crowdfund module
  runtime/src/crowdfund.rs
Labels: A0-pleasereview, A2-insubstantial

#606 Merge `futures03` and `joe-update-to-palette`
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  collator/src/lib.rs
  network/Cargo.toml
  runtime/Cargo.toml
  runtime/src/crowdfund.rs
  src/main.rs
  test-parachains/adder/collator/Cargo.toml
  test-parachains/adder/collator/src/main.rs
  validation/Cargo.toml
  validation/src/lib.rs
Labels: B2-breaksapi

#600 Update for Substrate master
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  collator/src/lib.rs
  network/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/Cargo.toml
  runtime/src/attestations.rs
  runtime/src/claims.rs
  runtime/src/crowdfund.rs
  runtime/src/impls.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/registrar.rs
  runtime/src/slots.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  src/main.rs
  test-parachains/adder/collator/Cargo.toml
  test-parachains/adder/collator/src/main.rs
  validation/Cargo.toml
  validation/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#410 `sentry-docker-compose.yml` initial version created
  docker/sentry-docker-compose.yml
Labels: A0-pleasereview

#607 Backports and a version bump
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  collator/src/lib.rs
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/Cargo.toml
  runtime/src/attestations.rs
  runtime/src/claims.rs
  runtime/src/crowdfund.rs
  runtime/src/impls.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/registrar.rs
  runtime/src/slots.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  src/main.rs
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/adder/collator/Cargo.toml
  test-parachains/adder/collator/src/main.rs
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
  validation/src/lib.rs
Labels: A8-backport

#615 Update to latest Substrate master
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  availability-store/src/lib.rs
  cli/src/lib.rs
  runtime/Cargo.toml
  runtime/src/parachains.rs
Labels: A0-pleasereview

#614 Move propose_with into a dedicated blocking threadpool
  Cargo.lock
  validation/Cargo.toml
  validation/src/lib.rs
Labels: A0-pleasereview

#616 Bump Substrate
  Cargo.lock
  network/src/gossip.rs
Labels: A2-insubstantial

#620 Mark unreachable match clause as unreachable!
  validation/src/lib.rs
Labels: A0-pleasereview

#624 *: Enable refactored authority discovery
  Cargo.lock
  cli/src/lib.rs
  runtime/src/lib.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#623 Update Substrate
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  availability-store/src/lib.rs
  cli/Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  network/src/gossip.rs
  network/src/gossip/message_routing.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/parachains.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
  validation/src/attestation_service.rs
  validation/src/collation.rs
  validation/src/error.rs
  validation/src/evaluation.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: A0-pleasereview, A2-insubstantial, B2-breaksapi

#628 Enable governance transactions
  runtime/src/lib.rs
Labels: A2-insubstantial

#629 Update to substrate master
  Cargo.lock
  cli/src/lib.rs
  service/src/lib.rs
Labels: A2-insubstantial

#630 Kusama sessions/epochs are 1 hour not 4.
  runtime/src/constants.rs
Labels: A2-insubstantial

#631 Bump Substrate
  Cargo.lock
Labels: A2-insubstantial

#632 Kusama CC3 chain spec
  service/res/kusama.json
Labels: A2-insubstantial

#633 Update to Substrate master
  Cargo.lock
  availability-store/Cargo.toml
  service/src/lib.rs
Labels: A0-pleasereview

#626 Add WASM CI checks and make availability-store compile for WASM
  .gitlab-ci.yml
  availability-store/Cargo.toml
  availability-store/src/lib.rs
Labels: A0-pleasereview

#634 Nicks are 32 bytes
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B2-breaksapi
