Repository paritytech/polkadot, pull requests merged in 2019-07, with the labels that each got.

#309 Add claims prefix to the claims trait
  runtime/src/claims.rs
Labels: A8-looksgood

#313 Make `communication_for` exit when we end a round
  network/src/validation.rs
  runtime/src/parachains.rs
  validation/src/lib.rs
Labels: A0-pleasereview

#316 Make `collator::Network` require `Send + Sync` to make it work
  collator/src/lib.rs
  test-parachains/adder/collator/src/main.rs
Labels: A0-pleasereview

#322 Remove duplicated '.idea' entry from the gitignore
  .gitignore
Labels: A0-pleasereview, A2-insubstantial

#321 Poll the service to drive the whole node
  cli/src/lib.rs
Labels: A0-pleasereview

#326 Fix chainspec and runtime
  runtime/src/lib.rs
  service/src/chain_spec.rs
Labels: A0-pleasereview

#329 Update to latest Substrate (7688cbc)
  Cargo.lock
  collator/Cargo.toml
  collator/src/lib.rs
  runtime/Cargo.toml
  runtime/src/claims.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/slots.rs
  service/src/chain_spec.rs
  service/src/lib.rs
  validation/Cargo.toml
  validation/src/attestation_service.rs
Labels: A8-looksgood

#325 Parachain validation moved to external process
  Cargo.lock
  cli/Cargo.toml
  cli/src/lib.rs
  collator/src/lib.rs
  parachain/Cargo.toml
  parachain/src/lib.rs
  parachain/src/wasm_executor.rs
  parachain/tests/adder/mod.rs
  parachain/tests/lib.rs
  parachain/tests/wasm_executor/mod.rs
  primitives/src/parachain.rs
  service/src/lib.rs
  src/main.rs
  test-parachains/adder/collator/src/main.rs
  test-parachains/halt/Cargo.toml
  test-parachains/halt/build.rs
  test-parachains/halt/src/lib.rs
  validation/src/collation.rs
  validation/src/lib.rs
Labels: A0-pleasereview

#339 Port dev account balance changes from Substrate PR 2883 to Polkadot
  runtime/src/lib.rs
  service/src/chain_spec.rs
Labels: A0-pleasereview

#340 Update to latest Substrate
  Cargo.lock
  collator/src/lib.rs
  network/src/tests/validation.rs
  primitives/src/lib.rs
  runtime/src/claims.rs
  runtime/src/constants.rs
  runtime/src/curated_grandpa.rs
  runtime/src/impls.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/src/slots.rs
  service/src/chain_spec.rs
  service/src/lib.rs
  validation/Cargo.toml
  validation/src/dynamic_inclusion.rs
  validation/src/error.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: A0-pleasereview
