Repository paritytech/polkadot, pull requests merged in 2019-01, with the labels that each got.

#68 Remove invalid value from chainspec
  service/res/alexander.json
Labels: A2-insubstantial

#77 Update log message for proposing blocks
  consensus/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#84 update to latest substrate
  Cargo.lock
  parachain/Cargo.toml
  service/src/lib.rs
Labels: A2-insubstantial

#76 Fixes for substrate#1404
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/Cargo.toml
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  service/src/chain_spec.rs
  service/src/lib.rs
Labels: A2-insubstantial

#85 service: use grandpa block import for locally sealed aura blocks
  service/src/lib.rs
Labels: A4-awaitingci, A8-looksgood, M4-core

#79 Remove availability statement
  consensus/src/collation.rs
  consensus/src/lib.rs
  consensus/src/shared_table/mod.rs
  network/src/consensus.rs
  network/src/router.rs
  parachain/src/lib.rs
  primitives/src/parachain.rs
  runtime/src/parachains.rs
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  statement-table/src/generic.rs
  statement-table/src/lib.rs
Labels: A0-pleasereview

#91 limit number of transactions when building blocks
  consensus/src/lib.rs
Labels: A0-pleasereview

#98 v0.3.2
  Cargo.lock
  cli/src/lib.rs
  collator/src/lib.rs
  consensus/src/collation.rs
  consensus/src/lib.rs
  runtime/src/lib.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
Labels: A0-pleasereview

#96 Parachain execution yields messages to send
  Cargo.lock
  availability-store/src/lib.rs
  consensus/Cargo.toml
  consensus/src/collation.rs
  consensus/src/lib.rs
  consensus/src/shared_table/mod.rs
  network/src/consensus.rs
  network/src/router.rs
  parachain/Cargo.toml
  parachain/src/lib.rs
  parachain/src/wasm_api.rs
  parachain/src/wasm_executor.rs
  parachain/tests/adder.rs
  parachain/tests/res/adder.wasm
  primitives/src/parachain.rs
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  test-parachains/adder/src/src
  test-parachains/adder/wasm/Cargo.toml
  test-parachains/adder/wasm/src/lib.rs
Labels: A8-looksgood

#100 cli: fix node shutdown
  cli/src/lib.rs
Labels: A8-looksgood

#105 Add comment about guarantees for validate function parameters
  parachain/src/wasm_executor.rs
Labels: A2-insubstantial, M3-docs

#108 Update README.adoc
  README.adoc
Labels: A8-looksgood

#56 Initial erasure-coding of availability data
  Cargo.lock
  Cargo.toml
  erasure-coding/Cargo.toml
  erasure-coding/src/lib.rs
  erasure-coding/src/wrapped_shard.rs
  primitives/src/lib.rs
  primitives/src/parachain.rs
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
Labels: A0-pleasereview

#97 Claim yer sale DOTs
  Cargo.lock
  cli/src/lib.rs
  collator/src/lib.rs
  consensus/src/collation.rs
  consensus/src/lib.rs
  runtime/Cargo.toml
  runtime/src/claims.rs
  runtime/src/lib.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/Cargo.toml
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  service/src/chain_spec.rs
Labels: A0-pleasereview

#107 Updates substrate to latest master
  Cargo.lock
  cli/Cargo.toml
  cli/src/lib.rs
  consensus/Cargo.toml
  consensus/src/attestation_service.rs
  consensus/src/lib.rs
  primitives/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/Cargo.toml
  runtime/wasm/build.sh
  runtime/wasm/src
  runtime/wasm/src/lib.rs
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  service/Cargo.toml
  service/src/lib.rs
Labels: A0-pleasereview

#114 Use new externs for eth crypto
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/claims.rs
  runtime/src/lib.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
Labels: A0-pleasereview, Q2-easy
