Repository paritytech/polkadot, pull requests merged in 2019-03, with the labels that each got.

#166 [v0.3] Integrates new gossip system into Polkadot
  Cargo.lock
  network/src/consensus.rs
  network/src/gossip.rs
  network/src/lib.rs
  network/src/router.rs
  network/src/tests.rs
  service/src/chain_spec.rs
  service/src/lib.rs
Labels: A0-pleasereview

#167 network: guard validation network future under exit signal
  network/src/validation.rs
Labels: A0-pleasereview, A2-insubstantial, B0-patchthis

#168 [Backport] network: guard validation network future under exit signal
  network/src/consensus.rs
Labels: A0-pleasereview, A2-insubstantial, A8-backport

#169 service: fix telemetry endpoints on alexander chainspec
  service/res/alexander.json
Labels: A0-pleasereview, A2-insubstantial, B0-patchthis

#172 Update to new gossip system.
  Cargo.lock
  network/src/gossip.rs
  network/src/lib.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  runtime/src/claims.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  validation/src/lib.rs
Labels: A8-looksgood

#174 CI update according to latest substrate
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#175 [v0.3] update to substrate master
  Cargo.lock
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  consensus/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  primitives/Cargo.toml
  runtime/Cargo.toml
  runtime/src/curated_grandpa.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/wasm/Cargo.toml
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  statement-table/Cargo.toml
  test-parachains/adder/collator/Cargo.toml
Labels: A0-pleasereview

#176 Update to Substrate master
  Cargo.lock
  collator/src/lib.rs
  network/src/collator_pool.rs
  network/src/gossip.rs
  network/src/lib.rs
  network/src/local_collations.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  primitives/src/lib.rs
  primitives/src/parachain.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/wasm/Cargo.lock
  service/src/chain_spec.rs
  service/src/lib.rs
  statement-table/src/lib.rs
  test-parachains/adder/collator/src/main.rs
  validation/src/collation.rs
  validation/src/error.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: A0-pleasereview

#178 [Backport] Telemetry fix
  service/res/alexander.json
Labels: A0-pleasereview, A2-insubstantial

#177 Update v0.3 to latest Substrate master
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  collator/src/lib.rs
  consensus/src/collation.rs
  consensus/src/error.rs
  consensus/src/lib.rs
  consensus/src/shared_table/mod.rs
  network/src/collator_pool.rs
  network/src/consensus.rs
  network/src/gossip.rs
  network/src/lib.rs
  network/src/local_collations.rs
  network/src/router.rs
  network/src/tests.rs
  parachain/tests/res/adder.wasm
  primitives/src/lib.rs
  primitives/src/parachain.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/Cargo.toml
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  statement-table/src/lib.rs
  test-parachains/adder/collator/src/main.rs
Labels: A0-pleasereview

#149 Collators get incoming parachain messages
  Cargo.lock
  cli/src/lib.rs
  collator/Cargo.toml
  collator/src/lib.rs
  network/Cargo.toml
  network/src/lib.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  service/src/lib.rs
  src/main.rs
  test-parachains/adder/collator/src/main.rs
  validation/src/attestation_service.rs
  validation/src/collation.rs
  validation/src/lib.rs
Labels: A0-pleasereview

#181 Some PoC-3 GRANDPA tweaks
  runtime/src/curated_grandpa.rs
  runtime/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview

#184 [master] use authorities when calculating duty roster
  runtime/src/parachains.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
Labels: A0-pleasereview

#185 use authorities when calculating duty roster
  runtime/src/parachains.rs
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
Labels: A0-pleasereview

#188 update to substrate master: bump version to v0.3.19
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  network/src/lib.rs
  network/src/tests.rs
  service/Cargo.toml
  service/src/lib.rs
Labels: A0-pleasereview

#195 Update to latest substrate-master and polkadot v0.3
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  collator/src/lib.rs
  erasure-coding/Cargo.toml
  executor/Cargo.toml
  network/Cargo.toml
  network/src/collator_pool.rs
  network/src/lib.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
  primitives/src/parachain.rs
  runtime/Cargo.toml
  runtime/src/claims.rs
  runtime/src/curated_grandpa.rs
  runtime/src/lib.rs
  runtime/src/parachains.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  statement-table/Cargo.toml
  test-parachains/adder/collator/Cargo.toml
  test-parachains/adder/collator/src/main.rs
  validation/Cargo.toml
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: A5-grumble

#189 Document Limiting Resources for Docker Containers
  doc/docker.adoc
Labels: A2-insubstantial

#197 Update to latest substrate master
  Cargo.lock
  erasure-coding/src/lib.rs
  network/src/gossip.rs
  network/src/tests/validation.rs
  runtime/Cargo.toml
  runtime/src/curated_grandpa.rs
  runtime/src/lib.rs
  runtime/wasm/Cargo.lock
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.compact.wasm
  runtime/wasm/target/wasm32-unknown-unknown/release/polkadot_runtime.wasm
  service/src/chain_spec.rs
  service/src/lib.rs
Labels: A0-pleasereview
