Repository paritytech/polkadot, pull requests merged in 2020-08, with the labels that each got.

#1521 rename merged rococo to rococo-v1
  Cargo.lock
  Cargo.toml
  runtime/rococo-v1/Cargo.toml
  runtime/rococo-v1/build.rs
  runtime/rococo-v1/src/constants.rs
  runtime/rococo-v1/src/lib.rs
Labels: B0-silent, C1-low

#1519 Fix transaction payment runtime api companion
  Cargo.lock
  cli/src/command.rs
  collator/src/lib.rs
  node/service/src/lib.rs
  node/test-service/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
  rpc/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo-v1/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#1516 Sort out validation errors
  node/core/backing/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/primitives/src/lib.rs
  node/subsystem/src/messages.rs
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/test-parachains/tests/wasm_executor/mod.rs
  validation/src/error.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1523 Companion for substrate/6782
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1525 Implementer's guide: notes on contextual execution
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/types/candidate.md
Labels: A0-pleasereview, B0-silent, C1-low, F5-documentation

#1517 Sudo wrapper for paras
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/paras_sudo_wrapper.rs
  runtime/parachains/src/paras.rs
  runtime/rococo-v1/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1527 Cleanup upcoming paras
  runtime/parachains/src/paras.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1529 Implementer's Guide: Fix a typo parathreads -> parachains
  roadmap/implementers-guide/src/runtime/scheduler.md
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, F5-documentation

#1363 Add Rococo test network
  Cargo.lock
  Cargo.toml
  cli/src/chain_spec.rs
  cli/src/command.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/build.rs
  runtime/rococo/src/constants.rs
  runtime/rococo/src/lib.rs
  scripts/prepare-test-net.sh
  service/Cargo.toml
  service/res/rococo.json
  service/src/chain_spec.rs
  service/src/lib.rs
Labels: A0-pleasereview, B2-runtimenoteworthy, C1-low, D2-breaksapi

#1533 Integrate ChainApi with all messages
  node/core/chain-api/src/lib.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/service/src/lib.rs
  node/subsystem/src/messages.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1531 Rewrite client handling
  Cargo.lock
  cli/src/browser.rs
  cli/src/command.rs
  collator/src/lib.rs
  node/test-service/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
  runtime/rococo-v1/Cargo.toml
  runtime/rococo/Cargo.toml
  service/src/client.rs
  service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1530 Unalias Substrate Imports
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  node/service/src/lib.rs
  node/test-service/src/chain_spec.rs
  runtime/common/Cargo.toml
  runtime/common/src/attestations.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/impls.rs
  runtime/common/src/lib.rs
  runtime/common/src/parachains.rs
  runtime/common/src/paras_sudo_wrapper.rs
  runtime/common/src/purchase.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/constants.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_balances.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/inclusion_inherent.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/scheduler.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/constants.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_balances.rs
  runtime/polkadot/tests/weights.rs
  runtime/rococo-v1/Cargo.toml
  runtime/rococo-v1/src/constants.rs
  runtime/rococo-v1/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/constants.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/src/constants.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/constants.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/pallet_balances.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/client.rs
  validation/Cargo.toml
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#1522 Companion PR: add weightinfo for democracy
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_democracy.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_democracy.rs
  runtime/polkadot/tests/weights.rs
Labels: A0-pleasereview, A7-companion, B2-runtimenoteworthy, C1-low, D2-breaksapi

#1528 Use DNS hostnames for westend bootnodes
  service/res/westend.json
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D0-patchthis

#1535 Network Bridge Refactoring
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/availability/availability-distribution.md
  roadmap/implementers-guide/src/node/availability/bitfield-distribution.md
  roadmap/implementers-guide/src/node/backing/pov-distribution.md
  roadmap/implementers-guide/src/node/backing/statement-distribution.md
  roadmap/implementers-guide/src/node/collators/collator-protocol.md
  roadmap/implementers-guide/src/node/utility/network-bridge.md
  roadmap/implementers-guide/src/types/network.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#1532 Revert enabling authority discovery by default
  cli/src/cli.rs
  cli/src/command.rs
  node/service/src/lib.rs
  node/test-service/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1540 [CI] Update check_labels runtimenoteworthy label
  scripts/gitlab/check_labels.sh
Labels: A2-insubstantial, B0-silent, C1-low

#1541 Bump Substrate, version
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#1546 [CI] Fix draft release publishing
  scripts/github/generate_release_text.rb
Labels: A2-insubstantial, B0-silent, C1-low

#1542 Add an Origin to parachains v1
  runtime/parachains/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1455 Companion: ignore checks for companion PR
  .editorconfig
  .gitlab-ci.yml
  scripts/gitlab/check_runtime.sh
  scripts/gitlab/check_runtime_benchmarks.sh
  scripts/gitlab/check_web_wasm.sh
  scripts/gitlab/lib.sh
  scripts/gitlab/test_deterministic_wasm.sh
  scripts/gitlab/test_linux_stable.sh
Labels: A0-pleasereview, B0-silent, C1-low

#1543 Add SyncOracle to network's Service
  Cargo.lock
  collator/src/lib.rs
  network/Cargo.toml
  network/src/protocol/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1547 Companion PR to delaying network startup to after initialization
  node/service/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#1548 Bump Substrate
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#1549 Revert "Ignore checks for companion PRs (#1455)"
  scripts/gitlab/check_runtime_benchmarks.sh
  scripts/gitlab/check_web_wasm.sh
  scripts/gitlab/test_deterministic_wasm.sh
  scripts/gitlab/test_linux_stable.sh
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1503 Implementer's guide: downward messages and HRMP, take 2
  roadmap/implementers-guide/src/glossary.md
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/paras.md
  roadmap/implementers-guide/src/runtime/router.md
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/messages.md
  roadmap/implementers-guide/src/types/runtime.md
Labels: A0-pleasereview, B0-silent, C1-low, F5-documentation

#1473 implement provisioner
  Cargo.lock
  Cargo.toml
  node/core/backing/src/lib.rs
  node/core/provisioner/Cargo.toml
  node/core/provisioner/src/lib.rs
  node/primitives/src/lib.rs
  node/subsystem/src/messages.rs
  node/subsystem/src/util.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/utility/provisioner.md
  roadmap/implementers-guide/src/runtime-api/README.md
  roadmap/implementers-guide/src/runtime-api/availability-cores.md
  roadmap/implementers-guide/src/runtime-api/candidate-events.md
  roadmap/implementers-guide/src/runtime-api/candidate-pending-availability.md
  roadmap/implementers-guide/src/runtime-api/global-validation-data.md
  roadmap/implementers-guide/src/runtime-api/local-validation-data.md
  roadmap/implementers-guide/src/runtime-api/session-index.md
  roadmap/implementers-guide/src/runtime-api/validation-code.md
  roadmap/implementers-guide/src/runtime-api/validator-groups.md
  roadmap/implementers-guide/src/runtime-api/validators.md
  roadmap/implementers-guide/src/runtime/scheduler.md
  roadmap/implementers-guide/src/types/availability.md
Labels: A0-pleasereview, B0-silent, C1-low

#1554 Align for "Starting parachain attestation session"
  validation/src/validation_service/mod.rs
Labels: B0-silent, C1-low

#1405 Implementer's guide: Messaging overview stub
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/messaging.md
Labels: A0-pleasereview, B0-silent, C1-low, F5-documentation

#1346 companion PR for #5732: pubsub RPC for grandpa justifications
  Cargo.lock
  node/service/src/lib.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  service/src/lib.rs
Labels: A7-companion, B1-releasenotes, C1-low

#1460 impl availability distribution
  Cargo.lock
  Cargo.toml
  node/network/availability-distribution/Cargo.toml
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/network/bitfield-distribution/Cargo.toml
  node/network/bitfield-distribution/src/lib.rs
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem/src/lib.rs
  node/subsystem/src/messages.rs
  parachain/src/primitives.rs
  primitives/src/v0.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/node/availability/availability-distribution.md
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1567 Support `build-spec` for other chains than Polkadot
  cli/src/cli.rs
  cli/src/command.rs
  service/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1569 Augment Implementer's Guide XCMP docs
  roadmap/implementers-guide/src/messaging.md
Labels: A0-pleasereview, B0-silent, C1-low

#1537 Network bridge refactoring impl
  Cargo.lock
  Cargo.toml
  node/network/availability-distribution/Cargo.toml
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/network/bitfield-distribution/Cargo.toml
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/Cargo.toml
  node/network/bridge/src/lib.rs
  node/network/pov-distribution/Cargo.toml
  node/network/pov-distribution/src/lib.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/lib.rs
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/lib.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/primitives/src/lib.rs
  node/service/src/lib.rs
  node/subsystem/Cargo.toml
  node/subsystem/src/messages.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1560 Companion PR for substrate #6672
  Cargo.lock
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#1545 Update .editorconfig to what we have in practice
  .editorconfig
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1563 service/src/lib: Update authority discovery construction
  Cargo.lock
  service/src/lib.rs
Labels: A7-companion, A7-looksgoodcantmerge, B0-silent, C1-low

#1575 Allow using any polkadot client instead of enum Client
  Cargo.lock
  collator/src/lib.rs
  node/test-service/src/lib.rs
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/adder/collator/src/main.rs
  service/src/client.rs
  service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1581 [CI] Add github token to generate-release-text
  .github/workflows/publish-draft-release.yml
Labels: A2-insubstantial, B0-silent, C1-low

#1501 Remove v0 parachains runtime
  Cargo.lock
  Cargo.toml
  cli/src/cli.rs
  cli/src/command.rs
  network/test/src/block_import.rs
  node/service/src/chain_spec.rs
  node/service/src/grandpa_support.rs
  node/test-service/src/chain_spec.rs
  node/test-service/src/lib.rs
  primitives/src/v1.rs
  runtime/common/src/attestations.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/dummy.rs
  runtime/common/src/impls.rs
  runtime/common/src/lib.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/build.rs
  runtime/rococo/src/constants.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/client/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  service/Cargo.toml
  service/res/rococo.json
  service/src/chain_spec.rs
  service/src/client.rs
  service/src/grandpa_support.rs
  service/src/lib.rs
Labels: A0-pleasereview, A1-needsburnin, B7-runtimenoteworthy, C1-low, D2-breaksapi

#1576 guide: validation data refactoring
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/collators/collation-generation.md
  roadmap/implementers-guide/src/node/utility/candidate-validation.md
  roadmap/implementers-guide/src/node/utility/provisioner.md
  roadmap/implementers-guide/src/runtime-api/README.md
  roadmap/implementers-guide/src/runtime-api/full-validation-data.md
  roadmap/implementers-guide/src/runtime-api/global-validation-data.md
  roadmap/implementers-guide/src/runtime-api/local-validation-data.md
  roadmap/implementers-guide/src/runtime-api/persisted-validation-data.md
  roadmap/implementers-guide/src/runtime/configuration.md
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/paras.md
  roadmap/implementers-guide/src/types/availability.md
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#1578 Use async test helper to simplify node testing
  Cargo.lock
  node/test-service/Cargo.toml
  node/test-service/tests/build-blocks.rs
  node/test-service/tests/call-function.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1574 Make parachain validation wasm executor functional
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1556 Implementer's Guide: Flesh out more details for upward messages
  roadmap/implementers-guide/src/messaging.md
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/inclusioninherent.md
  roadmap/implementers-guide/src/runtime/router.md
  roadmap/implementers-guide/src/types/messages.md
  roadmap/implementers-guide/src/types/runtime.md
Labels: A0-pleasereview, B0-silent, C1-low, F5-documentation

#1590 overseer: add a test to ensure all subsystem receive msgs
  Cargo.lock
  node/overseer/Cargo.toml
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1568 Companion PR for #6846
  Cargo.lock
  node/test-service/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1570 Add spawn_blocking to SubsystemContext
  node/core/candidate-validation/src/lib.rs
  node/overseer/src/lib.rs
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1557 implement collation generation subsystem
  Cargo.lock
  Cargo.toml
  node/collation-generation/Cargo.toml
  node/collation-generation/src/lib.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/primitives/Cargo.toml
  node/primitives/src/lib.rs
  node/service/src/lib.rs
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/collators/collation-generation.md
Labels: A0-pleasereview, B0-silent, C1-low

#1564 Companion PR for #6862
  Cargo.lock
  node/service/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1596 overseer: fix build
  Cargo.lock
  node/overseer/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1571 move AssignmentKind and CoreAssigment to scheduler
  node/subsystem/src/messages.rs
  primitives/src/v1.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/scheduler.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1595 Implementer's Guide: Promote `HrmpChannelId` and supply more docs
  roadmap/implementers-guide/src/runtime/router.md
  roadmap/implementers-guide/src/types/messages.md
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1606 Companion for Substrate 6868 (WeightInfo for System, Utility, and Timestamp)
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/frame_system.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_timestamp.rs
  runtime/kusama/src/weights/pallet_utility.rs
  runtime/parachains/src/paras.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/frame_system.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_timestamp.rs
  runtime/polkadot/src/weights/pallet_utility.rs
  runtime/polkadot/tests/weights.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/frame_system.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/pallet_timestamp.rs
  runtime/westend/src/weights/pallet_utility.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low, D2-breaksapi

#1536 initial prometheus metrics
  Cargo.lock
  node/collation-generation/src/lib.rs
  node/core/av-store/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/core/chain-api/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/pov-distribution/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/service/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/Cargo.toml
  node/subsystem/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1591 Implementer's Guide: Make HRMP use upward message kinds
  roadmap/implementers-guide/src/messaging.md
  roadmap/implementers-guide/src/runtime/router.md
  roadmap/implementers-guide/src/types/messages.md
Labels: A0-pleasereview, B0-silent, C1-low

#1585 Implement validation data refactor
  Cargo.lock
  Cargo.toml
  node/collation-generation/src/lib.rs
  node/core/av-store/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/overseer/src/lib.rs
  node/primitives/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/src/messages.rs
  parachain/src/primitives.rs
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/code-upgrader/Cargo.toml
  parachain/test-parachains/code-upgrader/build.rs
  parachain/test-parachains/code-upgrader/src/lib.rs
  parachain/test-parachains/code-upgrader/src/wasm_validation.rs
  parachain/test-parachains/code-upgrader/wasm/Cargo.toml
  parachain/test-parachains/tests/adder/mod.rs
  parachain/test-parachains/tests/code_upgrader/mod.rs
  parachain/test-parachains/tests/lib.rs
  parachain/test-parachains/tests/wasm_executor/mod.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/node/utility/candidate-validation.md
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/util.rs
  runtime/rococo-v1/src/lib.rs
  validation/src/pipeline.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1518 Initial guide text for approvals and especially approvals assignments
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/validity/approvals.md
  roadmap/implementers-guide/src/node/validity/assignments.md
  roadmap/implementers-guide/src/runtime/validity.md
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1611 implementers-guide: in TOC move collators before backing, to match protocol pipeline
  roadmap/implementers-guide/src/SUMMARY.md
Labels: A0-pleasereview, B0-silent, C1-low

#1607 Propose parachain pallet for Rococo
  Cargo.lock
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
  runtime/rococo/src/propose_parachain.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: A0-pleasereview, D2-breaksapi

#1613 Candidate backing respects scheduled collator
  node/core/backing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1612 Companion for Substrate #6815 (Dynamic Whitelist)
  Cargo.lock
  parachain/src/wasm_executor/mod.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1616 proposer: wait for a hash to be in the active-leaves set
  node/core/proposer/src/lib.rs
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1440 Annotated parameter names for events
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots.rs
  runtime/parachains/src/inclusion.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#1618 Use own timeout in tests instead of smol-timeout
  Cargo.lock
  node/network/availability-distribution/Cargo.toml
  node/network/availability-distribution/src/tests.rs
  node/network/bitfield-distribution/Cargo.toml
  node/network/bitfield-distribution/src/lib.rs
  node/subsystem-test-helpers/Cargo.toml
  node/subsystem-test-helpers/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1609 Remove v0 node-side parachains code
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  availability-store/src/lib.rs
  availability-store/src/store.rs
  availability-store/src/worker.rs
  cli/src/command.rs
  collator/Cargo.toml
  collator/README.adoc
  collator/src/lib.rs
  network/Cargo.toml
  network/README.adoc
  network/src/legacy/collator_pool.rs
  network/src/legacy/gossip/attestation.rs
  network/src/legacy/gossip/mod.rs
  network/src/legacy/local_collations.rs
  network/src/legacy/mod.rs
  network/src/lib.rs
  network/src/protocol/mod.rs
  network/src/protocol/tests.rs
  network/test/Cargo.toml
  network/test/src/block_import.rs
  network/test/src/lib.rs
  node/service/Cargo.toml
  node/test-service/Cargo.toml
  node/test-service/src/lib.rs
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/adder/collator/src/main.rs
  service/Cargo.toml
  service/src/lib.rs
  validation/Cargo.toml
  validation/src/block_production.rs
  validation/src/collation.rs
  validation/src/dynamic_inclusion.rs
  validation/src/error.rs
  validation/src/lib.rs
  validation/src/pipeline.rs
  validation/src/shared_table/includable.rs
  validation/src/shared_table/mod.rs
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview, A1-needsburnin, B1-releasenotes, C3-medium

#1623 Companion for Substrate #6929 (Execute `verify` logic when running benchmarks)
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low, D2-breaksapi

#1633 Update package.version in Cargo.toml
  Cargo.lock
  Cargo.toml
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#1631 Enable CI to build rococo
  .gitlab-ci.yml
  cli/src/browser.rs
  parachain/src/wasm_executor/mod.rs
  parachain/test-parachains/halt/src/lib.rs
  runtime/rococo/src/lib.rs
  service/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1316 Add release checklist
  RELEASE.md
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, F9-meta

#1646 Bump version to v0.8.23
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  erasure-coding/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo-v1/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#1470 Add manual action to build PR binary
  .gitlab-ci.yml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1524 Companion PR: add weightinfo for collective
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_collective.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_collective.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1655 node/network/bridge: Define protocol names as str
  Cargo.lock
  node/network/bridge/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#1647 update kvdb-rocksdb to 0.9.1 (companion for #6963)
  Cargo.lock
  node/core/av-store/Cargo.toml
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low

#1638 Extract Assignments and Approval guide text to an Approval informational section
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/approval.md
  roadmap/implementers-guide/src/node/utility/provisioner.md
  roadmap/implementers-guide/src/node/validity/README.md
  roadmap/implementers-guide/src/node/validity/approvals.md
  roadmap/implementers-guide/src/parachains-overview.md
  roadmap/implementers-guide/src/runtime/disputes.md
  roadmap/implementers-guide/src/runtime/scheduler.md
Labels: A0-pleasereview, B0-silent, C1-low

#1588 Implementer's Guide: Incorporate HRMP to TransientValidationData
  roadmap/implementers-guide/src/runtime/router.md
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/messages.md
Labels: A0-pleasereview, B0-silent, C1-low

#1664 Implementer's Guide: Messaging cleanups
  roadmap/implementers-guide/src/runtime/router.md
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/messages.md
Labels: A2-insubstantial, B0-silent, C1-low

#1665 chore: nits that were left in bitfield dist
  node/network/bitfield-distribution/src/lib.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low
