Repository paritytech/polkadot, pull requests merged in 2020-01, with the labels that each got.

#712 Bump Substrate and runtime version
  Cargo.lock
  cli/Cargo.toml
  cli/src/lib.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#714 ci: fix release tagging after tags are added on the master branch
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#715 Bump Substrate & runtime version
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#719 service: support setting fork blocks in config
  Cargo.lock
  service/Cargo.toml
  service/res/kusama.json
  service/src/chain_spec.rs
  service/src/lib.rs
Labels: A0-pleasereview, M4-core

#720 ci: make sure master branch is available for check_runtime
  scripts/gitlab/check_runtime.sh
Labels: A0-pleasereview, M1-ci

#678 service/src/lib.rs: Register network event stream for authority disc
  service/src/lib.rs
Labels: A0-pleasereview

#724 Hotfix for Kusama
  Cargo.lock
  cli/src/lib.rs
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  scripts/gitlab/check_runtime.sh
  service/res/kusama.json
  service/src/chain_spec.rs
  service/src/lib.rs
Labels: B2-breaksapi

#726 service: reset grandpa into a future round (not past)
  Cargo.lock
  service/src/lib.rs
Labels: A0-pleasereview, M4-core

#730 polkadot v0.7.13
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial

#733 Select native runtime based on chain spec
  Cargo.lock
  cli/src/chain_spec.rs
  cli/src/lib.rs
  collator/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview

#735 Add sudo module to `polkadot-runtime`
  Cargo.lock
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  service/src/chain_spec.rs
Labels: A0-pleasereview

#736 Bump versions
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/constants.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B2-breaksapi

#738 Remove kusama fixes
  cli/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview, M4-core

#739 Tweak Polkadot constants & bump Substrate
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A2-insubstantial

#741 Bumped version to v0.7.15, use minimallly-changed Substrate.
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B2-breaksapi

#665 Switch parachain interface to new `runtime_interface` macro
  Cargo.lock
  parachain/Cargo.toml
  parachain/src/lib.rs
  parachain/src/wasm_api.rs
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/tests/adder/mod.rs
  parachain/tests/lib.rs
  parachain/tests/wasm_executor/mod.rs
  primitives/src/parachain.rs
  test-parachains/adder/build.rs
  test-parachains/adder/collator/Cargo.toml
  test-parachains/adder/collator/src/main.rs
  test-parachains/adder/src/wasm_validation.rs
  test-parachains/halt/build.rs
  validation/src/collation.rs
Labels: A0-pleasereview

#744 v0.7.16
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B2-breaksapi

#723 Companion PR for Substrate#4394
  cli/Cargo.toml
  cli/src/browser.rs
  cli/src/lib.rs
  service/Cargo.toml
Labels: A7-looksgoodtestsfail

#732 Companion PR to substrate#4542
  network/src/tests/mod.rs
Labels: A7-looksgoodtestsfail

#747 Bump Substrate & versions
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/src/collator_pool.rs
  network/src/local_collations.rs
  network/src/tests/mod.rs
  parachain/Cargo.toml
  parachain/src/wasm_executor/mod.rs
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/src/crowdfund.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  service/Cargo.toml
  service/src/lib.rs
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B2-breaksapi

#743 Companion pr for Substrate #3860
  Cargo.lock
  availability-store/Cargo.toml
  availability-store/src/lib.rs
  availability-store/src/worker.rs
  cli/Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  collator/src/lib.rs
  network/Cargo.toml
  network/src/gossip.rs
  network/src/router.rs
  network/src/tests/mod.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/build.rs
  runtime/polkadot/src/lib.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  test-parachains/adder/collator/src/main.rs
  validation/Cargo.toml
  validation/src/attestation_service.rs
  validation/src/collation.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
Labels: A0-pleasereview

#753 Update to latest Substrate
  Cargo.lock
  runtime/common/src/attestations.rs
  runtime/kusama/src/lib.rs
Labels: A2-insubstantial, B2-breaksapi

#756 Bump Substrate
  Cargo.lock
  runtime/kusama/src/lib.rs
Labels: A2-insubstantial, B2-breaksapi

#757 Update Substrate, introduce Society/Recovery
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  service/src/lib.rs
Labels: A2-insubstantial

#740 rough draft of parachains roadmap
  roadmap/parachains.md
Labels: A0-pleasereview

#766 Some fixes required for Cumulus
  collator/src/lib.rs
  parachain/src/wasm_executor/mod.rs
  validation/src/collation.rs
  validation/src/lib.rs
Labels: A0-pleasereview

#767 Remote execution with additional logging
  parachain/src/wasm_executor/validation_host.rs
  validation/src/collation.rs
Labels: A0-pleasereview

#771 Fix overflow in crowdfunding module
  runtime/common/src/crowdfund.rs
  runtime/kusama/src/lib.rs
Labels: A8-looksgood

#768 Instantiate environment with asynchronous API
  Cargo.lock
  cli/Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  collator/src/lib.rs
  runtime/kusama/src/lib.rs
  service/src/lib.rs
  validation/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#773 Validation service refactoring
  service/src/lib.rs
  statement-table/src/generic.rs
  validation/src/attestation_service.rs
  validation/src/block_production.rs
  validation/src/error.rs
  validation/src/evaluation.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview

#776 v0.17.18: Update latest substrate
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  collator/src/lib.rs
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/src/tests/validation.rs
  parachain/Cargo.toml
  parachain/src/wasm_executor/mod.rs
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  service/Cargo.toml
  service/src/lib.rs
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview

#780 Bump substrate
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B2-breaksapi

#781 grandpa: increase gossip duration to 1s
  service/src/lib.rs
Labels: A0-pleasereview, M4-core

#777 Asyncify launch_work a bit more
  collator/src/lib.rs
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview

#774 ci: backport runtime version checks from v0.6 branch
  scripts/gitlab/check_runtime.sh
Labels: A0-pleasereview, M1-ci

#783 Update to latest Substrate master
  Cargo.lock
  cli/src/lib.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/kusama/build.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/build.rs
  runtime/polkadot/src/lib.rs
  service/src/lib.rs
  test-parachains/adder/build.rs
  test-parachains/halt/build.rs
Labels: A0-pleasereview, B2-breaksapi

#787 Fix building polkadot-service without rocksdb support
  service/Cargo.toml
Labels: B2-breaksapi

#792 Add spec for westend network
  cli/src/chain_spec.rs
  service/res/westend.json
  service/src/chain_spec.rs
Labels: B2-breaksapi

#796 Use decl_error in common runtime modules
  runtime/common/src/attestations.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
Labels: A0-pleasereview, B2-breaksapi

#798 ci: only tag breaksapi if there were changes to the runtime sources
  scripts/gitlab/check_runtime.sh
Labels: A0-pleasereview, M1-ci

#797 WIP: Update westend chain spec to go live.
  service/res/westend.json
Labels: B2-breaksapi

#800 Final commit of tested westend config
  service/res/westend.json
Labels: B2-breaksapi

#786 Update tokio to 0.2 again and remove `TaskExecutor`s
  Cargo.lock
  availability-store/Cargo.toml
  availability-store/src/lib.rs
  availability-store/src/worker.rs
  cli/Cargo.toml
  cli/src/lib.rs
  collator/Cargo.toml
  collator/src/lib.rs
  network/src/tests/validation.rs
  service/Cargo.toml
  service/src/lib.rs
  validation/Cargo.toml
  validation/src/block_production.rs
  validation/src/validation_service/mod.rs
Labels: B2-breaksapi

#807 Fix weights
  runtime/common/src/claims.rs
  runtime/kusama/src/lib.rs
Labels: B2-breaksapi

#808 Update Substrate
  Cargo.lock
  collator/src/lib.rs
  runtime/common/src/attestations.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#810 Reduces the number of threads we spawn
  Cargo.lock
  Cargo.toml
Labels: A2-insubstantial

#812 Update Substrate
  Cargo.lock
  cli/Cargo.toml
  cli/src/chain_spec.rs
  cli/src/cli.rs
  cli/src/command.rs
  cli/src/lib.rs
  collator/Cargo.toml
  collator/src/lib.rs
  primitives/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/src/registrar.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/build.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/build.rs
  runtime/polkadot/src/lib.rs
  service/src/lib.rs
  src/main.rs
  test-parachains/adder/Cargo.toml
  test-parachains/adder/build.rs
  test-parachains/adder/collator/src/main.rs
  test-parachains/halt/Cargo.toml
  test-parachains/halt/build.rs
Labels: A3-inprogress, B2-breaksapi

#813 Update to latest Substrate master
  Cargo.lock
  service/src/lib.rs
Labels: A0-pleasereview

#814 Bump substrate
  Cargo.lock
  runtime/kusama/src/lib.rs
Labels: A2-insubstantial, B2-breaksapi
