Repository paritytech/polkadot, pull requests merged in 2020-02, with the labels that each got.

#818 Blacklist invalid block in Kusama
  service/res/kusama.json
Labels: A0-pleasereview

#820 ci: fix check_runtime on busybox
  scripts/gitlab/check_runtime.sh
Labels: A0-pleasereview, M1-ci

#821 Re-do #810 but properly
  Cargo.lock
  Cargo.toml
Labels: A2-insubstantial

#816 Bump Substrate
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  cli/src/command.rs
  collator/Cargo.toml
  collator/src/lib.rs
  network/Cargo.toml
  network/src/router.rs
  network/src/tests/validation.rs
  network/src/validation.rs
  runtime/common/Cargo.toml
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  test-parachains/adder/collator/Cargo.toml
  test-parachains/adder/collator/src/main.rs
  validation/Cargo.toml
Labels: A0-pleasereview, B1-silent, B2-breaksapi

#788 rewrite network code to use notifications_protocol APIs from Substrate
  Cargo.lock
  collator/src/lib.rs
  network/Cargo.toml
  network/src/legacy/collator_pool.rs
  network/src/legacy/gossip/attestation.rs
  network/src/legacy/gossip/message_routing.rs
  network/src/legacy/gossip/mod.rs
  network/src/legacy/local_collations.rs
  network/src/legacy/mod.rs
  network/src/legacy/router.rs
  network/src/legacy/tests/mod.rs
  network/src/legacy/tests/validation.rs
  network/src/legacy/validation.rs
  network/src/lib.rs
  network/src/protocol.rs
  service/src/lib.rs
  validation/src/block_production.rs
  validation/src/collation.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview, B1-silent, B2-breaksapi

#835 Introduce a maximum code size and head data size
  runtime/common/src/crowdfund.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#837 Adds some debug logging
  network/src/legacy/collator_pool.rs
  parachain/src/lib.rs
  validation/src/collation.rs
Labels: A0-pleasereview, A2-insubstantial

#839 Revert async await to fix collation
  collator/src/lib.rs
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview

#823 Strip out old XCMP primitives
  availability-store/src/lib.rs
  availability-store/src/store.rs
  availability-store/src/worker.rs
  collator/src/lib.rs
  erasure-coding/src/lib.rs
  network/src/legacy/collator_pool.rs
  network/src/legacy/gossip/attestation.rs
  network/src/legacy/gossip/message_routing.rs
  network/src/legacy/gossip/mod.rs
  network/src/legacy/mod.rs
  network/src/legacy/router.rs
  network/src/legacy/tests/mod.rs
  network/src/legacy/tests/validation.rs
  network/src/legacy/validation.rs
  network/src/protocol.rs
  parachain/src/lib.rs
  parachain/tests/adder/mod.rs
  parachain/tests/wasm_executor/mod.rs
  primitives/src/parachain.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  test-parachains/adder/collator/src/main.rs
  test-parachains/adder/src/lib.rs
  test-parachains/adder/src/wasm_validation.rs
  validation/src/collation.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
  validation/src/validation_service/mod.rs
Labels: A7-looksgoodtestsfail, B1-silent, B2-breaksapi

#838 Make Existential Deposit in Runtime Tests Non-Zero
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
Labels: A0-pleasereview

#850 CI: Make alert_pending_release.sh filter substrate changes based on github labels...
  scripts/gitlab/alert_pending_release.sh
  scripts/gitlab/lib.sh
  scripts/gitlab/publish_draft_release.sh
Labels: B1-silent, M1-ci

#848 Remove `TargetedMessage`
  network/src/legacy/tests/validation.rs
  parachain/src/lib.rs
  parachain/src/wasm_api.rs
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/tests/lib.rs
  primitives/src/parachain.rs
  validation/src/collation.rs
  validation/src/lib.rs
Labels: A5-grumble, B1-silent, M4-core

#853 Update to latest substrate master
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  availability-store/src/worker.rs
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/src/legacy/gossip/mod.rs
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/src/attestations.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
  validation/src/block_production.rs
Labels: A0-pleasereview, B2-breaksapi

#855 cli: fix version info in config
  cli/src/command.rs
Labels: A0-pleasereview, M4-core

#854 Separate `WeightToFee` calculation for Kusama and Polkadot
  runtime/common/src/impls.rs
  runtime/common/src/lib.rs
  runtime/kusama/src/constants.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/constants.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#857 Redefine RequestId instead of using it from Substrate
  network/src/legacy/mod.rs
Labels: A2-insubstantial

#858 CI: fix bad URL in publish_draft_release.sh
  scripts/gitlab/publish_draft_release.sh
Labels: B1-silent, M1-ci

#843 A more comprehensive model for PoV-Blocks and Candidate receipts
  availability-store/src/lib.rs
  availability-store/src/store.rs
  availability-store/src/worker.rs
  collator/src/lib.rs
  erasure-coding/src/lib.rs
  network/src/legacy/collator_pool.rs
  network/src/legacy/gossip/mod.rs
  network/src/legacy/mod.rs
  network/src/legacy/router.rs
  network/src/legacy/tests/validation.rs
  network/src/legacy/validation.rs
  network/src/protocol.rs
  parachain/src/wasm_executor/mod.rs
  primitives/src/parachain.rs
  runtime/common/src/attestations.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  statement-table/src/lib.rs
  test-parachains/adder/collator/src/main.rs
  validation/src/block_production.rs
  validation/src/collation.rs
  validation/src/error.rs
  validation/src/evaluation.rs
  validation/src/lib.rs
  validation/src/pipeline.rs
  validation/src/shared_table/mod.rs
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview, B2-breaksapi

#851 Spawn a future to start the collator
  collator/src/lib.rs
  service/src/lib.rs
Labels: B2-breaksapi

#867 Update to libp2p 0.16.2
  Cargo.lock
Labels: A2-insubstantial

#868 Update yamux to version 0.4.4.
  Cargo.lock
Labels: A0-pleasereview, A2-insubstantial

#863 Update to latest Substrate master
  Cargo.lock
  cli/src/command.rs
  cli/src/lib.rs
  collator/src/lib.rs
  network/src/legacy/gossip/mod.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  service/src/chain_spec.rs
  service/src/lib.rs
  src/main.rs
Labels: A0-pleasereview, B2-breaksapi
