Repository paritytech/polkadot, pull requests merged in 2020-03, with the labels that each got.

#871 Pass parent head as input to parachain validation
  validation/src/pipeline.rs
Labels: A0-pleasereview, A2-insubstantial

#878 Update substrate
  Cargo.lock
  availability-store/src/lib.rs
  availability-store/src/worker.rs
  cli/Cargo.toml
  cli/src/command.rs
  collator/src/lib.rs
  network/src/legacy/tests/validation.rs
  network/src/protocol.rs
  parachain/src/wasm_executor/mod.rs
  runtime/common/src/attestations.rs
  runtime/common/src/parachains.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
  test-parachains/adder/collator/Cargo.toml
  validation/src/block_production.rs
  validation/src/validation_service/mod.rs
Labels: B2-breaksapi

#869 ci: increase artifact retention period
  .gitlab-ci.yml
Labels: A0-pleasereview, B1-silent, M1-ci

#860 Remove legacy network code
  availability-store/src/lib.rs
  availability-store/src/store.rs
  availability-store/src/worker.rs
  cli/src/command.rs
  collator/src/lib.rs
  network/src/legacy/gossip/attestation.rs
  network/src/legacy/gossip/mod.rs
  network/src/legacy/mod.rs
  network/src/legacy/router.rs
  network/src/legacy/tests/mod.rs
  network/src/legacy/tests/validation.rs
  network/src/legacy/validation.rs
  network/src/lib.rs
  network/src/protocol.rs
  service/src/lib.rs
  test-parachains/adder/collator/src/main.rs
  validation/src/pipeline.rs
  validation/src/shared_table/mod.rs
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview, B2-breaksapi

#883 Use jmalloc as default allocator
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
Labels: A2-insubstantial

#884 Fix a few typos in docs
  availability-store/src/lib.rs
  network/src/protocol.rs
  primitives/src/parachain.rs
Labels: A2-insubstantial, A8-looksgood, B1-silent, F5-documentation

#886 Update to Substrate master
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
  validation/src/block_production.rs
Labels: B2-breaksapi

#887 Bump version to knock the -dev
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B2-breaksapi

#891 network/src/legacy: Remove unnecessary super trait on GossipService
  network/src/legacy/mod.rs
Labels: A8-looksgood, B1-silent

#892 Fix the browser light client
  cli/Cargo.toml
  cli/src/browser.rs
  service/Cargo.toml
  service/src/lib.rs
Labels: A6-mustntgrumble

#876 Benchmark Polkadot Claims Pallet
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/cli.rs
  cli/src/command.rs
  parachain/Cargo.toml
  parachain/src/lib.rs
  parachain/src/wasm_api.rs
  primitives/Cargo.toml
  primitives/src/parachain.rs
  runtime/common/Cargo.toml
  runtime/common/src/attestations.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/impls.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slot_range.rs
  runtime/common/src/slots.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/build.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/build.rs
  runtime/polkadot/src/lib.rs
  service/Cargo.toml
  service/src/lib.rs
  test-parachains/adder/build.rs
  test-parachains/halt/build.rs
Labels: A8-looksgood, B2-breaksapi

#896 Update `tokio` to make sure to include the deadlock fix
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#898 Bump to latest Substrate
  Cargo.lock
  availability-store/src/lib.rs
  availability-store/src/worker.rs
  cli/src/chain_spec.rs
  cli/src/cli.rs
  cli/src/command.rs
  network/src/legacy/gossip/mod.rs
  network/test/src/lib.rs
  parachain/src/wasm_executor/mod.rs
  runtime/test-runtime/client/src/lib.rs
  service/src/chain_spec.rs
  service/src/lib.rs
  test-parachains/adder/collator/src/main.rs
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview

#899 Prepare for version 0.7.23
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B2-breaksapi

#900 Bump Substrate and runtime version
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, B2-breaksapi

#901 Remove CC3 designation
  service/res/kusama.json
Labels: A2-insubstantial

#902 Bump versions & Substrate.
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B2-breaksapi

#897 Tests for new network code
  network/src/legacy/gossip/mod.rs
  network/src/protocol/mod.rs
  network/src/protocol/tests.rs
  validation/src/block_production.rs
  validation/src/shared_table/mod.rs
Labels: A0-pleasereview

#903 Refactor storage hashing away from opaque types
  Cargo.lock
  runtime/common/src/attestations.rs
  runtime/common/src/claims.rs
  runtime/common/src/claims.scale
  runtime/common/src/crowdfund.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/client/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#905 Bump version and Substrate
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B2-breaksapi

#904 grandpa: add voting rule to pause new votes for a period
  Cargo.lock
  cli/src/cli.rs
  cli/src/command.rs
  collator/src/lib.rs
  service/Cargo.toml
  service/src/lib.rs
Labels: A0-pleasereview, M4-core

#907 Bump version
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B2-breaksapi

#911 remove hardcoded scheduled GRANDPA pause
  service/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#916 Release version v0.7.27
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/test-runtime/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview

#914 WIP: Upgrade kvdb_rocksdb dependency
  Cargo.lock
  availability-store/Cargo.toml
Labels: A8-looksgood

#910 Remove migration code.
  Cargo.lock
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#908 CI: Move publish_draft_release job to test stage, and substrate changelog subsections
  .gitlab-ci.yml
  scripts/gitlab/alert_pending_release.sh
  scripts/gitlab/publish_draft_release.sh
Labels: A0-pleasereview, B1-silent, M1-ci, M3-docs

#912 CI: Don't announce releases on updated
  .github/workflows/release-bot.yml
Labels: A2-insubstantial, B1-silent, M1-ci

#915 Make sure that the `start_collator` future implements `Send`
  collator/src/lib.rs
Labels: A8-looksgood, B1-silent

#917 Update and fix wasm code again, add cli check to .gitlab-ci.yml
  .gitlab-ci.yml
  cli/browser-demo/index.html
  cli/browser-demo/ws.js
  cli/src/browser.rs
Labels: A8-looksgood, B1-silent

#920 Introduce progressive democracy
  Cargo.lock
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/client/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/adder/collator/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B1-runtimenoteworthy, B2-breaksapi

#921 Bump parity-util-mem
  Cargo.lock
  Cargo.toml
Labels: A0-pleasereview

#840 Parachains double vote handler initial implementation.
  Cargo.lock
  primitives/src/parachain.rs
  runtime/common/Cargo.toml
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/src/lib.rs
Labels: A8-looksgood, B2-breaksapi

#926 deduplicate parity-util-mem
  Cargo.lock
  availability-store/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B1-silent

#927 Update yamux to version 0.4.5
  Cargo.lock
Labels: A0-pleasereview, A2-insubstantial, B1-silent

#929 Fix `runtime-benchmarks` build
  runtime/common/Cargo.toml
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
Labels: A0-pleasereview, A2-insubstantial, B2-breaksapi

#932 Remove unused files
  runtime/common/src/claims.scale
  runtime/common/src/testing.rs
Labels: A0-pleasereview, A2-insubstantial

#936 Add CI check for `runtime-benchmarks`
  .gitlab-ci.yml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#937 Update substrate for new on_initialize syntax and update on_initialize weight
  Cargo.lock
  runtime/common/src/crowdfund.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: B2-breaksapi

#928 Remove Parent Hash to Session mapping
  Cargo.lock
  network/src/legacy/gossip/attestation.rs
  network/src/legacy/gossip/mod.rs
  network/src/protocol/mod.rs
  network/src/protocol/tests.rs
  primitives/Cargo.toml
  primitives/src/parachain.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  validation/src/lib.rs
  validation/src/shared_table/mod.rs
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview, B2-breaksapi

#938 Transaction source (#5366) companion PR
  Cargo.lock
  runtime/common/src/claims.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#931 Manadatory Weight
  runtime/common/src/attestations.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/registrar.rs
Labels: A0-pleasereview, B2-breaksapi

#941 Upgrade substrate for new staking API and Telemtry API
  Cargo.lock
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  service/src/chain_spec.rs
Labels: B2-breaksapi

#940 Enable Offchain Phragmén.
  Cargo.lock
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#944 Add emojis to the console output
  cli/src/browser.rs
  cli/src/command.rs
  validation/src/block_production.rs
Labels: A2-insubstantial

#947 Upgrade bitvec and parity-scale-codec
  Cargo.lock
  availability-store/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  primitives/src/parachain.rs
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/src/attestations.rs
  runtime/common/src/parachains.rs
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/test-runtime/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  validation/Cargo.toml
  validation/src/shared_table/mod.rs
Labels: A2-insubstantial, B2-breaksapi

#957 Companion pr for substrate#5448
  Cargo.lock
  network/src/protocol/tests.rs
Labels: A0-pleasereview

#951 use strong key in parachains module KeyOwnerProofSystem
  runtime/common/src/parachains.rs
Labels: A0-pleasereview, B2-breaksapi

#948 Companion PR for #5436/#5445 + #5463
  Cargo.lock
  runtime/common/src/crowdfund.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#930 PoV-block gossip
  network/src/legacy/gossip/attestation.rs
  network/src/legacy/gossip/mod.rs
  network/src/protocol/mod.rs
  network/src/protocol/tests.rs
Labels: A0-pleasereview
