Repository paritytech/polkadot, pull requests merged in 2020-05, with the labels that each got.

#1063 Some fixes to compile for Android
  parachain/Cargo.toml
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
  service/src/lib.rs
  validation/src/lib.rs
Labels: A0-pleasereview, B1-silent

#1061 Companion for Substrate#5860
  Cargo.lock
  network/test/src/block_import.rs
  network/test/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview

#1040 Companion PR for Substrate #5375
  Cargo.lock
  rpc/Cargo.toml
  rpc/src/lib.rs
  service/src/lib.rs
Labels: A3-inprogress, A7-companion

#1064 Update Runtime Weights and Fee Calculation
  runtime/common/src/lib.rs
  runtime/kusama/src/constants.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/constants.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/constants.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#1067 Companion pr for Substrate #5889
  Cargo.lock
  runtime/common/src/parachains.rs
Labels: A0-pleasereview, B1-silent, B2-breaksapi

#1066 Increment Westend `spec_version`
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#1068 Fix unsigned priority of im-online @ kusama.
  runtime/kusama/src/lib.rs
Labels: A2-insubstantial, B2-breaksapi, M4-core

#1070 0.7.33 release
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B2-breaksapi

#1046 network/src/legacy/gossip: Return bounded channel when testing
  Cargo.lock
  network/src/legacy/gossip/mod.rs
Labels: A7-companion, B1-silent

#1000 grandpa: report equivocations on all runtimes
  Cargo.lock
  primitives/Cargo.toml
  primitives/src/lib.rs
  primitives/src/parachain.rs
  runtime/common/Cargo.toml
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  service/src/lib.rs
Labels: A3-inprogress, B2-breaksapi, M4-core

#1074 Update to latest Substrate master
  Cargo.lock
  cli/src/command.rs
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/build.rs
  parachain/test-parachains/code-upgrader/Cargo.toml
  parachain/test-parachains/code-upgrader/build.rs
  parachain/test-parachains/halt/Cargo.toml
  parachain/test-parachains/halt/build.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/build.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/build.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/build.rs
  runtime/westend/Cargo.toml
  runtime/westend/build.rs
Labels: A0-pleasereview, B2-breaksapi

#1072 [CI] add check_tags CI job
  .gitlab-ci.yml
  scripts/gitlab/check_tags.sh
  scripts/gitlab/lib.sh
Labels: B1-silent, M1-ci

#1075 Companion PR for substrate #5939
  network/test/src/lib.rs
Labels: A7-companion

#1085 cli/src/cli.rs: Document --enable-authority-discovery flag
  cli/src/cli.rs
Labels: A0-pleasereview, B1-silent

#1087 Check for correct tag in `check_tags.sh`
  scripts/gitlab/check_tags.sh
Labels: A0-pleasereview, B1-silent

#1081 Companion PR for paritytech/substrate#5954
  Cargo.lock
  runtime/common/src/impls.rs
  runtime/common/src/parachains.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B1-silent, B2-breaksapi

#1086 Change BlockHashCount Parameter
  runtime/common/src/lib.rs
Labels: A0-pleasereview, B1-runtimenoteworthy, B2-breaksapi

#1095 Companion pr for #6012
  Cargo.lock
  cli/src/command.rs
Labels: A0-pleasereview, B1-silent

#1050 Companion PR to 5802
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
Labels: A7-companion, B2-breaksapi

#1092 Add ‘transaction_version’ to the signed transaction
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B1-runtimenoteworthy

#1101 Update to lastest substrate master
  Cargo.lock
  availability-store/Cargo.toml
Labels: A8-mergewhengreen, B1-silent

#1099 ci: github api use token for pull requests
  scripts/gitlab/lib.sh
Labels: A8-mergewhengreen, B1-silent, M1-ci

#1076 Companion: Democracy add weight.
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A7-companion, A8-mergewhengreen, B1-runtimenoteworthy, B2-breaksapi

#1102 Fail test on warnings
  .gitlab-ci.yml
Labels: A7-companion, A8-mergewhengreen, B1-silent, F8-enhancement, M1-ci

#1093 [CI] Expose WASM binaries on publish
  .gitlab-ci.yml
Labels: B1-silent, M1-ci

#1098 Companion for #6025
  Cargo.lock
  network/test/src/block_import.rs
  network/test/src/lib.rs
  runtime/common/src/parachains.rs
  service/src/lib.rs
Labels: A7-companion, A8-mergewhengreen, B1-releasenotes, B2-breaksapi

#1091 Extra requirements for claimants
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  primitives/src/lib.rs
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/src/claims.rs
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, B1-silent, B2-breaksapi

#1100 Companion PR to #6039
  Cargo.lock
  network/test/src/lib.rs
Labels: A8-mergewhengreen, B1-silent

#1065 Enable Babe RPC for getting epoch authorship
  Cargo.lock
  rpc/Cargo.toml
  rpc/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes

#1105 fix Cargo.lock dependency version
  Cargo.lock
Labels: A0-pleasereview, B1-silent, M4-core

#1107 Update to latest Substrate
  Cargo.lock
Labels: A2-insubstantial, B1-silent

#1112 Update substrate, add block construction metrics
  Cargo.lock
  service/src/lib.rs
  validation/Cargo.toml
  validation/src/block_production.rs
Labels: A0-pleasereview, B1-silent

#1114 [CI] Move check-labels to .post stage
  .gitlab-ci.yml
Labels: A0-pleasereview, B1-silent, M1-ci

#1110 Companion for #6067
  Cargo.lock
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/lib.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B1-silent

#1125 Bump substrate
  Cargo.lock
Labels: A2-insubstantial, B1-silent

#1111 Companion for #6076 (Allow fee calculation to happen off-chain)
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/constants.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/constants.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/src/constants.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/constants.rs
Labels: A8-mergewhengreen, A9-companion-backlog, B1-releasenotes, B2-breaksapi

#1124 use new network identity format for Kusama bootnodes
  service/res/kusama.json
Labels: B1-releasenotes

#1120 [Companion PR] make council members able to note preimage using operation extirnsic
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A8-mergewhengreen, A9-companion-backlog, B1-runtimenoteworthy, B2-breaksapi

#1103 Companion for Substrate #5961 (on_offence weight)
  Cargo.lock
  rpc/src/lib.rs
  runtime/common/src/parachains.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B1-silent, B2-breaksapi

#1126 Add System to benchmarks
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A8-mergewhengreen, B1-silent, B2-breaksapi

#1119 updated from k < 3 to 0 < k <= 3
  erasure-coding/src/lib.rs
Labels: A8-mergewhengreen, B1-silent

#1104 Companion for #6046
  Cargo.lock
  runtime/common/src/impls.rs
Labels: A8-mergewhengreen, A9-companion-backlog, B1-silent, B2-breaksapi

#1127 cli: set default ss58 address format for each chain
  cli/src/command.rs
Labels: A8-mergewhengreen, B1-releasenotes, M4-core

#1123 Companion for #5877
  Cargo.lock
  runtime/common/src/impls.rs
Labels: A8-mergewhengreen, A9-companion-backlog, B1-silent, B2-breaksapi

#1128 Expose more benchmarks (Scheduler, Elections)
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, A8-mergewhengreen, B1-silent, B2-breaksapi

#1134 Update README
  README.md
  doc/networks/alexander.md
  doc/networks/dev.md
  doc/networks/krummelanke.md
  doc/networks/local.md
  doc/networks/networks.md
Labels: A0-pleasereview, B1-silent, F5-documentation

#1137 include implementor's guide in this repo
  roadmap/implementors-guide/guide.md
Labels: A2-insubstantial

#1136 [CI] Add Polkadot runtime version to release notes, change release title to Polkadot CC1
  scripts/gitlab/publish_draft_release.sh
Labels: A0-pleasereview, B1-silent, M1-ci

#1153 Add HeaderBackend trait to BuildParachainContext for cumulus validation
  collator/src/lib.rs
  service/src/client.rs
Labels: B1-silent

#1090 Add tests for Polkadot runtime weights and fees
  runtime/polkadot/src/constants.rs
  runtime/polkadot/tests/weights.rs
Labels: A3-inprogress, B1-silent

#1159 companion for substrate/pull/6132
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/claims.rs
  runtime/common/src/lib.rs
  runtime/common/src/parachains.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A7-companion, A8-mergewhengreen

#1160 Make sure that vested claims are not transferable
  runtime/common/src/claims.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/polkadot/tests/weights.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B1-runtimenoteworthy, B2-breaksapi

#1157 clarify some things about subsystems
  roadmap/implementors-guide/guide.md
Labels: A0-pleasereview

#1164 Bump
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B1-silent, B2-breaksapi

#1166 Bump ‘spec_version’ in Westend
  runtime/westend/src/lib.rs
Labels: B1-silent, B2-breaksapi

#1165 Bump Kusama spec version to 2000
  runtime/kusama/src/lib.rs
Labels: A2-insubstantial, B1-silent, B2-breaksapi

#1169 Update wasm builder to fix bugs in detecting changed files
  parachain/test-parachains/adder/build.rs
  parachain/test-parachains/code-upgrader/build.rs
  parachain/test-parachains/halt/build.rs
  runtime/kusama/build.rs
  runtime/polkadot/build.rs
  runtime/test-runtime/build.rs
  runtime/westend/build.rs
Labels: A2-insubstantial, B1-silent, B2-breaksapi

#1168 Improve the implementor's guide section on the Scheduler module
  roadmap/implementors-guide/guide.md
Labels: A0-pleasereview, B1-silent

#1156 Use Substrate Block Proposer
  Cargo.lock
  runtime/polkadot/src/lib.rs
  service/src/lib.rs
  validation/Cargo.toml
  validation/src/block_production.rs
Labels: A0-pleasereview, B1-silent, B2-breaksapi

#1172 Fix the Prometheus endpoint not working
  Cargo.lock
Labels: A2-insubstantial, B1-releasenotes
