Repository paritytech/polkadot, pull requests merged in 2020-09, with the labels that each got.

#1635 Companion PR for `Move subcommands from sc-cli to nodes #6948 `
  Cargo.lock
  cli/src/cli.rs
  cli/src/command.rs
  node/service/src/lib.rs
  service/Cargo.toml
  service/src/client.rs
  service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#1667 Implementer's Guide: Extinguish DispatchResult
  roadmap/implementers-guide/src/runtime/router.md
  roadmap/implementers-guide/src/types/messages.md
Labels: A2-insubstantial, B0-silent, C1-low

#1632 Implementer's Guide: Tighten HRMP
  roadmap/implementers-guide/src/runtime/router.md
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/runtime.md
Labels: A0-pleasereview, B0-silent, C1-low

#1666 Implementer's Guide: Integrate DMP into PersistentValidationData
  roadmap/implementers-guide/src/runtime/router.md
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/messages.md
Labels: A0-pleasereview, B0-silent, C1-low

#1673 Implementer's Guide: Allow negotiating the HRMP limits.
  roadmap/implementers-guide/src/runtime/router.md
  roadmap/implementers-guide/src/types/messages.md
  roadmap/implementers-guide/src/types/runtime.md
Labels: A2-insubstantial, B0-silent, C1-low

#1682 implementers-guide: more structure for overview pages, clarify some definitions
  roadmap/implementers-guide/src/README.md
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/architecture.md
  roadmap/implementers-guide/src/messaging.md
  roadmap/implementers-guide/src/protocol-approval.md
  roadmap/implementers-guide/src/protocol-overview.md
  roadmap/implementers-guide/src/runtime/scheduler.md
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1645 implement candidate selection subsystem
  Cargo.lock
  Cargo.toml
  node/core/candidate-selection/Cargo.toml
  node/core/candidate-selection/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/backing/candidate-selection.md
  roadmap/implementers-guide/src/node/collators/collator-protocol.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#1636 Remove Purchase Pallet from Polkadot + Westend
  runtime/common/src/dummy.rs
  runtime/common/src/purchase.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi, D9-needsaudit👮

#1622 Make ValidationPool accepts execution mode to run custom command or in process validation
  node/core/candidate-validation/src/lib.rs
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/test-parachains/tests/adder/mod.rs
  parachain/test-parachains/tests/wasm_executor/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1675 Backport: Make ValidationPool accepts execution mode to run custom command or in process validation (#1622)
  Cargo.lock
  collator/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/test-service/src/lib.rs
  parachain/Cargo.toml
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/adder/collator/src/main.rs
  parachain/test-parachains/tests/adder/mod.rs
  parachain/test-parachains/tests/code_upgrader/mod.rs
  parachain/test-parachains/tests/wasm_executor/mod.rs
  service/src/client.rs
  service/src/lib.rs
  validation/src/pipeline.rs
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1659 Collator protocol subsystem
  Cargo.lock
  Cargo.toml
  node/core/candidate-selection/src/lib.rs
  node/network/availability-distribution/Cargo.toml
  node/network/availability-distribution/src/tests.rs
  node/network/bitfield-distribution/Cargo.toml
  node/network/bitfield-distribution/src/lib.rs
  node/network/collator-protocol/Cargo.toml
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
  node/subsystem-test-helpers/Cargo.toml
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/src/messages.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1676 Add deb and RPM repository config and documentation
  .gitignore
  .rpm/polkadot.spec
  Cargo.toml
  README.md
  scripts/packaging/deb-maintainer-scripts/postinst
  scripts/packaging/polkadot.service
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent, C1-low

#1689 Implementer's Guide: Allow the watermark to always land on the relay parent
  roadmap/implementers-guide/src/runtime/router.md
Labels: A0-pleasereview, B0-silent, C1-low

#1695 Validation: don't detect STDIN closing when running in process
  network/src/protocol/tests.rs
  node/core/candidate-validation/src/lib.rs
  parachain/Cargo.toml
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/test-parachains/tests/adder/mod.rs
  parachain/test-parachains/tests/code_upgrader/mod.rs
  parachain/test-parachains/tests/wasm_executor/mod.rs
  service/src/lib.rs
  validation/src/collation.rs
  validation/src/pipeline.rs
  validation/src/shared_table/mod.rs
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1703 Forwardport: Validation: don't detect STDIN closing when running in process (#1695)
  node/core/candidate-validation/src/lib.rs
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/test-parachains/tests/adder/mod.rs
  parachain/test-parachains/tests/wasm_executor/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1670 Companion PR for ` Add a `build-sync-spec` subcommand and remove the CHT roots from the light sync state.`
  Cargo.lock
  cli/src/cli.rs
  cli/src/command.rs
  node/test-service/src/lib.rs
  service/src/client.rs
  service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#1709 Introduce Errors for XCMP
  runtime/common/src/parachains.rs
  xcm/src/v0/traits.rs
  xcm/xcm-executor/src/lib.rs
Labels: A0-pleasereview

#1713 Typo in proxy tests
  runtime/polkadot/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#1700 Update parity-multiaddr.
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low

#1714 Add a note about memory requirements
  README.md
Labels: A2-insubstantial, B0-silent, C1-low, F5-documentation

#1715 Update bytes.
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#1687 Companion PR for #7039: grandpa-rpc dont share subscription manager, only executor
  Cargo.lock
  node/service/src/lib.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1716 Add a specific memory requirements
  README.md
Labels: A2-insubstantial, B0-silent, C1-low, F5-documentation

#1718 Update some dependencies.
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#1661 Companion PR for #6984
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low, D2-breaksapi

#1723 `locked` flag added to building section.
  README.md
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#1720 Update Substrate and bump version to 0.8.24
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  erasure-coding/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo-v1/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#1668 Bump Nominator Reward Limits
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/polkadot/tests/weights.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/pallet_staking.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium, D2-breaksapi

#1727 Implementer's Guide: Router fixes
  roadmap/implementers-guide/src/runtime/inclusioninherent.md
  roadmap/implementers-guide/src/runtime/router.md
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/messages.md
  roadmap/implementers-guide/src/types/runtime.md
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, F5-documentation

#1721 Companion for #7103 (WeightInfo for Vesting)
  Cargo.lock
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_vesting.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_vesting.rs
  runtime/rococo-v1/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1697 Prepare Polkadot to be used by Cumulus
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/client.rs
  node/service/src/lib.rs
  parachain/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
  service/src/client.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1552 Companion for #6825
  Cargo.lock
  cli/Cargo.toml
  cli/src/command.rs
Labels: A7-companion, A8-mergeoncegreen, B0-silent, C1-low

#1726 Skeleton of the Router module
  runtime/common/src/paras_sudo_wrapper.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/router.rs
  runtime/rococo-v1/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1729 Unbreak master
  Cargo.lock
  cli/src/command.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1722 Updating tracing dependency
  Cargo.lock
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low

#1336 Companion PR for Bounties #5715
  Cargo.lock
  runtime/common/src/crowdfund.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_treasury.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_treasury.rs
  runtime/polkadot/tests/weights.rs
Labels: A7-companion, A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#1734 Companion PR for #7138 (WeightInfo for Scheduler)
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_scheduler.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_scheduler.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/pallet_scheduler.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#1733 Test helper to register a parachain
  Cargo.lock
  node/test-service/Cargo.toml
  node/test-service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1737 Bump jsonrpc-core to v15
  Cargo.lock
  rpc/Cargo.toml
Labels: A0-pleasereview, B1-releasenotes, C3-medium

#1735 Companion PR for #7136 (WeightInfo for Session / Offences)
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/tests/weights.rs
  runtime/rococo-v1/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#1736 Companion for 7155 (WeightInfo for Babe and Grandpa)
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo-v1/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#1739 Companion for substrate/pull/7161
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_elections_phragmen.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_elections_phragmen.rs
  runtime/polkadot/tests/weights.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1743 Companion for `ModuleToIndex` to `PalletInfo` rename
  Cargo.lock
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/lib.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo-v1/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#1692 Companion: Handle construct_runtime breaking change.
  Cargo.lock
  runtime/common/src/dummy.rs
  runtime/common/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A7-companion, A8-mergeoncegreen, B2-breaksapi, B7-runtimenoteworthy, C1-low, D2-breaksapi

#1744 Update to substrate 2.0
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#1745 provisioner tests: remove tokio from dev-dependencies
  Cargo.lock
  node/core/provisioner/Cargo.toml
  node/core/provisioner/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1749 Parachains: Introduce a dummy module to include the Origin.
  runtime/parachains/src/lib.rs
  runtime/parachains/src/origin.rs
  runtime/rococo-v1/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1728 Companion for #7111 (Introduce `cancel_proposal` and `blacklist`)
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_democracy.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_democracy.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#1753 collation-generation: guide and tidying
  node/collation-generation/src/error.rs
  node/collation-generation/src/lib.rs
  roadmap/implementers-guide/src/node/collators/collation-generation.md
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1741 Collator protocol followup
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1759 Register listeners in statement distribution
  node/network/statement-distribution/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#1760 XCM: Add the XCM primitives crate.
  Cargo.lock
  Cargo.toml
  xcm/Cargo.toml
  xcm/src/lib.rs
  xcm/src/v0/junction.rs
  xcm/src/v0/mod.rs
  xcm/src/v0/multi_asset.rs
  xcm/src/v0/multi_location.rs
  xcm/src/v0/order.rs
  xcm/src/v0/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1765 subsystem: move Metrics to utils
  Cargo.lock
  node/collation-generation/src/lib.rs
  node/core/av-store/Cargo.toml
  node/core/av-store/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/candidate-validation/Cargo.toml
  node/core/candidate-validation/src/lib.rs
  node/core/chain-api/Cargo.toml
  node/core/chain-api/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/core/runtime-api/Cargo.toml
  node/core/runtime-api/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/pov-distribution/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/Cargo.toml
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/lib.rs
  node/subsystem/Cargo.toml
  node/subsystem/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1766 Increase Westend `spec_version`
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#1769 WIP: remove deprecated only/except clauses, build is now manual on PRs
  .gitlab-ci.yml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low
