Repository paritytech/polkadot, pull requests merged in 2020-11, with the labels that each got.

#1895 Fixes bug that collator wasn't sending `Declare` message
  node/core/candidate-selection/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1896 Adder collator improvements
  Cargo.lock
  cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  node/service/src/client.rs
  node/service/src/lib.rs
  node/test/service/Cargo.toml
  node/test/service/src/lib.rs
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/adder/collator/README.md
  parachain/test-parachains/adder/collator/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
  parachain/test-parachains/adder/src/lib.rs
  parachain/test-parachains/adder/src/wasm_validation.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1885 Upward Message Passing implementation
  node/core/candidate-validation/src/lib.rs
  parachain/src/primitives.rs
  primitives/src/v0.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/messaging.md
  roadmap/implementers-guide/src/runtime/inclusioninherent.md
  roadmap/implementers-guide/src/runtime/router.md
  roadmap/implementers-guide/src/types/messages.md
  roadmap/implementers-guide/src/types/runtime.md
  runtime/common/src/paras_registrar.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/inclusion_inherent.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/router.rs
  runtime/parachains/src/router/ump.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1897 Backing fixes
  node/core/backing/src/lib.rs
  node/core/provisioner/src/lib.rs
  statement-table/src/generic.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1888 more resilient subsystems: av-store
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1904 adder collator updates
  parachain/test-parachains/adder/collator/README.md
  parachain/test-parachains/adder/collator/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1906 add native logging to check_upward_messages
  runtime/parachains/src/router/ump.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1905 Parachain improvements
  Cargo.lock
  node/core/backing/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/validator_side.rs
  node/overseer/src/lib.rs
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  node/subsystem-util/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1889 New Weights v0.8.26
  Cargo.lock
  runtime/kusama/src/weights/frame_system.rs
  runtime/kusama/src/weights/pallet_balances.rs
  runtime/kusama/src/weights/pallet_collective.rs
  runtime/kusama/src/weights/pallet_democracy.rs
  runtime/kusama/src/weights/pallet_elections_phragmen.rs
  runtime/kusama/src/weights/pallet_identity.rs
  runtime/kusama/src/weights/pallet_im_online.rs
  runtime/kusama/src/weights/pallet_indices.rs
  runtime/kusama/src/weights/pallet_multisig.rs
  runtime/kusama/src/weights/pallet_proxy.rs
  runtime/kusama/src/weights/pallet_scheduler.rs
  runtime/kusama/src/weights/pallet_session.rs
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/kusama/src/weights/pallet_timestamp.rs
  runtime/kusama/src/weights/pallet_treasury.rs
  runtime/kusama/src/weights/pallet_utility.rs
  runtime/kusama/src/weights/pallet_vesting.rs
  runtime/polkadot/src/weights/frame_system.rs
  runtime/polkadot/src/weights/pallet_balances.rs
  runtime/polkadot/src/weights/pallet_collective.rs
  runtime/polkadot/src/weights/pallet_democracy.rs
  runtime/polkadot/src/weights/pallet_elections_phragmen.rs
  runtime/polkadot/src/weights/pallet_identity.rs
  runtime/polkadot/src/weights/pallet_im_online.rs
  runtime/polkadot/src/weights/pallet_indices.rs
  runtime/polkadot/src/weights/pallet_multisig.rs
  runtime/polkadot/src/weights/pallet_proxy.rs
  runtime/polkadot/src/weights/pallet_scheduler.rs
  runtime/polkadot/src/weights/pallet_session.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/polkadot/src/weights/pallet_timestamp.rs
  runtime/polkadot/src/weights/pallet_treasury.rs
  runtime/polkadot/src/weights/pallet_utility.rs
  runtime/polkadot/src/weights/pallet_vesting.rs
  runtime/westend/src/weights/frame_system.rs
  runtime/westend/src/weights/pallet_balances.rs
  runtime/westend/src/weights/pallet_identity.rs
  runtime/westend/src/weights/pallet_im_online.rs
  runtime/westend/src/weights/pallet_indices.rs
  runtime/westend/src/weights/pallet_multisig.rs
  runtime/westend/src/weights/pallet_proxy.rs
  runtime/westend/src/weights/pallet_scheduler.rs
  runtime/westend/src/weights/pallet_session.rs
  runtime/westend/src/weights/pallet_staking.rs
  runtime/westend/src/weights/pallet_timestamp.rs
  runtime/westend/src/weights/pallet_utility.rs
  runtime/westend/src/weights/pallet_vesting.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1890 Update Proxy Filters
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1911 Moare fixes for parachains
  Cargo.lock
  node/core/backing/src/lib.rs
  node/core/proposer/Cargo.toml
  node/core/proposer/src/lib.rs
  node/core/provisioner/Cargo.toml
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/tests.rs
  node/network/bitfield-distribution/src/lib.rs
  node/subsystem/src/messages.rs
  primitives/src/v1.rs
  statement-table/src/generic.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1914 Remove stale upgrades from polkadot + kusama
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1913 fix bitfield selection
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1912 Do not validate a candidate in candidate selection
  Cargo.lock
  node/core/candidate-selection/Cargo.toml
  node/core/candidate-selection/src/lib.rs
  roadmap/implementers-guide/src/node/backing/candidate-selection.md
Labels: A0-pleasereview, B0-silent, C1-low

#1920 Simplify the bitfield signing job
  Cargo.lock
  node/core/bitfield-signing/Cargo.toml
  node/core/bitfield-signing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1908 more resilient subsystems
  node/collation-generation/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/pov-distribution/src/lib.rs
  node/subsystem-util/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1916 Make `CandidateHash` a real type
  core-primitives/src/lib.rs
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/network/protocol/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
  node/primitives/src/lib.rs
  node/subsystem/src/messages.rs
  primitives/src/v0.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/types/network.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  statement-table/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1921 Make sure we clear the freed the availability cores
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/inclusion_inherent.rs
  runtime/parachains/src/scheduler.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1922 Adds a comment as requested
  node/core/bitfield-signing/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1924 Distribute a PoV after seconding it
  node/collation-generation/src/lib.rs
  node/core/av-store/src/tests.rs
  node/core/backing/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/network/pov-distribution/src/lib.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/node/backing/candidate-backing.md
  roadmap/implementers-guide/src/node/backing/pov-distribution.md
  roadmap/implementers-guide/src/types/availability.md
Labels: A0-pleasereview, B0-silent, C1-low

#1900 Implement HRMP
  Cargo.lock
  core-primitives/src/lib.rs
  node/collation-generation/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/primitives/src/lib.rs
  node/subsystem/src/messages.rs
  parachain/src/primitives.rs
  parachain/test-parachains/adder/collator/src/lib.rs
  parachain/test-parachains/adder/src/wasm_validation.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/paras.md
  roadmap/implementers-guide/src/runtime/router.md
  roadmap/implementers-guide/src/types/messages.md
  roadmap/implementers-guide/src/types/runtime.md
  runtime/common/src/paras_registrar.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/router.rs
  runtime/parachains/src/router/hrmp.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/util.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/src/v0/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1929 Cargo.lock: Update dependencies
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low

#1928 Adds integration test based on adder collator
  Cargo.lock
  cli/Cargo.toml
  cli/src/command.rs
  node/core/candidate-validation/src/lib.rs
  node/service/src/chain_spec.rs
  node/service/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/test/client/Cargo.toml
  node/test/client/src/block_builder.rs
  node/test/service/Cargo.toml
  node/test/service/src/chain_spec.rs
  node/test/service/src/lib.rs
  node/test/service/tests/build-blocks.rs
  node/test/service/tests/call-function.rs
  parachain/src/wasm_executor/mod.rs
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/adder/collator/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
  parachain/test-parachains/adder/collator/tests/integration.rs
  rpc/Cargo.toml
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/constants.rs
  runtime/test-runtime/src/lib.rs
  scripts/gitlab/test_linux_stable.sh
Labels: A0-pleasereview, B0-silent, C1-low

#1933 Cleanups
  node/primitives/src/lib.rs
  node/test/service/src/lib.rs
  parachain/test-parachains/adder/collator/src/lib.rs
  roadmap/implementers-guide/src/node/collators/collation-generation.md
  runtime/test-runtime/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1932 Rename ExecutionMode to IsolationStrategy
  node/core/candidate-validation/src/lib.rs
  node/service/src/lib.rs
  node/test/service/src/lib.rs
  parachain/src/wasm_executor/mod.rs
  parachain/test-parachains/adder/collator/src/lib.rs
  parachain/test-parachains/tests/adder/mod.rs
  parachain/test-parachains/tests/wasm_executor/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1935 Don't just swallow message in dummy-subsystem, but log
  node/subsystem/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1926 Improve diagnostics for the ValidationOutputs checker / inclusion
  Cargo.lock
  runtime/parachains/Cargo.toml
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/router.rs
  runtime/parachains/src/router/dmp.rs
  runtime/parachains/src/router/hrmp.rs
  runtime/parachains/src/router/ump.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1942 [CI] Fix release Docker github action
  .github/workflows/publish-docker-release.yml
  scripts/docker/release.Dockerfile
Labels: A0-pleasereview, B0-silent, C1-low

#1816 Companion PR for Substrate #7186
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#1947 Restrict collating_using_adder_collator test on feature real-overseer
  parachain/test-parachains/adder/collator/tests/integration.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1949 Make sure adder collator test is executed in CI
  scripts/gitlab/test_linux_stable.sh
Labels: A2-insubstantial, B0-silent, C1-low

#1950 Add CI job to verify extrinsic ordering
  .gitlab-ci.yml
  scripts/gitlab/check_extrinsics_ordering.sh
Labels: A0-pleasereview, B0-silent, C1-low

#1939 Breakdown the Router module on Dmp, Ump, Hrmp modules
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/glossary.md
  roadmap/implementers-guide/src/runtime/dmp.md
  roadmap/implementers-guide/src/runtime/hrmp.md
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/inclusioninherent.md
  roadmap/implementers-guide/src/runtime/initializer.md
  roadmap/implementers-guide/src/runtime/ump.md
  runtime/common/src/paras_registrar.rs
  runtime/common/src/paras_sudo_wrapper.rs
  runtime/parachains/src/dmp.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/inclusion_inherent.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/router.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/ump.rs
  runtime/parachains/src/util.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1941 sudo_queue_downward_message
  runtime/common/src/paras_sudo_wrapper.rs
  runtime/parachains/src/paras.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1937 .github: Add dependabot config and thus enable dependabot
  .github/dependabot.yml
Labels: A0-pleasereview, B0-silent, C1-low

#1961 .github/dependabot: Handle Substrate crates manually
  .github/dependabot.yml
Labels: A0-pleasereview, B0-silent, C1-low

#1965 Patch some features for XCM
  parachain/src/primitives.rs
  runtime/parachains/src/origin.rs
  xcm/xcm-builder/src/currency_adapter.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1966 Connect to different validators on different leaves
  node/subsystem-util/src/validator_discovery.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1967 Companion PR for substrate#7549
  Cargo.lock
  node/network/bridge/Cargo.toml
  node/network/bridge/src/lib.rs
Labels: A7-companion, A8-mergeoncegreen, B0-silent, C1-low

#1969 [CI] Only increase priority of a release based on client changes
  scripts/github/generate_release_text.rb
Labels: A0-pleasereview, B0-silent, C1-low

#1984 add max_pov_size to runtime config and PersistedValidationData
  node/core/av-store/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/service/src/chain_spec.rs
  node/test/service/src/chain_spec.rs
  primitives/src/v1.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/util.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1988 fix approval keytypes doc
  roadmap/implementers-guide/src/types/approval.md
Labels: A0-pleasereview, B0-silent, C1-low

#1989 A simple check to reject obviously wrong validation code binaries
  runtime/common/src/lib.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/paras_sudo_wrapper.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1940 Add tracing support to node
  Cargo.lock
  cli/Cargo.toml
  core-primitives/src/lib.rs
  node/collation-generation/Cargo.toml
  node/collation-generation/src/lib.rs
  node/core/av-store/Cargo.toml
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/core/backing/Cargo.toml
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/Cargo.toml
  node/core/bitfield-signing/src/lib.rs
  node/core/candidate-selection/Cargo.toml
  node/core/candidate-selection/src/lib.rs
  node/core/candidate-validation/Cargo.toml
  node/core/candidate-validation/src/lib.rs
  node/core/chain-api/Cargo.toml
  node/core/chain-api/src/lib.rs
  node/core/proposer/Cargo.toml
  node/core/proposer/src/lib.rs
  node/core/provisioner/Cargo.toml
  node/core/provisioner/src/lib.rs
  node/core/runtime-api/Cargo.toml
  node/core/runtime-api/src/lib.rs
  node/network/availability-distribution/Cargo.toml
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/network/bitfield-distribution/Cargo.toml
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/Cargo.toml
  node/network/bridge/src/lib.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/Cargo.toml
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/pov-distribution/Cargo.toml
  node/network/pov-distribution/src/lib.rs
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/lib.rs
  node/overseer/Cargo.toml
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/subsystem-test-helpers/Cargo.toml
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/validator_discovery.rs
  node/subsystem/Cargo.toml
  node/subsystem/src/lib.rs
  node/test/service/Cargo.toml
  primitives/src/v1.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1992 cleanup validator discovery
  node/core/chain-api/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/src/collator_side.rs
  node/subsystem-util/src/validator_discovery.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#1994 Sane messaging defaults for rococo
  node/service/src/chain_spec.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1993 Add parity-keyring to install instructions
  README.md
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1955 Improve collator side of the collator-protocol
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1995 overseer: send_msg should not return an error
  node/collation-generation/src/lib.rs
  node/core/av-store/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/core/proposer/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/pov-distribution/src/lib.rs
  node/network/pov-distribution/src/tests.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/validator_discovery.rs
  node/subsystem/src/lib.rs
  node/test/service/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1954 companion for substrate#7546
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1953 *: Update authority discovery and remove WorkerConfig
  Cargo.lock
  cli/src/command.rs
  node/service/src/lib.rs
  node/test/service/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
Labels: A7-companion, A8-mergeoncegreen, B0-silent, C1-low

#2000 Update docker.md
  doc/docker.md
Labels: B0-silent, C1-low

#1999 Make sure we inform statement listeners about received statements
  node/network/statement-distribution/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2004 Switch to wasm-builder 3.0.0
  Cargo.lock
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/build.rs
  parachain/test-parachains/halt/Cargo.toml
  parachain/test-parachains/halt/build.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/build.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/build.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/build.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/build.rs
  runtime/westend/Cargo.toml
  runtime/westend/build.rs
  scripts/gitlab/test_deterministic_wasm.sh
Labels: A0-pleasereview, B0-silent, C1-low

#2006 backing: reorder votes to match bitfield in backed candidate
  node/core/backing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2005 Do not send messages twice in bitfield distribution
  Cargo.lock
  node/network/bitfield-distribution/Cargo.toml
  node/network/bitfield-distribution/src/lib.rs
  node/network/protocol/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1973 Session management for approval voting
  roadmap/implementers-guide/src/node/approval/approval-voting.md
Labels: A0-pleasereview, B0-silent, C1-low

#1951 Approval Distribution Subsystem
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/approval/README.md
  roadmap/implementers-guide/src/node/approval/approval-distribution.md
  roadmap/implementers-guide/src/node/approval/approval-networking.md
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/node/utility/network-bridge.md
  roadmap/implementers-guide/src/types/approval.md
  roadmap/implementers-guide/src/types/network.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#1990 PoV Distribution optimization
  Cargo.lock
  node/network/pov-distribution/Cargo.toml
  node/network/pov-distribution/src/error.rs
  node/network/pov-distribution/src/lib.rs
  node/network/pov-distribution/src/tests.rs
  node/subsystem-util/src/validator_discovery.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2008 Some code cleanup in overseer
  node/overseer/src/lib.rs
  node/subsystem/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2009 past-session validator discovery APIs
  node/core/runtime-api/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/lib.rs
  node/network/pov-distribution/src/error.rs
  node/network/pov-distribution/src/tests.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/validator_discovery.rs
  node/subsystem/src/messages.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/runtime/initializer.md
  roadmap/implementers-guide/src/runtime/session_info.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  roadmap/implementers-guide/src/types/runtime.md
  runtime/common/src/paras_registrar.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/session_info.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2017 Bump spec versions to ensure that we don't run in native
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2015 Make sure we don't send messages multiple times in the availability d…
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/network/statement-distribution/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2021 Add a fuzzer for the erasure coding
  erasure-coding/erasure_coding_fuzzer/Cargo.lock
  erasure-coding/erasure_coding_fuzzer/Cargo.toml
  erasure-coding/erasure_coding_fuzzer/src/reconstruct.rs
  erasure-coding/erasure_coding_fuzzer/src/round_trip.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#2020 Fix check_runtime.sh
  scripts/gitlab/check_runtime.sh
Labels: A0-pleasereview, B0-silent, C1-low

#2024 add module to features/std
  runtime/common/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#2010 Move erasure root out of candidate commitments and into descriptor
  node/collation-generation/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/primitives/src/lib.rs
  node/subsystem/src/messages.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  runtime/kusama/src/lib.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2026 proposer: guard all provisioner data work with timeout
  node/core/proposer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2022 erasure-coding: do not panic on 1 validator
  erasure-coding/erasure_coding_fuzzer/src/reconstruct.rs
  erasure-coding/erasure_coding_fuzzer/src/round_trip.rs
  erasure-coding/fuzzer/Cargo.lock
  erasure-coding/fuzzer/Cargo.toml
  erasure-coding/fuzzer/src/reconstruct.rs
  erasure-coding/fuzzer/src/round_trip.rs
  erasure-coding/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1972 change approval voting counting procedure
  roadmap/implementers-guide/src/node/approval/approval-voting.md
Labels: A0-pleasereview, B0-silent, C1-low

#2030 allow jobs to spawn sub-tasks
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/subsystem-util/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2031 util: implement FusedStream for Jobs
  node/subsystem-util/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2035 Process runtime api requests in the background
  Cargo.lock
  node/core/runtime-api/Cargo.toml
  node/core/runtime-api/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2038 cargo update -p sp-io
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#2037 Simplify subsystem jobs
  Cargo.lock
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/Cargo.toml
  node/core/bitfield-signing/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/tests.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/src/messages.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2028 Move candidate validation to the background
  node/core/backing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2041 Update Substrate again
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#2043 parachains runtime: configurable maximum validators per core
  roadmap/implementers-guide/src/runtime/scheduler.md
  roadmap/implementers-guide/src/types/runtime.md
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/scheduler.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2040 small improvements for parachains consensus
  node/core/proposer/src/lib.rs
  node/core/provisioner/Cargo.toml
  node/core/provisioner/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/network/bridge/src/lib.rs
  node/test/service/tests/build-blocks.rs
Labels: A0-pleasereview, B0-silent, C1-low
