Repository paritytech/polkadot, pull requests merged in 2020-04, with the labels that each got.

#954 Fix council/collective genesis
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  service/src/chain_spec.rs
Labels: A0-pleasereview, B2-breaksapi

#942 Companion for #5412
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  parachain/src/wasm_api.rs
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  test-parachains/adder/Cargo.toml
  test-parachains/halt/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#945 Make sure that Parachain heads are updated
  runtime/common/src/parachains.rs
Labels: A0-pleasereview, B2-breaksapi

#958 Rework consensus instance communication with the network worker
  network/src/lib.rs
  network/src/protocol/mod.rs
  network/src/protocol/tests.rs
  primitives/src/parachain.rs
Labels: A0-pleasereview

#959 A couple spaces where emojis were improperly laid out
  cli/src/browser.rs
  cli/src/command.rs
Labels: A2-insubstantial

#961 Introduce a skill-tree for remaining tasks in phase-1
  roadmap/phase-1.png
  roadmap/phase-1.toml
  roadmap/render.sh
Labels: A8-looksgood

#963 Don't depend directly on libp2p
  Cargo.lock
  network/test/Cargo.toml
  network/test/src/lib.rs
Labels: A2-insubstantial, B1-silent

#968 Make sure we send the validator key to collators on status
  network/src/protocol/mod.rs
  network/src/protocol/tests.rs
  service/src/lib.rs
Labels: A8-looksgood

#960 Companion PR to splitting Roles
  cli/src/command.rs
  collator/src/lib.rs
  network/src/legacy/gossip/mod.rs
  network/src/protocol/mod.rs
  network/src/protocol/tests.rs
  network/test/src/lib.rs
  service/src/lib.rs
Labels: A8-looksgood

#952 Ensure that table router is always built
  primitives/src/parachain.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/test-runtime/src/lib.rs
  validation/src/lib.rs
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview, B2-breaksapi

#972 refactor out validation hosts to pool struct
  Cargo.lock
  network/src/protocol/tests.rs
  parachain/Cargo.toml
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/tests/adder/mod.rs
  parachain/tests/wasm_executor/mod.rs
  validation/src/collation.rs
  validation/src/pipeline.rs
  validation/src/shared_table/mod.rs
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview

#967 Update for using Mandatory inherents
  runtime/common/src/attestations.rs
  runtime/common/src/parachains.rs
  validation/src/block_production.rs
Labels: A0-pleasereview, B2-breaksapi

#975 ci: deploy: remove test branch
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#976 Fix master by updating `Cargo.lock`
  Cargo.lock
Labels: A2-insubstantial

#918 Upgradeable validation functions
  Cargo.lock
  Cargo.toml
  collator/src/lib.rs
  parachain/Cargo.toml
  parachain/src/lib.rs
  parachain/src/primitives.rs
  parachain/src/wasm_api.rs
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/test-parachains/.gitignore
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/README.md
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/build.rs
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/adder/collator/src/main.rs
  parachain/test-parachains/adder/src/lib.rs
  parachain/test-parachains/adder/src/wasm_validation.rs
  parachain/test-parachains/adder/wasm/Cargo.toml
  parachain/test-parachains/code-upgrader/Cargo.toml
  parachain/test-parachains/code-upgrader/build.rs
  parachain/test-parachains/code-upgrader/src/lib.rs
  parachain/test-parachains/code-upgrader/src/wasm_validation.rs
  parachain/test-parachains/code-upgrader/wasm/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  parachain/test-parachains/halt/build.rs
  parachain/test-parachains/halt/src/lib.rs
  parachain/test-parachains/src/lib.rs
  parachain/test-parachains/tests/adder/mod.rs
  parachain/test-parachains/tests/code_upgrader/mod.rs
  parachain/test-parachains/tests/lib.rs
  parachain/test-parachains/tests/wasm_executor/mod.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
  primitives/src/parachain.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  validation/src/pipeline.rs
Labels: A8-looksgood, B2-breaksapi

#974 Enable staking validate unsigned
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A2-insubstantial, B2-breaksapi

#935 Update cli to new sc-cli API
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/build.rs
  cli/src/browser.rs
  cli/src/chain_spec.rs
  cli/src/cli.rs
  cli/src/command.rs
  cli/src/lib.rs
  collator/src/lib.rs
  network/test/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
  service/src/lib.rs
  src/main.rs
Labels: A3-inprogress, B2-breaksapi

#982 Companion PR to #5560 - Also includes polkadot#979 and polkadot#986
  Cargo.lock
  network/test/src/lib.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A2-insubstantial, A7-companion, B2-breaksapi

#988 Companion pr for new chain type RPC
  Cargo.lock
  service/src/chain_spec.rs
Labels: A0-pleasereview

#989 Update to Substrate master
  Cargo.lock
Labels: A2-insubstantial

#990 Update to Substrate master
  Cargo.lock
Labels: A0-pleasereview, A2-insubstantial

#964 Use strong types in runtime for parachain heads and validation code
  Cargo.lock
  network/src/protocol/tests.rs
  parachain/src/primitives.rs
  primitives/src/parachain.rs
  runtime/common/Cargo.toml
  runtime/common/src/crowdfund.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  validation/src/pipeline.rs
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview, B2-breaksapi

#993 Use tempdir for tests
  Cargo.lock
  Cargo.toml
  tests/invalid_order_arguments.rs
  tests/purge_chain_works.rs
  tests/running_the_node_and_interrupt.rs
Labels: A0-pleasereview, B1-silent

#983 Westend Mark II
  Cargo.lock
  Cargo.toml
  cli/src/chain_spec.rs
  cli/src/cli.rs
  cli/src/command.rs
  cli/src/lib.rs
  collator/src/lib.rs
  primitives/src/parachain.rs
  runtime/westend/Cargo.toml
  runtime/westend/build.rs
  runtime/westend/src/constants.rs
  runtime/westend/src/lib.rs
  service/Cargo.toml
  service/res/westend.json
  service/src/chain_spec.rs
  service/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B2-breaksapi

#997 Bump trie-db
  Cargo.lock
Labels: A2-insubstantial

#991 Make sure we send collators its role on connect
  network/src/protocol/mod.rs
  network/src/protocol/tests.rs
Labels: A0-pleasereview

#995 Companion PR to channel names
  Cargo.lock
  network/src/protocol/mod.rs
  service/src/lib.rs
Labels: A2-insubstantial, A7-companion

#998 Release 0.7.29
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, B2-breaksapi

#996 Updated for the new db
  Cargo.lock
  cli/Cargo.toml
  network/test/src/lib.rs
  service/Cargo.toml
  service/src/lib.rs
Labels: A8-looksgood

#1001 Bump substrate
  Cargo.lock
Labels: A2-insubstantial

#994 Companion PR for substrate#5446 (Update Weights to u64)
  Cargo.lock
  runtime/common/src/attestations.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/impls.rs
  runtime/common/src/lib.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/constants.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/constants.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/constants.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A7-companion, B2-breaksapi

#966 Adds an offchain call to submit double vote reports
  Cargo.lock
  primitives/src/parachain.rs
  runtime/common/Cargo.toml
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#984 service/src/lib: Enable authority discovery on sentry nodes
  Cargo.lock
  service/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes

#939 Companion PR for 5023
  Cargo.lock
  parachain/src/wasm_executor/mod.rs
Labels: A0-pleasereview, A7-companion

#987 Companion for Runtime Semver
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A7-companion, B2-breaksapi

#1003 Companion PR for 5657
  Cargo.lock
  network/test/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview, A7-companion

#1006 Release 0.7.30
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, B2-breaksapi

#1010 Make sure collators join the validation network
  collator/src/lib.rs
  network/src/protocol/mod.rs
  service/src/lib.rs
Labels: A0-pleasereview

#950 Companion to child trie api change #4857
  Cargo.lock
  parachain/src/wasm_executor/mod.rs
  runtime/common/src/crowdfund.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/client/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, A7-looksgoodtestsfail, B2-breaksapi

#969 Remove usage of substrate-test-runtime.
  Cargo.lock
  network/test/Cargo.toml
  network/test/src/block_import.rs
  runtime/test-runtime/client/Cargo.toml
  runtime/test-runtime/client/src/lib.rs
  runtime/test-runtime/src/genesismap.rs
  runtime/test-runtime/src/lib.rs
  service/Cargo.toml
  service/src/grandpa_support.rs
Labels: B2-breaksapi

#1014 Fix building master
  runtime/test-runtime/src/genesismap.rs
  service/res/westend.json
Labels: A0-pleasereview, B1-silent, B2-breaksapi

#985 Companion PR to #5182 - Substrate offchain signing
  Cargo.lock
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A7-companion, B2-breaksapi

#1015 Fix extensions handling for Parachain validation
  parachain/src/wasm_executor/mod.rs
Labels: A0-pleasereview, B1-silent

#1008 Companion for substrate/5686
  Cargo.lock
  runtime/common/src/attestations.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#1017 Offchain signing followup
  runtime/common/src/parachains.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#1021 Enable ValidateUnsigned For Westend Runtime.
  runtime/westend/src/lib.rs
Labels: B2-breaksapi

#1022 Bump Westend `spec_version` after the latest runtime upgrade
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B1-silent, B2-breaksapi

#1026 Companion pr for Substrate #5741
  Cargo.lock
  parachain/src/wasm_executor/mod.rs
Labels: A0-pleasereview, B1-silent

#1016 [CI] Changelog generation: add westend spec version and check changes against labels
  scripts/gitlab/publish_draft_release.sh
Labels: B1-silent, M1-ci

#1030 Companion PR to #5695
  Cargo.lock
  runtime/common/src/crowdfund.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#1032 Fix github license detection
  README.md
  file_header.txt
Labels: A2-insubstantial, F5-documentation, M0-build

#1025 Companion PR for #5200
  parachain/src/wasm_executor/mod.rs
  runtime/test-runtime/client/src/lib.rs
Labels: B2-breaksapi

#1012 Companion PR for #5501 and #5680
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A7-companion, B2-breaksapi

#1023 Introduce `BlockExecutionWeight` and `ExtrinsicBaseWeight`
  Cargo.lock
  runtime/common/src/attestations.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/lib.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B2-breaksapi

#1011 Assign DB weights to all runtimes
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A8-mergewhengreen, B2-breaksapi

#1033 Add 2 channels to release announcements github action
  .github/workflows/release-bot.yml
Labels: A0-pleasereview, B1-silent, M1-ci

#1034 Add runtime benchmarking suite to all runtimes
  .gitlab-ci.yml
  Cargo.lock
  runtime/common/src/claims.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#1041 Companion PR for 5795
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  parachain/src/wasm_executor/mod.rs
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: B2-breaksapi

#1036 Update Weights for Claims Pallet
  runtime/common/src/claims.rs
Labels: A0-pleasereview, B2-breaksapi

#1039 Companion Substaret/5683
  Cargo.lock
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#1043 Update substrate, set new dev version
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B2-breaksapi

#1045 Fix some features handling
  parachain/Cargo.toml
  runtime/common/Cargo.toml
Labels: A0-pleasereview, B2-breaksapi

#1037 Drop sc-client
  Cargo.lock
  availability-store/Cargo.toml
  cli/Cargo.toml
  cli/src/command.rs
  collator/Cargo.toml
  collator/src/lib.rs
  network/Cargo.toml
  network/test/Cargo.toml
  network/test/src/lib.rs
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/adder/collator/src/main.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/test-runtime/client/Cargo.toml
  runtime/test-runtime/client/src/lib.rs
  service/Cargo.toml
  service/src/chain_spec.rs
  service/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi

#1048 Fix collator interfaces to make them work with Cumulus
  collator/src/lib.rs
Labels: A0-pleasereview

#1044 Companion PR for treasury weight update (merged) Fix polkadot with substrate master
  Cargo.lock
  runtime/common/src/crowdfund.rs
Labels: A2-insubstantial, A7-companion, B2-breaksapi

#1052 Remove ClientProvider in favour of PolkadotClient
  collator/src/lib.rs
  service/src/client.rs
  service/src/lib.rs
Labels: A0-pleasereview

#1053 Use correct executor for Westend
  service/src/lib.rs
Labels: A0-pleasereview, A8-mergewhengreen

#1035 Companion PR for #5647
  collator/src/lib.rs
  network/test/src/block_import.rs
  network/test/src/lib.rs
  service/src/lib.rs
Labels: A7-companion

#1054 remove ClientProvider import
  service/src/lib.rs
Labels: A2-insubstantial

#1055 Add bad runtime upgrade block to westend chainspec
  service/res/westend.json
Labels: A0-pleasereview, M4-core

#1056 Prep v0.7.32
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B2-breaksapi

#1057 add space to bottom of file to trigger license detection
  LICENSE
Labels: A2-insubstantial, F5-documentation

#1058 Update to latest Substrate master
  Cargo.lock
Labels: A0-pleasereview
