Repository paritytech/polkadot, pull requests merged in 2020-10, with the labels that each got.

#1773 Companion for https://github.com/paritytech/substrate/pull/7236
  Cargo.lock
  parachain/src/wasm_executor/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1770 implement remaining subsystem metrics
  Cargo.lock
  node/core/candidate-selection/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/network/bitfield-distribution/Cargo.toml
  node/network/bitfield-distribution/src/lib.rs
  node/network/pov-distribution/Cargo.toml
  node/network/pov-distribution/src/lib.rs
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1774 Derive `From` for `AllMessages` and simplify `send_msg`
  Cargo.lock
  node/overseer/src/lib.rs
  node/subsystem/Cargo.toml
  node/subsystem/src/messages.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1559 Parachains v1 registrar module.
  runtime/common/src/lib.rs
  runtime/common/src/paras_registrar.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras.rs
  runtime/rococo-v1/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1780 Remove Stale Upgrades
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1768 Companion for substrate/pull/7215
  Cargo.lock
  runtime/common/src/lib.rs
  runtime/common/src/paras_registrar.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo-v1/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C7-high, D2-breaksapi

#1782 Adjust max nominators down to 128 (from 256)
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#1781 add two node local net script
  scripts/two-node-local-net.sh
Labels: A2-insubstantial, A3-inprogress, B0-silent, C1-low

#1785 v0.8.25
  Cargo.lock
  Cargo.toml
  RELEASE.md
  cli/Cargo.toml
  erasure-coding/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo-v1/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1771 XCM: Land xcm-executor
  Cargo.lock
  Cargo.toml
  xcm/xcm-executor/Cargo.toml
  xcm/xcm-executor/src/assets.rs
  xcm/xcm-executor/src/config.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1787 Make collation an optional return
  node/collation-generation/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/validator_side.rs
  node/overseer/src/lib.rs
  node/primitives/src/lib.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/node/collators/collation-generation.md
Labels: A2-insubstantial, B0-silent, C1-low

#1786 Registrar v1 follow-ups
  runtime/common/src/paras_registrar.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/origin.rs
  runtime/parachains/src/paras.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1699 NetworkBridge: validator (authorities) discovery api
  Cargo.lock
  node/core/runtime-api/src/lib.rs
  node/network/bridge/Cargo.toml
  node/network/bridge/src/lib.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/validator_discovery.rs
  node/subsystem/src/messages.rs
  primitives/Cargo.toml
  primitives/src/v1.rs
  roadmap/implementers-guide/src/node/utility/network-bridge.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  runtime/kusama/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo-v1/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1788 collator: fix a typo
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/validator_side.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1778 chain-api subsystem: implement BlockHeader messsage
  node/core/chain-api/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/utility/chain-api.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#1789 Pass relay parent as argument when collating
  node/collation-generation/src/lib.rs
  node/overseer/src/lib.rs
  node/primitives/src/lib.rs
  roadmap/implementers-guide/src/node/collators/collation-generation.md
Labels: A2-insubstantial, B0-silent, C1-low

#1790 Advertise to already connected validators
  node/network/collator-protocol/src/collator_side.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1792 Use `Pin<Box<>>` for collation future
  node/collation-generation/src/lib.rs
  node/overseer/src/lib.rs
  node/primitives/src/lib.rs
  roadmap/implementers-guide/src/node/collators/collation-generation.md
Labels: A2-insubstantial, B0-silent, C1-low

#1793 XCM: Land XCM Builder
  Cargo.lock
  Cargo.toml
  parachain/src/primitives.rs
  xcm/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-builder/src/currency_adapter.rs
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/location_conversion.rs
  xcm/xcm-builder/src/origin_conversion.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1794 Make `AllSubsystems` usage easier in tests
  Cargo.lock
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/subsystem-test-helpers/Cargo.toml
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1610 Companion for substrate/pull/6896
  Cargo.lock
  runtime/common/src/impls.rs
  runtime/common/src/lib.rs
  runtime/common/src/paras_registrar.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo-v1/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1798 Update index.html
  cli/browser-demo/index.html
Labels: A2-insubstantial, B0-silent, C1-low

#1740 Update to work with async keystore – Companion PR for #7000
  Cargo.lock
  node/core/backing/Cargo.toml
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/Cargo.toml
  node/core/bitfield-signing/src/lib.rs
  node/core/provisioner/Cargo.toml
  node/core/provisioner/src/lib.rs
  node/network/availability-distribution/Cargo.toml
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/network/bitfield-distribution/Cargo.toml
  node/network/bitfield-distribution/src/lib.rs
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/lib.rs
  node/service/src/lib.rs
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/lib.rs
  primitives/Cargo.toml
  primitives/src/v0.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/inclusion.rs
Labels: A1-needsburnin, A3-inprogress, A7-companion, B1-releasenotes, C1-low

#1800 Companion PR for #7247 (incremental priority group updates)
  Cargo.lock
  node/network/bridge/src/lib.rs
  node/network/bridge/src/validator_discovery.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#1802 Remove `collating_for` argument from service
  cli/src/command.rs
  node/service/src/lib.rs
  node/test-service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1803 Rename `node_handles` to `overseer_handler`
  node/service/src/lib.rs
  node/test-service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1808 Make `with_client` public and change its signature
  node/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1805 Tweak Cargo.tomls to make burnin easier
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#1807 Revert "revert enabling authority discovery by default (#1532)"
  cli/src/cli.rs
  cli/src/command.rs
  node/service/src/lib.rs
  node/test-service/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low

#1809 [CI] bump matrix-message-action to v0.0.3
  .github/workflows/burnin-label-notification.yml
  .github/workflows/publish-draft-release.yml
  .github/workflows/release-bot.yml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1810 Companion for Substrate#7318
  Cargo.lock
  cli/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1817 test-runtime: fix indentation
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1801 Companion PR for 'Add missing fields to the light sync state #7225'
  Cargo.lock
  cli/src/cli.rs
  cli/src/command.rs
  node/service/src/lib.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, A7-companion, B0-silent, C1-low

#1819 av-store: create a db dir if missing
  node/core/av-store/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1762 runtime: remove finality-tracker
  Cargo.lock
  node/service/src/lib.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A1-needsburnin, B0-silent, C1-low, D2-breaksapi

#1811 Add ParasSudoWrapper to test-runtime and bring back register_parachain to test-service
  Cargo.lock
  node/test-service/Cargo.toml
  node/test-service/src/lib.rs
  runtime/parachains/src/paras.rs
  runtime/rococo-v1/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1791 Companion PR for Substrate #7233
  Cargo.lock
  runtime/kusama/src/weights/frame_system.rs
  runtime/kusama/src/weights/pallet_timestamp.rs
  runtime/kusama/src/weights/pallet_treasury.rs
  runtime/kusama/src/weights/pallet_utility.rs
  runtime/polkadot/src/weights/frame_system.rs
  runtime/polkadot/src/weights/pallet_timestamp.rs
  runtime/polkadot/src/weights/pallet_treasury.rs
  runtime/polkadot/src/weights/pallet_utility.rs
  runtime/westend/src/weights/frame_system.rs
  runtime/westend/src/weights/pallet_timestamp.rs
  runtime/westend/src/weights/pallet_utility.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1829 Companion for Substrate#7350
  Cargo.lock
  runtime/common/src/claims.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1754 Automation for new release process
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/publish-draft-release.yml
  .github/workflows/release-candidate.yml
  RELEASE.md
  scripts/github/generate_release_text.rb
  scripts/release.sh
Labels: A0-pleasereview, B0-silent, C1-low

#1825 Companion PR for substrate #7328
  Cargo.lock
  node/core/proposer/src/lib.rs
  node/service/src/lib.rs
  node/test-service/Cargo.toml
  node/test-service/src/lib.rs
  validation/src/block_production.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1841 chore: add cargo spellcheck configuration and custom topic specifc dictionary
  .config/lingua.dic
  .config/spellcheck.toml
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1812 Include audit status of runtime changes in release notes
  scripts/github/generate_release_text.rb
Labels: A0-pleasereview, B0-silent, C1-low

#1820 Availability store pruning
  Cargo.lock
  node/core/av-store/Cargo.toml
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/network/availability-distribution/src/lib.rs
  node/subsystem/src/messages.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1842 Runtime API for checking validation outputs
  node/core/backing/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/primitives/src/lib.rs
  node/subsystem/src/messages.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/node/utility/candidate-validation.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  runtime/kusama/src/lib.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo-v1/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1835 node/service/src/lib: Do not spawn authority discovery on sentries
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#1843 Update everything to latest wasm-builder
  Cargo.lock
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/build.rs
  parachain/test-parachains/halt/Cargo.toml
  parachain/test-parachains/halt/build.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/build.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/build.rs
  runtime/rococo-v1/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/build.rs
  runtime/westend/Cargo.toml
  runtime/westend/build.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#1847 [CI] fix release text generation
  scripts/github/generate_release_text.rb
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#1850 fix compilation on nightly
  Cargo.lock
  node/test/service/src/lib.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#1852 Expose the backend from a full node
  node/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1834 introduce errors with info
  Cargo.lock
  cli/Cargo.toml
  cli/src/lib.rs
  erasure-coding/Cargo.toml
  erasure-coding/src/lib.rs
  node/collation-generation/Cargo.toml
  node/collation-generation/src/error.rs
  node/core/av-store/Cargo.toml
  node/core/av-store/src/lib.rs
  node/core/backing/Cargo.toml
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/Cargo.toml
  node/core/bitfield-signing/src/lib.rs
  node/core/candidate-selection/Cargo.toml
  node/core/candidate-selection/src/lib.rs
  node/core/candidate-validation/Cargo.toml
  node/core/candidate-validation/src/lib.rs
  node/core/chain-api/src/lib.rs
  node/core/proposer/Cargo.toml
  node/core/proposer/src/lib.rs
  node/core/provisioner/Cargo.toml
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/tests.rs
  node/core/runtime-api/Cargo.toml
  node/core/runtime-api/src/lib.rs
  node/network/availability-distribution/Cargo.toml
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/network/bitfield-distribution/Cargo.toml
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/Cargo.toml
  node/network/bridge/src/lib.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/Cargo.toml
  node/network/collator-protocol/src/lib.rs
  node/network/pov-distribution/Cargo.toml
  node/network/pov-distribution/src/lib.rs
  node/network/pov-distribution/src/tests.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/lib.rs
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/lib.rs
  node/overseer/Cargo.toml
  node/overseer/src/lib.rs
  node/primitives/src/lib.rs
  node/service/src/lib.rs
  node/subsystem-test-helpers/Cargo.toml
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/validator_discovery.rs
  node/subsystem/Cargo.toml
  node/subsystem/src/errors.rs
  node/subsystem/src/lib.rs
  node/subsystem/src/messages.rs
  parachain/Cargo.toml
  validation/Cargo.toml
  validation/src/error.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#1851 Prep for v0.8.26: bump version & substrate
  .github/ISSUE_TEMPLATE/release.md
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  erasure-coding/Cargo.toml
  node/test/client/Cargo.toml
  node/test/service/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo-v1/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1857 test-runtime: use sp-std instead of rstd
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1860 Should check Duration subtraction
  node/core/av-store/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1821 Finish XCM Executor Assets w/ Tests
  xcm/xcm-executor/Cargo.toml
  xcm/xcm-executor/src/assets.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1775 Companion for #7188: Implement `batch_all` and update Utillity Pallet for Weight/Fee Refunds
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_utility.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_utility.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/pallet_utility.rs
Labels: B7-runtimenoteworthy, C1-low, D1-audited👍, D2-breaksapi

#1862 Fix proposer factory prometheus registration
  Cargo.lock
  node/core/proposer/Cargo.toml
  node/core/proposer/src/lib.rs
  node/service/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1838 Reconfigure on_initialize weight.
  Cargo.lock
  runtime/common/src/lib.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#1855 use color_eyre for its backtrace feature and error reporting
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1795 start working on building the real overseer
  Cargo.lock
  cli/src/browser.rs
  cli/src/command.rs
  node/core/av-store/Cargo.toml
  node/core/av-store/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/core/chain-api/src/lib.rs
  node/core/proposer/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  node/service/src/grandpa_support.rs
  node/service/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/Cargo.toml
  node/subsystem/src/lib.rs
  node/test/service/src/lib.rs
  runtime/rococo-v1/src/lib.rs
  scripts/two-node-local-net.sh
  tests/purge_chain_works.rs
Labels: A0-pleasereview, A1-needsburnin, B0-silent, C1-low

#1859 Downward Message Processing implementation
  core-primitives/src/lib.rs
  node/collation-generation/src/lib.rs
  node/core/av-store/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/primitives/src/lib.rs
  node/subsystem/src/messages.rs
  parachain/src/primitives.rs
  parachain/test-parachains/tests/adder/mod.rs
  parachain/test-parachains/tests/wasm_executor/mod.rs
  primitives/src/v1.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/router.rs
  runtime/parachains/src/router/dmp.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/util.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo-v1/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1866 Update to the latest changes on master
  node/core/runtime-api/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1867 Let go fees
  node/collation-generation/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/primitives/src/lib.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/node/collators/collation-generation.md
  roadmap/implementers-guide/src/types/candidate.md
Labels: A0-pleasereview, B0-silent, C1-low

#1868 Rollback spec_version and fix check_runtime
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
  scripts/gitlab/check_runtime.sh
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1870 remove the --disable-authority-discovery flag & related
  cli/src/cli.rs
  cli/src/command.rs
  node/service/src/lib.rs
  node/test/service/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1872 Collator protocol should choose side
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1874 Add key subcommand
  cli/src/cli.rs
  cli/src/command.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1871 remove error wrapper type
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  parachain/Cargo.toml
  parachain/src/wasm_executor/mod.rs
  src/main.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1878 Change SpawnedSubsystem type to log subsystem errors
  node/collation-generation/src/lib.rs
  node/core/av-store/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/core/chain-api/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/collator-protocol/src/lib.rs
  node/network/pov-distribution/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1836 Update Tips to go 100% to Author
  runtime/common/Cargo.toml
  runtime/common/src/impls.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#1884 Only use dummy subsystems in overseer
  node/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1747 Companion for substrate #7159
  Cargo.lock
  runtime/common/src/crowdfund.rs
  runtime/common/src/slots.rs
  xcm/xcm-builder/src/currency_adapter.rs
Labels: A7-companion, A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#1875 DMP follow-ups
  node/core/candidate-validation/src/lib.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/runtime/router.md
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/messages.md
  roadmap/implementers-guide/src/types/runtime.md
Labels: A0-pleasereview, B0-silent, C1-low

#1886 Make sure validator discovery works with a delayed peer to validator mapping
  node/network/bridge/src/lib.rs
  node/network/bridge/src/validator_discovery.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1887 [CI] Switch to using paritytech/srtool
  .github/workflows/publish-draft-release.yml
  scripts/github/polkadot_release.erb
Labels: A0-pleasereview, B0-silent, C1-low

#1784 Companion for #6912
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo-v1/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low, D2-breaksapi

#1691 Implementer's guide: Approval Voting Subsystem
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/README.md
  roadmap/implementers-guide/src/node/approval/README.md
  roadmap/implementers-guide/src/node/approval/approval-networking.md
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/node/approval/dispute-participation.md
  roadmap/implementers-guide/src/node/availability/availability-recovery.md
  roadmap/implementers-guide/src/protocol-approval.md
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/session_info.md
  roadmap/implementers-guide/src/types/approval.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  roadmap/implementers-guide/src/types/runtime.md
Labels: A0-pleasereview, B0-silent, C1-low, S1-Design

#1892 A real overseer feature
  Cargo.toml
  cli/Cargo.toml
  node/service/Cargo.toml
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1864 Adds test parachain adder collator
  Cargo.lock
  Cargo.toml
  node/core/av-store/src/lib.rs
  node/network/collator-protocol/src/lib.rs
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  node/service/src/lib.rs
  node/subsystem-util/src/lib.rs
  parachain/Cargo.toml
  parachain/src/primitives.rs
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/adder/collator/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
  parachain/test-parachains/adder/src/lib.rs
  parachain/test-parachains/adder/wasm/Cargo.toml
  parachain/test-parachains/tests/adder/mod.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/README.md
  runtime/rococo/build.rs
  runtime/rococo/src/constants.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1894 fix service build: enable notifications protocol only under real overseer
  node/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low
