Repository paritytech/polkadot, pull requests merged in 2020-07, with the labels that each got.

#1331 Allow voting in democracy
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B2-runtimenoteworthy, C1-low

#1296 Add registrar proxy
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B2-runtimenoteworthy, C1-low

#1266 Downward & Upward messages
  Cargo.lock
  Cargo.toml
  availability-store/src/lib.rs
  availability-store/src/store.rs
  collator/src/lib.rs
  core-primitives/Cargo.toml
  core-primitives/src/lib.rs
  network/src/protocol/tests.rs
  parachain/Cargo.toml
  parachain/src/primitives.rs
  parachain/src/wasm_api.rs
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/src/main.rs
  parachain/test-parachains/adder/src/wasm_validation.rs
  parachain/test-parachains/code-upgrader/Cargo.toml
  parachain/test-parachains/code-upgrader/src/wasm_validation.rs
  parachain/test-parachains/tests/adder/mod.rs
  parachain/test-parachains/tests/code_upgrader/mod.rs
  parachain/test-parachains/tests/lib.rs
  parachain/test-parachains/tests/wasm_executor/mod.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
  primitives/src/parachain.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  validation/src/error.rs
  validation/src/pipeline.rs
  validation/src/validation_service/mod.rs
Labels: A8-mergeoncegreen, B2-runtimenoteworthy, C1-low

#1299 Companion PR for Allow specify schedule dispatch origin #6387
  runtime/common/src/parachains.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#1335 Check candidate signatures before including them in `set_heads`
  runtime/common/src/parachains.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1341 Reduce Westend deposit requirements
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  cli/src/command.rs
  collator/Cargo.toml
  collator/src/lib.rs
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  network/test/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/src/main.rs
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/src/parachains.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/constants.rs
  runtime/westend/src/lib.rs
  service/Cargo.toml
  service/src/lib.rs
  statement-table/Cargo.toml
  validation/Cargo.toml
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview, A7-companion, B2-runtimenoteworthy, C1-low

#1353 Make a collator send a collation as backup as well
  Cargo.lock
  network/Cargo.toml
  network/src/legacy/local_collations.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1330 babe: enable equivocation reporting on all runtimes
  Cargo.lock
  node/service/src/lib.rs
  runtime/common/src/parachains.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low

#1320 implement custom proposer
  Cargo.lock
  Cargo.toml
  node/core/proposer/Cargo.toml
  node/core/proposer/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/subsystem/src/messages.rs
  primitives/src/parachain.rs
  roadmap/implementors-guide/src/node/utility/provisioner.md
  roadmap/implementors-guide/src/types/overseer-protocol.md
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1349 Companion for #6567 (Benchmark Writer CLI)
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, A7-companion, A8-mergeoncegreen, B0-silent, C1-low

#1351 Companion for #6576
  Cargo.lock
  runtime/common/src/claims.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low

#1326 Implement the Statement Distribution Subsystem
  Cargo.lock
  Cargo.toml
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/lib.rs
  node/primitives/src/lib.rs
  node/subsystem/src/messages.rs
  primitives/src/parachain.rs
  roadmap/implementors-guide/src/node/backing/statement-distribution.md
Labels: A0-pleasereview, B0-silent, C1-low

#1342 Convert SignedAvailabilityBitfields from newtype to typedef
  node/subsystem/src/messages.rs
  primitives/src/parachain.rs
  runtime/parachains/src/inclusion.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1367 Companion for #6589
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low

#1366 I am dumb and can't spell
  .gitlab-ci.yml
  availability-store/src/worker.rs
  node/overseer/src/lib.rs
  roadmap/implementers-guide/.gitignore
  roadmap/implementers-guide/README.md
  roadmap/implementers-guide/book.toml
  roadmap/implementers-guide/src/README.md
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/architecture.md
  roadmap/implementers-guide/src/further-reading.md
  roadmap/implementers-guide/src/glossary.md
  roadmap/implementers-guide/src/node/README.md
  roadmap/implementers-guide/src/node/availability/README.md
  roadmap/implementers-guide/src/node/availability/availability-distribution.md
  roadmap/implementers-guide/src/node/availability/bitfield-distribution.md
  roadmap/implementers-guide/src/node/availability/bitfield-signing.md
  roadmap/implementers-guide/src/node/backing/README.md
  roadmap/implementers-guide/src/node/backing/candidate-backing.md
  roadmap/implementers-guide/src/node/backing/candidate-selection.md
  roadmap/implementers-guide/src/node/backing/pov-distribution.md
  roadmap/implementers-guide/src/node/backing/statement-distribution.md
  roadmap/implementers-guide/src/node/collators/README.md
  roadmap/implementers-guide/src/node/collators/collation-distribution.md
  roadmap/implementers-guide/src/node/collators/collation-generation.md
  roadmap/implementers-guide/src/node/overseer.md
  roadmap/implementers-guide/src/node/subsystems-and-jobs.md
  roadmap/implementers-guide/src/node/utility/README.md
  roadmap/implementers-guide/src/node/utility/availability-store.md
  roadmap/implementers-guide/src/node/utility/candidate-validation.md
  roadmap/implementers-guide/src/node/utility/misbehavior-arbitration.md
  roadmap/implementers-guide/src/node/utility/network-bridge.md
  roadmap/implementers-guide/src/node/utility/peer-set-manager.md
  roadmap/implementers-guide/src/node/utility/provisioner.md
  roadmap/implementers-guide/src/node/utility/runtime-api.md
  roadmap/implementers-guide/src/node/validity/README.md
  roadmap/implementers-guide/src/parachains-overview.md
  roadmap/implementers-guide/src/runtime/README.md
  roadmap/implementers-guide/src/runtime/configuration.md
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/inclusioninherent.md
  roadmap/implementers-guide/src/runtime/initializer.md
  roadmap/implementers-guide/src/runtime/paras.md
  roadmap/implementers-guide/src/runtime/router.md
  roadmap/implementers-guide/src/runtime/scheduler.md
  roadmap/implementers-guide/src/runtime/validity.md
  roadmap/implementers-guide/src/types/README.md
  roadmap/implementers-guide/src/types/availability.md
  roadmap/implementers-guide/src/types/backing.md
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/chain.md
  roadmap/implementers-guide/src/types/messages.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  roadmap/implementers-guide/src/types/runtime.md
  roadmap/implementers-guide/src/whence-parachains.md
Labels: A2-insubstantial, B0-silent, C1-low

#1314 Companion for #6500 (decl_module: frame_system as default ident)
  Cargo.lock
  runtime/common/src/attestations.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/inclusion_inherent.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/scheduler.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1373 Companion for #6584
  Cargo.lock
  availability-store/Cargo.toml
  runtime/common/Cargo.toml
  runtime/polkadot/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low

#1350 Companion PR for #6564
  Cargo.lock
  cli/src/cli.rs
  cli/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1380 Update to substrate#59ee76a0
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#1379 Use `SpawnNamed` to give tasks names
  availability-store/src/lib.rs
  availability-store/src/worker.rs
  collator/src/lib.rs
  network/src/legacy/gossip/mod.rs
  network/src/protocol/mod.rs
  network/src/protocol/tests.rs
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1371 Companion for #6599
  Cargo.lock
  node/service/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C3-medium

#1352 Companion for #6575 (Add `WeightInfo`)
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/lib.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1377 Update the Kusama bootnode IDs
  service/res/kusama.json
Labels: A2-insubstantial, B0-silent, C1-low

#1382 Bump Substrate
  Cargo.lock
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1344 Implement PoV Distribution Subsystem
  Cargo.lock
  Cargo.toml
  node/network/README.md
  node/network/pov-distribution/Cargo.toml
  node/network/pov-distribution/src/lib.rs
  node/subsystem/src/messages.rs
  primitives/src/parachain.rs
  roadmap/implementers-guide/src/node/backing/pov-distribution.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1375 Remove AwaitCanceled
  network/Cargo.toml
  network/src/protocol/mod.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1258 Make a test crate to make the runtime-test usable
  Cargo.lock
  Cargo.toml
  network/test/src/block_import.rs
  node/service/src/grandpa_support.rs
  node/test-service/Cargo.toml
  node/test-service/src/chain_spec.rs
  node/test-service/src/lib.rs
  node/test-service/tests/build-blocks.rs
  node/test-service/tests/call-function.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/client/Cargo.toml
  runtime/test-runtime/client/src/lib.rs
  runtime/test-runtime/src/genesismap.rs
  runtime/test-runtime/src/lib.rs
  service/src/grandpa_support.rs
  service/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, B2-breaksapi, C3-medium, D2-breaksapi

#1354 Delay session changes' effects on parachains by 1 block
  roadmap/implementers-guide/src/runtime/README.md
  roadmap/implementers-guide/src/runtime/initializer.md
  runtime/parachains/src/initializer.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1384 Companion PR for ' Simplify a few chain components creation APIs related to the service'
  Cargo.lock
  node/service/src/lib.rs
  service/src/lib.rs
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low

#1386 Companion for #6620
  Cargo.lock
  cli/src/command.rs
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low

#1312 CandidateBackingSubsystem
  Cargo.lock
  Cargo.toml
  node/core/backing/Cargo.toml
  node/core/backing/src/lib.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/primitives/src/lib.rs
  node/subsystem/src/messages.rs
  primitives/src/parachain.rs
  roadmap/implementers-guide/src/node/backing/candidate-backing.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/scheduler.rs
  statement-table/src/generic.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1374 Integrate all (dummy) subsystems with the Overseer
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/service/src/lib.rs
  node/subsystem/src/lib.rs
  node/subsystem/src/messages.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1361 Add Process.toml
  Process.toml
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1370 add more detail to provisioner block production section
  roadmap/implementers-guide/src/node/utility/provisioner.md
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1389 Revert log rotation
  Cargo.lock
  cli/src/command.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1391 Introduce polling pallet
  Cargo.lock
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/poll.rs
Labels: A8-mergeoncegreen, B2-runtimenoteworthy, C1-low

#1397 Tweak poll end block
  runtime/polkadot/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1395 *: Enable authority discovery by default
  cli/src/cli.rs
  cli/src/command.rs
  node/service/src/lib.rs
  node/test-service/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C3-medium

#1398 ci: fix subdirectory upload to s3
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#1376 mod subsystem-util
  Cargo.lock
  node/core/backing/Cargo.toml
  node/core/backing/src/lib.rs
  node/subsystem/Cargo.toml
  node/subsystem/src/lib.rs
  node/subsystem/src/messages.rs
  node/subsystem/src/util.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1406 Bump Substrate & versions
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#1390 [CI] check_runtime.sh redux
  scripts/gitlab/check_runtime.sh
  scripts/gitlab/lib.sh
Labels: A0-pleasereview, B0-silent, C1-low

#1408 add assumptions made by the Node-side
  roadmap/implementers-guide/src/node/README.md
Labels: A0-pleasereview, B0-silent, C1-low

#1422 Enable Polkadot Council elections
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B2-runtimenoteworthy, C3-medium, D2-breaksapi

#1401 Runtime APIs for node-side code
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/runtime-api/README.md
  roadmap/implementers-guide/src/runtime/scheduler.md
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#1413 inclusion: split CandidatePendingAvailability according to the guide
  roadmap/implementers-guide/src/runtime/inclusion.md
  runtime/parachains/src/inclusion.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1421 Define BurnDestination, Kusama Treasury burns to Society (#6671)
  Cargo.lock
  runtime/common/src/crowdfund.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A9-companion-backlog, B2-runtimenoteworthy, C1-low, D2-breaksapi

#1407 runtime: update grandpa equivocation reporting api
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A9-companion-backlog, B0-silent, C1-low, D2-breaksapi

#1369 Pallet for Purchase
  runtime/common/src/lib.rs
  runtime/common/src/purchase.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B2-runtimenoteworthy, C1-low, D2-breaksapi, D9-needsaudit👮

#1429 Add Purchase to Westend
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1430 Use SpawnNamed instead of Spawn in Overseer
  Cargo.lock
  node/core/backing/Cargo.toml
  node/core/backing/src/lib.rs
  node/network/bridge/Cargo.toml
  node/network/bridge/src/lib.rs
  node/network/pov-distribution/Cargo.toml
  node/network/pov-distribution/src/lib.rs
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/lib.rs
  node/overseer/Cargo.toml
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/primitives/Cargo.toml
  node/primitives/src/lib.rs
  node/service/src/lib.rs
  node/subsystem/src/lib.rs
  node/subsystem/src/util.rs
  node/test-helpers/subsystem/Cargo.toml
  node/test-helpers/subsystem/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1372 CI Regression Test for determinism of our wasm runtimes
  .gitlab-ci.yml
  Cargo.lock
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1433 Bump version, enable full governance
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, B2-runtimenoteworthy, C1-low, D2-breaksapi

#1403 Add test suite and minor refinements to the utility subsystem
  Cargo.lock
  Cargo.toml
  node/core/backing/Cargo.toml
  node/core/backing/src/lib.rs
  node/network/bridge/Cargo.toml
  node/network/bridge/src/lib.rs
  node/network/pov-distribution/Cargo.toml
  node/network/pov-distribution/src/lib.rs
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/lib.rs
  node/subsystem/Cargo.toml
  node/subsystem/src/lib.rs
  node/subsystem/src/messages.rs
  node/subsystem/src/test_helpers.rs
  node/subsystem/src/util.rs
  node/test-helpers/subsystem/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low

#1427 Companion PR for substrate#6676
  Cargo.lock
Labels: A0-pleasereview, A2-insubstantial, A7-companion, B0-silent, C1-low

#1443 Enable transfers
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/poll.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, B2-runtimenoteworthy, C1-low, D2-breaksapi

#1447 readme: --force no longer required
  README.md
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#1444 Companion for #6695 make impl_outer_origin default to use frame_system
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/lib.rs
  runtime/common/src/parachains.rs
  runtime/common/src/purchase.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/parachains/src/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1439 Scheduler: handle timeouts for no group rotation
  roadmap/implementers-guide/src/types/runtime.md
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/scheduler.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1423 Companion PR
  Cargo.lock
  availability-store/Cargo.toml
  collator/src/lib.rs
  node/test-service/tests/build-blocks.rs
  node/test-service/tests/call-function.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
  scripts/gitlab/check_runtime.sh
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1431 Replace StartWork and StopWork with an ActiveLeavesUpdate signal
  roadmap/implementers-guide/src/node/availability/bitfield-signing.md
  roadmap/implementers-guide/src/node/backing/candidate-backing.md
  roadmap/implementers-guide/src/node/backing/pov-distribution.md
  roadmap/implementers-guide/src/node/overseer.md
  roadmap/implementers-guide/src/node/subsystems-and-jobs.md
  roadmap/implementers-guide/src/node/utility/availability-store.md
  roadmap/implementers-guide/src/node/utility/network-bridge.md
  roadmap/implementers-guide/src/node/utility/provisioner.md
  roadmap/implementers-guide/src/node/utility/runtime-api.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#1456 Bump Substrate, version
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#1454 Dont bring down the node if validation has failed
  node/core/backing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1448 Companion PR for `Remove the service builder`
  Cargo.lock
  node/service/src/lib.rs
  node/test-service/src/lib.rs
  service/src/lib.rs
Labels: A7-companion, A8-mergeoncegreen, A9-companion-backlog, B0-silent, C1-low, D2-breaksapi

#1368 implement bitfield distribution subsystem
  Cargo.lock
  Cargo.toml
  node/network/bitfield-distribution/Cargo.toml
  node/network/bitfield-distribution/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/availability/bitfield-distribution.md
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#1364 implement bitfield signing subsystem
  Cargo.lock
  Cargo.toml
  node/bitfield-signing/Cargo.toml
  node/bitfield-signing/src/lib.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/service/src/lib.rs
  node/subsystem/src/messages.rs
  parachain/src/primitives.rs
  roadmap/implementers-guide/src/node/availability/bitfield-signing.md
Labels: A0-pleasereview, B0-silent, C1-low

#1459 assign authorship to parity
  node/bitfield-signing/Cargo.toml
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#1442 Include a reference to the validation data in the candidate descriptor
  collator/src/lib.rs
  network/src/protocol/tests.rs
  node/core/backing/src/lib.rs
  node/primitives/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
  primitives/src/v0.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/runtime-api/README.md
  roadmap/implementers-guide/src/runtime/configuration.md
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/paras.md
  roadmap/implementers-guide/src/types/availability.md
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  validation/src/pipeline.rs
  validation/src/validation_service/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1465 move bitfield-signing crate to `node/core`
  Cargo.lock
  Cargo.toml
  node/core/bitfield-signing/Cargo.toml
  node/core/bitfield-signing/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1394 Companion PR for #6569
  cli/src/command.rs
  node/service/src/chain_spec.rs
  node/test-service/src/chain_spec.rs
  parachain/test-parachains/adder/build.rs
  parachain/test-parachains/adder/src/lib.rs
  parachain/test-parachains/code-upgrader/build.rs
  parachain/test-parachains/code-upgrader/src/lib.rs
  parachain/test-parachains/halt/build.rs
  parachain/test-parachains/halt/src/lib.rs
  parachain/test-parachains/tests/adder/mod.rs
  parachain/test-parachains/tests/code_upgrader/mod.rs
  parachain/test-parachains/tests/wasm_executor/mod.rs
  runtime/kusama/build.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/build.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/build.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/build.rs
  runtime/westend/src/lib.rs
  service/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1468 Update latest substrate master
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1469 Companion for #6726
  Cargo.lock
  network/src/protocol/tests.rs
  network/test/src/block_import.rs
  network/test/src/lib.rs
  node/core/backing/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/pov-distribution/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/subsystem/src/util.rs
  parachain/Cargo.toml
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/tests/adder/mod.rs
  parachain/test-parachains/tests/code_upgrader/mod.rs
  parachain/test-parachains/tests/wasm_executor/mod.rs
  runtime/test-runtime/client/src/lib.rs
  validation/src/collation.rs
  validation/src/pipeline.rs
  validation/src/shared_table/mod.rs
  validation/src/validation_service/mod.rs
Labels: B0-silent, C1-low

#1467 Refactor service to allow building full (and light) node matching chain spec
  cli/src/browser.rs
  cli/src/command.rs
  service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1458 add ActiveLeavesUpdate, remove StartWork, StopWork
  Cargo.lock
  node/core/backing/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/Cargo.toml
  node/network/bridge/src/lib.rs
  node/network/pov-distribution/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
  node/subsystem/Cargo.toml
  node/subsystem/src/lib.rs
  node/subsystem/src/util.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1445 Update comments in polkadot runtime
  runtime/polkadot/src/lib.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#1404 Availability store subsystem
  Cargo.lock
  Cargo.toml
  node/core/av-store/Cargo.toml
  node/core/av-store/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/pov-distribution/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
  node/subsystem/src/lib.rs
  node/subsystem/src/messages.rs
  node/subsystem/src/util.rs
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#1424 Availability store subsystem guide
  roadmap/implementers-guide/src/node/utility/availability-store.md
  roadmap/implementers-guide/src/runtime/scheduler.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#1475 Replace Process.toml with json
  Process.json
  Process.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1492 Fix `erasure_fetch_drop_also_drops_gossip_sender` test
  network/src/protocol/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1485 Add new Runtime API messages and make runtime API request fallible
  Cargo.lock
  node/core/backing/Cargo.toml
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/pov-distribution/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/subsystem/src/messages.rs
  node/subsystem/src/util.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1472 Companion PR for `Various small improvements to service construction.`.
  Cargo.lock
  node/network/bitfield-distribution/Cargo.toml
  node/service/src/lib.rs
  rpc/src/lib.rs
  service/src/lib.rs
Labels: A7-companion, A9-companion-backlog, B0-silent, C1-low, D2-breaksapi

#1489 Use the correct `TaskExecutor` in validation
  network/src/protocol/mod.rs
  validation/src/shared_table/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1490 add simple name derivation heuristic for JobManager Subsystem impl
  node/subsystem/src/util.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1491 Update scale codec to latest version to fix bug in future rustc version
  Cargo.lock
  availability-store/Cargo.toml
  collator/Cargo.toml
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  node/core/proposer/Cargo.toml
  node/network/bitfield-distribution/Cargo.toml
  node/network/bridge/Cargo.toml
  node/network/pov-distribution/Cargo.toml
  node/network/statement-distribution/Cargo.toml
  node/primitives/Cargo.toml
  node/service/Cargo.toml
  node/subsystem/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/client/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#1496 Update Substrate, bump versions, clean up sort
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/src/registrar.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/parachains/src/paras.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#1466 Fix bitfield signing
  node/core/av-store/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/subsystem/src/messages.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1499 Companion PR for `Add a `DefaultQueue` type alias to remove the need to use `sp_api::TransactionFor``
  Cargo.lock
  node/service/src/lib.rs
  service/src/lib.rs
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low

#1502 Add a default trie-memory-tracker feature to the cli
  Cargo.lock
  cli/Cargo.toml
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low

#1479 Update README docs related to local build
  README.md
Labels: A8-mergeoncegreen, B0-silent, C1-low, F5-documentation

#1493 [CI] Publish draft release redux
  .github/workflows/publish-draft-release.yml
  .gitlab-ci.yml
  scripts/github/generate_release_text.rb
  scripts/github/polkadot_release.erb
  scripts/gitlab/publish_draft_release.sh
Labels: A2-insubstantial, B0-silent, C1-low

#1425 Companion for #6610 (Balances Weight Trait)
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/balances.rs
  runtime/kusama/src/weights/mod.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/balances.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/tests/weights.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/balances.rs
  runtime/westend/src/weights/mod.rs
Labels: A0-pleasereview, A7-companion, B2-runtimenoteworthy, C1-low, D2-breaksapi

#1494 Implement the Runtime API subsystem
  Cargo.lock
  Cargo.toml
  node/core/runtime-api/Cargo.toml
  node/core/runtime-api/src/lib.rs
  node/subsystem/src/messages.rs
  primitives/src/v1.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1504 reduce slash defer durations
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, B2-runtimenoteworthy, C7-high, D2-breaksapi

#1432 Candidate Validation Subsystem
  Cargo.lock
  Cargo.toml
  node/core/candidate-validation/Cargo.toml
  node/core/candidate-validation/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/utility/candidate-validation.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#1506 [CI] Build wasm blob with srtool and include prop hashes and blobs in release notes
  .github/workflows/publish-draft-release.yml
  scripts/github/generate_release_text.rb
  scripts/github/lib.rb
  scripts/github/polkadot_release.erb
Labels: A2-insubstantial, B0-silent, C1-low

#1457 Guide: add a diagram for Inclusion Pipeline & Approval Subsystem
  roadmap/implementers-guide/src/parachains-overview.md
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, F5-documentation

#1452 guide: collator networking & subsystems
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/availability/availability-distribution.md
  roadmap/implementers-guide/src/node/availability/bitfield-distribution.md
  roadmap/implementers-guide/src/node/backing/pov-distribution.md
  roadmap/implementers-guide/src/node/backing/statement-distribution.md
  roadmap/implementers-guide/src/node/collators/collation-distribution.md
  roadmap/implementers-guide/src/node/collators/collation-generation.md
  roadmap/implementers-guide/src/node/collators/collator-protocol.md
  roadmap/implementers-guide/src/node/utility/network-bridge.md
  roadmap/implementers-guide/src/parachains-overview.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#1514 Print error message when collation failed
  collator/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, Q2-easy

#1505 Parachains-runtime
  Cargo.lock
  Cargo.toml
  primitives/src/v0.rs
  primitives/src/v1.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/build.rs
  runtime/rococo/src/constants.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low
