Repository paritytech/polkadot, pull requests merged in 2020-06, with the labels that each got.

#1175 Keep the table router for the lifetime of the validation instance alive
  network/src/protocol/mod.rs
  validation/src/error.rs
  validation/src/validation_service/mod.rs
Labels: A8-mergeoncegreen, B1-silent

#1178 Identity pallet
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B1-runtimenoteworthy, B2-breaksapi

#1179 Fix threads leakage by strictly depending on async-std 1.5.0
  Cargo.lock
Labels: A2-insubstantial, B1-silent

#1180 Remove old runtime requirements section, reorganize, and improve ToC
  roadmap/implementors-guide/guide.md
Labels: A2-insubstantial, B1-silent

#1152 Overseer
  Cargo.lock
  Cargo.toml
  overseer/Cargo.toml
  overseer/examples/minimal-example.rs
  overseer/src/lib.rs
Labels: A0-pleasereview, B1-silent

#1187 Update constraints
  runtime/polkadot/src/lib.rs
Labels: A2-insubstantial, B1-silent, B2-breaksapi

#1158 New parachain runtime skeleton
  Cargo.lock
  Cargo.toml
  roadmap/implementors-guide/guide.md
  runtime/parachains/Cargo.toml
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/scheduler.rs
  runtime/parachains/src/validity.rs
Labels: A8-mergeoncegreen, B1-silent, B2-breaksapi

#1184 Comanion for substrate/pull/6173
  Cargo.lock
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A7-companion, A8-mergeoncegreen, B2-breaksapi

#1189 note pruning of orphan blocks in the overseer description
  roadmap/implementors-guide/guide.md
Labels: A0-pleasereview

#1188 Adds start and stop work heartbeats.
  Cargo.lock
  overseer/Cargo.toml
  overseer/examples/minimal-example.rs
  overseer/src/lib.rs
Labels: A0-pleasereview, B1-silent

#1161 Add an overview of Validity subsystems
  roadmap/implementors-guide/validity-subsystems-overview.md
Labels: A0-pleasereview, B1-silent

#1190 Generalised proxies in Polkadot
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/constants.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/constants.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/constants.rs
  runtime/westend/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, B1-runtimenoteworthy, B2-breaksapi

#1196 Update to Substrate master
  Cargo.lock
Labels: A2-insubstantial, B1-silent

#1201 Backport #1179 and bump to 0.8.3
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B0-patchthis, B1-silent

#1200 establish new `node` folder for overseer, messages, and subsystems
  Cargo.lock
  Cargo.toml
  node/core/README.md
  node/messages/Cargo.toml
  node/messages/src/lib.rs
  node/network/README.md
  node/overseer/Cargo.toml
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
Labels: A0-pleasereview, A8-mergeoncegreen, B1-silent

#1176 Add exception to overseer communication and write up local and remote disputes
  roadmap/implementors-guide/guide.md
Labels: A0-pleasereview, B1-silent

#1206 Companion for Substrate #6123
  Cargo.lock
  service/src/lib.rs
Labels: A0-pleasereview, B1-silent

#1204 Companion PR for #6214
  Cargo.lock
  runtime/common/src/impls.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A7-companion, A9-companion-backlog, B1-runtimenoteworthy, B2-breaksapi

#1212 Companion for #6273 (Introduce stacked filtering)
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, A7-companion, B1-runtimenoteworthy, B2-breaksapi

#1216 v0.8.5
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, B1-silent, B2-breaksapi

#1203 [CI] Change git diff behaviour for generating release notes
  scripts/gitlab/lib.sh
Labels: A2-insubstantial, B1-silent, M1-ci

#1198 Admin facility to move claims with council permission.
  runtime/common/src/claims.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B1-runtimenoteworthy, B2-breaksapi

#1191 [CI] Fix release notification message, and add rustc version to release notes
  .github/workflows/release-bot.yml
  .gitlab-ci.yml
  scripts/gitlab/lib.sh
  scripts/gitlab/publish_draft_release.sh
Labels: B1-silent, M1-ci

#1219 Bump versions.
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B1-silent, B2-breaksapi

#1167 Companion PR to substrate/6178
  Cargo.lock
  service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B1-silent

#1220 v0.8.7 (pre)
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B1-silent, B2-breaksapi

#1215 companion pr for #6235
  Cargo.lock
  runtime/test-runtime/client/Cargo.toml
  runtime/test-runtime/client/src/lib.rs
Labels: A7-companion, B1-silent, B2-breaksapi

#1194 CI images were moved
  .gitlab-ci.yml
Labels: A7-companion, B1-silent, M1-ci

#1222 v0.8.7
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, A9-companion-backlog, B1-silent, B2-breaksapi, C1-low

#1245 service: update to latest ServiceBuilder changes
  Cargo.lock
  service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B1-silent, M4-core

#1246 Allow starting westend chain from start_collator
  collator/src/lib.rs
Labels: A0-pleasereview, B1-silent, C1-low

#1247 Convert guide from single markdown file to mdbook
  roadmap/implementors-guide/.gitignore
  roadmap/implementors-guide/README.md
  roadmap/implementors-guide/book.toml
  roadmap/implementors-guide/guide.md
  roadmap/implementors-guide/src/README.md
  roadmap/implementors-guide/src/SUMMARY.md
  roadmap/implementors-guide/src/architecture.md
  roadmap/implementors-guide/src/further-reading.md
  roadmap/implementors-guide/src/glossary.md
  roadmap/implementors-guide/src/node/README.md
  roadmap/implementors-guide/src/node/availability/README.md
  roadmap/implementors-guide/src/node/availability/availability-distribution.md
  roadmap/implementors-guide/src/node/availability/bitfield-distribution.md
  roadmap/implementors-guide/src/node/availability/bitfield-signing.md
  roadmap/implementors-guide/src/node/backing/README.md
  roadmap/implementors-guide/src/node/backing/candidate-backing.md
  roadmap/implementors-guide/src/node/backing/candidate-selection.md
  roadmap/implementors-guide/src/node/backing/pov-distribution.md
  roadmap/implementors-guide/src/node/backing/statement-distribution.md
  roadmap/implementors-guide/src/node/collators/README.md
  roadmap/implementors-guide/src/node/collators/collation-distribution.md
  roadmap/implementors-guide/src/node/collators/collation-generation.md
  roadmap/implementors-guide/src/node/overseer.md
  roadmap/implementors-guide/src/node/subsystems-and-jobs.md
  roadmap/implementors-guide/src/node/utility/README.md
  roadmap/implementors-guide/src/node/utility/availability-store.md
  roadmap/implementors-guide/src/node/utility/candidate-validation.md
  roadmap/implementors-guide/src/node/utility/misbehavior-arbitration.md
  roadmap/implementors-guide/src/node/utility/network-bridge.md
  roadmap/implementors-guide/src/node/utility/peer-set-manager.md
  roadmap/implementors-guide/src/node/utility/provisioner.md
  roadmap/implementors-guide/src/node/validity/README.md
  roadmap/implementors-guide/src/parachains-overview.md
  roadmap/implementors-guide/src/runtime/README.md
  roadmap/implementors-guide/src/runtime/configuration.md
  roadmap/implementors-guide/src/runtime/inclusion.md
  roadmap/implementors-guide/src/runtime/inclusioninherent.md
  roadmap/implementors-guide/src/runtime/initializer.md
  roadmap/implementors-guide/src/runtime/paras.md
  roadmap/implementors-guide/src/runtime/scheduler.md
  roadmap/implementors-guide/src/runtime/validity.md
  roadmap/implementors-guide/src/type-definitions.md
  roadmap/implementors-guide/src/whence-parachains.md
  roadmap/implementors-guide/validity-subsystems-overview.md
Labels: A0-pleasereview, B1-silent, C1-low

#1162 Scheduler Module
  Cargo.lock
  roadmap/implementors-guide/src/runtime/inclusioninherent.md
  roadmap/implementors-guide/src/runtime/paras.md
  roadmap/implementors-guide/src/runtime/scheduler.md
  runtime/parachains/Cargo.toml
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/scheduler.rs
Labels: A0-pleasereview, B1-silent, B2-breaksapi

#1234 New service initial commit
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/command.rs
  cli/src/lib.rs
  collator/Cargo.toml
  collator/src/lib.rs
  node/overseer/src/lib.rs
  node/service/Cargo.toml
  node/service/README.adoc
  node/service/src/chain_spec.rs
  node/service/src/client.rs
  node/service/src/grandpa_support.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B1-silent

#1252 Bump versions, tweak deposit costs.
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/constants.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/constants.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/constants.rs
  runtime/westend/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B1-runtimenoteworthy, B2-breaksapi, C1-low

#1257 update provisioner subsystem
  roadmap/implementors-guide/src/node/backing/candidate-backing.md
  roadmap/implementors-guide/src/node/utility/provisioner.md
  roadmap/implementors-guide/src/type-definitions.md
Labels: A0-pleasereview, B1-silent

#1226 Companion: remove IsCallable make use of introduced in-origin filtering
  Cargo.lock
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/lib.rs
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/mock.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A8-mergeoncegreen, A9-companion-backlog, B2-breaksapi, B2-runtimenoteworthy, C1-low, D9-needsaudit👮

#1267 [CI] Auto-label new PRs depending on status
  .github/workflows/auto-label-prs.yml
Labels: A0-pleasereview, B0-silent, C1-low

#1271 [CI] Fix autolabel
  .github/workflows/auto-label-prs.yml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1272 Change absolute links in Implementers's Guide to relative links
  roadmap/implementors-guide/src/architecture.md
  roadmap/implementors-guide/src/node/availability/availability-distribution.md
  roadmap/implementors-guide/src/node/availability/bitfield-distribution.md
  roadmap/implementors-guide/src/node/availability/bitfield-signing.md
  roadmap/implementors-guide/src/node/backing/candidate-backing.md
  roadmap/implementors-guide/src/node/backing/candidate-selection.md
  roadmap/implementors-guide/src/node/backing/pov-distribution.md
  roadmap/implementors-guide/src/node/backing/statement-distribution.md
  roadmap/implementors-guide/src/node/overseer.md
  roadmap/implementors-guide/src/node/subsystems-and-jobs.md
  roadmap/implementors-guide/src/node/utility/candidate-validation.md
  roadmap/implementors-guide/src/node/utility/provisioner.md
  roadmap/implementors-guide/src/node/validity/README.md
  roadmap/implementors-guide/src/parachains-overview.md
  roadmap/implementors-guide/src/runtime/README.md
  roadmap/implementors-guide/src/runtime/configuration.md
  roadmap/implementors-guide/src/runtime/inclusioninherent.md
  roadmap/implementors-guide/src/runtime/initializer.md
  roadmap/implementors-guide/src/runtime/scheduler.md
  roadmap/implementors-guide/src/runtime/validity.md
  roadmap/implementors-guide/src/type-definitions.md
Labels: B0-silent, C1-low

#1253 small tweaks to candidate selection
  roadmap/implementors-guide/src/node/backing/candidate-selection.md
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1273 v0.8.9
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, B2-breaksapi, C1-low

#1260 Companion PR for add system_dryRun #6300
  Cargo.lock
  rpc/Cargo.toml
  rpc/src/lib.rs
Labels: A0-pleasereview, A9-companion-backlog

#1277 v0.8.10 (Polkadot 10)
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  scripts/gitlab/check_runtime.sh
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#1259 [CI] Add criticality of release to release notes
  .gitlab-ci.yml
  scripts/gitlab/check_labels.sh
  scripts/gitlab/publish_draft_release.sh
Labels: A0-pleasereview, B0-silent, C1-low

#1264 Update guide candidate validation module
  roadmap/implementors-guide/src/node/utility/candidate-validation.md
  roadmap/implementors-guide/src/type-definitions.md
Labels: A0-pleasereview, B0-silent

#1278 Add some logging to the validation pipeline.
  validation/src/pipeline.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#1270 Various Guide Improvements
  roadmap/implementors-guide/src/SUMMARY.md
  roadmap/implementors-guide/src/node/availability/bitfield-distribution.md
  roadmap/implementors-guide/src/node/backing/candidate-backing.md
  roadmap/implementors-guide/src/node/backing/candidate-selection.md
  roadmap/implementors-guide/src/node/backing/statement-distribution.md
  roadmap/implementors-guide/src/node/overseer.md
  roadmap/implementors-guide/src/node/utility/availability-store.md
  roadmap/implementors-guide/src/node/utility/candidate-validation.md
  roadmap/implementors-guide/src/node/utility/network-bridge.md
  roadmap/implementors-guide/src/node/utility/provisioner.md
  roadmap/implementors-guide/src/node/utility/runtime-api.md
  roadmap/implementors-guide/src/runtime/configuration.md
  roadmap/implementors-guide/src/runtime/inclusioninherent.md
  roadmap/implementors-guide/src/runtime/scheduler.md
  roadmap/implementors-guide/src/type-definitions.md
  roadmap/implementors-guide/src/types/README.md
  roadmap/implementors-guide/src/types/availability.md
  roadmap/implementors-guide/src/types/backing.md
  roadmap/implementors-guide/src/types/candidate.md
  roadmap/implementors-guide/src/types/chain.md
  roadmap/implementors-guide/src/types/overseer-protocol.md
  roadmap/implementors-guide/src/types/runtime.md
Labels: A0-pleasereview, B0-silent, C1-low

#1265 Add some message types from subsystem definitions
  Cargo.lock
  Cargo.toml
  node/messages/Cargo.toml
  node/messages/src/lib.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/primitives/Cargo.toml
  node/primitives/src/lib.rs
  node/service/src/lib.rs
  primitives/src/lib.rs
  primitives/src/parachain.rs
  roadmap/implementors-guide/src/node/backing/statement-distribution.md
  roadmap/implementors-guide/src/types/overseer-protocol.md
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1263 Companion for substrate/pull/6334
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/impls.rs
  runtime/common/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A8-mergeoncegreen, A9-companion-backlog, B0-silent, B2-runtimenoteworthy, C1-low

#1274 Bump trie-db (Companion for substrate#6364)
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/parachains/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, A7-companion, B1-releasenotes

#1281 Revert yamux to 0.4.5
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#1279 Guide: router module
  roadmap/implementors-guide/src/SUMMARY.md
  roadmap/implementors-guide/src/runtime/inclusion.md
  roadmap/implementors-guide/src/runtime/initializer.md
  roadmap/implementors-guide/src/runtime/router.md
  roadmap/implementors-guide/src/types/messages.md
  roadmap/implementors-guide/src/types/runtime.md
Labels: A0-pleasereview, B0-silent, C1-low

#1242 Inclusion Module
  primitives/src/parachain.rs
  roadmap/implementors-guide/src/runtime/README.md
  roadmap/implementors-guide/src/runtime/inclusion.md
  roadmap/implementors-guide/src/runtime/inclusioninherent.md
  roadmap/implementors-guide/src/runtime/paras.md
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/inclusion_inherent.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/scheduler.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#1285 Update `libp2p-ping`.
  Cargo.lock
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1286 v0.8.11
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1291 remove CARGO_HOME caching as it's still broken
  .gitlab-ci.yml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1293 [CI] Don't autolabel insubstantial PRs 'pleasereview'
  .github/workflows/auto-label-prs.yml
Labels: A2-insubstantial, B0-silent, C1-low

#1297 Fix glossary link (snowballed)
  .gitlab-ci.yml
  roadmap/implementors-guide/README.md
  roadmap/implementors-guide/book.toml
  roadmap/implementors-guide/src/architecture.md
  roadmap/implementors-guide/src/glossary.md
  roadmap/implementors-guide/src/node/availability/availability-distribution.md
  roadmap/implementors-guide/src/node/availability/bitfield-distribution.md
  roadmap/implementors-guide/src/node/availability/bitfield-signing.md
  roadmap/implementors-guide/src/node/backing/candidate-backing.md
  roadmap/implementors-guide/src/node/backing/candidate-selection.md
  roadmap/implementors-guide/src/node/backing/pov-distribution.md
  roadmap/implementors-guide/src/node/backing/statement-distribution.md
  roadmap/implementors-guide/src/node/overseer.md
  roadmap/implementors-guide/src/node/subsystems-and-jobs.md
  roadmap/implementors-guide/src/node/utility/availability-store.md
  roadmap/implementors-guide/src/node/utility/candidate-validation.md
  roadmap/implementors-guide/src/node/utility/network-bridge.md
  roadmap/implementors-guide/src/node/utility/provisioner.md
  roadmap/implementors-guide/src/node/utility/runtime-api.md
  roadmap/implementors-guide/src/node/validity/README.md
  roadmap/implementors-guide/src/parachains-overview.md
  roadmap/implementors-guide/src/runtime/README.md
  roadmap/implementors-guide/src/runtime/configuration.md
  roadmap/implementors-guide/src/runtime/inclusioninherent.md
  roadmap/implementors-guide/src/runtime/initializer.md
  roadmap/implementors-guide/src/runtime/scheduler.md
  roadmap/implementors-guide/src/runtime/validity.md
  roadmap/implementors-guide/src/types/availability.md
  roadmap/implementors-guide/src/types/backing.md
  roadmap/implementors-guide/src/types/candidate.md
  roadmap/implementors-guide/src/types/overseer-protocol.md
Labels: A2-insubstantial, B0-silent, C1-low, F5-documentation

#1283 signed wrapper
  node/messages/src/lib.rs
  node/primitives/src/lib.rs
  primitives/src/parachain.rs
  roadmap/implementors-guide/src/node/backing/statement-distribution.md
  roadmap/implementors-guide/src/types/availability.md
  roadmap/implementors-guide/src/types/backing.md
  roadmap/implementors-guide/src/types/overseer-protocol.md
  runtime/common/src/parachains.rs
  runtime/common/src/registrar.rs
  runtime/parachains/src/inclusion.rs
  statement-table/src/lib.rs
  validation/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1289 [CI] Refactor publish_draft_release.sh
  scripts/gitlab/check_labels.sh
  scripts/gitlab/lib.sh
  scripts/gitlab/publish_draft_release.sh
Labels: A0-pleasereview, B0-silent, C1-low

#1292 node: spawn babe and grandpa as blocking tasks
  Cargo.lock
  node/service/src/lib.rs
  service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#1294 Expand PoV Distribution section and improve candidate types
  roadmap/implementors-guide/src/node/availability/availability-distribution.md
  roadmap/implementors-guide/src/node/backing/candidate-backing.md
  roadmap/implementors-guide/src/node/backing/pov-distribution.md
  roadmap/implementors-guide/src/node/backing/statement-distribution.md
  roadmap/implementors-guide/src/runtime/inclusion.md
  roadmap/implementors-guide/src/runtime/router.md
  roadmap/implementors-guide/src/types/availability.md
  roadmap/implementors-guide/src/types/backing.md
  roadmap/implementors-guide/src/types/candidate.md
  roadmap/implementors-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#1210 Companion for Substrate #6269 (nested storage tx)
  Cargo.lock
  parachain/src/wasm_executor/mod.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, A9-companion-backlog, B1-releasenotes, C3-medium

#1287 Companion PR for https://github.com/paritytech/substrate/pull/6400
  Cargo.lock
  collator/src/lib.rs
Labels: A8-mergeoncegreen, A9-companion-backlog, B0-silent, C1-low

#1303 Make Proxy `NonTransfer` filter explicit
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B2-runtimenoteworthy, C3-medium

#1302 Update staking reward curves
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B2-runtimenoteworthy, C1-low

#1309 Make `produce_candidate` return an `Option`
  collator/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1307 Companion PR for `Fix the browser node and ensure it doesn't colour the informant output` #6457
  cli/src/command.rs
  collator/src/lib.rs
  node/service/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
  service/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#1298 Exploration of using graphwiz
  roadmap/implementors-guide/.gitignore
  roadmap/implementors-guide/README.md
  roadmap/implementors-guide/book.toml
  roadmap/implementors-guide/src/architecture.md
  roadmap/implementors-guide/src/parachains-overview.md
Labels: A3-inprogress, B0-silent, C1-low

#1306 CheckEra -> CheckMortality
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A7-companion, A8-mergeoncegreen, B0-silent, C1-low

#1284 Companion PR for #6386 (Read/Write Tracking)
  Cargo.lock
  parachain/src/wasm_executor/mod.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#1315 Companion for #6503
  Cargo.lock
  Cargo.toml
  availability-store/Cargo.toml
  cli/Cargo.toml
  collator/Cargo.toml
  erasure-coding/Cargo.toml
  network/Cargo.toml
  network/test/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  service/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A9-companion-backlog, B0-silent, C1-low

#1324 [CI] Add Github Action to notify devops of PRs labelled with A1-needsburnin
  .github/workflows/burnin-label-notification.yml
Labels: A0-pleasereview, B0-silent, C1-low

#1288 Companion PR for `Remove the service, replacing it with a struct of individual chain components`
  Cargo.lock
  cli/src/browser.rs
  cli/src/command.rs
  cli/src/lib.rs
  collator/src/lib.rs
  node/service/src/lib.rs
  service/src/lib.rs
Labels: A7-companion, A9-companion-backlog, B0-silent, C1-low

#1280 Implement Network Bridge
  Cargo.lock
  Cargo.toml
  node/network/bridge/Cargo.toml
  node/network/bridge/src/lib.rs
  node/overseer/Cargo.toml
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/primitives/Cargo.toml
  node/primitives/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/subsystem/Cargo.toml
  node/subsystem/src/lib.rs
  node/subsystem/src/messages.rs
  node/test-helpers/subsystem/Cargo.toml
  node/test-helpers/subsystem/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#1329 Companion for Substrate #6508
  Cargo.lock
  network/test/src/block_import.rs
  network/test/src/lib.rs
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low

#1321 Companion for #6511
  runtime/kusama/src/lib.rs
Labels: A7-companion, A8-mergeoncegreen, A9-companion-backlog, B2-runtimenoteworthy, C1-low

#1328 Use spawner to spawn work task instead of tokio
  collator/src/lib.rs
Labels: A5-grumble, B0-silent, C1-low

#1325 Subsystem::start takes self by-value
  node/network/bridge/src/lib.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/service/src/lib.rs
  node/subsystem/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low
