Repository paritytech/polkadot, pull requests merged in 2020-12, with the labels that each got.

#2049 execute_with_client: add 'static bound for Backend
  node/service/src/client.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#2051 adder-collator cli flags
  parachain/test-parachains/adder/collator/src/cli.rs
  parachain/test-parachains/adder/collator/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2042 Cadidate selection check assignment
  Cargo.lock
  node/core/candidate-selection/Cargo.toml
  node/core/candidate-selection/src/lib.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2011 guide: Availability Recovery
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/node/availability/availability-recovery.md
  roadmap/implementers-guide/src/types/network.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#2057 Use correct logging target for network bridge
  node/network/bridge/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2052 be more careful about fusing in `select!`
  node/collation-generation/src/lib.rs
  node/core/backing/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2056 Make it possible for the adder collator to calculate any state
  parachain/test-parachains/adder/collator/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2058 minor cleanup
  node/network/collator-protocol/src/collator_side.rs
  node/subsystem-util/src/validator_discovery.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2048 Companion PR for removing register notif protocol
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#1832 Fix locked ksm in council votes.
  runtime/kusama/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi, F2-bug

#2064 Fix Broken Build (Trait -> Config)
  runtime/kusama/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#1985 companion for substrate#7474
  Cargo.lock
  cli/src/command.rs
  node/test/service/src/lib.rs
  parachain/test-parachains/adder/collator/tests/integration.rs
Labels: A7-companion, B0-silent, C1-low

#1909 do not store backed candidates in the provisioner
  node/core/backing/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/src/messages.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/node/backing/candidate-backing.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#2068 Useless modules and misspellings
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/validity.rs
Labels: A7-looksgoodcantmerge, B0-silent, C1-low

#2067 Sudo utility for establishing an HRMP channel
  runtime/common/src/paras_sudo_wrapper.rs
  runtime/parachains/src/hrmp.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2071 Add tracing for candidate validation failures in backing
  node/core/backing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2069 Add an upper number of maximum parallel runtime api requests
  node/core/runtime-api/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2079 Update release documentation + checklist
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/publish-draft-release.yml
  .github/workflows/release-candidate.yml
  RELEASE.md
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#2080 Fix tests on master
  node/core/backing/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/tests.rs
  node/overseer/src/lib.rs
  node/test/service/tests/build-blocks.rs
  primitives/src/v1.rs
  scripts/gitlab/test_linux_stable.sh
Labels: A0-pleasereview, B0-silent, C1-low

#2082 Bump substrate, and bump version to v0.8.27
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  erasure-coding/Cargo.toml
  node/test/client/Cargo.toml
  node/test/service/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2081 Rework `ConnectionsRequests`
  node/network/collator-protocol/src/collator_side.rs
  node/network/pov-distribution/src/lib.rs
  node/subsystem-util/src/validator_discovery.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2084 Do not spam when we can not send a message to a job
  node/subsystem-util/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2053 add a brief description of goals of the GRANDPA voting rule
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/grandpa-voting-rule.md
Labels: A0-pleasereview, B0-silent, C1-low

#1420 Companion for #6629 (weight params refactor)
  Cargo.lock
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/impls.rs
  runtime/common/src/lib.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/constants.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/polkadot/src/constants.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/constants.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/constants.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, B2-breaksapi, C1-low, D2-breaksapi

#2087 Adds consistency checks for the `HostConfiguration`
  node/service/src/chain_spec.rs
  node/test/service/src/chain_spec.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/runtime-api/validator-groups.md
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/scheduler.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2077 Companion for #7671 (child trie deletion host function)
  Cargo.lock
  parachain/src/wasm_executor/mod.rs
  runtime/common/src/crowdfund.rs
Labels: A7-companion, A9-companion-backlog, B0-silent, C1-low, D2-breaksapi

#2083 Companion to "Expand remote keystore interface to allow for hybrid mode"
  Cargo.lock
  node/test/service/src/lib.rs
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low

#2099 runtime/session_info: avoid heavy loop when introduced on a live chain
  runtime/parachains/src/session_info.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2096 Cargo.lock: Update to async-tls 0.10.2
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low

#2097 [WIP] Update weights in prep for v0.8.27
  runtime/kusama/src/weights/pallet_balances.rs
  runtime/kusama/src/weights/pallet_collective.rs
  runtime/kusama/src/weights/pallet_democracy.rs
  runtime/kusama/src/weights/pallet_elections_phragmen.rs
  runtime/kusama/src/weights/pallet_identity.rs
  runtime/kusama/src/weights/pallet_im_online.rs
  runtime/kusama/src/weights/pallet_indices.rs
  runtime/kusama/src/weights/pallet_multisig.rs
  runtime/kusama/src/weights/pallet_proxy.rs
  runtime/kusama/src/weights/pallet_scheduler.rs
  runtime/kusama/src/weights/pallet_session.rs
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/kusama/src/weights/pallet_timestamp.rs
  runtime/kusama/src/weights/pallet_treasury.rs
  runtime/kusama/src/weights/pallet_utility.rs
  runtime/kusama/src/weights/pallet_vesting.rs
  runtime/polkadot/src/weights/pallet_balances.rs
  runtime/polkadot/src/weights/pallet_collective.rs
  runtime/polkadot/src/weights/pallet_democracy.rs
  runtime/polkadot/src/weights/pallet_elections_phragmen.rs
  runtime/polkadot/src/weights/pallet_identity.rs
  runtime/polkadot/src/weights/pallet_im_online.rs
  runtime/polkadot/src/weights/pallet_indices.rs
  runtime/polkadot/src/weights/pallet_multisig.rs
  runtime/polkadot/src/weights/pallet_proxy.rs
  runtime/polkadot/src/weights/pallet_scheduler.rs
  runtime/polkadot/src/weights/pallet_session.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/polkadot/src/weights/pallet_timestamp.rs
  runtime/polkadot/src/weights/pallet_treasury.rs
  runtime/polkadot/src/weights/pallet_utility.rs
  runtime/polkadot/src/weights/pallet_vesting.rs
  runtime/westend/src/weights/pallet_balances.rs
  runtime/westend/src/weights/pallet_identity.rs
  runtime/westend/src/weights/pallet_im_online.rs
  runtime/westend/src/weights/pallet_indices.rs
  runtime/westend/src/weights/pallet_multisig.rs
  runtime/westend/src/weights/pallet_proxy.rs
  runtime/westend/src/weights/pallet_scheduler.rs
  runtime/westend/src/weights/pallet_session.rs
  runtime/westend/src/weights/pallet_staking.rs
  runtime/westend/src/weights/pallet_timestamp.rs
  runtime/westend/src/weights/pallet_utility.rs
  runtime/westend/src/weights/pallet_vesting.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2107 addition error definitions
  Cargo.lock
  cli/src/command.rs
  node/core/av-store/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/subsystem/src/lib.rs
  node/test/service/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2102 session_info: store the assigment ids
  runtime/parachains/src/session_info.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2106 session_ info: small fixes
  runtime/parachains/src/session_info.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2092 Add assignment keys to session keys, no separate approvals key
  node/service/src/chain_spec.rs
  node/test/service/src/chain_spec.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/protocol-approval.md
  roadmap/implementers-guide/src/runtime/session_info.md
  roadmap/implementers-guide/src/types/approval.md
  runtime/common/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/session_info.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  scripts/prepare-test-net.sh
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2113 refactor availability dist tests
  Cargo.lock
  node/network/availability-distribution/Cargo.toml
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
Labels: A3-inprogress, B0-silent, C1-low

#1934 Add Basic XCM
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/paras_sudo_wrapper.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/ump.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2111 Approval types
  Cargo.lock
  node/primitives/Cargo.toml
  node/primitives/src/approval.rs
  node/primitives/src/lib.rs
  roadmap/implementers-guide/src/types/approval.md
Labels: A0-pleasereview, B0-silent, C1-low

#2120 [CI] Fix check_line_width.sh
  scripts/gitlab/check_line_width.sh
Labels: A0-pleasereview, B0-silent, C1-low

#2025 Companion for #7536 (Pallet Treasury Refactor)
  Cargo.lock
  node/service/src/chain_spec.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/impls.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_bounties.rs
  runtime/kusama/src/weights/pallet_tips.rs
  runtime/kusama/src/weights/pallet_treasury.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_bounties.rs
  runtime/polkadot/src/weights/pallet_tips.rs
  runtime/polkadot/src/weights/pallet_treasury.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi

#2121 Add logging to collation-generation
  node/collation-generation/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2089 Reward validators for participating in parachains
  roadmap/implementers-guide/src/runtime/inclusion.md
  runtime/common/src/paras_registrar.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/reward_points.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2125 CI: buildah to build images
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#2127 Improve Jaeger errors and debugging experience
  node/subsystem/src/errors.rs
  node/subsystem/src/jaeger.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2129 guide: minor fixes approval distribution
  roadmap/implementers-guide/src/node/approval/approval-distribution.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A2-insubstantial, B0-silent, C1-low

#2128 refactor View to include finalized_number
  node/collation-generation/src/lib.rs
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/core/chain-api/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/pov-distribution/src/lib.rs
  node/network/pov-distribution/src/tests.rs
  node/network/protocol/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/src/lib.rs
  primitives/src/v0.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/node/utility/network-bridge.md
  runtime/parachains/src/inclusion.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2104 Fix bug and further optimizations in availability distribution
  Cargo.lock
  node/core/av-store/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/network/availability-distribution/Cargo.toml
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/availability/availability-distribution.md
Labels: A0-pleasereview, B0-silent, C1-low

#2132 add better spans for unbacked candidates
  node/core/backing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2135 adjust span names
  node/core/bitfield-signing/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/proposer/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2136 address review comments from 2104
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2134 Add candidate info to OccupiedCore
  node/core/bitfield-signing/src/lib.rs
  node/core/provisioner/src/tests.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/node/availability/bitfield-signing.md
  roadmap/implementers-guide/src/runtime-api/availability-cores.md
  roadmap/implementers-guide/src/runtime/inclusion.md
  runtime/kusama/src/lib.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2137 remove `FixCouncilHistoricalVotes`
  runtime/kusama/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2140 Fix Jaeger service name
  node/subsystem/src/jaeger.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2142 fix bug where we over-eagerly remove backing spans for candidates we validate ourselves
  node/core/backing/src/lib.rs
  node/primitives/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2144 Some typos and misspellings in docs I found, during my studies.
  node/core/backing/src/lib.rs
  node/overseer/src/lib.rs
  roadmap/implementers-guide/src/node/README.md
Labels: A0-pleasereview, B0-silent, C1-low

#2141 Rococo V1
  Cargo.lock
  node/service/res/rococo.json
  runtime/rococo/src/constants.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2145 avoid creating duplicate unbacked spans when we see extra statements
  node/core/backing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2148 overseer: observe stalled subsystems and shut down
  node/overseer/src/lib.rs
  node/subsystem/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2146 Fix statement distribution: forward statements to other peers.
  node/network/statement-distribution/src/lib.rs
  node/subsystem/src/jaeger.rs
  roadmap/implementers-guide/src/node/backing/statement-distribution.md
Labels: A0-pleasereview, B0-silent, C1-low

#2123 Do not use rely on the block initialization when calling runtime APIs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/runtime/scheduler.md
  runtime/common/src/paras_registrar.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/scheduler.rs
  runtime/parachains/src/util.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2143 Alter behavior of `max_validators_per_core`
  roadmap/implementers-guide/src/runtime/scheduler.md
  runtime/parachains/src/scheduler.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2167 Support variable session length for Rococo chains at genesis
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  runtime/rococo/src/constants.rs
  runtime/rococo/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#2170 Companion for #7789 (BabeApi::current_epoch)
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, A7-companion, B7-runtimenoteworthy, C3-medium, D2-breaksapi

#2159 Companion for Substrate#7775
  Cargo.lock
  cli/src/command.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#2147 Allow council to slash treasury tip
  Cargo.lock
  runtime/kusama/src/weights/pallet_tips.rs
  runtime/polkadot/src/weights/pallet_tips.rs
Labels: B7-runtimenoteworthy, C1-low, D2-breaksapi

#2180 Companion for Substrate#7795
  Cargo.lock
  cli/Cargo.toml
  cli/src/command.rs
  node/test/service/tests/build-blocks.rs
  parachain/test-parachains/adder/collator/tests/integration.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2171 Migrate Claims Pallet to WeightInfo
  Cargo.lock
  runtime/common/src/claims.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/runtime_common_claims.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/runtime_common_claims.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2182 Companion for #7810 (Define ss58 prefix inside the runtime)
  Cargo.lock
  parachain/src/wasm_executor/mod.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdfund.rs
  runtime/common/src/impls.rs
  runtime/common/src/lib.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B7-runtimenoteworthy, C1-low, D2-breaksapi
