Repository paritytech/polkadot, pull requests merged in 2021-03, with the labels that each got.

#2489 Add Xcm sender.
  runtime/common/src/lib.rs
  runtime/common/src/xcm_sender.rs
  runtime/parachains/src/dmp.rs
  runtime/rococo/src/lib.rs
  xcm/src/v0/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2522 Companion for init the `RuntimeLogger` automatically
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/inclusion_inherent.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/ump.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  xcm/xcm-executor/Cargo.toml
  xcm/xcm-executor/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2538 subsystem for issuing background connection requests
  Cargo.lock
  Cargo.toml
  node/network/bridge/src/lib.rs
  node/network/gossip-support/Cargo.toml
  node/network/gossip-support/src/lib.rs
  node/overseer/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/subsystem/src/messages.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2549 Initialize telemetry earlier
  node/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2548 Companion for `ExecuteBlock` changes in Substrate
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#2552 Whole subsystem test for new availability-distribution
  .gitlab-ci.yml
  Cargo.lock
  node/network/availability-distribution/Cargo.toml
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/requester/fetch_task/tests.rs
  node/network/availability-distribution/src/session_cache.rs
  node/network/availability-distribution/src/tests.rs
  node/network/availability-distribution/src/tests/mock.rs
  node/network/availability-distribution/src/tests/mod.rs
  node/network/availability-distribution/src/tests/state.rs
  node/subsystem-test-helpers/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2557 bump spec versions in kusama, polkadot and westend again
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#2556 Fix links in docs.
  roadmap/implementers-guide/src/node/availability/availability-distribution.md
Labels: A2-insubstantial, B0-silent, C1-low

#2559 Jaeger spans for availability distribution
  node/jaeger/src/lib.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/tests.rs
  node/network/availability-distribution/src/requester/mod.rs
  node/network/availability-distribution/src/responder.rs
  node/network/availability-distribution/src/session_cache.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2565 add log message when real-overseer is enabled
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2563 Print an error if a collator connects to a node without real-overseer
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2569 Make warning nicer
  node/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2575 Substrate companion #8275
  Cargo.lock
  node/service/src/chain_spec.rs
  node/test/service/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2576 XCM: Location Conversion for AccountKey20
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/location_conversion.rs
  xcm/xcm-builder/src/origin_conversion.rs
Labels: B0-silent, C1-low

#2583 Mostly, let guide reflect #2579
  node/core/backing/src/lib.rs
  roadmap/implementers-guide/src/node/backing/statement-distribution.md
Labels: A2-insubstantial, B0-silent, C1-low

#2589 Make Substrate deps uniform
  bridges/bin/millau/node/Cargo.toml
  bridges/bin/millau/runtime/Cargo.toml
  bridges/bin/rialto/node/Cargo.toml
  bridges/bin/rialto/runtime/Cargo.toml
  bridges/bin/runtime-common/Cargo.toml
  bridges/modules/call-dispatch/Cargo.toml
  bridges/modules/currency-exchange/Cargo.toml
  bridges/modules/ethereum-contract/builtin/Cargo.toml
  bridges/modules/ethereum/Cargo.toml
  bridges/modules/finality-verifier/Cargo.toml
  bridges/modules/message-lane/Cargo.toml
  bridges/modules/message-lane/rpc/Cargo.toml
  bridges/modules/shift-session-manager/Cargo.toml
  bridges/modules/substrate/Cargo.toml
  bridges/primitives/currency-exchange/Cargo.toml
  bridges/primitives/ethereum-poa/Cargo.toml
  bridges/primitives/header-chain/Cargo.toml
  bridges/primitives/kusama/Cargo.toml
  bridges/primitives/message-lane/Cargo.toml
  bridges/primitives/millau/Cargo.toml
  bridges/primitives/polkadot/Cargo.toml
  bridges/primitives/rialto/Cargo.toml
  bridges/primitives/runtime/Cargo.toml
  bridges/primitives/test-utils/Cargo.toml
  bridges/relays/ethereum/Cargo.toml
  bridges/relays/kusama-client/Cargo.toml
  bridges/relays/millau-client/Cargo.toml
  bridges/relays/polkadot-client/Cargo.toml
  bridges/relays/rialto-client/Cargo.toml
  bridges/relays/substrate-client/Cargo.toml
  bridges/relays/substrate/Cargo.toml
  bridges/relays/utils/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#2580 Replace XCM `Error::Undefined` usage
  xcm/src/v0/traits.rs
  xcm/xcm-builder/src/currency_adapter.rs
  xcm/xcm-executor/src/traits.rs
Labels: B0-silent, C1-low

#2585 Add some magic to signed statements and approval votes
  node/core/approval-voting/src/lib.rs
  node/core/backing/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/primitives/src/lib.rs
  primitives/src/v0.rs
  statement-table/src/generic.rs
  statement-table/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2586 Configurable maximum validators
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/initializer.md
  roadmap/implementers-guide/src/runtime/scheduler.md
  roadmap/implementers-guide/src/runtime/session_info.md
  roadmap/implementers-guide/src/runtime/shared.md
  roadmap/implementers-guide/src/types/runtime.md
  runtime/common/src/paras_registrar.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/scheduler.rs
  runtime/parachains/src/session_info.rs
  runtime/parachains/src/shared.rs
  runtime/parachains/src/util.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2578 Substrate companion #8280
  Cargo.lock
  node/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2467 Companion PR for substrate PR 8072 - Add a config field to babe epochs
  Cargo.lock
  node/core/approval-voting/src/import.rs
  node/core/runtime-api/src/lib.rs
  node/primitives/src/lib.rs
  node/service/src/chain_spec.rs
  node/test/service/src/chain_spec.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B2-breaksapi, B7-runtimenoteworthy, C1-low, D2-breaksapi

#2600 prefix parachain log targets with parachain::
  node/collation-generation/src/lib.rs
  node/core/approval-voting/src/lib.rs
  node/core/av-store/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/core/chain-api/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/network/approval-distribution/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-recovery/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/src/lib.rs
  node/network/gossip-support/src/lib.rs
  node/network/pov-distribution/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
  node/service/src/grandpa_support.rs
  node/subsystem-util/src/validator_discovery.rs
  parachain/src/wasm_executor/validation_host.rs
  runtime/parachains/src/inclusion_inherent.rs
  runtime/parachains/src/ump.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2463 Companion for #8137 (MMR Custom RPC)
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#2597 remove statement::invalid
  node/core/backing/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/primitives/src/lib.rs
  primitives/src/v0.rs
  statement-table/src/generic.rs
  statement-table/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2603 Better error handling in approval-voting
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2605 avoid reshuffling active validators
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/session_info.rs
  runtime/parachains/src/shared.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2535 Polkadot companion for #8143
  Cargo.lock
  cli/src/browser.rs
  cli/src/command.rs
  node/core/proposer/Cargo.toml
  node/core/proposer/src/lib.rs
  node/service/src/lib.rs
  node/test/service/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2604 more tracing for av-store
  Cargo.lock
  cli/Cargo.toml
  node/collation-generation/Cargo.toml
  node/core/approval-voting/Cargo.toml
  node/core/av-store/Cargo.toml
  node/core/av-store/src/lib.rs
  node/core/backing/Cargo.toml
  node/core/bitfield-signing/Cargo.toml
  node/core/candidate-selection/Cargo.toml
  node/core/candidate-validation/Cargo.toml
  node/core/chain-api/Cargo.toml
  node/core/proposer/Cargo.toml
  node/core/provisioner/Cargo.toml
  node/core/runtime-api/Cargo.toml
  node/network/approval-distribution/Cargo.toml
  node/network/availability-distribution/Cargo.toml
  node/network/availability-recovery/Cargo.toml
  node/network/bitfield-distribution/Cargo.toml
  node/network/bridge/Cargo.toml
  node/network/collator-protocol/Cargo.toml
  node/network/gossip-support/Cargo.toml
  node/network/pov-distribution/Cargo.toml
  node/network/statement-distribution/Cargo.toml
  node/overseer/Cargo.toml
  node/service/Cargo.toml
  node/subsystem-test-helpers/Cargo.toml
  node/subsystem-util/Cargo.toml
  node/subsystem/Cargo.toml
  node/test/service/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#2612 some more metrics for approval voting
  node/core/approval-voting/src/approval_checking.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2606 availability distribution: don't early return on runtime errors
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/requester/mod.rs
  node/network/availability-distribution/src/session_cache.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2615 Adds deregister_validators call for propose-parachain
  runtime/rococo/src/lib.rs
  runtime/rococo/src/propose_parachain.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2614 node: decrease block production backoff max interval on rococo
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2602 runtime: define NextSessionRotation in im-online instances
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B1-releasenotes, C1-low, D2-breaksapi

#2618 more diagnostic logs for approval-voting
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/persisted_entries.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2620 Backing and collator protocol traces including para-id
  node/core/backing/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/jaeger/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2623 add tracing when no assignment in candidate selection
  node/core/candidate-selection/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2294 New slots/auctions architecture
  Cargo.lock
  node/service/src/chain_spec.rs
  runtime/common/Cargo.toml
  runtime/common/src/auctions.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/lib.rs
  runtime/common/src/mock.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/slots.rs
  runtime/common/src/traits.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/shared.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/propose_parachain.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/auctions.rs
  runtime/westend/src/weights/crowdloan.rs
  runtime/westend/src/weights/paras_registrar.rs
  runtime/westend/src/weights/slots.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#2626 update ring to 0.16.20
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#2628 Remove TODO from Substrate#2986
  runtime/kusama/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#2622 Companion for sub/8176
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/purchase.rs
  runtime/kusama/src/constants.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_election_provider_multi_phase.rs
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/constants.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_election_provider_multi_phase.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/rococo/src/constants.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/src/constants.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/constants.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/pallet_election_provider_multi_phase.rs
  runtime/westend/src/weights/pallet_staking.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2627 Add /data symlink to Docker containers
  scripts/docker/Dockerfile
  scripts/docker/release.Dockerfile
Labels: A0-pleasereview, B0-silent, C1-low

#2562 Fix wrong deposit amount in council voters.
  node/service/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C7-high, D2-breaksapi

#2630 re benchmark
  runtime/kusama/src/weights/pallet_election_provider_multi_phase.rs
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/weights/pallet_election_provider_multi_phase.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/westend/src/weights/pallet_election_provider_multi_phase.rs
  runtime/westend/src/weights/pallet_staking.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#2631 Reduce number of active leaves at startup
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2638 yet another set of logging improvements
  node/core/approval-voting/src/lib.rs
  node/core/candidate-selection/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2358 Polkadot companion for Substrate PR #7640 (Store multiple Justifications per block)
  Cargo.lock
  node/service/src/client.rs
  runtime/common/src/integration_tests.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low, D2-breaksapi

#2634 Companion for Substrate#8386
  Cargo.lock
  node/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2621 Request based collation fetching
  Cargo.lock
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/tests.rs
  node/network/availability-distribution/src/tests/state.rs
  node/network/bridge/src/action.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/multiplexer.rs
  node/network/bridge/src/network.rs
  node/network/collator-protocol/Cargo.toml
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/pov-distribution/src/lib.rs
  node/network/pov-distribution/src/tests.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/lib.rs
  node/network/protocol/src/request_response/mod.rs
  node/network/protocol/src/request_response/request.rs
  node/network/protocol/src/request_response/v1.rs
  node/subsystem/src/messages.rs
  primitives/Cargo.toml
  primitives/src/v1.rs
  roadmap/implementers-guide/src/node/availability/availability-distribution.md
  roadmap/implementers-guide/src/node/collators/collator-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#2629 Companion for #8372 (Replace 'Module' with 'Pallet' in construct_runtime macro)
  Cargo.lock
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/lib.rs
  bridges/modules/call-dispatch/src/lib.rs
  bridges/modules/currency-exchange/src/lib.rs
  bridges/modules/ethereum/src/mock.rs
  bridges/modules/finality-verifier/src/lib.rs
  bridges/modules/finality-verifier/src/mock.rs
  bridges/modules/message-lane/src/instant_payments.rs
  bridges/modules/message-lane/src/mock.rs
  bridges/modules/shift-session-manager/src/lib.rs
  bridges/modules/substrate/src/mock.rs
  runtime/common/src/auctions.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/impls.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/lib.rs
  runtime/common/src/mock.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/dmp.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/inclusion_inherent.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/scheduler.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/propose_parachain.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A7-companion, B0-silent, C1-low, D2-breaksapi

#2608 integrate faster erasure code
  Cargo.lock
  erasure-coding/Cargo.toml
  erasure-coding/src/lib.rs
  erasure-coding/src/wrapped_shard.rs
Labels: A0-pleasereview, B1-releasenotes, B2-breaksapi, C1-low

#2570 Update for the new substrate client API
  Cargo.lock
  node/service/src/client.rs
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low

#2645 Improve logging
  node/collation-generation/src/lib.rs
  node/core/backing/src/lib.rs
  node/network/availability-recovery/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2644 Don't accept incoming connections for collators
  node/network/bridge/src/lib.rs
  node/network/protocol/src/peer_set.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2642 restructure polkadot-node-jaeger
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/proposer/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/jaeger/src/config.rs
  node/jaeger/src/errors.rs
  node/jaeger/src/lib.rs
  node/jaeger/src/spans.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/responder.rs
  node/network/availability-recovery/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/pov-distribution/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2650 bump reed-solomon-novelpoly to v0.0.3
  Cargo.lock
  erasure-coding/Cargo.toml
  erasure-coding/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#2432 Companion for substrate/pull/8113 (Unleash multi phase)
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/pallet_staking.rs
Labels: A0-pleasereview, A7-companion, B7-runtimenoteworthy, C1-low, D2-breaksapi

#2643 CI: build an image and trigger simnet
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#2637 Increase payable nominators per validator
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/westend/src/weights/pallet_staking.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#2668 Add debug messages to the bridge actions
  node/network/bridge/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2663 more approval voting instrumentation
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/persisted_entries.rs
  node/core/approval-voting/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#2660 Add Parachain Onboarding to Rococo
  bridges/modules/call-dispatch/src/lib.rs
  bridges/primitives/runtime/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/propose_parachain.rs
  runtime/rococo/src/validator_manager.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#2669 Improve logging
  Cargo.lock
  node/core/av-store/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/gossip-support/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2673 Fix up CI for new labels
  scripts/github/check_labels.sh
  scripts/github/generate_release_text.rb
  scripts/gitlab/check_runtime.sh
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2617 [CI] Require D*-audit labels for any runtime changes
  .github/workflows/check-labels.yml
  scripts/common/lib.sh
  scripts/github/check_labels.sh
  scripts/gitlab/check_runtime.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2671 Tweak Rococo Settings For Onboarding Testing
  runtime/rococo/src/constants.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2677 Fix check-labels.yml for forked repos
  .github/workflows/check-labels.yml
  scripts/github/check_labels.sh
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low 📌

#2676 Remove unused constants
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2665 Fix Crowdloan Dissolve and Add Auction Cancel
  runtime/common/src/auctions.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
  runtime/westend/src/weights/auctions.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-breaksapi, D3-trivial 🧸

#2666 Allow Root to Edit a Crowdloan Configuration
  runtime/common/src/crowdloan.rs
  runtime/westend/src/weights/crowdloan.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-breaksapi, D3-trivial 🧸

#2670 Sample Auction Winners Every `SampleLength` Blocks
  runtime/common/src/auctions.rs
  runtime/common/src/integration_tests.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2684 Additional logging for polkadot network protocols
  node/network/approval-distribution/src/lib.rs
  node/network/availability-distribution/src/requester/mod.rs
  node/network/availability-distribution/src/responder.rs
  node/network/availability-recovery/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/pov-distribution/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  primitives/src/v1.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2685 fix/jaeger: avoid array debug repr
  node/jaeger/src/spans.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2687 Bigger is better.
  node/network/protocol/src/request_response/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#2680 Evict inactive peers from the collator protocol peer-set
  Cargo.lock
  node/network/bridge/src/action.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/network.rs
  node/network/collator-protocol/Cargo.toml
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/protocol/src/reputation.rs
  node/service/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/utility/network-bridge.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2689 Remove Parachains Stuff from Westend
  node/service/src/chain_spec.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/auctions.rs
  runtime/westend/src/weights/crowdloan.rs
  runtime/westend/src/weights/paras_registrar.rs
  runtime/westend/src/weights/slots.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2691 Unify maximum supported PoV size a bit.
  node/network/protocol/src/request_response/mod.rs
  node/service/src/chain_spec.rs
  primitives/src/v1.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2693 Additional approval-distribution logging
  node/network/approval-distribution/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2616 CI: initial fuzzer jobs
  .github/workflows/honggfuzz.yml
  erasure-coding/fuzzer/.gitignore
  erasure-coding/fuzzer/Cargo.lock
  erasure-coding/fuzzer/Cargo.toml
  scripts/github/run_fuzzer.sh
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2686 Companion for substrate/pull/8445
  Cargo.lock
  runtime/kusama/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#2697 Improve approval tracing
  node/core/approval-voting/src/criteria.rs
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2695 Tweaked logging
  node/network/approval-distribution/src/lib.rs
  node/network/availability-recovery/src/lib.rs
  node/primitives/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2672 Polkadot companion for Substrate#8420
  Cargo.lock
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low 📌

#2635 collator-protocol: add message authentication
  Cargo.lock
  node/network/bridge/src/lib.rs
  node/network/collator-protocol/Cargo.toml
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/protocol/src/lib.rs
  node/service/src/lib.rs
  node/test/service/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
  parachain/test-parachains/adder/collator/tests/integration.rs
  roadmap/implementers-guide/src/types/network.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2701 rococo: use insecure parent hash randomness
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2683 Companion for `substrate/pull/8368`
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#2705 Update Rococo v1
  .github/workflows/check-labels.yml
  runtime/common/src/auctions.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/auctions.rs
  runtime/westend/src/weights/crowdloan.rs
  scripts/github/check_labels.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2704 [CI] Fix generate_release_text.rb
  scripts/github/generate_release_text.rb
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌

#2699 f+1 validators always approve
  node/core/approval-voting/src/approval_checking.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  roadmap/implementers-guide/src/node/approval/approval-voting.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2694 Port availability recovery to use req/res
  Cargo.lock
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/tests.rs
  node/network/availability-distribution/src/responder.rs
  node/network/availability-distribution/src/tests/state.rs
  node/network/availability-recovery/Cargo.toml
  node/network/availability-recovery/src/error.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/multiplexer.rs
  node/network/protocol/src/lib.rs
  node/network/protocol/src/request_response/mod.rs
  node/network/protocol/src/request_response/request.rs
  node/network/protocol/src/request_response/v1.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/availability/availability-distribution.md
  roadmap/implementers-guide/src/node/availability/availability-recovery.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2708 Enable debug assertions on rococo.
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#2709 Enable debug assertions on rococo (on rococo).
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2711 overseer: AllSubsystems magic and subsystem channel sizes metrics
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2715 debug assert for real.
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸, F2-bug

#2716 Enable debug assert for real.
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2656 Check that Para is Registered before Accepting a Bid
  runtime/common/src/auctions.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/traits.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-breaksapi, D3-trivial 🧸

#2718 Add block number to activated leaves and associated fixes
  node/collation-generation/src/lib.rs
  node/core/approval-voting/src/lib.rs
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/core/backing/src/lib.rs
  node/network/availability-distribution/src/requester/mod.rs
  node/network/availability-distribution/src/tests/state.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/gossip-support/src/lib.rs
  node/network/pov-distribution/src/lib.rs
  node/network/pov-distribution/src/tests.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/src/lib.rs
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2721 Separate metrics for messages sent & received
  Cargo.lock
  node/metered-channel/Cargo.toml
  node/metered-channel/src/bounded.rs
  node/metered-channel/src/lib.rs
  node/metered-channel/src/unbounded.rs
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2722 chore: avoid glob imports
  bridges/modules/ethereum/src/benchmarking.rs
  bridges/relays/ethereum/src/substrate_sync_loop.rs
  node/metered-channel/src/bounded.rs
  node/metered-channel/src/lib.rs
  node/metered-channel/src/unbounded.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2713 Parachain Onboarding Extras
  runtime/common/src/paras_sudo_wrapper.rs
  runtime/common/src/slots.rs
  runtime/common/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2717 Reduce network bridge logging verbosity
  node/network/bridge/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2727 use novelpoly 1.0.0
  Cargo.lock
  erasure-coding/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2723 Fix Crowdloan Withdraw Requirements
  runtime/common/src/crowdloan.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2725 use a gauge for approval lag
  node/service/src/grandpa_support.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2729 duplicate logging fix
  node/network/approval-distribution/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2728 Introduce `add_memo` for Crowdloans
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2688 Increase rotation period
  runtime/kusama/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#2731 Handle Onboarding in Current Lease Period
  runtime/common/src/mock.rs
  runtime/common/src/slots.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2733 Rococo Runtime Updates for Onboarding
  node/service/src/chain_spec.rs
  runtime/common/src/auctions.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/mock.rs
  runtime/common/src/paras_sudo_wrapper.rs
  runtime/common/src/slots.rs
  runtime/common/src/traits.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/auctions.rs
  runtime/westend/src/weights/crowdloan.rs
  runtime/westend/src/weights/paras_registrar.rs
  runtime/westend/src/weights/slots.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2732 approval-distribution: moar logs
  node/network/approval-distribution/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#2734 approval-distribution: moar metrics
  node/network/approval-distribution/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#2675 Approval voting failsafe
  node/core/approval-voting/src/approval_db/v1/mod.rs
  node/core/approval-voting/src/approval_db/v1/tests.rs
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/persisted_entries.rs
  node/core/approval-voting/src/tests.rs
  primitives/src/v1.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/mock.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2707 use named generic types in generate_solution_type
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2640 Request based PoV distribution
  Cargo.lock
  Cargo.toml
  node/core/backing/Cargo.toml
  node/core/backing/src/lib.rs
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/metrics.rs
  node/network/availability-distribution/src/pov_requester/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/requester/mod.rs
  node/network/availability-distribution/src/responder.rs
  node/network/availability-distribution/src/runtime.rs
  node/network/availability-distribution/src/session_cache.rs
  node/network/availability-distribution/src/tests/mock.rs
  node/network/availability-distribution/src/tests/state.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/multiplexer.rs
  node/network/bridge/src/network.rs
  node/network/pov-distribution/Cargo.toml
  node/network/pov-distribution/src/error.rs
  node/network/pov-distribution/src/lib.rs
  node/network/pov-distribution/src/tests.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/lib.rs
  node/network/protocol/src/request_response/mod.rs
  node/network/protocol/src/request_response/request.rs
  node/network/protocol/src/request_response/v1.rs
  node/overseer/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/availability/availability-distribution.md
  roadmap/implementers-guide/src/node/backing/candidate-backing.md
  roadmap/implementers-guide/src/node/backing/pov-distribution.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A3-inprogress, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2227 Overseer: subsystems communicate directly
  Cargo.lock
  node/metered-channel/src/bounded.rs
  node/metered-channel/src/lib.rs
  node/metered-channel/src/unbounded.rs
  node/network/bridge/src/lib.rs
  node/overseer/Cargo.toml
  node/overseer/src/lib.rs
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2726 Call NetworkService::add_known_address before sending a request
  node/network/bridge/src/network.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/protocol/src/request_response/request.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2742 approval-voting: more spans and metrics
  node/core/approval-voting/src/approval_db/v1/mod.rs
  node/core/approval-voting/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#2737 approval-distribution: limit the amount of assignments on unify
  node/network/approval-distribution/src/lib.rs
  roadmap/implementers-guide/src/node/approval/approval-distribution.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2736 Split NetworkBridge and break cycles with Unbounded
  Cargo.lock
  node/core/approval-voting/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/Cargo.toml
  node/core/bitfield-signing/src/lib.rs
  node/core/candidate-selection/Cargo.toml
  node/core/candidate-selection/src/lib.rs
  node/core/provisioner/Cargo.toml
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/tests.rs
  node/network/bridge/Cargo.toml
  node/network/bridge/src/action.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/network.rs
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem-util/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2740 Emit an Event for Random Block Selected in Auction
  runtime/common/src/auctions.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2743 Move non runtime related stuff into node/primitives
  Cargo.lock
  core-primitives/src/lib.rs
  erasure-coding/Cargo.toml
  erasure-coding/src/lib.rs
  node/collation-generation/src/lib.rs
  node/core/approval-voting/src/approval_checking.rs
  node/core/approval-voting/src/lib.rs
  node/core/av-store/Cargo.toml
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/jaeger/Cargo.toml
  node/jaeger/src/spans.rs
  node/metered-channel/src/bounded.rs
  node/metered-channel/src/unbounded.rs
  node/network/availability-distribution/Cargo.toml
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/pov_requester/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/tests.rs
  node/network/availability-distribution/src/responder.rs
  node/network/availability-distribution/src/tests/mock.rs
  node/network/availability-distribution/src/tests/state.rs
  node/network/availability-recovery/Cargo.toml
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/protocol/src/peer_set.rs
  node/network/protocol/src/request_response/mod.rs
  node/network/protocol/src/request_response/v1.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/primitives/Cargo.toml
  node/primitives/src/lib.rs
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  node/subsystem/src/messages.rs
  parachain/src/primitives.rs
  parachain/test-parachains/adder/collator/src/lib.rs
  primitives/Cargo.toml
  primitives/src/v0.rs
  primitives/src/v1.rs
  runtime/parachains/src/inclusion.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2741 Allow Non Intersecting Bids in Para Auction
  runtime/common/src/auctions.rs
  runtime/common/src/integration_tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2751 Reduce signal channel sizes and more logging on approval-voting
  node/core/approval-voting/src/import.rs
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2313 Updated docker documentation.
  doc/docker.md
  docker/readme-docker.adoc
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2752 use unbounded when notifying distribution of new blocks
  node/core/approval-voting/src/import.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2745 Add Many Sanity Checks to Crowdloans
  runtime/common/src/auctions.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2757 send assignments even when we have an approval
  node/network/approval-distribution/src/lib.rs
  node/network/approval-distribution/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2758 more logs in issue-approval
  node/core/approval-voting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2756 Runtime Updates for Rococo v1 Onboarding
  runtime/common/src/auctions.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/traits.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2738 Less connected graph for rococo
  node/network/gossip-support/src/lib.rs
  node/network/protocol/src/peer_set.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2755 tracing for pending_known map
  node/network/approval-distribution/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2762 availability-distribution: Retry failed fetches on next block.
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/tests.rs
  node/network/availability-distribution/src/requester/mod.rs
  node/network/availability-distribution/src/tests/mock.rs
  node/network/availability-distribution/src/tests/mod.rs
  node/network/availability-distribution/src/tests/state.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2759 Companion for Substrate#8472
  Cargo.lock
  node/service/src/grandpa_support.rs
  node/test/client/Cargo.toml
  node/test/client/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2761 approval-distribution: add an assertion
  node/network/approval-distribution/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2763 Retry availability until the receiver of the request is dropped
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/persisted_entries.rs
  node/network/availability-recovery/src/error.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  roadmap/implementers-guide/src/node/availability/availability-recovery.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2662 Fungibles adapter and MultiLocation::X8
  Cargo.lock
  xcm/src/v0/multi_location.rs
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-builder/src/currency_adapter.rs
  xcm/xcm-builder/src/fungibles_adapter.rs
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-executor/src/traits.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#2775 Fix fungible usage
  xcm/xcm-builder/src/fungibles_adapter.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2772 network-bridge: elevate log level for connections
  node/network/bridge/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#2776 gossip: choose a random subset on send instead of limiting connections
  Cargo.lock
  node/network/approval-distribution/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/gossip-support/Cargo.toml
  node/network/gossip-support/src/lib.rs
  node/network/protocol/src/lib.rs
  node/network/protocol/src/peer_set.rs
  node/network/statement-distribution/src/lib.rs
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2777 Add Root Functions to Parachains System
  runtime/common/src/integration_tests.rs
  runtime/common/src/paras_registrar.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2724 Add some tests to demonstrate an estimate of the nominator limit
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2774 Add proxy and utility pallets.
  Cargo.lock
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2779 Fix future-polling loop in availability and add a better early-exit
  node/network/availability-recovery/src/lib.rs
  roadmap/implementers-guide/src/node/availability/availability-recovery.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, D5-nicetohaveaudit ⚠️

#2771 proper executor/block type for benchmarks and try-runtime
  cli/src/command.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2778 Better timeout values now that we are going to be connected to all nodes.
  node/network/protocol/src/request_response/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2790 statement-distribution: do not use OurViewChange
  node/network/statement-distribution/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌
