Repository paritytech/polkadot, pull requests merged in 2021-02, with the labels that each got.

#2351 Add tests that check the value of MQCs
  runtime/parachains/src/dmp.rs
  runtime/parachains/src/hrmp.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2350 v0.8.28-rc3
  Cargo.lock
  cli/Cargo.toml
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/collation-generation/Cargo.toml
  node/core/approval-voting/Cargo.toml
  node/core/av-store/Cargo.toml
  node/core/backing/Cargo.toml
  node/core/bitfield-signing/Cargo.toml
  node/core/candidate-selection/Cargo.toml
  node/core/candidate-validation/Cargo.toml
  node/core/chain-api/Cargo.toml
  node/core/proposer/Cargo.toml
  node/core/provisioner/Cargo.toml
  node/core/runtime-api/Cargo.toml
  node/jaeger/Cargo.toml
  node/network/approval-distribution/Cargo.toml
  node/network/availability-distribution/Cargo.toml
  node/network/availability-recovery/Cargo.toml
  node/network/bitfield-distribution/Cargo.toml
  node/network/bridge/Cargo.toml
  node/network/collator-protocol/Cargo.toml
  node/network/pov-distribution/Cargo.toml
  node/network/protocol/Cargo.toml
  node/network/statement-distribution/Cargo.toml
  node/overseer/Cargo.toml
  node/primitives/Cargo.toml
  node/service/Cargo.toml
  node/subsystem-test-helpers/Cargo.toml
  node/subsystem-util/Cargo.toml
  node/subsystem/Cargo.toml
  node/test/client/Cargo.toml
  node/test/service/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  statement-table/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2363 Fixed a grammatical error
  README.md
Labels: A2-insubstantial, B0-silent, C1-low

#2364 Remove from `known_collators` on disconnect
  node/network/collator-protocol/src/validator_side.rs
Labels: A2-insubstantial, B0-silent, C1-low

#1865 Conpanion for Substrate#7127
  Cargo.lock
  runtime/common/src/lib.rs
  runtime/common/src/paras_registrar.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/session_info.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A7-companion, B0-silent, C1-low, D2-breaksapi

#2367 Log unknown collator
  node/network/collator-protocol/src/validator_side.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2315 Companion for #7963 (IPFS server)
  Cargo.lock
  node/service/src/client.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#2369 Fix bug in statement table
  statement-table/src/generic.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2352 Generic request/response infrastructure for Polkadot
  Cargo.lock
  node/network/approval-distribution/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/Cargo.toml
  node/network/bridge/src/action.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/multiplexer.rs
  node/network/bridge/src/network.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/pov-distribution/src/lib.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/lib.rs
  node/network/protocol/src/peer_set.rs
  node/network/protocol/src/request_response.rs
  node/network/protocol/src/request_response/request.rs
  node/network/protocol/src/request_response/v1.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
  node/service/src/lib.rs
  node/subsystem/src/messages.rs
  node/subsystem/src/messages/network_bridge_event.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2375 Diagnostics quality of life improvements
  core-primitives/src/lib.rs
  node/collation-generation/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/protocol/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2379 Cargo build step needs pre requisites not mentioned
  README.md
Labels: A2-insubstantial, B0-silent, C1-low

#2380 End multiplexer stream once one of its inputs end.
  node/network/bridge/src/lib.rs
  node/network/bridge/src/multiplexer.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2381 Unused variable can be ignored
  node/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2384 Cargo.lock: Update to libp2p-swarm v0.27.2
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low

#2334 Cancel Proxy Type
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B7-runtimenoteworthy, C1-low, D2-breaksapi

#2354 Explicit Para Lifecycle w/ Upgrades and Downgrades
  roadmap/implementers-guide/src/runtime/paras.md
  runtime/parachains/src/lib.rs
  runtime/parachains/src/paras.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#2385 node: pass local authorship info to the transaction pool
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#2386 Backports for v0.8.28-rc4
  Cargo.lock
  node/service/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2391 bump spec versions in kusama, polkadot and westend
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#2392 Send view to new peers
  node/network/bridge/src/lib.rs
  roadmap/implementers-guide/src/node/utility/network-bridge.md
Labels: A0-pleasereview, B0-silent, C1-low

#2388 Publish rococo on every push to `rococo-v1` branch
  .gitlab-ci.yml
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low

#2378 guide: more robust approval counting procedure
  roadmap/implementers-guide/src/node/approval/approval-voting.md
Labels: A0-pleasereview, B0-silent, C1-low

#2372 validator_discovery: pass PeerSet to the request
  Cargo.lock
  node/network/availability-recovery/src/lib.rs
  node/network/bridge/src/action.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/pov-distribution/src/lib.rs
  node/network/pov-distribution/src/tests.rs
  node/network/protocol/src/peer_set.rs
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/validator_discovery.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2399 [release-branch bugfix] Bump substrate
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  erasure-coding/Cargo.toml
  node/test/client/Cargo.toml
  node/test/service/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  statement-table/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low

#2409 Use construct_runtime in tests, remove default PalletInfo impl
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/impls.rs
  runtime/common/src/lib.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots.rs
  runtime/parachains/src/dmp.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/inclusion_inherent.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/scheduler.rs
  runtime/parachains/src/session_info.rs
  runtime/parachains/src/ump.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2387 Enable wasmtime caching for PVF (companion for #8057)
  Cargo.lock
  cli/src/cli.rs
  cli/src/command.rs
  node/service/src/lib.rs
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/test-parachains/tests/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#2402 validator_discovery: cache by (Hash, ParaId)
  node/network/collator-protocol/src/collator_side.rs
  node/network/pov-distribution/src/lib.rs
  node/subsystem-util/src/validator_discovery.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2414 Corrected Physical
  README.md
Labels: A2-insubstantial, B0-silent, C1-low

#2331 Companion for #7936: Migrate pallet-balances to pallet attribute macro
  Cargo.lock
  runtime/common/src/impls.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2404 runtime: set equivocation report longevity
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low, D2-breaksapi

#2415 [CI] Move check_labels to github actions
  .github/workflows/check-labels.yml
  .gitlab-ci.yml
  scripts/common/lib.sh
  scripts/github/check_labels.sh
  scripts/gitlab/check_runtime.sh
  scripts/gitlab/check_runtime_benchmarks.sh
  scripts/gitlab/check_web_wasm.sh
  scripts/gitlab/test_deterministic_wasm.sh
  scripts/gitlab/test_linux_stable.sh
Labels: A0-pleasereview, B0-silent, C1-low

#2420 Introduce PerPeerSet utility that allows to segrate based on PeerSet
  node/network/bridge/src/validator_discovery.rs
  node/network/protocol/src/peer_set.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2112 Implement Approval Voting Subsystem
  Cargo.lock
  node/core/approval-voting/Cargo.toml
  node/core/approval-voting/src/approval_checking.rs
  node/core/approval-voting/src/approval_db/mod.rs
  node/core/approval-voting/src/approval_db/v1/mod.rs
  node/core/approval-voting/src/approval_db/v1/tests.rs
  node/core/approval-voting/src/criteria.rs
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/persisted_entries.rs
  node/core/approval-voting/src/tests.rs
  node/core/approval-voting/src/time.rs
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/core/runtime-api/Cargo.toml
  node/core/runtime-api/src/cache.rs
  node/core/runtime-api/src/lib.rs
  node/network/approval-distribution/src/lib.rs
  node/network/approval-distribution/src/tests.rs
  node/overseer/src/lib.rs
  node/primitives/Cargo.toml
  node/primitives/src/approval.rs
  node/primitives/src/lib.rs
  node/service/src/lib.rs
  node/subsystem/src/messages.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2425 Rococo genesis 1337
  node/service/res/rococo.json
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2429 CancelProxy uses `reject_announcement` instead of `remove_announcement`
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C3-medium, D2-breaksapi

#2430 Notify collators about seconded collation
  Cargo.lock
  node/collation-generation/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/candidate-selection/Cargo.toml
  node/core/candidate-selection/src/lib.rs
  node/network/collator-protocol/Cargo.toml
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/protocol/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
  node/primitives/src/lib.rs
  node/subsystem/src/messages.rs
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/adder/collator/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
  parachain/test-parachains/adder/collator/tests/integration.rs
  roadmap/implementers-guide/src/node/collators/collation-generation.md
  roadmap/implementers-guide/src/node/subsystems-and-jobs.md
  roadmap/implementers-guide/src/types/network.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#2436 Bump if-watch to `0.1.8` to fix panic
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#2408 Companion for substrate#8079
  .github/ISSUE_TEMPLATE/bug_report.md
  Cargo.lock
  docker/sentry-docker-compose.yml
  node/network/protocol/src/lib.rs
  node/service/src/lib.rs
  node/test/service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#2437 Polkadot companion for 8114
  Cargo.lock
  node/core/proposer/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/service/src/client.rs
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low

#2413 Initializer + Paras Clean Up Messages When Offboarding
  roadmap/implementers-guide/src/runtime/dmp.md
  roadmap/implementers-guide/src/runtime/hrmp.md
  roadmap/implementers-guide/src/runtime/paras.md
  roadmap/implementers-guide/src/runtime/ump.md
  runtime/parachains/src/dmp.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/ump.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2422 node: migrate grandpa voting rule to async api
  Cargo.lock
  node/service/src/grandpa_support.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#2440 Mitigation of SIGBUS
  Cargo.lock
  node/core/candidate-validation/src/lib.rs
  parachain/Cargo.toml
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/src/wasm_executor/validation_host/workspace.rs
  parachain/test-parachains/tests/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2412 Integrate Approval Voting into Overseer / Service / GRANDPA
  Cargo.lock
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  node/overseer/src/lib.rs
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  node/service/src/grandpa_support.rs
  node/service/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#2445 Clean up sizes for a workspace
  parachain/src/primitives.rs
  parachain/src/wasm_executor/validation_host/workspace.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2452 fix approval import tests and some bugs
  node/core/approval-voting/src/import.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2438 companion: Babe remove inherent
  Cargo.lock
  node/test/client/Cargo.toml
  node/test/client/src/block_builder.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2424 Disputes High-level rewrite & Disputes runtime
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/utility/provisioner.md
  roadmap/implementers-guide/src/protocol-disputes.md
  roadmap/implementers-guide/src/protocol-overview.md
  roadmap/implementers-guide/src/runtime-api/known-disputes.md
  roadmap/implementers-guide/src/runtime/disputes.md
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/inclusioninherent.md
  roadmap/implementers-guide/src/runtime/initializer.md
  roadmap/implementers-guide/src/runtime/parainherent.md
  roadmap/implementers-guide/src/types/backing.md
  roadmap/implementers-guide/src/types/disputes.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  roadmap/implementers-guide/src/types/runtime.md
Labels: A0-pleasereview, B0-silent, C1-low

#2450 Make sure the adder collator fails when something is wrong
  Cargo.lock
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/adder/collator/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2382 Polkadot companion for #8043
  Cargo.lock
  node/service/src/lib.rs
  node/test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2449 [CI] Fix check-tx-version Gitlab job
  .gitlab-ci.yml
  scripts/common/lib.sh
  scripts/gitlab/check_extrinsics_ordering.sh
Labels: A0-pleasereview, B0-silent, C1-low

#2462 refactor/reputation: unify the values used
  node/network/approval-distribution/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-recovery/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/action.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/network.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/pov-distribution/src/lib.rs
  node/network/protocol/src/lib.rs
  node/network/protocol/src/reputation.rs
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
  node/subsystem/src/messages.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2456 Allow at most one candidate with a code upgrade in a block
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/tests.rs
  roadmap/implementers-guide/src/node/utility/provisioner.md
  runtime/parachains/src/inclusion_inherent.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2461 approval import: fix earliest_stored_session and underflow
  node/core/approval-voting/src/import.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2421 make approval voting work on a small testnet
  node/core/approval-voting/src/approval_db/v1/mod.rs
  node/core/approval-voting/src/approval_db/v1/tests.rs
  node/core/approval-voting/src/import.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2455 remove unused RequestBlockAuthorshipData
  node/core/provisioner/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/subsystems-and-jobs.md
  roadmap/implementers-guide/src/node/utility/provisioner.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#2465 Track the collation status in the collator protocol
  node/network/collator-protocol/src/collator_side.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2466 Full chunk messages for availability-recovery
  node/network/availability-recovery/src/lib.rs
  node/network/protocol/src/lib.rs
  primitives/src/v1.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2453 A fast-path for requesting `AvailableData` from backing validators
  node/core/approval-voting/src/lib.rs
  node/network/availability-recovery/src/error.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  node/overseer/src/lib.rs
  node/service/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/node/availability/availability-recovery.md
  roadmap/implementers-guide/src/types/network.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#2470 gate approval-checking logic
  Cargo.toml
  node/service/Cargo.toml
  node/service/src/grandpa_support.rs
  node/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2473 [jaeger] unify all used tags, introduce builder pattern, additional…
  node/core/backing/src/lib.rs
  node/jaeger/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/statement-distribution/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2471 Replace AuxStore with custom RocksDB
  Cargo.lock
  node/core/approval-voting/Cargo.toml
  node/core/approval-voting/src/approval_db/v1/mod.rs
  node/core/approval-voting/src/approval_db/v1/tests.rs
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2406 Session Delayed Para Changes / Actions Queue
  roadmap/implementers-guide/src/runtime/README.md
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/paras.md
  roadmap/implementers-guide/src/runtime/shared.md
  runtime/common/src/paras_registrar.rs
  runtime/common/src/paras_sudo_wrapper.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/scheduler.rs
  runtime/parachains/src/session_info.rs
  runtime/parachains/src/shared.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/propose_parachain.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D2-breaksapi

#2477 feat/jaeger: more spans, more stages
  .config/lingua.dic
  node/core/av-store/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/jaeger/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/pov-distribution/src/lib.rs
  node/network/pov-distribution/src/tests.rs
  node/network/protocol/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2478 Companion for Substrate#8155
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2492 Substrate companion for #8163
  Cargo.lock
  node/core/approval-voting/src/criteria.rs
  node/core/approval-voting/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/provisioner/src/tests.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/subsystem-util/src/lib.rs
  primitives/src/v0.rs
  runtime/parachains/src/inclusion.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2498 Update thread_local past the memory leak
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#2488 Companion for 8166 (Update `storage_kill` return value)
  Cargo.lock
  parachain/src/wasm_executor/mod.rs
  runtime/common/src/crowdloan.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2491 Fix XCM encoding in HRMP pallet.
  runtime/parachains/src/hrmp.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2496 Remove v0.8.28 runtime migrations
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2481 Change a few fee/weight parameters
  Cargo.lock
  runtime/common/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2493 feat/view: assure heads in a view are sorted
  .config/lingua.dic
  node/network/approval-distribution/src/lib.rs
  node/network/approval-distribution/src/tests.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/pov-distribution/src/lib.rs
  node/network/protocol/src/lib.rs
  node/network/statement-distribution/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2476 Enable two phase election provider in runtimes in 'DryRun' mode
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/paras_registrar.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2494 Override RuntimeApi::authorities() to include past sessions
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2480 Approval Checking Improvements Omnibus
  Cargo.lock
  cli/src/cli.rs
  cli/src/command.rs
  node/core/approval-voting/src/criteria.rs
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  node/core/av-store/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/network/approval-distribution/src/lib.rs
  node/network/availability-recovery/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/protocol/src/lib.rs
  node/service/src/chain_spec.rs
  node/service/src/grandpa_support.rs
  roadmap/implementers-guide/src/node/approval/approval-distribution.md
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/parainherent.md
  runtime/kusama/src/lib.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/inclusion_inherent.rs
  runtime/parachains/src/initializer.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2510 fix master: use view.iter() instead of view.heads
  node/network/approval-distribution/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2506 Companion for #8184
  Cargo.lock
  runtime/kusama/src/weights/frame_system.rs
  runtime/polkadot/src/weights/frame_system.rs
  runtime/westend/src/weights/frame_system.rs
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low, D2-breaksapi

#2447 Migration testing CLI
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/cli.rs
  cli/src/command.rs
  node/service/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2508 Properly use weights for the new election pallet
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_election_provider_multi_phase.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_election_provider_multi_phase.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/pallet_election_provider_multi_phase.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2518 merge approval-checking feature back into real-overseer
  Cargo.toml
  node/service/Cargo.toml
  node/service/src/grandpa_support.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2521 spawn availability store and approval voting subsystems as blocking tasks
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2507 Companion for Substrate #8185
  Cargo.lock
  node/core/proposer/src/lib.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2526 make runtime API and chain API subsystems blocking too
  node/overseer/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2523 Companion for Substrate #8148
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#2527 small cleanup after #2518
  node/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2525 some initial spans for approval voting
  Cargo.lock
  node/core/approval-voting/Cargo.toml
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  node/jaeger/Cargo.toml
  node/jaeger/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2248 Add an optional verifier to crowdloan
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/crowdloan.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2495 test: add unit test to catch missing distribution to subsystems faster
  Cargo.lock
  Cargo.toml
  cli/src/browser.rs
  node/network/bridge/src/lib.rs
  node/subsystem/Cargo.toml
  node/subsystem/dispatch-gen/Cargo.toml
  node/subsystem/dispatch-gen/src/lib.rs
  node/subsystem/dispatch-gen/tests/ui/err-01-missing-skip.rs
  node/subsystem/dispatch-gen/tests/ui/err-01-missing-skip.stderr
  node/subsystem/dispatch-gen/tests/ui/err-02-missing-from.rs
  node/subsystem/dispatch-gen/tests/ui/err-02-missing-from.stderr
  node/subsystem/dispatch-gen/tests/ui/ok-01-with-intermediate.rs
  node/subsystem/src/lib.rs
  node/subsystem/src/messages.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#2530 fix expect catching
  node/metered-channel/src/unbounded.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#2531 make runtime_api non blocking task again
  node/overseer/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2534 Backport substrate#8212
  Cargo.lock
  cli/Cargo.toml
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/collation-generation/Cargo.toml
  node/core/approval-voting/Cargo.toml
  node/core/av-store/Cargo.toml
  node/core/backing/Cargo.toml
  node/core/bitfield-signing/Cargo.toml
  node/core/candidate-selection/Cargo.toml
  node/core/candidate-validation/Cargo.toml
  node/core/chain-api/Cargo.toml
  node/core/proposer/Cargo.toml
  node/core/provisioner/Cargo.toml
  node/core/runtime-api/Cargo.toml
  node/jaeger/Cargo.toml
  node/network/approval-distribution/Cargo.toml
  node/network/availability-distribution/Cargo.toml
  node/network/availability-recovery/Cargo.toml
  node/network/bitfield-distribution/Cargo.toml
  node/network/bridge/Cargo.toml
  node/network/collator-protocol/Cargo.toml
  node/network/pov-distribution/Cargo.toml
  node/network/protocol/Cargo.toml
  node/network/statement-distribution/Cargo.toml
  node/overseer/Cargo.toml
  node/primitives/Cargo.toml
  node/service/Cargo.toml
  node/subsystem-test-helpers/Cargo.toml
  node/subsystem-util/Cargo.toml
  node/subsystem/Cargo.toml
  node/test/client/Cargo.toml
  node/test/service/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  statement-table/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#2423 Request based availability distribution
  Cargo.lock
  node/core/approval-voting/src/approval_checking.rs
  node/core/approval-voting/src/criteria.rs
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/persisted_entries.rs
  node/core/approval-voting/src/tests.rs
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/tests.rs
  node/jaeger/src/lib.rs
  node/network/approval-distribution/src/tests.rs
  node/network/availability-distribution/Cargo.toml
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/metrics.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/tests.rs
  node/network/availability-distribution/src/requester/mod.rs
  node/network/availability-distribution/src/responder.rs
  node/network/availability-distribution/src/session_cache.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/network.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/pov-distribution/src/lib.rs
  node/network/pov-distribution/src/tests.rs
  node/network/protocol/src/lib.rs
  node/network/protocol/src/request_response.rs
  node/network/protocol/src/request_response/request.rs
  node/network/protocol/src/request_response/v1.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/src/messages.rs
  primitives/src/v0.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/reward_points.rs
  runtime/parachains/src/scheduler.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2533 validator_discovery: some logs to help identify discovery issues
  node/network/bridge/src/validator_discovery.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2539 Fix links in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: A2-insubstantial, B0-silent, C1-low

#2532 Add events for hrmp pallet.
  runtime/common/src/paras_registrar.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/mock.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low, D2-breaksapi

#2541 Companion for Substrate #8120
  Cargo.lock
  runtime/kusama/src/weights/frame_system.rs
  runtime/polkadot/src/weights/frame_system.rs
  runtime/westend/src/weights/frame_system.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low, D2-breaksapi
