Repository paritytech/polkadot, pull requests merged in 2021-12, with the labels that each got.

#4181 companion for pallet order fix.
  Cargo.lock
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/lib.rs
  runtime/common/src/integration_tests.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/disputes.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D5-nicetohaveaudit ⚠️

#4419 Parachains runtime improvements
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/inclusion/mod.rs
  runtime/parachains/src/inclusion/tests.rs
  runtime/parachains/src/paras_inherent.rs
  runtime/parachains/src/paras_inherent/misc.rs
  runtime/parachains/src/paras_inherent/mod.rs
  runtime/parachains/src/paras_inherent/tests.rs
  runtime/parachains/src/paras_inherent/weights.rs
Labels: F6-refactor, A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4436 Backport release notes generation fix
  .github/workflows/publish-draft-release.yml
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4438 Add miss features
  runtime/parachains/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4405 Companion for 10379 (EnsureOneOf)
  Cargo.lock
  runtime/common/src/auctions.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4350 Add CI team to `CODEOWNERS` file
  .github/CODEOWNERS
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4318 Improve paras runtime `BenchBuilder` api
  runtime/parachains/src/builder.rs
  runtime/parachains/src/paras_inherent/benchmarking.rs
  runtime/parachains/src/paras_inherent/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#4413 Companion for substrate/10347
  Cargo.lock
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/westend/src/weights/pallet_staking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4447 Bump tx versions
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4450 Backport bump tx versions (#4447)
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4421 Add parent header hash to log
  runtime/parachains/src/paras_inherent/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3943 Rococo: ability to programatically assign slots to teams
  parachain/src/primitives.rs
  runtime/common/src/assigned_slots.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/lib.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  scripts/gitlab/lingua.dic
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#4441 Trivial Fixes to Benchmark List and Template
  runtime/polkadot/src/lib.rs
  xcm/pallet-xcm-benchmarks/template.hbs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4306 companion for #10231
  Cargo.lock
  runtime/common/src/elections.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  utils/remote-ext-tests/bags-list/src/voter_bags.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#4418 Add doc about runtime version bump
  .github/ISSUE_TEMPLATE/release.md
Labels: F5-documentation, A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4451 Fix cumulus companion CI job
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4458 Fix path of the polkadot sha256
  .gitlab-ci.yml
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4460 Update docs on `validation_upgrade_frequency`
  primitives/src/v1/mod.rs
  roadmap/implementers-guide/src/types/runtime.md
  runtime/parachains/src/configuration.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4463 Fix path of the polkadot_injected docker image
  .github/workflows/publish-docker-release.yml
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4422 assure backed candidates are always sorted
  runtime/parachains/src/paras_inherent/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4454 Run paras inherent benchmarks
  runtime/kusama/src/weights/runtime_parachains_paras_inherent.rs
  runtime/parachains/src/paras_inherent/benchmarking.rs
  runtime/polkadot/src/weights/runtime_parachains_paras_inherent.rs
  runtime/westend/src/weights/runtime_parachains_paras_inherent.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4475 Disable asset transfers on Polkadot
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4452 Restore Rococo <> Wococo bridges (headers + messages)
  node/service/src/chain_spec.rs
  runtime/rococo/src/bridge_messages.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#4482 Some fixes the compiler pointed out to me
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/collator-protocol/src/validator_side/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4486 Companion for Substrate#10444
  Cargo.lock
  node/service/src/grandpa_support.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌

#4341 Companion for #10309 - child-bounties
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, A7-companion, C1-low 📌, D1-audited 👍

#3899 Companion to Substrate #9829 (Add `put_in_front_of` extrinsic to bags-list)
  Cargo.lock
  runtime/kusama/src/weights/pallet_bags_list.rs
  runtime/polkadot/src/weights/pallet_bags_list.rs
  runtime/westend/src/weights/pallet_bags_list.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4408 pvf-precheck: Strip PastCodeMeta
  roadmap/implementers-guide/src/runtime/paras.md
  runtime/parachains/src/inclusion/mod.rs
  runtime/parachains/src/inclusion/tests.rs
  runtime/parachains/src/paras.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4420 pvf-precheck: update configuration module
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/migration.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#4492 Use saturating_add when converting a Vec<MultiAsset> to MultiAssets
  xcm/src/v1/multiasset.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4494 Update substrate
  Cargo.lock
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4390 Companion for #10382 (Insufficient asset quotas and deposits)
  Cargo.lock
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/lib.rs
  bridges/modules/dispatch/src/lib.rs
  bridges/modules/grandpa/src/mock.rs
  bridges/modules/messages/src/mock.rs
  bridges/modules/shift-session-manager/src/lib.rs
  bridges/modules/token-swap/src/mock.rs
  runtime/common/src/assigned_slots.rs
  runtime/common/src/auctions.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/impls.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/lib.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
  xcm/xcm-simulator/fuzzer/src/parachain.rs
  xcm/xcm-simulator/fuzzer/src/relay_chain.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#4498 cli: increase the time limit for the host-perf-check command
  cli/src/host_perf_check.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4466 Companion for #10177 (Make wasm runtime cache size configurable)
  Cargo.lock
  bridges/bin/millau/node/src/service.rs
  bridges/bin/rialto-parachain/node/src/service.rs
  bridges/bin/rialto/node/src/service.rs
  node/service/src/lib.rs
  node/test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4497 avoid unwrap_or_default in paras
  runtime/parachains/src/paras.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3623 Companion PR for removing Prometheus metrics prefix
  .gitlab-ci.yml
  Cargo.lock
  node/collation-generation/src/lib.rs
  node/core/approval-voting/src/lib.rs
  node/core/av-store/src/metrics.rs
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/core/chain-api/src/lib.rs
  node/core/dispute-coordinator/src/metrics.rs
  node/core/provisioner/src/metrics.rs
  node/core/pvf/src/metrics.rs
  node/core/runtime-api/src/lib.rs
  node/network/approval-distribution/src/lib.rs
  node/network/availability-distribution/src/metrics.rs
  node/network/availability-recovery/src/metrics.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/dispute-distribution/src/metrics.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/metrics.rs
  node/overseer/src/tests.rs
  node/service/src/lib.rs
  node/service/src/relay_chain_selection.rs
Labels: B0-silent, A7-companion, C1-low 📌

#4509 Don't cache unavailable results.
  node/network/availability-recovery/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4456 Extract Runtime Constants into Separate Crates
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  node/test/service/Cargo.toml
  node/test/service/src/chain_spec.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/constants/Cargo.toml
  runtime/kusama/constants/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/constants/Cargo.toml
  runtime/polkadot/constants/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/constants/Cargo.toml
  runtime/rococo/constants/src/lib.rs
  runtime/rococo/src/bridge_messages.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/constants/Cargo.toml
  runtime/test-runtime/constants/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/constants/Cargo.toml
  runtime/westend/constants/src/lib.rs
  runtime/westend/src/lib.rs
  utils/remote-ext-tests/bags-list/Cargo.toml
  utils/remote-ext-tests/bags-list/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4514 Upgrade Substrate and downgrade libc
  Cargo.lock
  node/core/pvf/Cargo.toml
  xcm/pallet-xcm-benchmarks/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4384 Companion for #10356: Preimage registrar and Scheduler integration
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_preimage.rs
  runtime/kusama/src/weights/pallet_scheduler.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_preimage.rs
  runtime/polkadot/src/weights/pallet_scheduler.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/pallet_preimage.rs
  runtime/westend/src/weights/pallet_scheduler.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮, E1-runtimemigration

#4493 Add CheckNonZeroSender to runtime configs
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto-parachain/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/lib.rs
  bridges/primitives/polkadot-core/src/lib.rs
  node/test/polkadot-simnet/common/src/lib.rs
  node/test/service/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/bridge_messages.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  utils/staking-miner/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4515 Substrate companion for #10470
  Cargo.lock
  runtime/kusama/src/weights/frame_system.rs
  runtime/polkadot/src/weights/frame_system.rs
  runtime/westend/src/weights/frame_system.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4233 Do not allow death on Crowdloan `contribute` + Introduce `contribute_all`
  runtime/common/src/crowdloan.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#4472 Revert loop prevention
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/network/availability-distribution/src/requester/mod.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/tests.rs
  roadmap/implementers-guide/src/node/availability/availability-distribution.md
  roadmap/implementers-guide/src/node/availability/bitfield-signing.md
  roadmap/implementers-guide/src/node/utility/provisioner.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4500 Companion #10403: Remove Default for AccountId
  Cargo.lock
  bridges/bin/millau/node/src/chain_spec.rs
  bridges/bin/rialto-parachain/node/src/chain_spec.rs
  bridges/bin/rialto/node/src/chain_spec.rs
  bridges/modules/messages/src/instant_payments.rs
  bridges/primitives/header-chain/tests/justification.rs
  bridges/primitives/polkadot-core/src/lib.rs
  bridges/primitives/test-utils/src/keyring.rs
  node/core/approval-voting/src/criteria.rs
  node/network/approval-distribution/src/tests.rs
  node/network/bridge/src/tests.rs
  node/network/gossip-support/src/lib.rs
  node/overseer/src/tests.rs
  node/primitives/src/approval.rs
  node/service/src/chain_spec.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/runtime/mod.rs
  node/test/service/src/chain_spec.rs
  node/test/service/tests/call-function.rs
  primitives/Cargo.toml
  primitives/src/v0.rs
  runtime/common/src/auctions.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/impls.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/tests.rs
  runtime/parachains/src/builder.rs
  runtime/parachains/src/paras_inherent/tests.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/bridge_messages.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#4470 Reanchor should return canonical location
  runtime/test-runtime/src/xcm_config.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/src/v1/multiasset.rs
  xcm/src/v1/multilocation.rs
  xcm/xcm-builder/src/location_conversion.rs
  xcm/xcm-executor/src/assets.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/conversion.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#4471 Companion for Substrate#10394
  Cargo.lock
  node/core/pvf/src/executor_intf.rs
Labels: F6-refactor, A0-pleasereview, F7-optimisation, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#4525 PVF validation host: do not alter niceness
  Cargo.lock
  node/core/pvf/Cargo.toml
  node/core/pvf/src/host.rs
  node/core/pvf/src/prepare/pool.rs
  node/core/pvf/src/prepare/queue.rs
  node/core/pvf/src/prepare/worker.rs
  node/core/pvf/src/priority.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4401 add Encointer as TrustedTeleporter to Kusama
  runtime/kusama/src/lib.rs
Labels: A1-onice, A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#4213 introduce trusted teleporter Encointer for Rococo and Westend
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#4530 fix compile with new compiler - dead code
  node/core/dispute-coordinator/src/metrics.rs
  node/malus/src/variants/suggest_garbage_candidate.rs
  utils/staking-miner/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4461 CI: rename polkasync job
  .gitlab-ci.yml
Labels: B0-silent, C1-low 📌

#4483 Add support for wasm runtime metrics try #2
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/command.rs
  node/client/Cargo.toml
  node/metrics/Cargo.toml
  node/metrics/src/lib.rs
  node/metrics/src/runtime.rs
  node/metrics/src/tests.rs
  node/service/Cargo.toml
  primitives/src/v1/metrics.rs
  primitives/src/v1/mod.rs
  runtime/kusama/Cargo.toml
  runtime/metrics/Cargo.toml
  runtime/metrics/src/lib.rs
  runtime/metrics/src/with_runtime_metrics.rs
  runtime/metrics/src/without_runtime_metrics.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/paras_inherent/mod.rs
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/westend/Cargo.toml
  scripts/gitlab/test_linux_stable.sh
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D5-nicetohaveaudit ⚠️

#4532 Add notice on upgrading some constants
  primitives/src/v1/mod.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4478 paras: add log target
  runtime/parachains/src/paras.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4539 naming consistency
  bridges/bin/rialto/node/src/overseer.rs
  node/core/provisioner/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/tests.rs
  node/service/src/overseer.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4528 Support new version of zombienet
  .gitlab-ci.yml
  node/malus/integrationtests/0001-dispute-valid-block.toml
  zombienet_tests/parachains/0001-parachains-smoke-test.toml
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌

#4546 Fix fmt on master
  runtime/parachains/src/paras.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4464 enable disputes for known chains, except for polkadot
  .gitlab-ci.yml
  Cargo.toml
  bridges/bin/rialto/node/src/overseer.rs
  bridges/bin/rialto/node/src/service.rs
  cli/Cargo.toml
  node/core/dispute-coordinator/src/dummy.rs
  node/core/dispute-coordinator/src/error.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/metrics.rs
  node/core/dispute-coordinator/src/real/backend.rs
  node/core/dispute-coordinator/src/real/db/v1.rs
  node/core/dispute-coordinator/src/real/initialized.rs
  node/core/dispute-coordinator/src/real/mod.rs
  node/core/dispute-coordinator/src/real/ordering/mod.rs
  node/core/dispute-coordinator/src/real/participation/mod.rs
  node/core/dispute-coordinator/src/real/tests.rs
  node/core/dispute-coordinator/src/status.rs
  node/core/provisioner/src/lib.rs
  node/malus/Cargo.toml
  node/overseer/overseer-gen/proc-macro/src/impl_builder.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/service/src/relay_chain_selection.rs
  node/service/src/tests.rs
  scripts/gitlab/test_linux_stable.sh
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, A1-needsburnin

#4059 Create a README for XCMv2 detailing notable changes
  xcm/src/v1/README.md
  xcm/src/v2/mod.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D2-notlive 💤

#4559 [disputes] remove invalid subsystem replace
  node/service/src/overseer.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4553 [Zombienet] use v1.0.2
  .gitlab-ci.yml
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌

#4560 Fix chain API ancestors look-up at genesis block
  node/core/chain-api/src/lib.rs
  node/core/chain-api/src/tests.rs
  node/subsystem-types/src/messages.rs
Labels: F2-bug, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4562 [Zombienet] fix test creds
  .gitlab-ci.yml
  node/malus/integrationtests/0001-dispute-valid-block.feature
  zombienet_tests/parachains/0001-parachains-smoke-test.feature
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌

#4565 Suggest installing graphviz before book building
  roadmap/implementers-guide/README.md
Labels: F5-documentation, B0-silent, C1-low 📌

#4561 Update Polkadot
  runtime/kusama/constants/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/constants/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/constants/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4557 Dispute-coordinator: fix underflow panic
  node/core/dispute-coordinator/src/real/ordering/mod.rs
  node/core/dispute-coordinator/src/real/ordering/tests.rs
Labels: F1-panic, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4556 Substrate companion for change slot duration fetching
  Cargo.lock
  bridges/bin/rialto/node/src/service.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4540 parachains: Fix configuration module
  runtime/kusama/src/weights/runtime_parachains_configuration.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/migration.rs
  runtime/polkadot/src/weights/runtime_parachains_configuration.rs
  runtime/westend/src/weights/runtime_parachains_configuration.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#4542 pvf-precheck: hook up runtime API
  Cargo.lock
  node/core/runtime-api/Cargo.toml
  node/core/runtime-api/src/cache.rs
  node/core/runtime-api/src/lib.rs
  node/core/runtime-api/src/tests.rs
  node/subsystem-types/src/messages.rs
  primitives/src/v1/mod.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4459 pvf-precheck: update rustdoc for paras module
  runtime/parachains/src/paras.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4506 Companion for Substrate#10445
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#4410 Fix currently-checking-cache
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, A1-needsburnin, D5-nicetohaveaudit ⚠️

#4582 chore: rename for consistency
  node/core/runtime-api/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4569 configuration: refactor configuration initialization
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/initializer.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4437 First step in implementing #4386
  node/core/backing/src/lib.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/protocol/src/request_response/mod.rs
  roadmap/implementers-guide/src/node/backing/candidate-backing.md
  runtime/parachains/src/inclusion/mod.rs
  runtime/parachains/src/inclusion/tests.rs
Labels: A0-pleasereview, F7-optimisation, B0-silent, C1-low 📌, D1-audited 👍

#4595 runtime-api: Fix runtime version checking
  node/core/runtime-api/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4594 Fix checking for the `ParachainHost` runtime api
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C7-high ❗️

#4593 Better logs and metrics on PoV fetching.
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/metrics.rs
  node/network/availability-distribution/src/pov_requester/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4104 Companion for substrate#9732
  Cargo.lock
  Cargo.toml
  bridges/primitives/chain-rococo/src/lib.rs
  bridges/primitives/runtime/src/storage_proof.rs
  erasure-coding/src/lib.rs
  node/core/pvf/src/executor_intf.rs
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#4545 session-info: add new fields + migration
  node/client/src/lib.rs
  node/core/approval-voting/src/criteria.rs
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  node/core/dispute-coordinator/src/real/initialized.rs
  node/core/dispute-coordinator/src/real/tests.rs
  node/core/runtime-api/src/cache.rs
  node/core/runtime-api/src/lib.rs
  node/core/runtime-api/src/tests.rs
  node/network/availability-distribution/src/tests/mock.rs
  node/network/availability-distribution/src/tests/state.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/dispute-distribution/src/tests/mock.rs
  node/network/dispute-distribution/src/tests/mod.rs
  node/network/statement-distribution/src/tests.rs
  node/overseer/src/lib.rs
  node/primitives/src/disputes/message.rs
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/rolling_session_window.rs
  node/subsystem-util/src/runtime/mod.rs
  primitives/src/lib.rs
  primitives/src/v1/mod.rs
  primitives/src/v2/mod.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/session_info.rs
  runtime/parachains/src/session_info/migration.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium 📣, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#4547 session-info: add dispute_period and random_seed
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/tests.rs
  node/core/dispute-coordinator/src/real/tests.rs
  node/core/runtime-api/src/tests.rs
  node/network/availability-distribution/src/tests/mock.rs
  node/network/availability-recovery/src/tests.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/dispute-distribution/src/tests/mock.rs
  node/network/statement-distribution/src/tests.rs
  node/subsystem-util/src/rolling_session_window.rs
  primitives/src/v2/mod.rs
  runtime/parachains/src/session_info.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#4588 Make check-dependent-* only be executed in PRs
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4600 zombienet: fixed adder-collator image for the smoke test
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4581 configuration: Unified consistency checks
  node/service/src/chain_spec.rs
  runtime/parachains/src/configuration.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#4613 Fix flaky test in polkadot-node-metrics
  node/metrics/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4580 configuration: Consistency checks for PVF pre-checking
  node/service/src/chain_spec.rs
  node/test/service/src/chain_spec.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/scheduler.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#4625 paras: fix placeholder weight
  runtime/parachains/src/paras.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4583 configuration: validation_upgrade_delay consistency
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/inclusion/tests.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D5-nicetohaveaudit ⚠️

#4629 runtime-api: add validation_code_hash API
  node/core/runtime-api/src/cache.rs
  node/core/runtime-api/src/lib.rs
  node/core/runtime-api/src/tests.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-util/src/lib.rs
  primitives/src/v2/mod.rs
  roadmap/implementers-guide/src/runtime-api/validation-code.md
  runtime/kusama/src/lib.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4618 Use derive macro to generate XcmWeightInfo trait
  Cargo.lock
  xcm/procedural/Cargo.toml
  xcm/procedural/src/lib.rs
  xcm/procedural/src/weight_info.rs
  xcm/src/v2/mod.rs
  xcm/src/v2/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4612 pvf-precheck: update implementers' guide
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/utility/candidate-validation.md
  roadmap/implementers-guide/src/node/utility/pvf-prechecker.md
  roadmap/implementers-guide/src/pvf-prechecking.md
  roadmap/implementers-guide/src/runtime-api/pvf-prechecking.md
  roadmap/implementers-guide/src/runtime/configuration.md
  roadmap/implementers-guide/src/runtime/paras.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  roadmap/implementers-guide/src/types/pvf-prechecking.md
  roadmap/implementers-guide/src/types/runtime.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4627 custom cargo profiles for production
  .gitlab-ci.yml
  Cargo.toml
  scripts/gitlab/test_linux_stable.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4575 paras: add governance control dispatchables
  runtime/kusama/src/weights/runtime_parachains_paras.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/paras/benchmarking.rs
  runtime/polkadot/src/weights/runtime_parachains_paras.rs
  runtime/rococo/src/weights/runtime_parachains_paras.rs
  runtime/westend/src/weights/runtime_parachains_paras.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#4637 derive Copy and Clone for Upgrade signals
  primitives/src/v1/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4635 configuration: Rename validation_upgrade_{frequency -> cooldown}
  node/service/src/chain_spec.rs
  node/test/service/src/chain_spec.rs
  primitives/src/v1/mod.rs
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/paras.md
  roadmap/implementers-guide/src/types/README.md
  roadmap/implementers-guide/src/types/runtime.md
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/migration.rs
  runtime/parachains/src/paras.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4603 paras: fix upgrade restriction signal
  runtime/parachains/src/dmp.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/inclusion/tests.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/scheduler.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️
