Repository paritytech/polkadot, pull requests merged in 2021-10, with the labels that each got.

#3981 Bump async-std's version to remove conflict on Substrate for Cumulus
  node/core/pvf/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3976 Replace rococo chainspec with new one
  node/service/res/rococo.json
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3982 Remove incorrect proof about Jemalloc
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3985 add polkadot-simnet runner
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3984 av-store: clean up StoreAvailableData message
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/backing/src/tests.rs
  node/core/dispute-participation/src/lib.rs
  node/core/dispute-participation/src/tests.rs
  node/subsystem-types/src/messages.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3990 add logs to relay chain selection
  node/service/src/relay_chain_selection.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3991 Fix an off-by-one: revert rather than revert-to
  roadmap/implementers-guide/src/runtime/disputes.md
  runtime/parachains/src/disputes.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3993 add disputes call to Rococo
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3988 Tidy up XCM errors in preparation for v2.
  scripts/gitlab/lingua.dic
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/tests.rs
  xcm/src/v2/mod.rs
  xcm/src/v2/traits.rs
  xcm/xcm-executor/integration-tests/src/lib.rs
  xcm/xcm-executor/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#3904 always broadcast tranche 0 assignments and add a delay before approval
  node/core/approval-voting/src/approval_checking.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  roadmap/implementers-guide/src/node/approval/approval-voting.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3996 some tweaks to rococo-local
  node/service/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3997 preserve finalized block in active leaves
  node/overseer/src/lib.rs
  node/overseer/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3994 avoid expect, on free availability core
  runtime/parachains/src/inclusion.rs
  runtime/rococo/src/lib.rs
Labels: A3-inprogress, B0-silent, C1-low 📌

#3859 ignore irrelevant approvals in logs
  node/core/approval-voting/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3998 change genesis authority set for wococo-local, revert rococo-local
  node/service/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4000 bump substrate
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3999 Remove unoccupied bit check
  runtime/parachains/src/inclusion.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3851 fix clock drift for assignments issued before the block
  node/core/approval-voting/src/approval_checking.rs
  node/core/approval-voting/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4004 Fix unoccupied bitfields
  runtime/parachains/src/inclusion.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#4002 Use background tasks properly in candidate-validation
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3992 chore: ci list files that spellcheck finds
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3631 GHA: extrinsic ordering, new filter to generate a summary
  .github/workflows/extrinsic-ordering-check-from-bin.yml
  scripts/github/extrinsic-ordering-filter.sh
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4001 Make candidate validation timeouts configurable
  node/core/approval-voting/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/backing/src/tests.rs
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/tests.rs
  node/core/dispute-participation/src/lib.rs
  node/core/dispute-participation/src/tests.rs
  node/core/pvf/src/execute/queue.rs
  node/core/pvf/src/execute/worker.rs
  node/core/pvf/src/host.rs
  node/core/pvf/tests/it/main.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/src/tests.rs
  node/primitives/src/lib.rs
  node/subsystem-types/src/messages.rs
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/node/backing/candidate-backing.md
  roadmap/implementers-guide/src/node/disputes/dispute-participation.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#4008 Free disputed cores before processing bitfields
  roadmap/implementers-guide/src/runtime/parainherent.md
  roadmap/implementers-guide/src/runtime/scheduler.md
  runtime/parachains/src/paras_inherent.rs
  runtime/parachains/src/scheduler.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3884 chore: update `builder` image
  scripts/dockerfiles/polkadot/build.sh
  scripts/dockerfiles/polkadot/docker-compose-local.yml
  scripts/dockerfiles/polkadot/docker-compose.yml
  scripts/dockerfiles/polkadot/polkadot_builder.Dockerfile
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3901 Companion for #9834 (Transaction Priority)
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B7-runtimenoteworthy, A7-companion, C3-medium 📣, D1-audited 👍

#3980 Allow an Offset to Lease Periods
  runtime/common/src/auctions.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/slots.rs
  runtime/common/src/traits.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#3866 Add call-decoding weight to benchmarks
  runtime/common/src/claims.rs
  runtime/kusama/src/weights/runtime_common_claims.rs
  runtime/polkadot/src/weights/runtime_common_claims.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3966 Re-configure offchain repeat frequency for elections
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#3946 Silence some alerts due to overly verbose warnings.
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/statement-distribution/src/error.rs
  node/network/statement-distribution/src/lib.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#3924 collect included disputes from on-chain
  doc/shell-completion.md
  node/core/dispute-coordinator/src/real/mod.rs
  node/core/dispute-coordinator/src/real/tests.rs
  node/core/runtime-api/src/cache.rs
  node/core/runtime-api/src/lib.rs
  node/core/runtime-api/src/tests.rs
  node/primitives/src/disputes/mod.rs
  node/subsystem-types/src/messages.rs
  primitives/src/v0.rs
  primitives/src/v1/mod.rs
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
  roadmap/implementers-guide/src/runtime/parainherent.md
  roadmap/implementers-guide/src/types/disputes.md
  runtime/kusama/src/lib.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/paras_inherent.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  scripts/gitlab/lingua.dic
  statement-table/src/generic.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4105 companion PR to removal of light client
  Cargo.lock
  bridges/.config/lingua.dic
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4127 increase ump_service_total_weight's default value
  node/service/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4183 differentiate log messages
  node/core/dispute-coordinator/src/real/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4180 remove duplicate Deposit from OnUnbalanced implementation
  runtime/common/src/impls.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#4179 collator-protocol/validator_side: a couple of fixes
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4189 bump rococo spec
  node/service/res/rococo.json
  runtime/rococo/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸
