Repository paritytech/polkadot, pull requests merged in 2021-04, with the labels that each got.

#2566 Node-side subsystems for Disputes
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/approval/README.md
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/node/approval/dispute-participation.md
  roadmap/implementers-guide/src/node/backing/candidate-backing.md
  roadmap/implementers-guide/src/node/disputes/README.md
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
  roadmap/implementers-guide/src/node/disputes/dispute-distribution.md
  roadmap/implementers-guide/src/node/disputes/dispute-participation.md
  roadmap/implementers-guide/src/node/grandpa-voting-rule.md
  roadmap/implementers-guide/src/node/utility/provisioner.md
  roadmap/implementers-guide/src/runtime-api/candidates-included.md
  roadmap/implementers-guide/src/runtime-api/disputes-info.md
  roadmap/implementers-guide/src/runtime-api/known-disputes.md
  roadmap/implementers-guide/src/runtime/disputes.md
  roadmap/implementers-guide/src/types/disputes.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  roadmap/implementers-guide/src/types/runtime.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2101 Merkle Mountain Range & BEEFY integration
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  node/service/src/client.rs
  node/service/src/lib.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/mmr.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  scripts/prepare-test-net.sh
Labels: B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#2794 Companion for OnSetCode #8496
  Cargo.lock
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/lib.rs
  bridges/modules/call-dispatch/src/lib.rs
  bridges/modules/currency-exchange/src/lib.rs
  bridges/modules/ethereum/src/mock.rs
  bridges/modules/finality-verifier/src/mock.rs
  bridges/modules/message-lane/src/mock.rs
  bridges/modules/shift-session-manager/src/lib.rs
  bridges/modules/substrate/src/mock.rs
  runtime/common/src/auctions.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/impls.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/lib.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2792 Avoid querying the local validator in availability recovery
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/tests/state.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/availability/availability-recovery.md
  roadmap/implementers-guide/src/node/utility/availability-store.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2786 gossip: do not try to connect if we are not validators
  Cargo.lock
  node/network/gossip-support/Cargo.toml
  node/network/gossip-support/src/lib.rs
  node/network/protocol/src/peer_set.rs
  node/service/src/lib.rs
  node/subsystem-util/src/validator_discovery.rs
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/utility/gossip-support.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2791 Add dispute types and change InclusionInherent to ParasInherent
  node/collation-generation/src/lib.rs
  node/core/proposer/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/tests.rs
  node/subsystem/src/messages.rs
  node/test/client/src/block_builder.rs
  primitives/src/v1.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras_inherent.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/util.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2796 tweaks to relevant_authority_ids
  runtime/parachains/src/runtime_api_impl/v1.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2795 Companion PR for substrate#8510
  Cargo.lock
  node/network/protocol/src/request_response/request.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low 📌

#2781 Approval Voting improvements
  Cargo.lock
  node/core/approval-voting/Cargo.toml
  node/core/approval-voting/src/approval_checking.rs
  node/core/approval-voting/src/approval_db/v1/mod.rs
  node/core/approval-voting/src/approval_db/v1/tests.rs
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/persisted_entries.rs
  node/core/approval-voting/src/tests.rs
  node/core/av-store/Cargo.toml
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/network/approval-distribution/src/lib.rs
  node/network/bridge/Cargo.toml
  node/network/bridge/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/parachains_db.rs
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/node/utility/network-bridge.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2800 remove approval checking training wheels
  node/service/src/grandpa_support.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2798 gossip: move authorities request to runtime api subsystem
  Cargo.lock
  node/core/runtime-api/Cargo.toml
  node/core/runtime-api/src/cache.rs
  node/core/runtime-api/src/lib.rs
  node/network/gossip-support/Cargo.toml
  node/network/gossip-support/src/lib.rs
  node/service/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/src/messages.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#2593 Ease parachain candidate code fetching
  node/collation-generation/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/primitives/src/lib.rs
  parachain/src/primitives.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/runtime/paras.md
  runtime/kusama/src/lib.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤, D9-needsaudit👮

#2806 add disputes members to `HostConfiguration`
  node/service/src/chain_spec.rs
  node/test/service/src/chain_spec.rs
  roadmap/implementers-guide/src/types/runtime.md
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/paras.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2625 companion: update wasmtime to 0.24.0
  Cargo.lock
  node/primitives/Cargo.toml
  node/primitives/src/lib.rs
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low 📌

#2802 change some configuration for rococo
  node/service/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2809 approval-distribution: split peer knowledge into sent and received
  node/network/approval-distribution/src/lib.rs
  node/network/approval-distribution/src/tests.rs
  roadmap/implementers-guide/src/node/approval/approval-distribution.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2810 Collation protocol: stricter validators
  Cargo.lock
  node/collation-generation/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/requester/mod.rs
  node/network/availability-distribution/src/runtime.rs
  node/network/availability-distribution/src/session_cache.rs
  node/network/availability-distribution/src/tests/mod.rs
  node/network/availability-recovery/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/collator-protocol/Cargo.toml
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/gossip-support/src/lib.rs
  node/network/protocol/src/lib.rs
  node/service/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/validator_discovery.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/node/collators/collator-protocol.md
  roadmap/implementers-guide/src/types/network.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2788 Create Macro for Implementing `SlotRange`
  Cargo.lock
  Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/slot_range_helper/Cargo.toml
  runtime/common/slot_range_helper/src/lib.rs
  runtime/common/src/auctions.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/lib.rs
  runtime/common/src/slot_range.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2770 Crowdloan Dissolve Requires All Funds Refunded
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2807 feat: Add poke to Crowdloan
  runtime/common/src/crowdloan.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2816 Collators: Declare to all peers
  node/network/collator-protocol/src/collator_side.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2817 bitfield-dist: fix state update on gossip
  node/network/approval-distribution/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/statement-distribution/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2818 Network bridge metrics
  node/network/bridge/Cargo.toml
  node/network/bridge/src/lib.rs
  node/network/bridge/src/network.rs
  node/network/collator-protocol/src/collator_side.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2819 finally get unbacked candidates to descend from root span correctly
  node/core/backing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2813 tests: use future::join instead of future::select
  node/core/av-store/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/provisioner/src/tests.rs
  node/network/approval-distribution/src/tests.rs
  node/network/availability-distribution/src/tests/mod.rs
  node/network/availability-distribution/src/tests/state.rs
  node/network/availability-recovery/src/tests.rs
  node/network/bridge/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/statement-distribution/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2821 Properly remove peers from sets and merge the two Network traits
  node/network/bridge/src/lib.rs
  node/network/bridge/src/network.rs
  node/network/bridge/src/validator_discovery.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2827 parachain_db: fix incorrect config cache sizes
  node/service/src/parachains_db.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#2826 Enable debug assertions on burn-in PRs
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2823 statement-distribution: do not verify signatures for duplicate statements
  node/network/statement-distribution/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2829 parachain db versioning
  node/service/src/parachains_db/mod.rs
  node/service/src/parachains_db/upgrade.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2830 update rococo genesis
  node/service/res/rococo.json
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2831 update twox-hash
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2832 remove WASM_MAGIC
  runtime/common/src/integration_tests.rs
  runtime/common/src/lib.rs
  runtime/common/src/mock.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/paras_sudo_wrapper.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2808 Relax Origin Checks in Registrar, Add Lock to Registration
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/mock.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/traits.rs
  runtime/parachains/src/paras.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2785 Add Root Functions to HRMP
  runtime/parachains/src/hrmp.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2840 Rococo Updates (Origin Checks and 10 Min Sessions)
  node/service/res/rococo.json
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/mock.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/traits.rs
  runtime/parachains/src/paras.rs
  runtime/rococo/src/constants.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2839 Reduce Epoch Duration to 10 Min for Rococo
  runtime/rococo/src/constants.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2844 fix failing test
  runtime/common/src/paras_registrar.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2833 check for lost race before warning
  node/core/approval-voting/src/import.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2836 XCM revamp
  Cargo.lock
  runtime/common/src/paras_sudo_wrapper.rs
  runtime/common/src/xcm_sender.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/ump.rs
  runtime/rococo/src/lib.rs
  xcm/Cargo.toml
  xcm/src/double_encoded.rs
  xcm/src/lib.rs
  xcm/src/v0/junction.rs
  xcm/src/v0/mod.rs
  xcm/src/v0/multi_asset.rs
  xcm/src/v0/order.rs
  xcm/src/v0/traits.rs
  xcm/xcm-builder/src/barriers.rs
  xcm/xcm-builder/src/currency_adapter.rs
  xcm/xcm-builder/src/filter_asset_location.rs
  xcm/xcm-builder/src/fungibles_adapter.rs
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/location_conversion.rs
  xcm/xcm-builder/src/matches_fungible.rs
  xcm/xcm-builder/src/mock.rs
  xcm/xcm-builder/src/origin_conversion.rs
  xcm/xcm-builder/src/tests.rs
  xcm/xcm-builder/src/weight.rs
  xcm/xcm-executor/src/assets.rs
  xcm/xcm-executor/src/config.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits.rs
  xcm/xcm-executor/src/traits/conversion.rs
  xcm/xcm-executor/src/traits/filter_asset_location.rs
  xcm/xcm-executor/src/traits/matches_fungible.rs
  xcm/xcm-executor/src/traits/mod.rs
  xcm/xcm-executor/src/traits/on_response.rs
  xcm/xcm-executor/src/traits/should_execute.rs
  xcm/xcm-executor/src/traits/transact_asset.rs
  xcm/xcm-executor/src/traits/weight.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2851 add new chainspec for rococo
  node/service/res/rococo.json
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-breaksapi, D3-trivial 🧸

#2828 fix erasure-coding fuzz tests
  erasure-coding/fuzzer/.gitignore
  erasure-coding/fuzzer/Cargo.lock
  erasure-coding/fuzzer/Cargo.toml
  erasure-coding/fuzzer/src/reconstruct.rs
  erasure-coding/fuzzer/src/round_trip.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#2834 Remove real-overseer 🎉
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  node/overseer/Cargo.toml
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/service/Cargo.toml
  node/service/src/grandpa_support.rs
  node/service/src/lib.rs
  node/service/src/parachains_db/mod.rs
  node/service/src/parachains_db/upgrade.rs
  node/subsystem-test-helpers/src/lib.rs
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/adder/collator/README.md
  parachain/test-parachains/adder/collator/tests/integration.rs
  scripts/adder-collator.sh
  scripts/gitlab/test_linux_stable.sh
  scripts/two-node-local-net.sh
Labels: A0-pleasereview, A1-needsburnin, B0-silent, C1-low 📌, D3-trivial 🧸

#2846 Introduce plurality XCM locations
  xcm/src/v0/junction.rs
  xcm/src/v0/mod.rs
  xcm/src/v0/multi_location.rs
  xcm/xcm-executor/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2856 bump spec versions across the board
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2855 runtime: fix the session keys migration that includes the beefy key type
  runtime/common/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2857 Update Release Checklist for Westend Runtime Upgrade
  .github/ISSUE_TEMPLATE/release.md
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2852 Code, PoV compression and remove `CompressedPoV` struct
  Cargo.lock
  node/collation-generation/Cargo.toml
  node/collation-generation/src/lib.rs
  node/core/candidate-validation/Cargo.toml
  node/core/candidate-validation/src/lib.rs
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/pov_requester/mod.rs
  node/network/availability-distribution/src/responder.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/protocol/src/request_response/mod.rs
  node/network/protocol/src/request_response/v1.rs
  node/primitives/Cargo.toml
  node/primitives/src/lib.rs
  parachain/test-parachains/adder/collator/src/lib.rs
  roadmap/implementers-guide/src/types/network.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2710 New PVF validation host
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/cli.rs
  cli/src/command.rs
  node/core/candidate-validation/Cargo.toml
  node/core/candidate-validation/src/lib.rs
  node/core/pvf/Cargo.toml
  node/core/pvf/bin/puppet_worker.rs
  node/core/pvf/src/artifacts.rs
  node/core/pvf/src/error.rs
  node/core/pvf/src/execute/mod.rs
  node/core/pvf/src/execute/queue.rs
  node/core/pvf/src/execute/worker.rs
  node/core/pvf/src/executor_intf.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/lib.rs
  node/core/pvf/src/prepare/mod.rs
  node/core/pvf/src/prepare/pool.rs
  node/core/pvf/src/prepare/queue.rs
  node/core/pvf/src/prepare/worker.rs
  node/core/pvf/src/priority.rs
  node/core/pvf/src/pvf.rs
  node/core/pvf/src/testing.rs
  node/core/pvf/src/worker_common.rs
  node/core/pvf/tests/it/adder.rs
  node/core/pvf/tests/it/main.rs
  node/core/pvf/tests/it/worker_common.rs
  node/service/src/lib.rs
  node/test/service/src/lib.rs
  node/test/service/tests/build-blocks.rs
  node/test/service/tests/call-function.rs
  parachain/Cargo.toml
  parachain/src/lib.rs
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
  parachain/src/wasm_executor/validation_host/workspace.rs
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/adder/collator/bin/puppet_worker.rs
  parachain/test-parachains/adder/collator/src/lib.rs
  parachain/test-parachains/adder/collator/tests/integration.rs
  parachain/test-parachains/tests/adder/mod.rs
  parachain/test-parachains/tests/wasm_executor/mod.rs
Labels: A0-pleasereview, A9-FUCKYEAH!, B0-silent, C1-low 📌

#2859 silence some parachain warnings
  node/core/approval-voting/src/import.rs
  node/network/availability-distribution/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#2860 no backing job early exit if not validator
  node/core/backing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2863 set groups correctly even if not validator
  node/core/backing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2864 ModuleId to PalletId
  Cargo.lock
  runtime/common/src/crowdloan.rs
  runtime/common/src/impls.rs
  runtime/common/src/integration_tests.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2868 bitfield-dist: check signatures once
  node/network/bitfield-distribution/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2865 XCM Revamp Continued
  Cargo.lock
  Cargo.toml
  runtime/common/src/xcm_sender.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/ump.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  xcm/Cargo.toml
  xcm/pallet-xcm/Cargo.toml
  xcm/pallet-xcm/src/lib.rs
  xcm/src/v0/junction.rs
  xcm/src/v0/mod.rs
  xcm/src/v0/traits.rs
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/origin_conversion.rs
  xcm/xcm-executor/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2858 Introduce System Parachains into Registrar
  parachain/src/primitives.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/slots.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2869 Introduce/integrate a collective into Rococo Relay
  Cargo.lock
  node/service/src/chain_spec.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
  xcm/xcm-builder/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2803 Req/res optimization for statement distribution
  Cargo.lock
  node/core/proposer/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/multiplexer.rs
  node/network/protocol/src/lib.rs
  node/network/protocol/src/request_response/mod.rs
  node/network/protocol/src/request_response/request.rs
  node/network/protocol/src/request_response/v1.rs
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/requester.rs
  node/network/statement-distribution/src/responder.rs
  node/overseer/src/lib.rs
  node/primitives/src/lib.rs
  node/service/src/chain_spec.rs
  node/subsystem/src/messages.rs
  primitives/src/v1.rs
  runtime/rococo/src/constants.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2692 Remove hack around Yamux window size
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2870 update rococo and remove cursed BEEFY migration
  node/service/res/rococo.json
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2871 distribution: handle sqrt peer view updates
  node/network/approval-distribution/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/subsystem-util/src/lib.rs
  roadmap/implementers-guide/src/node/utility/gossip-support.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2782 Cost analysis of a council election full block
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2862 Change Auctions to Eight Lease Periods Per Slot
  Cargo.lock
  runtime/common/slot_range_helper/Cargo.toml
  runtime/common/slot_range_helper/src/lib.rs
  runtime/common/src/auctions.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/slot_range.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#2872 Rococo allows ROC to be teleported from Tick, Trick and Track
  runtime/rococo/src/lib.rs
  xcm/xcm-builder/src/filter_asset_location.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2873 Dedupe some code and companion for #8589
  Cargo.lock
  runtime/rococo/src/lib.rs
  xcm/xcm-builder/src/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2735 Max notification size -> 100k.
  node/network/protocol/src/peer_set.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2848 Expose `SampleLength` in Consts Metadata
  runtime/common/src/auctions.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2764 Remove already triggered migrations
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2875 More tests for new request based statement distribution
  Cargo.lock
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/requester.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2674 Rename constant to EPOCH_DURATION_IN_SLOTS
  runtime/kusama/src/constants.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/constants.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/constants.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/constants.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2876 Remove unused and sometime invalid type alias
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2560 Companion for inherent checks: #8173
  Cargo.lock
  runtime/parachains/src/paras_inherent.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low 📌

#2649 Companion for Trim compact solution for length during preparation
  Cargo.lock
  runtime/common/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-breaksapi, D5-nicetohaveaudit ⚠️

#2881 Pull latest version of libp2p-dns
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2837 Update srtool
  .github/workflows/publish-draft-release.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2883 Companion for Substrate#8588
  Cargo.lock
  node/core/proposer/src/lib.rs
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low 📌

#2889 Only accept requests from peers that got notified by us.
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/responder.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2886 Expose paras config in rococo runtime
  node/service/src/chain_spec.rs
  runtime/rococo/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2891 Reduce Minimum Vested Transfer by 100x
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#2897 Infrastructure improvements
  Cargo.lock
  node/core/candidate-validation/src/lib.rs
  node/network/approval-distribution/src/lib.rs
  node/network/approval-distribution/src/tests.rs
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/pov_requester/mod.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/protocol/src/request_response/mod.rs
  node/network/statement-distribution/src/lib.rs
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/runtime/error.rs
  node/subsystem-util/src/runtime/mod.rs
  node/subsystem/src/messages/network_bridge_event.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, F6-refactor

#2895 Companion for substrate/pull/8596
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_membership.rs
  runtime/parachains/src/paras_inherent.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/session_info.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low 📌, D3-trivial 🧸

#2894 Companion PR for substrate#8625
  Cargo.lock
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low 📌

#2904 pass COLLATOR_IMAGE var to simnet
  .gitlab-ci.yml
Labels: B0-silent, C1-low 📌

#2899 bump rocksdb to 6.17.3
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#2908 Companion for substrate#8643
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low 📌

#2906 Bump BEEFY
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2910 Update substrate
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2914 runtime: prepare Westend runtime for BEEFY
  Cargo.lock
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2916 runtime: remove mmr and beefy from westend runtime
  Cargo.lock
  node/service/src/chain_spec.rs
  node/service/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2885 CI: optimizations
  .gitlab-ci.yml
  scripts/gitlab/test_linux_stable.sh
  scripts/gitlab/trigger_pipeline.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2918 Introduce Wococo testnet
  cli/src/command.rs
  node/service/res/wococo.json
  node/service/src/chain_spec.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2924 Companion for impl Zero and One for fixed point numbers
  Cargo.lock
  runtime/common/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2765 companion for substrate/pull/8044
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#2926 Update Kusama Nominations to 24
  runtime/kusama/src/lib.rs
Labels: A0-pleasereview, B0-silent, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#2930 Update `grandpa-bridge-gadget` Dependency
  Cargo.lock
  node/service/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
Labels: A0-pleasereview

#2920 Simplify some Option / Result / ? operator patterns
  bridges/modules/ethereum/src/validators.rs
  node/core/approval-voting/src/approval_checking.rs
  node/network/approval-distribution/src/lib.rs
  node/network/availability-distribution/src/tests/mod.rs
  node/network/availability-recovery/src/lib.rs
  node/network/statement-distribution/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2937 Bump BEEFY
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2936 CI: build collator image on rococo branch too
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2934 Add Statemint teleport
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2896 Add XCM Origin and converter
  Cargo.lock
  runtime/rococo/src/lib.rs
  xcm/pallet-xcm/Cargo.toml
  xcm/pallet-xcm/src/lib.rs
  xcm/src/v0/mod.rs
  xcm/src/v0/multi_location.rs
  xcm/src/v0/traits.rs
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/mock.rs
  xcm/xcm-builder/src/weight.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/weight.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2941 Fix link to polkadot runtime spec in implementers guide
  roadmap/implementers-guide/src/further-reading.md
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2940 change junction parachain id from named field to unnamed field
  runtime/common/src/xcm_sender.rs
  runtime/parachains/src/ump.rs
  runtime/rococo/src/lib.rs
  xcm/src/v0/junction.rs
  xcm/xcm-builder/src/location_conversion.rs
  xcm/xcm-builder/src/mock.rs
  xcm/xcm-builder/src/origin_conversion.rs
  xcm/xcm-builder/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2928 Add Dev Config for Rococo and Wococo
  cli/src/command.rs
  node/service/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2942 Bump Substrate.
  Cargo.lock
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2927 Send statements to own backing group first
  Cargo.lock
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/pov_requester/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/responder.rs
  node/network/availability-distribution/src/session_cache.rs
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/error.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/requester.rs
  node/service/src/lib.rs
  node/subsystem-util/src/error_handling.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/runtime/error.rs
  node/subsystem-util/src/runtime/mod.rs
  node/subsystem/src/messages.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2946 Bump BEEFY
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#2952 Required weight is returned in case it exceeds limit.
  runtime/parachains/src/ump.rs
  xcm/src/v0/multi_location.rs
  xcm/src/v0/traits.rs
  xcm/xcm-executor/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2953 Allow normal accounts to execute XCM for withdraw+teleport
  Cargo.lock
  runtime/rococo/src/lib.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/src/v0/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2949 feat: add proc macro to reduce overseer mock boilerplate
  Cargo.lock
  node/overseer/Cargo.toml
  node/overseer/src/lib.rs
  node/overseer/subsystems-gen/Cargo.toml
  node/overseer/subsystems-gen/src/lib.rs
  node/overseer/subsystems-gen/tests/ui/err-01-enum.rs
  node/overseer/subsystems-gen/tests/ui/err-01-enum.stderr
  node/overseer/subsystems-gen/tests/ui/err-01-generic-used-twice.rs
  node/overseer/subsystems-gen/tests/ui/err-01-generic-used-twice.stderr
  node/overseer/subsystems-gen/tests/ui/err-01-no-generic.rs
  node/overseer/subsystems-gen/tests/ui/err-01-no-generics.stderr
  node/overseer/subsystems-gen/tests/ui/ok-01-w-generics.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2957 Implement null weight trader
  xcm/src/v0/traits.rs
  xcm/xcm-executor/src/traits/weight.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#2959 v0.9.0 prep
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/service/Cargo.toml
  node/test/client/Cargo.toml
  node/test/service/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/slot_range_helper/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  statement-table/Cargo.toml
  xcm/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸
