Repository paritytech/polkadot, pull requests merged in 2021-05, with the labels that each got.

#2964 BEEFY: make KeyStore optional
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2854 Add parachains modules to Westend and Kusama runtimes
  Cargo.lock
  node/service/src/chain_spec.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/constants.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/runtime_common_paras_registrar.rs
  runtime/kusama/src/weights/runtime_common_slots.rs
  runtime/parachains/src/configuration.rs
  runtime/polkadot/src/constants.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/constants.rs
  runtime/rococo/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/constants.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/runtime_common_paras_registrar.rs
  runtime/westend/src/weights/runtime_common_slots.rs
  xcm/xcm-builder/src/barriers.rs
  xcm/xcm-builder/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#2945 Companion for Substrate#8663
  Cargo.lock
  runtime/common/src/impls.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#2966 Companion PR for #8414 - Remove OffencesWeightSoftLimit
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low 📌, D3-trivial 🧸

#2648 Companion for Multi-phase elections solution resubmission
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#2845 Companion for Substrate#8526
  Cargo.lock
  Cargo.toml
  erasure-coding/Cargo.toml
  node/core/parachains-inherent/Cargo.toml
  node/core/parachains-inherent/src/lib.rs
  node/core/proposer/Cargo.toml
  node/core/proposer/src/lib.rs
  node/overseer/src/lib.rs
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  node/service/src/client.rs
  node/service/src/lib.rs
  roadmap/implementers-guide/src/node/subsystems-and-jobs.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  runtime/parachains/Cargo.toml
  runtime/parachains/src/paras_inherent.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low 📌

#2967 runtime: remove BabePalletPrefix impls for old migration
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2963 More secure `Signed` implementation
  Cargo.lock
  node/core/backing/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/parachains-inherent/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/pov_requester/mod.rs
  node/network/availability-distribution/src/requester/mod.rs
  node/network/bitfield-distribution/Cargo.toml
  node/network/bitfield-distribution/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/error.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/protocol/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/primitives/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/runtime/mod.rs
  node/subsystem/src/messages.rs
  primitives/src/v0.rs
  primitives/src/v1/mod.rs
  primitives/src/v1/signed.rs
  roadmap/implementers-guide/src/types/overseer-protocol.md
  runtime/parachains/src/inclusion.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#2971 Fix flaky test
  node/network/bridge/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2972 runtime: remove beefy and mmr from westend (again)
  Cargo.lock
  node/service/res/westend.json
  node/service/src/chain_spec.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2968 runtime: remove random_seed from BlockBuilder API
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low 📌, D3-trivial 🧸

#2974 Change Statemint ID (not system para)
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2975 kusama, westend: use proper parachain session keys
  runtime/kusama/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2970 Enable Pallet XCM for Kusama & Westend
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2980 Always connect in collator protocol.
  node/network/collator-protocol/src/collator_side.rs
  scripts/gitlab/check_extrinsics_ordering.sh
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2986 Guide updates for changed statement distribution
  roadmap/implementers-guide/src/node/backing/statement-distribution.md
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2989 Some overdue cleanup
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/requester/mod.rs
  node/network/availability-distribution/src/requester/session_cache.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2958 Companion PR for #8682
  Cargo.lock
  node/network/bridge/src/lib.rs
  node/network/protocol/src/peer_set.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low 📌

#2984 Flood protection for large statements.
  node/network/statement-distribution/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2988 Make ParaId value of public paras non-discretionary
  parachain/src/primitives.rs
  primitives/src/v1/mod.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/paras_registrar.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#2993 CI: bot allows simnet failure
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#2995 Dispatchable for teleporting assets
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/src/v0/mod.rs
  xcm/src/v0/traits.rs
  xcm/xcm-builder/src/weight.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/weight.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#3001 Bump version to v0.9.1 and spec_version to v9010
  .github/workflows/publish-draft-release.yml
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/service/Cargo.toml
  node/test/client/Cargo.toml
  node/test/service/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/slot_range_helper/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  scripts/github/generate_release_text.rb
  statement-table/Cargo.toml
  xcm/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2587 Initial integration of Gilts pallet (Kusama)
  Cargo.lock
  node/service/src/chain_spec.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/kusama/src/tests.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_gilt.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D5-nicetohaveaudit ⚠️

#3008 Extrinsic for reserving a parachain ID
  runtime/common/src/integration_tests.rs
  runtime/common/src/paras_registrar.rs
  runtime/kusama/src/weights/runtime_common_paras_registrar.rs
  runtime/westend/src/weights/runtime_common_paras_registrar.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#3007 Check out/in assets when teleporting to maintain total issuance
  runtime/kusama/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/src/v0/traits.rs
  xcm/xcm-builder/src/currency_adapter.rs
  xcm/xcm-builder/src/fungibles_adapter.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/transact_asset.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#3014 Enable Para Registration on Kusama
  runtime/kusama/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#3013 Use BeefyParams
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3010 Introduce reserve-asset transfer extrinsic
  runtime/kusama/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/pallet-xcm/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#3003 Support opening HRMP channels in genesis
  node/service/src/chain_spec.rs
  runtime/parachains/src/hrmp.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3009 validator_discovery: simplification
  node/network/availability-distribution/src/pov_requester/mod.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/gossip-support/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/validator_discovery.rs
  node/subsystem/src/messages.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3005 Narrow the set of available host functions for PVF
  Cargo.lock
  node/core/pvf/src/executor_intf.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3021 bump spec versions in kusama, polkadot and westend again II
  .gitlab-ci.yml
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#2983 Add Bridge Header Sync to Rococo Runtime
  Cargo.lock
  Cargo.toml
  node/service/src/chain_spec.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#3018 Check Parachain is Fully Registered Before Starting a Crowdloan
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D9-needsaudit 👮

#3023 Update Substrate in Polkadot
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3025 Grab stream of networking events earlier
  node/network/bridge/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3027 Fix ArtifactId::path
  node/core/pvf/src/artifacts.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3039 [CI][WIP] Fix check_labels
  .github/workflows/check-labels.yml
  scripts/github/check_labels.sh
Labels: A3-inprogress, B0-silent, C1-low 📌

#3043 CI: remove unnecessary jobs while simnet is under work
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3041 reword error: channel is _terminated and_ empty
  node/overseer/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3031 Update auctions pallet to FRAME v2
  runtime/common/src/auctions.rs
  runtime/common/src/integration_tests.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3042 Statemint can teleport into Kusama
  runtime/kusama/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3050 Remove host configuration set migration from Kusama & Westend
  runtime/kusama/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3045 Register ReadRuntimeVersionExt
  node/core/pvf/src/executor_intf.rs
Labels: A0-pleasereview, B1-releasenotes, C7-high ❗️, D3-trivial 🧸

#3055 Actually connect to new validators at session boundary.
  node/network/gossip-support/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3052 validator_discovery: less flexible, but simpler design
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/pov_requester/mod.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/gossip-support/src/lib.rs
  node/subsystem/src/messages.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3036 Update crowdloan pallet to FRAME v2
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3058 Reserves for bids during ending period persist until auction done
  runtime/common/src/auctions.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#3059 validator-discovery: basic retrying logic
  Cargo.lock
  node/network/bridge/src/lib.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/gossip-support/Cargo.toml
  node/network/gossip-support/src/lib.rs
  node/network/gossip-support/src/tests.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3062 Bump substrate prior to v0.9.2
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3066 Add `AuxStore` as super trait of `AbstractClient`
  node/service/src/client.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3017 Add `OnSwap` hook for Crowdloans.
  runtime/kusama/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3057 Put WIP artifacts next to ready ones
  node/core/pvf/src/host.rs
  node/core/pvf/src/prepare/pool.rs
  node/core/pvf/src/prepare/worker.rs
  node/core/pvf/src/worker_common.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#3035 Add `parachain_desired_peer_count` metric
  node/network/bridge/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3070 State can be finished due to `Share` message.
  node/network/statement-distribution/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3067 chore: cargo spellcheck
  README.md
  bridges/primitives/chain-kusama/src/lib.rs
  bridges/primitives/chain-polkadot/src/lib.rs
  bridges/primitives/chain-rococo/src/lib.rs
  bridges/primitives/chain-westend/src/lib.rs
  bridges/primitives/runtime/src/lib.rs
  node/core/pvf/src/artifacts.rs
  node/core/pvf/src/host.rs
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/requester/mod.rs
  node/network/availability-distribution/src/tests/state.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/network.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/protocol/src/lib.rs
  node/network/protocol/src/peer_set.rs
  node/network/protocol/src/request_response/request.rs
  node/network/statement-distribution/src/error.rs
  node/network/statement-distribution/src/requester.rs
  node/network/statement-distribution/src/responder.rs
  node/primitives/src/lib.rs
  node/service/src/chain_spec.rs
  node/subsystem-util/src/error_handling.rs
  node/subsystem-util/src/runtime/mod.rs
  node/subsystem/src/lib.rs
  node/subsystem/src/messages/network_bridge_event.rs
  node/test/service/src/chain_spec.rs
  node/test/service/src/lib.rs
  primitives/src/v0.rs
  primitives/src/v1/mod.rs
  runtime/common/src/auctions.rs
  runtime/common/src/claims.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3068 network-bridge: downgrade log level of benefit rep change
  node/network/bridge/src/lib.rs
  node/network/protocol/src/reputation.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3073 Some more debug logging
  node/core/backing/src/lib.rs
  node/core/candidate-validation/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3077 bump rocksdb to 6.17.3 (again)
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3080 Add Proxy Calls to Westend and Kusama
  runtime/kusama/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#3082 add the correct indirection to reward points for backing
  runtime/parachains/src/reward_points.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#3084 clear PVF cache artifacts on startup
  node/core/pvf/src/artifacts.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3085 Bump version & substrate for release v0.9.3
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/service/Cargo.toml
  node/test/client/Cargo.toml
  node/test/service/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/slot_range_helper/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  statement-table/Cargo.toml
  xcm/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3076 Remove memory limits
  scripts/packaging/polkadot.service
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3102 validator_discovery: small tweak in retrying logic
  node/network/gossip-support/src/lib.rs
  node/network/gossip-support/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3096 Companion for `substrate/pull/8889`
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#3099 Companion for `substrate/pull/8903`
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C7-high ❗️, D5-nicetohaveaudit ⚠️

#3106 Add `UsageProvider` trait to `AbstractClient`
  node/service/src/client.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3111 dependabot: ignore beefy git updates
  .github/dependabot.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3019 grandpa: enable observer for light client
  Cargo.lock
  node/service/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low 📌, D3-trivial 🧸

#2994 Companion for substrate#8724
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#3119 Dependabot: Fix labels and ignore `try-runtime-*`
  .github/dependabot.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3022 primitives: export the current slot number storage key
  Cargo.lock
  primitives/Cargo.toml
  primitives/src/v1/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3051 WIP: CI: simnet to run pinned versions
  .gitlab-ci.yml
  scripts/gitlab/trigger_pipeline.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2990 Companion PR for #8748
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌

#3069 Allow bridge relayers to be built from repo
  Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3129 enable Config for Paras on Kusama & Westend
  node/service/src/chain_spec.rs
  runtime/kusama/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3130 Use proper host configuration everywhere
  node/service/src/chain_spec.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3118 Companion for #8793 (Simple MaxEncodedLen)
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#3134 set session-info availability cores based on scheduler
  runtime/parachains/src/session_info.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3135 Be more smart when loading the chain spec
  cli/src/command.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3138 XCM docstring typo fix
  xcm/pallet-xcm/src/lib.rs
  xcm/src/v0/mod.rs
  xcm/src/v0/multi_location.rs
  xcm/src/v0/traits.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3136 Update simnet tests to v4
  scripts/gitlab/trigger_pipeline.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3133 fix approval-checking GRANDPA voting rule
  node/service/src/grandpa_support.rs
Labels: A0-pleasereview, B1-releasenotes, C3-medium 📣, D5-nicetohaveaudit ⚠️

#3104 Reversion Safety tools for overseer and subsystems
  Cargo.lock
  node/core/av-store/src/tests.rs
  node/core/backing/src/lib.rs
  node/network/availability-distribution/src/tests/state.rs
  node/network/availability-recovery/src/tests.rs
  node/network/bridge/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/gossip-support/src/tests.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/Cargo.toml
  node/overseer/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/src/lib.rs
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/node/availability/bitfield-signing.md
  roadmap/implementers-guide/src/node/backing/candidate-backing.md
  roadmap/implementers-guide/src/node/overseer.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3142 Add Westmint as a Trusted Teleport to Westend
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸
