Repository paritytech/polkadot, pull requests merged in 2021-06, with the labels that each got.

#3144 Increase PoV timeout slightly.
  node/network/protocol/src/request_response/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3114 Companion for PR 8913
  Cargo.lock
  node/core/pvf/Cargo.toml
  node/core/pvf/src/artifacts.rs
  node/core/pvf/src/execute/worker.rs
  node/core/pvf/src/executor_intf.rs
  node/core/pvf/src/testing.rs
Labels: A3-inprogress, B0-silent, C1-low 📌, D3-trivial 🧸

#3147 Make script usable from both pipeline and localhost
  .gitlab-ci.yml
  scripts/gitlab/trigger_pipeline.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3154 use the Barrier type in Westend XcmConfig
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3063 Update registrar pallet to FRAME v2
  runtime/common/src/paras_registrar.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3074 Update para sudo wrapper pallet to FRAME v2
  runtime/common/src/paras_sudo_wrapper.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3153 Bump Substrate
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3075 Update purchase pallet to FRAME v2
  runtime/common/src/purchase.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2948 XCM docs and tests
  parachain/src/primitives.rs
  xcm/src/double_encoded.rs
  xcm/src/v0/multi_asset.rs
  xcm/src/v0/multi_location.rs
  xcm/src/v0/traits.rs
  xcm/xcm-builder/src/barriers.rs
  xcm/xcm-builder/src/currency_adapter.rs
  xcm/xcm-builder/src/filter_asset_location.rs
  xcm/xcm-builder/src/fungibles_adapter.rs
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/location_conversion.rs
  xcm/xcm-builder/src/matches_fungible.rs
  xcm/xcm-builder/src/mock.rs
  xcm/xcm-builder/src/origin_conversion.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/conversion.rs
  xcm/xcm-executor/src/traits/filter_asset_location.rs
  xcm/xcm-executor/src/traits/matches_fungibles.rs
  xcm/xcm-executor/src/traits/mod.rs
  xcm/xcm-executor/src/traits/on_response.rs
  xcm/xcm-executor/src/traits/should_execute.rs
  xcm/xcm-executor/src/traits/transact_asset.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3030 Companion PR for Substrate #8824 (Migrate pallet-democracy to pallet attribute macro)
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3167 Fix teleport accounting and add some events
  node/service/src/chain_spec.rs
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/ump.md
  roadmap/implementers-guide/src/types/runtime.md
  runtime/kusama/src/lib.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/ump.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/xcm-executor/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C7-high ❗️, D5-nicetohaveaudit ⚠️

#3157 validator-discovery: some extra logs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/network.rs
  node/network/bridge/src/validator_discovery.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3169 Bump version, substrate, beefy in prep for v0.9.4
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/service/Cargo.toml
  node/test/client/Cargo.toml
  node/test/service/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/slot_range_helper/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  statement-table/Cargo.toml
  xcm/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3171 bump spec version
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low 📌, D3-trivial 🧸

#3174 Cleanup unused errors & events in lease coordination pallets
  runtime/common/src/auctions.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/slots.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2890 Update for the new substrate client API
  Cargo.lock
  node/service/src/client.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3176 Named reserve companion
  Cargo.lock
  runtime/common/src/auctions.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/impls.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3175 put a cap on finality lag
  node/service/src/grandpa_support.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3180 better logging for approval voting failures
  node/core/approval-voting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3179 approval-distribution: send all messages on unify
  node/network/approval-distribution/src/lib.rs
  roadmap/implementers-guide/src/node/approval/approval-distribution.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3181 impose minimum limitation on explicit votes too
  node/service/src/grandpa_support.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#2956 node: fix babe worker params
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low 📌

#3187 Fix historical validation code runtime API
  runtime/parachains/src/paras.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3190 node: fix grandpa voting rule
  node/service/src/grandpa_support.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3195 bump spec_version
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3191 Companion for #9036
  Cargo.lock
  node/test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3148 Remove candidate selection
  Cargo.lock
  Cargo.toml
  node/core/backing/src/lib.rs
  node/core/candidate-selection/Cargo.toml
  node/core/candidate-selection/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/protocol/src/lib.rs
  node/overseer/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/backing/candidate-selection.md
  roadmap/implementers-guide/src/node/collators/collator-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3189 polkadot-service: Make native runtime configurable
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/command.rs
  node/client/Cargo.toml
  node/client/src/lib.rs
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  node/service/src/lib.rs
  parachain/test-parachains/adder/collator/Cargo.toml
  src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3194 Companion for #8990
  Cargo.lock
  bridges/bin/millau/node/src/chain_spec.rs
  bridges/bin/rialto/node/src/chain_spec.rs
  bridges/bin/rialto/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/rialto_poa.rs
  bridges/modules/dispatch/src/lib.rs
  bridges/modules/messages/src/lib.rs
  bridges/relays/bin-ethereum/src/instances.rs
  node/service/src/chain_spec.rs
  node/test/service/src/chain_spec.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/hrmp.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low 📌, D3-trivial 🧸

#3197 remove tracing::intrument annotations
  node/collation-generation/src/lib.rs
  node/core/av-store/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/core/chain-api/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/network/approval-distribution/src/lib.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/requester/mod.rs
  node/network/availability-distribution/src/requester/session_cache.rs
  node/network/availability-distribution/src/responder.rs
  node/network/availability-recovery/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/network.rs
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3198 update pvf heap page limit
  node/core/pvf/src/executor_intf.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#3186 Companion to #8966
  Cargo.lock
  cli/src/cli.rs
  cli/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3061 Update mmr pallet to FRAME v2
  runtime/common/src/mmr.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3203 Companion to substrate#8943: Disable color-eyre default features
  Cargo.lock
  Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3206 chore: move tests into separate files
  node/collation-generation/src/lib.rs
  node/collation-generation/src/tests.rs
  node/core/runtime-api/src/lib.rs
  node/core/runtime-api/src/tests.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/tests.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/tests.rs
  node/overseer/src/lib.rs
  node/overseer/src/tests.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3207 chore: cargo-spelling config impro
  .config/lingua.dic
  .config/spellcheck.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3208 Companion for Substrate#9082
  Cargo.lock
  node/overseer/subsystems-gen/Cargo.toml
  node/subsystem/dispatch-gen/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3184 Companion for #9018 (`transfer_all`)
  Cargo.lock
  runtime/kusama/src/weights/pallet_balances.rs
  runtime/polkadot/src/weights/pallet_balances.rs
  runtime/westend/src/weights/pallet_balances.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#3204 Substrate companion #9074
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3210 replace HistoricalValidationCode usages with ValidationCodeByHash
  node/core/approval-voting/src/lib.rs
  node/core/runtime-api/src/cache.rs
  node/core/runtime-api/src/lib.rs
  node/core/runtime-api/src/tests.rs
  node/subsystem/src/messages.rs
  parachain/src/primitives.rs
  primitives/src/v1/mod.rs
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/node/disputes/dispute-participation.md
  roadmap/implementers-guide/src/runtime-api/historical_validation_code.md
  roadmap/implementers-guide/src/runtime-api/validation-code.md
  roadmap/implementers-guide/src/runtime/paras.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  runtime/kusama/src/lib.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3215 Bump Substrate
  Cargo.lock
  runtime/parachains/src/reward_points.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3220 tabify tests
  node/collation-generation/src/lib.rs
  node/collation-generation/src/tests.rs
  node/core/provisioner/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/network/approval-distribution/src/lib.rs
  node/network/availability-recovery/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/tests.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests.rs
  node/network/gossip-support/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/tests.rs
  node/overseer/src/lib.rs
  node/overseer/src/tests.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3221 collator-protocol/validator_side: small refactoring
  node/network/collator-protocol/src/validator_side/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3219 fix connections leak
  node/network/bridge/src/network.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3032 Update claims pallet to FRAME v2
  runtime/common/src/claims.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3212 create newtype for ValidationCodeHash
  node/core/pvf/src/artifacts.rs
  node/core/pvf/src/pvf.rs
  node/core/runtime-api/src/tests.rs
  parachain/src/primitives.rs
  primitives/src/v1/mod.rs
  roadmap/implementers-guide/src/runtime-api/validation-code.md
  roadmap/implementers-guide/src/runtime/paras.md
  roadmap/implementers-guide/src/types/candidate.md
  runtime/kusama/src/lib.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3214 Companion for #9085 (pub calls)
  Cargo.lock
  runtime/common/src/claims.rs
  runtime/common/src/mmr.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots.rs
  xcm/pallet-xcm/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3150 Dispute Coordinator Subsystem
  Cargo.lock
  Cargo.toml
  core-primitives/src/lib.rs
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  node/core/dispute-coordinator/Cargo.toml
  node/core/dispute-coordinator/src/db/mod.rs
  node/core/dispute-coordinator/src/db/v1.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/tests.rs
  node/network/bridge/src/tests.rs
  node/overseer/src/lib.rs
  node/primitives/Cargo.toml
  node/primitives/src/approval.rs
  node/primitives/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/rolling_session_window.rs
  node/subsystem/src/messages.rs
  primitives/src/v0.rs
  primitives/src/v1/mod.rs
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3228 add metric for timing recovery and approval
  node/core/approval-voting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3229 use fresh_start in rolling window error
  node/subsystem-util/src/rolling_session_window.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3233 approval votes checking logs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  node/network/approval-distribution/src/lib.rs
  node/network/approval-distribution/src/tests.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3200 Companion for #9061
  Cargo.lock
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/lib.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A7-companion, B0-silent, C1-low 📌, D3-trivial 🧸

#3201 companion for staking/election: prolonged era and emergency mode for governance submission.
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B7-runtimenoteworthy, C7-high ❗️, D5-nicetohaveaudit ⚠️

#3245 use correct unbounded meter for statement distribution
  node/overseer/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3247 Better metrics for approval voting
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/persisted_entries.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3240 Fix test environment
  runtime/common/src/impls.rs
Labels: A0-pleasereview, A2-insubstantial, A7-companion, B0-silent, C1-low 📌, D3-trivial 🧸

#3088 Update `FallbackStrategy` to `Nothing`
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A1-onice, B7-runtimenoteworthy, C7-high ❗️, D1-audited 👍

#3234 implement dispute participation subsystem
  Cargo.lock
  Cargo.toml
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/tests.rs
  node/core/dispute-participation/Cargo.toml
  node/core/dispute-participation/src/lib.rs
  node/core/dispute-participation/src/tests.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/disputes/dispute-participation.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3238 Bump version, spec_version & substrate in prep for release v0.9.5
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/service/Cargo.toml
  node/test/client/Cargo.toml
  node/test/service/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/slot_range_helper/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  statement-table/Cargo.toml
  xcm/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3251 Drop guard for detecting stale approvals
  node/core/approval-voting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3216 Companion for #8949
  Cargo.lock
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/lib.rs
  runtime/common/src/claims.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low 📌, D3-trivial 🧸

#3260 Companion for #8920 (Control Staking)
  Cargo.lock
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/westend/src/weights/pallet_staking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3249 Use Safe Math in XCM Builder
  xcm/xcm-builder/src/weight.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium 📣, D1-audited 👍

#3224 malus - mockable overseer mvp
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/command.rs
  cli/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/malus/Cargo.toml
  node/malus/src/lib.rs
  node/malus/src/variant-a.rs
  node/service/Cargo.toml
  node/service/src/grandpa_support.rs
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/service/src/parachains_db/mod.rs
  node/test/service/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌

#3266 bridges: update finality-grandpa to 0.14.1
  Cargo.lock
  bridges/modules/ethereum-contract-builtin/Cargo.toml
  bridges/modules/grandpa/Cargo.toml
  bridges/primitives/header-chain/Cargo.toml
  bridges/primitives/test-utils/Cargo.toml
  bridges/relays/bin-substrate/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3252 Approval checking unit tests
  node/core/approval-voting/src/approval_checking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3261 extract determine_new_blocks into a separate utility
  node/core/approval-voting/src/import.rs
  node/subsystem-util/src/determine_new_blocks.rs
  node/subsystem-util/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3272 Fix `pallet-xcm` Origin
  runtime/kusama/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/pallet-xcm/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3237 Allow Council to Use Scheduler
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#3273 Add XCM Decode Limit
  xcm/src/double_encoded.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#3278 Export 'TakeRevenue' trait.
  xcm/xcm-builder/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3283 CLI: Add missing feature checking and check if someone passes a file
  cli/src/command.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3262 Implementers' Guide: Chain Selection
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/node/backing/candidate-backing.md
  roadmap/implementers-guide/src/node/grandpa-voting-rule.md
  roadmap/implementers-guide/src/node/utility/chain-selection.md
  roadmap/implementers-guide/src/protocol-chain-selection.md
  roadmap/implementers-guide/src/protocol-disputes.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3276 Companion #9019 (max rpc payload override)
  Cargo.lock
  node/test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3288 cleanup more tests and spaces
  node/core/backing/src/lib.rs
  node/core/backing/src/tests.rs
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/tests.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bitfield-distribution/src/tests.rs
  node/network/bridge/src/tests.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  parachain/src/primitives.rs
  runtime/parachains/src/scheduler.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3264 Extract and test count_no_shows method for approval voting
  node/core/approval-voting/src/approval_checking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3291 Add bridge team as codeowners of `bridges` Subtree
  .github/CODEOWNERS
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌

#3275 add revert consensus log
  primitives/src/v1/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3299 Set new staking limits
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C7-high ❗️, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#3270 improved gossip topology
  Cargo.lock
  node/network/approval-distribution/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bitfield-distribution/src/tests.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/network.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/gossip-support/Cargo.toml
  node/network/gossip-support/src/lib.rs
  node/network/gossip-support/src/tests.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/tests.rs
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/lib.rs
  node/subsystem/src/messages.rs
  node/subsystem/src/messages/network_bridge_event.rs
  roadmap/implementers-guide/src/node/utility/gossip-support.md
  roadmap/implementers-guide/src/node/utility/network-bridge.md
  roadmap/implementers-guide/src/types/network.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌

#3309 Follow-up PR: Count no-shows
  node/core/approval-voting/src/approval_checking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3302 Bump BEEFY
  Cargo.lock
  node/client/src/lib.rs
  node/service/src/chain_spec.rs
  node/service/src/lib.rs
  rpc/src/lib.rs
  runtime/common/src/lib.rs
  runtime/common/src/mmr.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3301 Block weight ChainAPI
  Cargo.lock
  node/core/chain-api/Cargo.toml
  node/core/chain-api/src/lib.rs
  node/primitives/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/utility/chain-api.md
  roadmap/implementers-guide/src/node/utility/chain-selection.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3308 network-bridge: remove action_sink abstraction
  node/network/bridge/src/lib.rs
  node/network/bridge/src/network.rs
  node/network/bridge/src/tests.rs
  node/network/bridge/src/validator_discovery.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3294 Companion for substrate#9138
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3313 Improvements to `determine_new_blocks`
  node/subsystem-util/src/determine_new_blocks.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3268 Companion for substrate#9128
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3319 downgrade a warn log to debug
  node/core/approval-voting/src/import.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3321 disable approval-checking voting rule on polkadot
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3334 Export `fungibles_adapter` Types
  xcm/xcm-builder/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3329 Use `max_code_size` and `max_wasm_data_size` from Parachains Configuration
  node/network/protocol/src/request_response/mod.rs
  node/primitives/src/lib.rs
  node/service/src/chain_spec.rs
  node/test/service/src/chain_spec.rs
  primitives/src/v1/mod.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/paras_registrar.rs
  runtime/kusama/src/constants.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/runtime_common_paras_registrar.rs
  runtime/parachains/src/configuration.rs
  runtime/rococo/src/constants.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/runtime_common_paras_registrar.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#3277 Chain Selection Subsystem Logic
  Cargo.lock
  Cargo.toml
  node/core/chain-selection/Cargo.toml
  node/core/chain-selection/src/backend.rs
  node/core/chain-selection/src/lib.rs
  node/core/chain-selection/src/tests.rs
  node/core/chain-selection/src/tree.rs
  node/network/bridge/src/tests.rs
  node/overseer/src/lib.rs
  node/subsystem-util/src/determine_new_blocks.rs
  node/subsystem/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3339 Remove the streamunordered crate
  Cargo.lock
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3333 Only fetch one collation at a time per relay parent
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests.rs
  node/network/protocol/src/request_response/mod.rs
  node/network/protocol/src/request_response/request.rs
Labels: A0-pleasereview, B1-releasenotes, C3-medium 📣

#3337 make `ctx.spawn` blocking
  node/collation-generation/src/lib.rs
  node/core/approval-voting/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/malus/src/lib.rs
  node/metered-channel/src/lib.rs
  node/metered-channel/src/unbounded.rs
  node/network/availability-distribution/src/pov_requester/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-recovery/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3078 Fast sync companion PR
  Cargo.lock
  node/core/chain-api/src/lib.rs
  roadmap/implementers-guide/src/further-reading.md
  roadmap/implementers-guide/src/glossary.md
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3158 Dispute distribution guide
  node/network/protocol/src/lib.rs
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
  roadmap/implementers-guide/src/node/disputes/dispute-distribution.md
  roadmap/implementers-guide/src/protocol-disputes.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3306 Approval Checking: Avoid redundant checks
  Cargo.lock
  node/core/approval-voting/Cargo.toml
  node/core/approval-voting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3347 runtime: remove randomness collective flip pallet
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/slots.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3341 SelectChain implementation for relay chains
  Cargo.lock
  node/overseer/src/lib.rs
  node/service/Cargo.toml
  node/service/src/grandpa_support.rs
  node/service/src/lib.rs
  node/service/src/relay_chain_selection.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3205 doc: describe outline for system tests
  doc/testing.md
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3356 av-store: use determine_new_blocks
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  roadmap/implementers-guide/src/node/utility/availability-store.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3346 Do not allow any crowdloan contributions during the VRF period
  runtime/common/src/auctions.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/traits.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#3267 Companion for upgrade of transaction-payment to pallet macro
  Cargo.lock
  runtime/kusama/src/tests.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low 📌, D3-trivial 🧸

#3361 Don't allow bids for a ParaId where there is an overlapping lease period
  runtime/common/src/auctions.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/slots.rs
  runtime/common/src/traits.rs
  runtime/kusama/src/weights/runtime_common_auctions.rs
  runtime/kusama/src/weights/runtime_common_crowdloan.rs
  runtime/kusama/src/weights/runtime_common_slots.rs
  runtime/westend/src/weights/runtime_common_auctions.rs
  runtime/westend/src/weights/runtime_common_crowdloan.rs
  runtime/westend/src/weights/runtime_common_slots.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium 📣, D5-nicetohaveaudit ⚠️

#3368 Bump versions & spec_versions
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/service/Cargo.toml
  node/test/client/Cargo.toml
  node/test/service/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/slot_range_helper/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  statement-table/Cargo.toml
  xcm/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3375 Use associated constant for max
  bridges/bin/rialto/runtime/src/exchange.rs
  bridges/bin/rialto/runtime/src/kovan.rs
  bridges/bin/rialto/runtime/src/rialto_poa.rs
  bridges/modules/ethereum/src/finality.rs
  bridges/modules/ethereum/src/mock.rs
  bridges/modules/ethereum/src/validators.rs
  bridges/modules/ethereum/src/verification.rs
  node/core/backing/src/lib.rs
  node/network/protocol/src/reputation.rs
  primitives/src/v1/mod.rs
  roadmap/implementers-guide/src/node/backing/pov-distribution.md
  runtime/common/src/claims.rs
  runtime/common/src/purchase.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3364 disable approval-checking-grandpa on dev chain
  node/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3360 Only send one collation per relay parent at a time to validators
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  roadmap/implementers-guide/src/node/collators/collator-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3362 Ensure that we fetch another collation if the first collation was invalid
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#2793 Companion for Decouple Staking and Election - Part 3: Signed Phase
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/elections.rs
  runtime/common/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_election_provider_multi_phase.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_election_provider_multi_phase.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/pallet_election_provider_multi_phase.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D9-needsaudit 👮

#3376 Companion for #9193
  Cargo.lock
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/westend/src/weights/pallet_staking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3372 Bump BEEFY: adjust gossip
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3381 add simnet tests
  simnet_tests/README.md
  simnet_tests/configs/adder.json
  simnet_tests/configs/simple_rococo_testnet.toml
  simnet_tests/run_tests.sh
  simnet_tests/tests/parachains.feature
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3386 Minor refactor
  node/core/runtime-api/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸
