Repository paritytech/polkadot, pull requests merged in 2021-09, with the labels that each got.

#3511 technical committee is using the weight of council, but should have its own generated weight instead
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_collective.rs
  runtime/kusama/src/weights/pallet_collective_council.rs
  runtime/kusama/src/weights/pallet_collective_technical_committee.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_collective.rs
  runtime/polkadot/src/weights/pallet_collective_council.rs
  runtime/polkadot/src/weights/pallet_collective_technical_committee.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3750 disputes: fix relay chain selection sanity check
  node/core/approval-voting/src/lib.rs
  node/service/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3762 chore: test helper arbitrary ordering for 2
  node/subsystem-test-helpers/src/lib.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#3753 Fixes/improvements for disputes
  node/core/dispute-coordinator/src/dummy.rs
  node/core/dispute-coordinator/src/real/mod.rs
  node/core/dispute-coordinator/src/real/tests.rs
  node/network/availability-recovery/src/lib.rs
  node/service/src/relay_chain_selection.rs
  node/service/src/tests.rs
  node/subsystem-types/src/messages.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3487 Companion for substrate #9371
  Cargo.lock
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D5-nicetohaveaudit ⚠️

#3759 dependabot: ignore yet another git dep
  .github/dependabot.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3736 XCM: Automatic Version Negotiation
  roadmap/implementers-guide/src/types/overseer-protocol.md
  runtime/kusama/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/test-runtime/src/xcm_config.rs
  runtime/westend/src/lib.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/pallet-xcm/src/tests.rs
  xcm/src/lib.rs
  xcm/src/v0/mod.rs
  xcm/src/v1/mod.rs
  xcm/src/v1/multilocation.rs
  xcm/src/v2/mod.rs
  xcm/src/v2/traits.rs
  xcm/xcm-builder/src/barriers.rs
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/mock.rs
  xcm/xcm-builder/src/tests.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-executor/src/config.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/mod.rs
  xcm/xcm-executor/src/traits/on_response.rs
  xcm/xcm-executor/src/traits/should_execute.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#3764 Enable disputes on rococo
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3734 Add VoteLocking config
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3775 feat/overseer: introduce closure init
  node/core/candidate-validation/src/lib.rs
  node/malus/src/variant-a.rs
  node/overseer/all-subsystems-gen/src/lib.rs
  node/overseer/all-subsystems-gen/tests/ui/err-01-generic-used-twice.rs
  node/overseer/all-subsystems-gen/tests/ui/err-01-generic-used-twice.stderr
  node/overseer/all-subsystems-gen/tests/ui/err-01-no-generic.rs
  node/overseer/all-subsystems-gen/tests/ui/err-01-no-generic.stderr
  node/overseer/all-subsystems-gen/tests/ui/err-01-no-generics.stderr
  node/overseer/all-subsystems-gen/tests/ui/ok-01-w-generics.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/overseer-gen/proc-macro/src/impl_builder.rs
  node/overseer/src/lib.rs
  node/overseer/src/tests.rs
  node/subsystem-test-helpers/src/lib.rs
Labels: A3-inprogress, B0-silent, C1-low 📌

#3785 Convert rococo chainspec to raw chainspec
  node/service/res/rococo.json
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3788 set `DisputesHandler` in initializer on Rococo
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#3789 bump substrate and beefy
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3715 Add tests and modify as_vec implementation
  Cargo.lock
  erasure-coding/src/lib.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-recovery/src/lib.rs
  node/primitives/Cargo.toml
  node/primitives/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3795 Make parts of the xcm-executor public
  xcm/xcm-executor/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3781 allow config NextFreeParaId in genesis
  node/service/src/chain_spec.rs
  runtime/common/src/paras_registrar.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3682 staking-miner: docker images
  cli/Cargo.toml
  docker/README.md
  scripts/docker/staking-miner/staking_miner-builder.Dockerfile
  scripts/docker/staking-miner/staking_miner-injected.Dockerfile
  scripts/gitlab/lingua.dic
  utils/staking-miner/README.md
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#3731 Remove migration done by runtime version 9090
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3805 Fix buildah issue 3500
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3808 Ensure that `para_head` hash matches the actual head
  parachain/src/primitives.rs
  runtime/parachains/src/inclusion.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3263 Companion for substrate#9080
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#3802 Introduce XCM Weight Traits
  Cargo.lock
  xcm/src/lib.rs
  xcm/src/v2/mod.rs
  xcm/src/v2/traits.rs
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-builder/src/currency_adapter.rs
  xcm/xcm-builder/src/weight.rs
  xcm/xcm-executor/src/lib.rs
Labels: B0-silent, C1-low 📌, D2-notlive 💤

#3707 Update Slot Range Expect Proof
  runtime/common/src/auctions.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3796 participate in disputes only if haven't voted already
  node/core/dispute-coordinator/src/real/mod.rs
  node/core/dispute-coordinator/src/real/tests.rs
Labels: B0-silent, C1-low 📌

#3812 Fix flaky availability-recovery test
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3784 Don't drop UMP queue items if weight exhausted
  runtime/parachains/src/mock.rs
  runtime/parachains/src/ump.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C7-high ❗️, D5-nicetohaveaudit ⚠️

#3722 Change pipeline to use Vault
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3816 Add vault secrets to publish-rustdoc job
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3819 Add words to the dictionnary
  bridges/.config/lingua.dic
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3543 Do not expire HRMP open channel requests
  node/service/src/chain_spec.rs
  parachain/src/primitives.rs
  roadmap/implementers-guide/src/runtime/hrmp.md
  roadmap/implementers-guide/src/types/runtime.md
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/hrmp.rs
  scripts/gitlab/lingua.dic
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌

#3752 Allow staking miner to use different election algorithms
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/elections.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
  utils/staking-miner/Cargo.toml
  utils/staking-miner/src/dry_run.rs
  utils/staking-miner/src/emergency_solution.rs
  utils/staking-miner/src/main.rs
  utils/staking-miner/src/monitor.rs
  utils/staking-miner/src/rpc_helpers.rs
  utils/staking-miner/src/signer.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#3823 Add Canvas to trusted chains in Rococo
  runtime/rococo/src/lib.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#3827 Add logging for worker spawn failures
  node/core/pvf/src/worker_common.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3830 Substrate Companion #9737
  Cargo.lock
  cli/src/command.rs
  node/test/polkadot-simnet/common/src/lib.rs
  node/test/service/Cargo.toml
  node/test/service/src/lib.rs
  node/test/service/tests/build-blocks.rs
  node/test/service/tests/call-function.rs
  parachain/test-parachains/adder/collator/tests/integration.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3757 Companion for #9648
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/elections.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3820 make polkadot-runtime optional feature
  .gitlab-ci.yml
  cli/Cargo.toml
  cli/src/command.rs
  cli/src/lib.rs
  node/client/Cargo.toml
  node/client/src/lib.rs
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  node/service/src/lib.rs
  scripts/gitlab/check_no_default_features.sh
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#3828 dockerfiles: upgrade to ubuntu:20.04; some chore
  bridges/Dockerfile
  bridges/ci.Dockerfile
  bridges/deployments/BridgeDeps.Dockerfile
  bridges/deployments/bridges/poa-rialto/Front-end.Dockerfile
  bridges/deployments/monitoring/GrafanaMatrix.Dockerfile
  bridges/deployments/networks/OpenEthereum.Dockerfile
  docker/Dockerfile
  scripts/docker/Dockerfile
  scripts/docker/collator.Dockerfile
  scripts/docker/release.Dockerfile
  scripts/docker/staking-miner/staking_miner-builder.Dockerfile
  scripts/docker/staking-miner/staking_miner-injected.Dockerfile
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#3838 Fix Complaints in CI
  runtime/common/src/elections.rs
  runtime/kusama/src/weights/pallet_collective_council.rs
  runtime/kusama/src/weights/pallet_collective_technical_committee.rs
  runtime/polkadot/src/weights/pallet_collective_council.rs
  runtime/polkadot/src/weights/pallet_collective_technical_committee.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3813 Put all authorities of a session into `SessionInfo`.
  node/network/gossip-support/src/lib.rs
  node/subsystem-util/src/runtime/mod.rs
  primitives/src/v1/mod.rs
  roadmap/implementers-guide/src/runtime/session_info.md
  runtime/parachains/src/session_info.rs
  runtime/parachains/src/util.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#3265 Companion for substrate#9115
  Cargo.lock
  node/test/polkadot-simnet/common/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#3575 UMP: Support Overweight messages
  node/service/src/chain_spec.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/migration.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/ump.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  scripts/gitlab/lingua.dic
  xcm/xcm-simulator/example/src/relay_chain.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#3846 improve approval tracing
  node/core/approval-voting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3843 Add build with docker info to README
  README.md
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3848 approval-voting: processed wakeups can also update approval state
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3860 add type info derive to senderror
  xcm/src/v2/traits.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3842 add dispute metrics, some chores
  Cargo.lock
  node/core/dispute-coordinator/src/dummy.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/metrics.rs
  node/core/dispute-coordinator/src/real/mod.rs
  node/core/dispute-coordinator/src/real/tests.rs
  node/malus/Cargo.toml
  node/malus/src/lib.rs
  node/malus/src/tests.rs
  node/malus/src/variant-a.rs
  node/overseer/src/lib.rs
  node/service/src/overseer.rs
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3855 Don't try to connect to ourselves.
  node/network/gossip-support/src/lib.rs
  node/network/gossip-support/src/tests.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#3844 Raised nits on #3813
  runtime/parachains/src/util.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3840 Companion for #9764 (Force Unreserve)
  Cargo.lock
  runtime/kusama/src/weights/pallet_balances.rs
  runtime/polkadot/src/weights/pallet_balances.rs
  runtime/westend/src/weights/pallet_balances.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3871 update Rococo.json
  node/service/res/rococo.json
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3870 Add info logging to dispute activation
  node/core/dispute-coordinator/src/real/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3413 Companion for Store voters in unsorted bags to get good stake iteration properties
  Cargo.lock
  Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/src/elections.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/kusama/src/voter_bags.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_bags_list.rs
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  runtime/westend/src/voter_bags.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/pallet_bags_list.rs
  runtime/westend/src/weights/pallet_staking.rs
  utils/remote-ext-tests/bags-list/Cargo.toml
  utils/remote-ext-tests/bags-list/README.md
  utils/remote-ext-tests/bags-list/src/main.rs
  utils/remote-ext-tests/bags-list/src/voter_bags.rs
  utils/voter-bags/Cargo.toml
  utils/voter-bags/src/main.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#3853 Dispute distribution improvements
  node/network/dispute-distribution/src/metrics.rs
  node/network/dispute-distribution/src/sender/mod.rs
  node/network/dispute-distribution/src/sender/send_task.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#3868 remove connected disconnected state only
  Cargo.lock
  doc/testing.md
  node/malus/src/variant-a.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/overseer-gen/proc-macro/src/impl_builder.rs
  node/overseer/src/dummy.rs
  node/overseer/src/lib.rs
  node/overseer/src/metrics.rs
  node/overseer/src/subsystems.rs
  node/overseer/src/tests.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/service/src/relay_chain_selection.rs
  node/service/src/tests.rs
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3887 Run fmt
  node/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3862 Add benchmarking for parachain runtime configuration pallet
  runtime/common/src/integration_tests.rs
  runtime/common/src/paras_registrar.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/runtime_parachains_configuration.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/benchmarking.rs
  runtime/parachains/src/configuration/weights.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/runtime_parachains_configuration.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3885 ci: cache seed in fuzzer job
  .github/workflows/honggfuzz.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3893 Gather memory usage statistics through `parity-util-mem`
  Cargo.lock
  cli/Cargo.toml
  node/metrics/Cargo.toml
  node/metrics/src/lib.rs
  node/metrics/src/memory_stats.rs
  node/overseer/Cargo.toml
  node/overseer/src/lib.rs
  node/overseer/src/metrics.rs
  node/service/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3744 Companion for Generate storage info for pallet im_online #9654
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3896 Revert "remove connected disconnected state only"
  Cargo.lock
  doc/testing.md
  node/malus/src/variant-a.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/overseer-gen/proc-macro/src/impl_builder.rs
  node/overseer/src/dummy.rs
  node/overseer/src/lib.rs
  node/overseer/src/metrics.rs
  node/overseer/src/subsystems.rs
  node/overseer/src/tests.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/service/src/relay_chain_selection.rs
  node/service/src/tests.rs
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3897 Bump `parity-util-mem` to 0.10.2
  Cargo.lock
Labels: F7-footprint, A0-pleasereview, B0-silent, C1-low 📌

#3895 Re-enable metadata compare CI check
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3704 Substrate Companion for #9566
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#3888 Add benchmarking for parachain runtime paras pallet
  primitives/src/v1/mod.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/paras_registrar.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/runtime_parachains_paras.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/paras/benchmarking.rs
  runtime/parachains/src/paras/weights.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/runtime_parachains_paras.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3886 add tracing to assignment criteria
  node/core/approval-voting/src/criteria.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3892 Companion for Generate storage info for pallet grandpa #9817
  Cargo.lock
  bridges/bin/rialto/runtime/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#3900 Companion for substrate PR#9766
  Cargo.lock
  runtime/common/src/elections.rs
  runtime/kusama/src/weights/pallet_election_provider_multi_phase.rs
  runtime/polkadot/src/weights/pallet_election_provider_multi_phase.rs
  runtime/westend/src/weights/pallet_election_provider_multi_phase.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#3831 Companion for Generate storage info for pallet babe #9760
  Cargo.lock
  runtime/common/src/integration_tests.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#3912 Ensure all parachain configuration extrinsics are operational
  runtime/parachains/src/configuration.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3905 Add new rococo chainspec
  node/service/res/rococo.json
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3908 Benchmark Disputes `force_unfreeze` extrinsic
  Cargo.lock
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/collation-generation/Cargo.toml
  node/core/approval-voting/Cargo.toml
  node/core/av-store/Cargo.toml
  node/core/candidate-validation/Cargo.toml
  node/core/chain-api/Cargo.toml
  node/core/dispute-participation/Cargo.toml
  node/core/pvf/Cargo.toml
  node/jaeger/Cargo.toml
  node/network/availability-distribution/Cargo.toml
  node/network/availability-recovery/Cargo.toml
  node/network/bridge/Cargo.toml
  node/network/collator-protocol/Cargo.toml
  node/network/dispute-distribution/Cargo.toml
  node/network/protocol/Cargo.toml
  node/network/statement-distribution/Cargo.toml
  node/overseer/overseer-gen/proc-macro/Cargo.toml
  node/primitives/Cargo.toml
  node/subsystem-util/Cargo.toml
  node/test/client/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  primitives/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/slot_range_helper/Cargo.toml
  runtime/common/src/integration_tests.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/disputes/benchmarking.rs
  runtime/parachains/src/disputes/weights.rs
  runtime/parachains/src/mock.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
  runtime/rococo/src/weights/mod.rs
  runtime/rococo/src/weights/runtime_parachains_disputes.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  statement-table/Cargo.toml
  xcm/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3906 Add a `force_unfreeze` extrinsic to the disputes module
  Cargo.lock
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/disputes/benchmarking.rs
  runtime/parachains/src/mock.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
  runtime/rococo/src/weights/mod.rs
  runtime/rococo/src/weights/runtime_parachains_disputes.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3815 add parachains pallets to Polkadot runtime
  Cargo.lock
  node/service/src/chain_spec.rs
  runtime/common/src/crowdloan.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/constants.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/runtime_common_auctions.rs
  runtime/polkadot/src/weights/runtime_common_crowdloan.rs
  runtime/polkadot/src/weights/runtime_common_paras_registrar.rs
  runtime/polkadot/src/weights/runtime_common_slots.rs
  runtime/polkadot/src/weights/runtime_parachains_configuration.rs
  runtime/polkadot/src/weights/runtime_parachains_paras.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D1-audited 👍

#3911 update BaseXcmWeight to match Kusama
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3915 Backports for 0.9.10
  Cargo.lock
  node/core/backing/src/lib.rs
Labels: A2-insubstantial, B1-releasenotes, A7-companion, C1-low 📌

#3919 Fix broken links in README
  README.md
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3807 Substrate Companion for rust 1.54
  .gitlab-ci.yml
  Cargo.lock
  node/overseer/all-subsystems-gen/tests/ui/err-01-generic-used-twice.stderr
  node/overseer/overseer-gen/tests/ui/err-01-duplicate-consumer.stderr
  node/overseer/overseer-gen/tests/ui/err-04-missing-error.stderr
  parachain/test-parachains/halt/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3923 Remove BEEFY repo dependency
  Cargo.lock
  node/client/Cargo.toml
  node/service/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3927 Update logging in paras_inherent
  runtime/parachains/src/paras_inherent.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3930 Ignore `generate-bags` by dependabot
  .github/dependabot.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3845 Fix spelling
  bridges/.config/lingua.dic
  bridges/relays/bin-substrate/src/cli/derive_account.rs
  bridges/relays/bin-substrate/src/cli/encode_message.rs
  bridges/relays/bin-substrate/src/cli/init_bridge.rs
  bridges/relays/bin-substrate/src/cli/mod.rs
  bridges/relays/bin-substrate/src/messages_lane.rs
  bridges/relays/bin-substrate/src/on_demand_headers.rs
  bridges/relays/client-substrate/src/chain.rs
  bridges/relays/client-substrate/src/client.rs
  scripts/gitlab/lingua.dic
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3934 Do not compile `wasm_api` module when not needed.
  parachain/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3818 XCM Benchmarks for Asset Transactor w/ Fungible Asset
  Cargo.lock
  Cargo.toml
  runtime/polkadot/src/weights/runtime_common_crowdloan.rs
  runtime/polkadot/src/weights/runtime_common_paras_registrar.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/xcm/mod.rs
  runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  xcm/Cargo.toml
  xcm/pallet-xcm-benchmarks/Cargo.toml
  xcm/pallet-xcm-benchmarks/src/fungible/benchmarking.rs
  xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  xcm/pallet-xcm-benchmarks/src/fungible/mod.rs
  xcm/pallet-xcm-benchmarks/src/lib.rs
  xcm/pallet-xcm-benchmarks/src/mock.rs
  xcm/pallet-xcm-benchmarks/template.hbs
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/weight.rs
  xcm/xcm-executor/Cargo.toml
  xcm/xcm-executor/src/assets.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3939 Fix bin-substrate toml
  bridges/relays/bin-substrate/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3873 Added multisig in Rococo
  Cargo.lock
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3916 Log info about low connectivity and unreachable validators
  Cargo.lock
  node/network/bridge/src/lib.rs
  node/network/bridge/src/tests.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/gossip-support/Cargo.toml
  node/network/gossip-support/src/lib.rs
  node/network/gossip-support/src/tests.rs
  node/network/protocol/src/lib.rs
  node/overseer/src/lib.rs
  node/service/src/overseer.rs
  node/subsystem-types/src/messages.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3903 disputes: reject single-sided disputes
  runtime/parachains/src/disputes.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3944 minor chore changes
  node/core/dispute-coordinator/src/real/mod.rs
  parachain/test-parachains/adder/collator/README.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3948 fix flaky chain-selection tests
  node/core/chain-selection/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3898 remove connected disconnected state, 3rd attempt
  Cargo.lock
  doc/testing.md
  node/malus/src/tests.rs
  node/malus/src/variant-a.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/overseer-gen/proc-macro/src/impl_builder.rs
  node/overseer/src/dummy.rs
  node/overseer/src/lib.rs
  node/overseer/src/metrics.rs
  node/overseer/src/subsystems.rs
  node/overseer/src/tests.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/service/src/relay_chain_selection.rs
  node/service/src/tests.rs
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, A1-needsburnin

#3880 Docker files chore
  .github/workflows/publish-docker-release.yml
  .gitlab-ci.yml
  doc/docker.md
  scripts/dockerfiles/collator_injected.Dockerfile
  scripts/dockerfiles/polkadot/README.md
  scripts/dockerfiles/polkadot/build.sh
  scripts/dockerfiles/polkadot/docker-compose-local.yml
  scripts/dockerfiles/polkadot/docker-compose.yml
  scripts/dockerfiles/polkadot/polkadot_builder.Dockerfile
  scripts/dockerfiles/polkadot_injected_debug.Dockerfile
  scripts/dockerfiles/polkadot_injected_release.Dockerfile
  scripts/dockerfiles/staking-miner/staking-miner_builder.Dockerfile
  scripts/dockerfiles/staking-miner/staking-miner_injected.Dockerfile
  scripts/gitlab/lingua.dic
  utils/staking-miner/README.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3955 Fix master
  node/service/src/overseer.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3954 approval-voting: populate session cache in advance
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/tests.rs
  node/core/dispute-coordinator/src/real/mod.rs
  node/primitives/src/lib.rs
  node/subsystem-util/src/rolling_session_window.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3962 CI: run disputes tests
  node/core/dispute-coordinator/src/real/mod.rs
  node/core/dispute-coordinator/src/real/tests.rs
  scripts/gitlab/test_linux_stable.sh
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3834 Substrate Companion for #9552
  Cargo.lock
  node/primitives/Cargo.toml
  runtime/rococo/src/validator_manager.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3938 Companion for Substrate#9867
  Cargo.lock
  node/service/src/relay_chain_selection.rs
Labels: B0-silent, A7-companion, C1-low 📌

#3874 remove `AllSubsystems` and `AllSubsystemsGen` types
  Cargo.lock
  Cargo.toml
  cli/src/lib.rs
  node/core/pvf/src/artifacts.rs
  node/malus/src/variant-a.rs
  node/network/availability-distribution/src/requester/session_cache.rs
  node/network/availability-recovery/src/futures_undead.rs
  node/network/dispute-distribution/src/error.rs
  node/network/statement-distribution/src/error.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/Cargo.toml
  node/overseer/all-subsystems-gen/Cargo.toml
  node/overseer/all-subsystems-gen/src/lib.rs
  node/overseer/all-subsystems-gen/tests/ui/err-01-enum.rs
  node/overseer/all-subsystems-gen/tests/ui/err-01-enum.stderr
  node/overseer/all-subsystems-gen/tests/ui/err-01-generic-used-twice.rs
  node/overseer/all-subsystems-gen/tests/ui/err-01-generic-used-twice.stderr
  node/overseer/all-subsystems-gen/tests/ui/err-01-no-generic.rs
  node/overseer/all-subsystems-gen/tests/ui/err-01-no-generic.stderr
  node/overseer/all-subsystems-gen/tests/ui/err-01-no-generics.stderr
  node/overseer/all-subsystems-gen/tests/ui/ok-01-w-generics.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/overseer-gen/proc-macro/Cargo.toml
  node/overseer/overseer-gen/proc-macro/src/impl_builder.rs
  node/overseer/overseer-gen/proc-macro/src/impl_channels_out.rs
  node/overseer/overseer-gen/proc-macro/src/impl_overseer.rs
  node/overseer/overseer-gen/proc-macro/src/lib.rs
  node/overseer/src/dummy.rs
  node/overseer/src/lib.rs
  node/overseer/src/subsystems.rs
  node/overseer/src/tests.rs
  node/primitives/src/lib.rs
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem-types/src/messages.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/purchase.rs
  runtime/common/src/traits.rs
  runtime/parachains/src/hrmp.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/src/v1/multilocation.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3969 paras_inherent: reject only candidates with concluded disputes
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/paras_inherent.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3972 revert +1 change to be on the safer side
  node/primitives/src/lib.rs
  node/subsystem-util/src/rolling_session_window.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3973 Drop availability only for candidates that lose disputes
  roadmap/implementers-guide/src/runtime/disputes.md
  roadmap/implementers-guide/src/runtime/parainherent.md
  runtime/parachains/src/paras_inherent.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3974 node/service: fix disputes tests
  node/service/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3627 Make most XCM APIs accept an Into<MultiLocation> where MultiLocation is accepted
  runtime/common/src/xcm_sender.rs
  runtime/parachains/src/ump.rs
  runtime/test-runtime/src/xcm_config.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/src/v1/multilocation.rs
  xcm/src/v1/traits.rs
  xcm/src/v2/traits.rs
  xcm/xcm-builder/src/mock.rs
  xcm/xcm-builder/src/origin_conversion.rs
  xcm/xcm-builder/src/tests.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/conversion.rs
  xcm/xcm-executor/src/traits/weight.rs
  xcm/xcm-simulator/example/src/lib.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3977 Fix master compilation
  xcm/pallet-xcm-benchmarks/src/mock.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3961 Companion for substrate PR#9890
  Cargo.lock
  runtime/kusama/src/weights/pallet_democracy.rs
  runtime/polkadot/src/weights/pallet_democracy.rs
Labels: B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#3978 gossip-support: set last_session_index earlier
  node/network/gossip-support/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌
