Repository paritytech/polkadot, pull requests merged in 2021-11, with the labels that each got.

#4030 Update GHA to s3krit/matrix-message-action@v0.0.3 + doc
  .github/workflows/check-labels.yml
  .github/workflows/extrinsic-ordering-check-from-bin.yml
  .github/workflows/publish-docker-release.yml
  .github/workflows/publish-draft-release.yml
  .github/workflows/release-bot.yml
  .github/workflows/release-candidate.yml
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4051 Update SimNet test to the new format
  .gitlab-ci.yml
  simnet_tests/README.md
  simnet_tests/parachains/configs/adder.json
  simnet_tests/parachains/configs/simple_rococo_testnet.toml
  simnet_tests/parachains/test_suit_description.toml
  simnet_tests/parachains/tests/parachains.feature
  simnet_tests/run_tests.sh
  simnet_tests/tests/parachains.feature
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4188 Offchain: Disable http requests
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4200 Update CI image to use the latest rustc
  node/overseer/overseer-gen/proc-macro/src/impl_channels_out.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4065 More remote tests for bags-list pallet
  Cargo.lock
  Cargo.toml
  utils/generate-bags/Cargo.toml
  utils/generate-bags/src/main.rs
  utils/remote-ext-tests/bags-list/Cargo.toml
  utils/remote-ext-tests/bags-list/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#4201 Fix misleading logs in collator protocol.
  node/network/collator-protocol/src/validator_side/mod.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4219 minor doc chores
  node/metered-channel/src/oneshot.rs
  node/overseer/overseer-gen/proc-macro/Cargo.toml
  node/overseer/overseer-gen/proc-macro/src/impl_channels_out.rs
  node/overseer/overseer-gen/proc-macro/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4223 Change path for simnet tests to master
  .gitlab-ci.yml
Labels: F4-tests, A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4231 fix(staking miner): use `StorageKey` in rpc call getStorage
  utils/staking-miner/src/monitor.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4222 Update `bridge/` codeowners
  .github/CODEOWNERS
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4203 availability recovery type name clarifications
  node/core/av-store/src/lib.rs
  node/core/av-store/src/metrics.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  roadmap/implementers-guide/src/node/availability/availability-recovery.md
Labels: F5-documentation, F6-refactor, A0-pleasereview, B0-silent, C1-low 📌

#4220 Increase maximum chunk size to adjust for small networks.
  node/network/protocol/src/request_response/mod.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4245 Companion to Substrate #10167 – cargo unleash reactivation
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4210 Update `wasmtime` and related dependencies (companion for Substrate#10149)
  Cargo.lock
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#4258 Update dependencies for latest substrate master
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4211 Add more XCM tracing
  xcm/pallet-xcm/src/lib.rs
  xcm/xcm-builder/src/barriers.rs
  xcm/xcm-builder/src/currency_adapter.rs
  xcm/xcm-builder/src/filter_asset_location.rs
  xcm/xcm-builder/src/fungibles_adapter.rs
  xcm/xcm-builder/src/origin_conversion.rs
  xcm/xcm-builder/src/weight.rs
  xcm/xcm-executor/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4256 Companion – Update jsonrpsee to 0.4.1
  Cargo.lock
  utils/staking-miner/Cargo.toml
  utils/staking-miner/src/dry_run.rs
  utils/staking-miner/src/main.rs
  utils/staking-miner/src/monitor.rs
  utils/staking-miner/src/rpc_helpers.rs
  utils/staking-miner/src/signer.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3957 CI: chore
  .gitlab-ci.yml
  CONTRIBUTING.md
  README.md
  doc/shell-completion.md
  doc/testing.md
  scripts/gitlab/check_line_width.sh
  scripts/gitlab/lingua.dic
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4239 Per subsystem CPU usage tracking
  Cargo.lock
  node/collation-generation/src/lib.rs
  node/core/av-store/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/core/pvf/src/executor_intf.rs
  node/core/runtime-api/src/lib.rs
  node/jaeger/src/lib.rs
  node/network/availability-distribution/src/tests/state.rs
  node/network/availability-recovery/src/lib.rs
  node/overseer/overseer-gen/examples/dummy.rs
  node/overseer/overseer-gen/proc-macro/src/impl_builder.rs
  node/overseer/overseer-gen/proc-macro/src/impl_misc.rs
  node/overseer/overseer-gen/src/lib.rs
  node/overseer/src/lib.rs
  node/overseer/src/tests.rs
  node/service/src/lib.rs
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/tests.rs
  parachain/test-parachains/adder/collator/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌

#4261 collator-protocol: do not connect to the next group
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests.rs
  roadmap/implementers-guide/src/node/collators/collator-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4195 Enable full use of pallet-bags-list in westend and kusama runtimes
  runtime/kusama/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#4191 Remove light client companion
  Cargo.lock
  bridges/modules/grandpa/src/lib.rs
  bridges/modules/grandpa/src/mock.rs
  node/client/src/lib.rs
  node/core/pvf/src/executor_intf.rs
  node/service/src/chain_spec.rs
  node/service/src/lib.rs
  primitives/src/v1/mod.rs
  rpc/src/lib.rs
  runtime/parachains/src/initializer/benchmarking.rs
Labels: A0-pleasereview, B1-releasenotes, B7-runtimenoteworthy, A7-companion, C1-low 📌, D3-trivial 🧸

#4253 req/resp: use IfDisconnected::ImmediateError
  node/network/availability-distribution/src/pov_requester/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/tests.rs
  node/network/availability-distribution/src/tests/state.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  node/network/dispute-distribution/src/sender/send_task.rs
  node/network/dispute-distribution/src/tests/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4269 Increment the retired metric instead of spawned
  node/core/pvf/src/metrics.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4267 Bump pwasm-utils to 0.18.2
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4274 chore: fmt should print version
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4241 3x8 update nightly fix fmt
  node/network/availability-distribution/src/requester/mod.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/statement-distribution/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4273 Limit the number of PVF workers
  node/core/pvf/src/host.rs
  node/core/pvf/tests/it/main.rs
Labels: A0-pleasereview, B1-releasenotes, C3-medium 📣

#4123 PVF host prechecking support v2
  node/core/pvf/src/artifacts.rs
  node/core/pvf/src/error.rs
  node/core/pvf/src/executor_intf.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/lib.rs
  node/core/pvf/src/prepare/pool.rs
  node/core/pvf/src/prepare/queue.rs
  node/core/pvf/src/prepare/worker.rs
  scripts/gitlab/lingua.dic
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4270 Increase preparation timeout
  node/core/pvf/src/metrics.rs
  node/core/pvf/src/prepare/worker.rs
Labels: A0-pleasereview, B1-releasenotes, C7-high ❗️

#4280 Gracefully handle filtering bitfields & candidates
  Cargo.lock
  primitives/src/v1/signed.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/paras_inherent.rs
Labels: A0-pleasereview

#4287 Refactor inherent data weight limiting logic
  runtime/parachains/src/paras_inherent.rs
Labels: A0-pleasereview

#4283 Tweaks to XCM for Benchmarking
  xcm/pallet-xcm/src/lib.rs
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/mock.rs
  xcm/xcm-builder/src/test_utils.rs
  xcm/xcm-builder/src/tests.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/on_response.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4262 Update event variants
  Cargo.lock
  node/test/polkadot-simnet/common/src/lib.rs
  node/test/polkadot-simnet/test/src/main.rs
Labels: B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#4294 Update implementors guide with `sanitize_*` & `enter`
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/parainherent.md
  roadmap/implementers-guide/src/types/runtime.md
  runtime/parachains/src/paras_inherent.rs
Labels: A0-pleasereview

#4303 Make wasm runtimes compile with benchmarks enabled
  Cargo.lock
  parachain/src/primitives.rs
  primitives/Cargo.toml
  primitives/src/v1/mod.rs
  primitives/src/v1/signed.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/builder.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#3949 Companion for substrate#9878
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, A7-companion, C1-low 📌, D5-nicetohaveaudit ⚠️

#4295 Substrate companion: Authority discovery multiple peer ids
  Cargo.lock
  node/network/bridge/src/lib.rs
  node/network/bridge/src/tests.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/dispute-distribution/src/receiver/mod.rs
  node/network/dispute-distribution/src/tests/mock.rs
  node/network/gossip-support/src/lib.rs
  node/network/gossip-support/src/tests.rs
  node/network/protocol/src/authority_discovery.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/tests.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-types/src/messages/network_bridge_event.rs
  roadmap/implementers-guide/src/types/network.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4314 Remove sort_unstable_by
  runtime/parachains/src/paras_inherent.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4320 Enable BEEFY explicitly
  cli/src/cli.rs
  cli/src/command.rs
  node/service/src/lib.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4304 prepare worker: Catch unexpected unwinds
  node/core/pvf/src/error.rs
  node/core/pvf/src/prepare/worker.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#4317 fix pallet-xcm extrinsic doc comments
  xcm/pallet-xcm/src/lib.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#4322 Use magic code instead of default code in benchbuilder
  runtime/parachains/src/builder.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4321 Add missing license header
  runtime/parachains/src/builder.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4324 export hrmp config
  node/service/src/chain_spec.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4328 Dependabot: Ignore sub-tokens
  .github/dependabot.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4134 Dispute spam protection
  Cargo.lock
  Cargo.toml
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/dispute-coordinator/src/metrics.rs
  node/core/dispute-coordinator/src/real/backend.rs
  node/core/dispute-coordinator/src/real/db/v1.rs
  node/core/dispute-coordinator/src/real/error.rs
  node/core/dispute-coordinator/src/real/initialized.rs
  node/core/dispute-coordinator/src/real/mod.rs
  node/core/dispute-coordinator/src/real/ordering/mod.rs
  node/core/dispute-coordinator/src/real/ordering/tests.rs
  node/core/dispute-coordinator/src/real/participation/mod.rs
  node/core/dispute-coordinator/src/real/participation/queues/mod.rs
  node/core/dispute-coordinator/src/real/participation/queues/tests.rs
  node/core/dispute-coordinator/src/real/participation/tests.rs
  node/core/dispute-coordinator/src/real/spam_slots.rs
  node/core/dispute-coordinator/src/real/status.rs
  node/core/dispute-coordinator/src/real/tests.rs
  node/core/dispute-participation/Cargo.toml
  node/core/dispute-participation/src/lib.rs
  node/core/dispute-participation/src/tests.rs
  node/network/availability-distribution/src/error.rs
  node/network/bridge/src/tests.rs
  node/network/dispute-distribution/src/lib.rs
  node/network/dispute-distribution/src/receiver/mod.rs
  node/overseer/src/dummy.rs
  node/overseer/src/lib.rs
  node/overseer/src/tests.rs
  node/primitives/src/lib.rs
  node/service/Cargo.toml
  node/service/src/overseer.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/rolling_session_window.rs
  node/subsystem-util/src/runtime/error.rs
  node/subsystem-util/src/runtime/mod.rs
  primitives/src/v1/mod.rs
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/approval/README.md
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
  roadmap/implementers-guide/src/node/disputes/dispute-distribution.md
  roadmap/implementers-guide/src/node/disputes/dispute-participation.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4331 Log para inherent inputs
  runtime/parachains/src/paras_inherent.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4254 remove provisioner checks
  Cargo.lock
  node/core/provisioner/Cargo.toml
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/metrics.rs
  node/core/provisioner/src/tests.rs
  node/service/src/overseer.rs
  roadmap/implementers-guide/src/node/utility/provisioner.md
  scripts/gitlab/lingua.dic
Labels: A3-inprogress, B0-silent, C1-low 📌

#4334 prefer code upgrades in inherent filtering
  runtime/parachains/src/paras_inherent.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4336 Companion for Taskmanager: Remove `clean_shutdown`
  Cargo.lock
  node/test/service/tests/build-blocks.rs
  node/test/service/tests/call-function.rs
  parachain/test-parachains/adder/collator/tests/integration.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4337 Logging & metrics improvements - Ladi's attempt to replicate Rob's PR
  node/core/backing/src/lib.rs
  node/core/dispute-coordinator/src/real/initialized.rs
  node/network/dispute-distribution/src/sender/send_task.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4131 introduce malus + zombienet based integration tests
  .gitlab-ci.yml
  Cargo.lock
  cli/src/command.rs
  node/malus/Cargo.toml
  node/malus/README.md
  node/malus/container/Containerfile-cargo-chef
  node/malus/container/build.sh
  node/malus/container/malus-local-build.Containerfile
  node/malus/container/polkadot-local-build.Containerfile
  node/malus/integrationtests/0001-dispute-valid-block.feature
  node/malus/integrationtests/0001-dispute-valid-block.toml
  node/malus/src/interceptor.rs
  node/malus/src/malus.rs
  node/malus/src/shared.rs
  node/malus/src/variant-a.rs
  node/malus/src/variants/back_garbage_candidate.rs
  node/malus/src/variants/dispute_valid_candidates.rs
  node/malus/src/variants/mod.rs
  node/malus/src/variants/suggest_garbage_candidate.rs
  node/service/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/test/polkadot-simnet/node/src/main.rs
  scripts/dockerfiles/malus.Dockerfile
  scripts/gitlab/lingua.dic
  simnet_tests/README.md
  simnet_tests/parachains/configs/adder.json
  simnet_tests/parachains/configs/simple_rococo_testnet.toml
  simnet_tests/parachains/test_suit_description.toml
  simnet_tests/parachains/tests/parachains.feature
  zombienet_tests/README.md
  zombienet_tests/parachains/0001-parachains-smoke-test.feature
  zombienet_tests/parachains/0001-parachains-smoke-test.toml
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌

#4346 use correct `gh_dir` env for zombienet
  .gitlab-ci.yml
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4313 Add XCM pallet and config to Polkadot runtime
  Cargo.lock
  node/service/src/chain_spec.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#4305 Inherent filtering follow up
  primitives/Cargo.toml
  primitives/src/v1/signed.rs
  runtime/kusama/src/weights/runtime_parachains_paras_inherent.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/builder.rs
  runtime/parachains/src/paras_inherent/benchmarking.rs
  runtime/polkadot/src/weights/runtime_parachains_paras_inherent.rs
  runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs
  runtime/westend/src/weights/runtime_parachains_paras_inherent.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4355 add missing feature
  xcm/pallet-xcm/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4352 Add Provisioner dispute metrics
  node/core/parachains-inherent/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/metrics.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4358 Fix use of weight limit errors
  xcm/src/v0/traits.rs
  xcm/src/v1/traits.rs
  xcm/src/v2/traits.rs
  xcm/xcm-builder/src/tests.rs
  xcm/xcm-executor/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#4362 OCD: Remove ,) in PVF
  node/core/pvf/src/host.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4349 add additional assurances to `create_inherent`
  roadmap/implementers-guide/src/runtime/inclusion.md
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/paras_inherent.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#4359 Fix provisioner metrics doc typo
  node/core/provisioner/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4356 add disputes to Kusama runtime
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/runtime_parachains_disputes.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D5-nicetohaveaudit ⚠️

#4347 [ci] Add ssh token for publishing gh-pages
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4312 Add Statemine as parachain 1000 to rococo trusted teleporters
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4376 Update W3F URL links
  runtime/common/src/lib.rs
  runtime/parachains/src/reward_points.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4374 Fix Provisioner dispute metrics naming
  node/core/provisioner/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4360 Impose new restrictions on paras init and cleanup
  runtime/common/src/paras_registrar.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/scheduler.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#4372 Do not log PVF prunning every hour
  node/core/pvf/src/host.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4380 Fix typo: ambigious -> ambiguous
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/tests.rs
  node/core/pvf/src/error.rs
  node/core/pvf/src/execute/queue.rs
  node/core/pvf/src/host.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4379 companion for substrate/10377
  Cargo.lock
  runtime/common/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4364 Treat non-deterministic prep errors as internal errors
  node/core/candidate-validation/src/lib.rs
  node/core/pvf/src/error.rs
  node/core/pvf/src/host.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#4385 [BACKPORT] backport changes for v0.9.13
  Cargo.lock
  node/core/candidate-validation/src/lib.rs
  node/core/pvf/src/error.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/prepare/worker.rs
  parachain/Cargo.toml
  parachain/src/primitives.rs
  primitives/Cargo.toml
  primitives/src/v0.rs
  primitives/src/v1/mod.rs
  primitives/src/v1/signed.rs
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/parainherent.md
  roadmap/implementers-guide/src/types/runtime.md
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/runtime_parachains_paras_inherent.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/builder.rs
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/paras/benchmarking.rs
  runtime/parachains/src/paras_inherent.rs
  runtime/parachains/src/paras_inherent/benchmarking.rs
  runtime/parachains/src/scheduler.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/runtime_parachains_paras_inherent.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
  runtime/rococo/src/weights/mod.rs
  runtime/rococo/src/weights/runtime_parachains_paras_inherent.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/runtime_parachains_paras_inherent.rs
Labels: A8-backport, A0-pleasereview

#4403 [zombienet] Increment `within` time for dispute tests
  node/malus/integrationtests/0001-dispute-valid-block.feature
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌

#4389 rococo-runtime: Switch to latest `construct_runtime!` syntax
  node/service/src/chain_spec.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/paras_registrar.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/validator_manager.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4345 make chain selection typed and more explicit in naming and logging
  node/service/src/lib.rs
  node/service/src/relay_chain_selection.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4407 pvf-precheck: Add `sign` in subsystem-util
  node/subsystem-util/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4392 Pin changelogerator to the latest compatible version for the current flow
  .github/workflows/publish-draft-release.yml
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4375 Revert "remove provisioner checks (#4254)"
  Cargo.lock
  node/core/provisioner/Cargo.toml
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/tests.rs
  node/service/src/overseer.rs
  roadmap/implementers-guide/src/node/utility/provisioner.md
  scripts/gitlab/lingua.dic
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4387 Companion for #10324 - update frame-benchmarking/runtime-benchmarks
  Cargo.lock
  bridges/bin/rialto/runtime/Cargo.toml
  bridges/modules/currency-exchange/Cargo.toml
  bridges/modules/ethereum/Cargo.toml
  bridges/modules/grandpa/Cargo.toml
  bridges/modules/messages/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/westend/Cargo.toml
  xcm/xcm-executor/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4415 Double time we give spawned tasks.
  node/network/availability-distribution/src/tests/state.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4339 Update system event variants
  Cargo.lock
  xcm/xcm-simulator/example/src/lib.rs
Labels: B0-silent, A7-companion, C1-low 📌, D2-notlive 💤

#4409 pvf-precheck: Candidate Validation Changes
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/tests.rs
  node/subsystem-types/src/messages.rs
  scripts/gitlab/lingua.dic
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸
