Repository paritytech/polkadot, pull requests merged in 2021-01, with the labels that each got.

#2185 differentiate spans for erasure-coding and storage
  node/core/backing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2189 Improve jaeger spans for bitfield signing
  node/core/bitfield-signing/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2191 Improve unbacked span
  node/core/backing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2161 Add relay storage root to persisted validation data
  node/core/av-store/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/proposer/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/test/client/src/block_builder.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/inclusioninherent.md
  roadmap/implementers-guide/src/types/candidate.md
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/inclusion_inherent.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/util.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2169 Improve Network Spans
  erasure-coding/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/subsystem/src/jaeger.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2195 Use correct ROC currency name
  node/service/res/rococo.json
Labels: A2-insubstantial, B0-silent, C1-low

#2194 Parachains well known keys and abridged primitives
  Cargo.lock
  primitives/Cargo.toml
  primitives/src/v1.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/ump.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2196 Add one Jaeger span per relay parent
  Cargo.lock
  Cargo.toml
  node/collation-generation/src/lib.rs
  node/core/av-store/Cargo.toml
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/candidate-selection/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/jaeger/Cargo.toml
  node/jaeger/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/collator-protocol/Cargo.toml
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/pov-distribution/Cargo.toml
  node/network/pov-distribution/src/lib.rs
  node/network/pov-distribution/src/tests.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/lib.rs
  node/subsystem/Cargo.toml
  node/subsystem/src/errors.rs
  node/subsystem/src/lib.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2060 Reduce the inclusion inherent's actual weight if the block is already heavy
  primitives/src/v1.rs
  runtime/parachains/src/inclusion_inherent.rs
  runtime/parachains/src/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2193 [Release backport] Backport substrate#7733 and switch to that branch
  Cargo.lock
  cli/Cargo.toml
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/collation-generation/Cargo.toml
  node/core/av-store/Cargo.toml
  node/core/backing/Cargo.toml
  node/core/bitfield-signing/Cargo.toml
  node/core/candidate-selection/Cargo.toml
  node/core/candidate-validation/Cargo.toml
  node/core/chain-api/Cargo.toml
  node/core/proposer/Cargo.toml
  node/core/provisioner/Cargo.toml
  node/core/runtime-api/Cargo.toml
  node/network/availability-distribution/Cargo.toml
  node/network/bitfield-distribution/Cargo.toml
  node/network/bridge/Cargo.toml
  node/network/collator-protocol/Cargo.toml
  node/network/pov-distribution/Cargo.toml
  node/network/protocol/Cargo.toml
  node/network/statement-distribution/Cargo.toml
  node/overseer/Cargo.toml
  node/primitives/Cargo.toml
  node/service/Cargo.toml
  node/subsystem-test-helpers/Cargo.toml
  node/subsystem-util/Cargo.toml
  node/subsystem/Cargo.toml
  node/test/client/Cargo.toml
  node/test/service/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2206 Improve the `unbacked-span`
  node/core/backing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2202 Companion PR for 7822 (Remove `_{}` from benchmarks)
  Cargo.lock
  runtime/common/src/claims.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-breaksapi

#2200 runtime: add Babe::next_epoch runtime api method
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B7-runtimenoteworthy, C1-low, D2-breaksapi

#2201 Add metrics timing message passing from OverseerSubsystemContext to Overseer::route_message
  Cargo.lock
  node/overseer/Cargo.toml
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2215 Make order consistent
  primitives/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#2212 CI: remove squash and fix buildah push
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#2205 upgrade a few dependencies (companion for 7831)
  Cargo.lock
  node/core/av-store/Cargo.toml
  node/test/service/Cargo.toml
  parachain/Cargo.toml
  runtime/parachains/Cargo.toml
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#2095 Companion PR for refactoring priority groups
  Cargo.lock
  node/network/bridge/src/lib.rs
  node/network/bridge/src/validator_discovery.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#2216 Switch to latest Jaeger and improve the spans
  Cargo.lock
  node/core/bitfield-signing/src/lib.rs
  node/jaeger/Cargo.toml
  node/jaeger/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2223 Optimizations of av-store
  Cargo.lock
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/network/availability-distribution/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#2197 Batch messages to network bridge and introduce a timeout to `SubsystemContext::send_message`
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests.rs
  node/network/bridge/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/node/utility/network-bridge.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#2226 Avoid cloning and multiple entry calls
  node/core/av-store/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2232 Exit from av-store loop on fatal error.
  node/core/av-store/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2233 Do not send empty view updates to peers
  node/network/availability-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2236 subsystems have an unbounded channel to the overseer
  Cargo.lock
  node/overseer/Cargo.toml
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2231 repair Dockerfile /data path
  docker/Dockerfile
Labels: A0-pleasereview, B1-releasenotes, C1-low

#2237 alternate availability store schema
  Cargo.lock
  node/core/av-store/Cargo.toml
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  roadmap/implementers-guide/src/node/utility/availability-store.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#2245 Pass relay_storage_root into ValidationParams
  node/core/candidate-validation/src/lib.rs
  parachain/src/primitives.rs
  parachain/test-parachains/adder/collator/src/lib.rs
  parachain/test-parachains/tests/adder/mod.rs
  parachain/test-parachains/tests/wasm_executor/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2166 Crowdloan Updates
  runtime/common/src/crowdloan.rs
  runtime/common/src/lib.rs
  runtime/common/src/slots.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2247 parity-scale-codec 1.3.5 -> 1.3.6
  Cargo.lock
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/core/av-store/Cargo.toml
  node/core/candidate-validation/Cargo.toml
  node/network/availability-distribution/Cargo.toml
  node/network/bitfield-distribution/Cargo.toml
  node/network/bridge/Cargo.toml
  node/network/protocol/Cargo.toml
  node/primitives/Cargo.toml
  node/subsystem-test-helpers/Cargo.toml
  node/subsystem-util/Cargo.toml
  node/subsystem/Cargo.toml
  node/test/client/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  statement-table/Cargo.toml
  validation/Cargo.toml
  xcm/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2243 Adds propose parachain pallet
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  runtime/common/src/lib.rs
  runtime/parachains/src/paras.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
  runtime/rococo/src/propose_parachain.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2217 CI: add rococo build and conteinerization
  .gitlab-ci.yml
Labels: A0-pleasereview, B1-releasenotes, C3-medium

#2256 CI: Fix container publishing
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low

#2255 Bump rococo version
  runtime/rococo/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2258 Fix run_to_block functions
  runtime/parachains/src/dmp.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/session_info.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2246 Avoid inlining `update_config_member`
  runtime/parachains/src/configuration.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2225 HRMP channel deposits
  parachain/src/primitives.rs
  runtime/common/src/paras_registrar.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/mock.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2235 metered mpsc channel
  Cargo.lock
  Cargo.toml
  node/metered-channel/Cargo.toml
  node/metered-channel/src/bounded.rs
  node/metered-channel/src/lib.rs
  node/metered-channel/src/unbounded.rs
  node/network/bridge/Cargo.toml
  node/network/bridge/src/lib.rs
  node/overseer/src/lib.rs
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2262 Companion for substrate#7892
  Cargo.lock
  runtime/parachains/src/session_info.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#2260 Copy para host config for rococo-staging
  node/service/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2264 display errors with their sources
  Cargo.lock
  cli/Cargo.toml
  cli/src/command.rs
  parachain/test-parachains/adder/collator/src/main.rs
Labels: A0-pleasereview, A7-companion, A8-mergeoncegreen, B0-silent, C1-low

#2257 scheduler: handle re-scheduling around finalization correctly
  primitives/src/v1.rs
  roadmap/implementers-guide/src/runtime-api/availability-cores.md
  roadmap/implementers-guide/src/runtime-api/validator-groups.md
  roadmap/implementers-guide/src/runtime/inclusioninherent.md
  roadmap/implementers-guide/src/runtime/scheduler.md
  runtime/parachains/src/inclusion_inherent.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/scheduler.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2263 Some refactoring in network-bridge in the course of dealing with #2177
  Cargo.lock
  node/network/bridge/src/action.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/network.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/lib.rs
  node/network/protocol/src/peer_set.rs
  node/service/src/lib.rs
  roadmap/implementers-guide/src/node/utility/network-bridge.md
Labels: A0-pleasereview, B0-silent, C1-low

#2267 small cleanup
  node/overseer/src/lib.rs
  runtime/parachains/src/session_info.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2190 Companion for Substrate#7692
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A7-companion, B0-silent, C1-low, D2-breaksapi

#2253 Companion for substrate #7868
  Cargo.lock
  node/test/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2271 Remove polkadot-validation crate
  Cargo.lock
  Cargo.toml
  validation/Cargo.toml
  validation/README.adoc
  validation/src/block_production.rs
  validation/src/error.rs
  validation/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2122 Availability recovery subsystem
  Cargo.lock
  Cargo.toml
  erasure-coding/src/lib.rs
  node/network/availability-recovery/Cargo.toml
  node/network/availability-recovery/src/error.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  node/network/protocol/src/lib.rs
  node/overseer/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/subsystem/src/errors.rs
  node/subsystem/src/messages.rs
Labels: A5-grumble, B0-silent, C1-low

#2261 Add warning when dropping inclusion inherent
  runtime/parachains/src/inclusion_inherent.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2265 Switch to Wasmtime for parachain execution
  cli/Cargo.toml
  parachain/Cargo.toml
  parachain/src/wasm_executor/mod.rs
  parachain/test-parachains/halt/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low

#2276 use fill_level gauges instead of histograms
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2152 Companion for #7363 (Account-providers ref-counting)
  Cargo.lock
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots.rs
Labels: A2-insubstantial, A7-companion, A9-companion-backlog, B0-silent, C1-low, D2-breaksapi, D9-needsaudit👮

#2279 Improve logging to make debugging parachains easier
  node/core/backing/src/lib.rs
  node/network/collator-protocol/src/validator_side.rs
  parachain/src/wasm_executor/validation_host.rs
Labels: A0-pleasereview, B0-silent, C1-low, Q2-easy

#2284 Make large collations downloads work
  Cargo.lock
  node/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2162 Approval Voting Database
  Cargo.lock
  Cargo.toml
  node/core/approval-voting/Cargo.toml
  node/core/approval-voting/src/aux_schema/mod.rs
  node/core/approval-voting/src/aux_schema/tests.rs
  node/core/approval-voting/src/lib.rs
  node/primitives/src/approval.rs
  roadmap/implementers-guide/src/node/approval/approval-voting.md
Labels: A0-pleasereview, B0-silent, C1-low

#2272 Remove TransientValidationData
  node/collation-generation/src/lib.rs
  node/core/backing/src/lib.rs
  node/core/runtime-api/src/lib.rs
  node/primitives/src/lib.rs
  node/subsystem-util/src/lib.rs
  node/subsystem/src/messages.rs
  parachain/test-parachains/adder/collator/src/lib.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/collators/collation-generation.md
  roadmap/implementers-guide/src/runtime-api/full-validation-data.md
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  runtime/kusama/src/lib.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/util.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2287 Companion PR for adding max notification sizes
  Cargo.lock
  node/network/protocol/src/peer_set.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#2291 Glossary updates
  roadmap/implementers-guide/src/glossary.md
Labels: A2-insubstantial, B0-silent, C1-low

#1948 Companion PR for https://github.com/paritytech/substrate/pull/7463
  Cargo.lock
  cli/src/browser.rs
  cli/src/command.rs
  node/service/src/lib.rs
  node/test/service/Cargo.toml
  node/test/service/src/lib.rs
  node/test/service/tests/build-blocks.rs
  parachain/test-parachains/adder/collator/tests/integration.rs
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/westend/src/weights/pallet_staking.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low, D2-breaksapi

#1719 Companion for sub/7040
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_elections_phragmen.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_elections_phragmen.rs
Labels: A0-pleasereview, A7-companion, B7-runtimenoteworthy, C1-low, D2-breaksapi

#2288 Compress the PoV block before sending it over the network
  Cargo.lock
  node/network/collator-protocol/src/collator_side.rs
  node/network/collator-protocol/src/validator_side.rs
  node/network/pov-distribution/src/lib.rs
  node/network/pov-distribution/src/tests.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/lib.rs
  roadmap/implementers-guide/src/types/network.md
  scripts/gitlab/check_web_wasm.sh
Labels: A0-pleasereview, B0-silent, C1-low

#2297 Update Weight for Pallet Staking including Kick
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/westend/src/weights/pallet_staking.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2301 Add support for Grandpa warp sync
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2100 Companion for #7339: cleaner GRANDPA RPC API
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B1-releasenotes, C1-low

#2310 Put parachain head hash into `CandidateDescriptor`
  node/collation-generation/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/primitives/src/lib.rs
  parachain/src/primitives.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/types/candidate.md
Labels: A0-pleasereview, B0-silent, C1-low

#2320 Add a `convert_payload` function to `Signed`
  node/primitives/src/lib.rs
  primitives/src/v0.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2160 impl approval distribution
  Cargo.lock
  Cargo.toml
  node/network/approval-distribution/Cargo.toml
  node/network/approval-distribution/src/lib.rs
  node/network/approval-distribution/src/tests.rs
  node/network/bridge/src/lib.rs
  node/network/protocol/src/lib.rs
  node/overseer/src/lib.rs
  node/primitives/Cargo.toml
  node/primitives/src/approval.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/subsystem/src/messages.rs
  primitives/src/v1.rs
  roadmap/implementers-guide/src/node/approval/approval-distribution.md
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/types/approval.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low

#2286 Message and Data Type Flow Visualizations
  roadmap/implementers-guide/book.toml
  roadmap/implementers-guide/mermaid-init.js
  roadmap/implementers-guide/mermaid.min.js
  roadmap/implementers-guide/src/node/subsystems-and-jobs.md
  roadmap/implementers-guide/src/types/README.md
Labels: A0-pleasereview, B0-silent, C1-low

#2308 [CI] Matrix release-notifications redux
  .github/workflows/release-bot.yml
Labels: A0-pleasereview, B0-silent, C1-low

#2322 Refact proposal pallet
  Cargo.lock
  runtime/rococo/src/lib.rs
  runtime/rococo/src/propose_parachain.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2327 Bump version to 0.8.28 & bump substrate
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  erasure-coding/Cargo.toml
  node/test/client/Cargo.toml
  node/test/service/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  statement-table/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2309 runtime-api subsystem lru cache
  Cargo.lock
  core-primitives/Cargo.toml
  core-primitives/src/lib.rs
  node/core/runtime-api/Cargo.toml
  node/core/runtime-api/src/cache.rs
  node/core/runtime-api/src/lib.rs
  parachain/Cargo.toml
  parachain/src/primitives.rs
  primitives/Cargo.toml
  primitives/src/v0.rs
  primitives/src/v1.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2328 Companion for #7953: remove runtime checks in prove_finality
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2330 Bump transaction_version for polkadot + kusama
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2333 Rococo v1-1
  node/service/res/rococo.json
  runtime/rococo/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2126 Use Extensible Multiaddress in all Polkadot Runtimes
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#2337 Bump tx version for westend and test-runtime, bump substrate
  Cargo.lock
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D2-breaksapi

#2285 high altitude description of disputes
  .config/lingua.dic
  .config/spellcheck.toml
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/disputes-flow.md
  roadmap/implementers-guide/src/protocol-disputes.md
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent, C1-low

#2222 misbehavior: report multiple offenses per validator as necessary
  node/core/backing/src/lib.rs
  node/primitives/src/lib.rs
  node/subsystem/src/messages.rs
  roadmap/implementers-guide/src/types/overseer-protocol.md
  statement-table/src/generic.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2342 use executor cache in polkadot-parachain executor
  core-primitives/src/lib.rs
  parachain/src/wasm_executor/mod.rs
  parachain/src/wasm_executor/validation_host.rs
Labels: A0-pleasereview, B0-silent, C1-low

#2345 Companion for #7997
  Cargo.lock
  node/core/approval-voting/src/aux_schema/mod.rs
  node/core/approval-voting/src/aux_schema/tests.rs
  node/network/approval-distribution/src/tests.rs
  node/primitives/src/approval.rs
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low, D2-breaksapi

#2348 Companion PR for 7934
  Cargo.lock
  cli/src/command.rs
  node/test/service/tests/build-blocks.rs
  parachain/test-parachains/adder/collator/tests/integration.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#2336 Companion PR for #7951
  Cargo.lock
  node/service/src/lib.rs
  node/test/service/src/lib.rs
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low

#2343 Upgrade codec to 2.0 and bitvec to 0.20 (companion)
  Cargo.lock
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/core/approval-voting/Cargo.toml
  node/core/av-store/Cargo.toml
  node/core/av-store/src/lib.rs
  node/core/backing/Cargo.toml
  node/core/backing/src/lib.rs
  node/core/candidate-validation/Cargo.toml
  node/core/provisioner/Cargo.toml
  node/core/provisioner/src/lib.rs
  node/core/runtime-api/Cargo.toml
  node/network/availability-distribution/Cargo.toml
  node/network/bitfield-distribution/Cargo.toml
  node/network/bridge/Cargo.toml
  node/network/bridge/src/lib.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/lib.rs
  node/primitives/Cargo.toml
  node/primitives/src/lib.rs
  node/subsystem-test-helpers/Cargo.toml
  node/subsystem-util/Cargo.toml
  node/subsystem/Cargo.toml
  node/test/client/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  primitives/Cargo.toml
  primitives/src/v0.rs
  primitives/src/v1.rs
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  statement-table/Cargo.toml
  statement-table/src/generic.rs
  xcm/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
Labels: A0-pleasereview, A7-companion, B0-silent, C1-low, D2-breaksapi

#2347 Approval voting guide changes
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/runtime-api/candidate-events.md
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low
