Repository paritytech/polkadot, pull requests merged in 2021-08, with the labels that each got.

#3538 XCM simulator
  Cargo.lock
  Cargo.toml
  parachain/Cargo.toml
  parachain/src/primitives.rs
  xcm/Cargo.toml
  xcm/xcm-simulator/Cargo.toml
  xcm/xcm-simulator/example/Cargo.toml
  xcm/xcm-simulator/example/src/lib.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
  xcm/xcm-simulator/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#3549 Companion for #9373 (Refactor Benchmarks for Wasm Memory)
  Cargo.lock
  bridges/bin/rialto/runtime/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, C1-low 📌, D2-notlive 💤

#3382 Companion PR for warp sync support.
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3551 Change pallet naming in test-runtime
  node/test/service/src/chain_spec.rs
  runtime/parachains/src/configuration.rs
  runtime/test-runtime/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3550 some fixes to please cargo-spellcheck
  parachain/src/primitives.rs
  roadmap/implementers-guide/README.md
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/disputes-flow.md
  roadmap/implementers-guide/src/node/approval/approval-distribution.md
  roadmap/implementers-guide/src/node/availability/availability-distribution.md
  roadmap/implementers-guide/src/node/availability/availability-recovery.md
  roadmap/implementers-guide/src/node/availability/bitfield-signing.md
  roadmap/implementers-guide/src/node/backing/candidate-backing.md
  roadmap/implementers-guide/src/node/backing/statement-distribution.md
  roadmap/implementers-guide/src/node/collators/collator-protocol.md
  roadmap/implementers-guide/src/node/disputes/README.md
  roadmap/implementers-guide/src/node/disputes/dispute-distribution.md
  roadmap/implementers-guide/src/node/disputes/dispute-participation.md
  roadmap/implementers-guide/src/node/overseer.md
  roadmap/implementers-guide/src/node/utility/chain-selection.md
  roadmap/implementers-guide/src/node/utility/gossip-support.md
  roadmap/implementers-guide/src/node/utility/network-bridge.md
  roadmap/implementers-guide/src/node/utility/runtime-api.md
  roadmap/implementers-guide/src/protocol-approval.md
  roadmap/implementers-guide/src/protocol-disputes.md
  roadmap/implementers-guide/src/types/approval.md
  rpc/src/lib.rs
  scripts/gitlab/lingua.dic
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3553 Remove unused type
  runtime/common/src/paras_registrar.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3556 Enable `std` feature to fix compilation in Cumulus
  parachain/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3449 Companion: Limit the maximum number of wasm memory pages a runtime can have
  Cargo.lock
  node/core/pvf/src/executor_intf.rs
Labels: A0-pleasereview, B1-releasenotes, C7-high ❗️, D3-trivial 🧸

#3561 bump crossbeam-deque to 0.7.4
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3531 Parachains para_inherent.rs to FrameV2
  runtime/kusama/src/lib.rs
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras_inherent.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3539 Add unit tests to pallet-xcm
  Cargo.lock
  xcm/pallet-xcm/Cargo.toml
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/pallet-xcm/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3524 Companion for substrate#9414
  Cargo.lock
  runtime/common/src/integration_tests.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A7-companion, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3371 Introduce upgrade go-ahead and upgrade restriction signals
  primitives/src/v1/mod.rs
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/paras.md
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/paras.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium 📣, D5-nicetohaveaudit ⚠️

#3515 [CI] Add manual Gitlab job for running all benchmarks
  .github/ISSUE_TEMPLATE/release.md
  .gitlab-ci.yml
  scripts/run_all_benches.sh
  scripts/run_benches_for_runtime.sh
Labels: A3-inprogress, B0-silent, C1-low 📌

#3569 Fix flaky test
  node/network/bridge/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3570 [CI] Fix listing pallets for benchmarks jobs
  scripts/run_benches_for_runtime.sh
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌

#3471 node/approval-voting: Continue to migrate tests to subsystem tests
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/old_tests.rs
  node/core/approval-voting/src/persisted_entries.rs
  node/core/approval-voting/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, F4-tests

#3568 Substrate companion #9491
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  node/service/src/lib.rs
  rpc/src/lib.rs
  runtime/common/src/claims.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3567 Bump versions, substrate and beefy in prep for v0.9.9
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/client/Cargo.toml
  node/malus/Cargo.toml
  node/service/Cargo.toml
  node/test/client/Cargo.toml
  node/test/service/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/slot_range_helper/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  statement-table/Cargo.toml
  xcm/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
  xcm/xcm-simulator/Cargo.toml
  xcm/xcm-simulator/example/Cargo.toml
Labels: A3-inprogress, B0-silent, C1-low 📌, D3-trivial 🧸

#3577 Return `relay_parent` as result of collation seconded signal as well
  node/network/collator-protocol/src/collator_side/mod.rs
  node/primitives/src/lib.rs
  node/subsystem-types/src/messages.rs
  parachain/test-parachains/adder/collator/src/lib.rs
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3578 Avoid bad pattern of wildcard fees
  runtime/kusama/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/pallet-xcm/src/tests.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#3579 Introduce hard limit on XCM assets
  xcm/pallet-xcm/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3576 Version bumps to 0.9.9
  Cargo.lock
  erasure-coding/fuzzer/Cargo.toml
  node/collation-generation/Cargo.toml
  node/core/approval-voting/Cargo.toml
  node/core/av-store/Cargo.toml
  node/core/backing/Cargo.toml
  node/core/bitfield-signing/Cargo.toml
  node/core/candidate-validation/Cargo.toml
  node/core/chain-api/Cargo.toml
  node/core/chain-selection/Cargo.toml
  node/core/dispute-coordinator/Cargo.toml
  node/core/dispute-participation/Cargo.toml
  node/core/parachains-inherent/Cargo.toml
  node/core/provisioner/Cargo.toml
  node/core/pvf/Cargo.toml
  node/core/runtime-api/Cargo.toml
  node/jaeger/Cargo.toml
  node/metered-channel/Cargo.toml
  node/metrics/Cargo.toml
  node/network/approval-distribution/Cargo.toml
  node/network/availability-distribution/Cargo.toml
  node/network/availability-recovery/Cargo.toml
  node/network/bitfield-distribution/Cargo.toml
  node/network/bridge/Cargo.toml
  node/network/collator-protocol/Cargo.toml
  node/network/dispute-distribution/Cargo.toml
  node/network/gossip-support/Cargo.toml
  node/network/protocol/Cargo.toml
  node/network/statement-distribution/Cargo.toml
  node/overseer/Cargo.toml
  node/overseer/all-subsystems-gen/Cargo.toml
  node/overseer/overseer-gen/Cargo.toml
  node/overseer/overseer-gen/proc-macro/Cargo.toml
  node/primitives/Cargo.toml
  node/subsystem-test-helpers/Cargo.toml
  node/subsystem-types/Cargo.toml
  node/subsystem-util/Cargo.toml
  node/subsystem/Cargo.toml
  node/test/polkadot-simnet/common/Cargo.toml
  node/test/polkadot-simnet/node/Cargo.toml
  node/test/polkadot-simnet/test/Cargo.toml
  utils/staking-miner/Cargo.toml
  xcm/pallet-xcm/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3571 Follow up for #3282
  node/core/dispute-coordinator/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3522 companion: for call usage https://github.com/paritytech/substrate/pull/9418
  Cargo.lock
  runtime/common/src/paras_sudo_wrapper.rs
  runtime/kusama/src/tests.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/tests.rs
  utils/staking-miner/src/main.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/tests.rs
  xcm/xcm-simulator/example/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#3589 Companion for #9512 (Support test-runner to submit unsigned_extrinsic)
  Cargo.lock
  node/test/polkadot-simnet/common/src/lib.rs
  node/test/polkadot-simnet/test/src/main.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3586 Harden XCM v1 for Recursions
  Cargo.lock
  Cargo.toml
  runtime/parachains/src/ump.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/src/lib.rs
  runtime/test-runtime/src/xcm_config.rs
  xcm/src/double_encoded.rs
  xcm/src/lib.rs
  xcm/src/v0/traits.rs
  xcm/src/v1/traits.rs
  xcm/xcm-executor/integration-tests/Cargo.toml
  xcm/xcm-executor/integration-tests/src/lib.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-simulator/example/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3591 Companion to #9514 (Remove Filter and use Contains instead)
  Cargo.lock
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/lib.rs
  bridges/modules/currency-exchange/src/lib.rs
  bridges/modules/dispatch/src/lib.rs
  bridges/modules/ethereum/src/mock.rs
  bridges/modules/grandpa/src/mock.rs
  bridges/modules/messages/src/mock.rs
  bridges/modules/shift-session-manager/src/lib.rs
  runtime/common/src/auctions.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/impls.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/lib.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#3598 Fix Polkadot Build
  runtime/test-runtime/src/lib.rs
  runtime/test-runtime/src/xcm_config.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3596 Add logging to PVF and other related parts
  node/core/approval-voting/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/tests.rs
  node/core/pvf/src/artifacts.rs
  node/core/pvf/src/execute/queue.rs
  node/core/pvf/src/execute/worker.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/prepare/pool.rs
  node/core/pvf/src/prepare/queue.rs
  node/core/pvf/src/prepare/worker.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3597 Fix Backwards Compatability with v0 Response
  xcm/src/v0/junction.rs
  xcm/src/v0/mod.rs
  xcm/src/v1/mod.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3602 Minor fix to encoding for XCM v1
  xcm/src/v1/multiasset.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3590 companion pr for substrate:auto_db
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌

#3404 Ensure MultiLocation always has a canonical representation
  runtime/common/src/xcm_sender.rs
  runtime/kusama/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/xcm_config.rs
  runtime/westend/src/lib.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/pallet-xcm/src/tests.rs
  xcm/src/v0/junction.rs
  xcm/src/v0/mod.rs
  xcm/src/v0/multi_asset.rs
  xcm/src/v0/multi_location.rs
  xcm/src/v0/order.rs
  xcm/src/v1/junction.rs
  xcm/src/v1/mod.rs
  xcm/src/v1/multiasset.rs
  xcm/src/v1/multilocation.rs
  xcm/src/v1/order.rs
  xcm/src/v1/traits.rs
  xcm/xcm-builder/src/barriers.rs
  xcm/xcm-builder/src/currency_adapter.rs
  xcm/xcm-builder/src/fungibles_adapter.rs
  xcm/xcm-builder/src/location_conversion.rs
  xcm/xcm-builder/src/matches_fungible.rs
  xcm/xcm-builder/src/mock.rs
  xcm/xcm-builder/src/origin_conversion.rs
  xcm/xcm-builder/src/tests.rs
  xcm/xcm-executor/integration-tests/src/lib.rs
  xcm/xcm-executor/src/assets.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/conversion.rs
  xcm/xcm-executor/src/traits/transact_asset.rs
  xcm/xcm-simulator/example/src/lib.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
  xcm/xcm-simulator/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#3609 Remove stale migrations
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3619 Fix kusama local chain name
  .github/ISSUE_TEMPLATE/release.md
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3617 Make RelayedFrom typesafe
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/tests.rs
  xcm/src/v0/mod.rs
  xcm/src/v1/mod.rs
  xcm/src/v1/multilocation.rs
  xcm/xcm-builder/src/fungibles_adapter.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-simulator/example/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3620 New Github Workflow to check extrinsic ordering
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/extrinsic-ordering-check-from-bin.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3611 use WEIGHT_PER_SECOND in FixedRateOfFungible
  xcm/xcm-builder/src/weight.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3613 CI: rustdoc
  .gitlab-ci.yml
Labels: A3-inprogress, B1-releasenotes, C3-medium 📣

#3625 CI: fix rustdoc publishing
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3621 More standard staking miner deposits
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#3624 Remove request multiplexer
  Cargo.lock
  node/network/availability-distribution/Cargo.toml
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/pov_requester/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/responder.rs
  node/network/availability-distribution/src/tests/mod.rs
  node/network/availability-distribution/src/tests/state.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  node/network/bridge/Cargo.toml
  node/network/bridge/src/lib.rs
  node/network/bridge/src/multiplexer.rs
  node/network/bridge/src/tests.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/Cargo.toml
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/collator-protocol/src/error.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/dispute-distribution/Cargo.toml
  node/network/dispute-distribution/src/error.rs
  node/network/dispute-distribution/src/lib.rs
  node/network/dispute-distribution/src/receiver/error.rs
  node/network/dispute-distribution/src/receiver/mod.rs
  node/network/dispute-distribution/src/sender/error.rs
  node/network/dispute-distribution/src/tests/mod.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/request_response/incoming/error.rs
  node/network/protocol/src/request_response/incoming/mod.rs
  node/network/protocol/src/request_response/mod.rs
  node/network/protocol/src/request_response/outgoing.rs
  node/network/protocol/src/request_response/request.rs
  node/network/protocol/src/request_response/v1.rs
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/error.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/responder.rs
  node/network/statement-distribution/src/tests.rs
  node/overseer/all-subsystems-gen/src/lib.rs
  node/overseer/src/lib.rs
  node/overseer/src/tests.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/error_handling.rs
  node/subsystem-util/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3636 Replace cumulus with polkadot in license headers
  xcm/pallet-xcm/src/lib.rs
  xcm/src/v0/junction.rs
  xcm/src/v0/mod.rs
  xcm/src/v0/multi_asset.rs
  xcm/src/v0/multi_location.rs
  xcm/src/v0/order.rs
  xcm/src/v0/traits.rs
  xcm/src/v1/junction.rs
  xcm/src/v1/mod.rs
  xcm/src/v1/multilocation.rs
  xcm/src/v1/order.rs
  xcm/src/v1/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3633 Companion for Substrate#9547
  Cargo.lock
  rpc/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3612 collect better memory stats
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  core-primitives/src/lib.rs
  node/core/pvf/src/worker_common.rs
  node/metrics/Cargo.toml
  node/metrics/src/lib.rs
  node/metrics/src/memory_stats.rs
  node/metrics/src/metronome.rs
  node/overseer/Cargo.toml
  node/overseer/src/lib.rs
  node/overseer/src/metrics.rs
  node/overseer/src/tests.rs
  node/service/Cargo.toml
  scripts/gitlab/lingua.dic
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3640 Remove BuyExecution::orders
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/src/v0/order.rs
  xcm/src/v1/order.rs
  xcm/xcm-builder/src/tests.rs
  xcm/xcm-builder/src/weight.rs
  xcm/xcm-executor/integration-tests/src/lib.rs
  xcm/xcm-executor/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3643 Companion PR for 'Simplify `NativeExecutionDispatch` and remove the `native_executor_instance!`' (9562)
  Cargo.lock
  Cargo.toml
  bridges/bin/millau/node/src/service.rs
  bridges/bin/rialto/node/src/service.rs
  node/client/src/lib.rs
  node/test/polkadot-simnet/common/src/lib.rs
  node/test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌

#3628 check runtime version in staking miner
  Cargo.lock
  utils/staking-miner/Cargo.toml
  utils/staking-miner/src/dry_run.rs
  utils/staking-miner/src/emergency_solution.rs
  utils/staking-miner/src/main.rs
  utils/staking-miner/src/monitor.rs
  utils/staking-miner/src/prelude.rs
  utils/staking-miner/src/signer.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#3647 Simnet v8 move tests
  .gitlab-ci.yml
  scripts/gitlab/trigger_pipeline.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3654 Remove check_web_wasm job
  .gitlab-ci.yml
  scripts/gitlab/check_web_wasm.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3537 add integration tests to xcm-builder
  Cargo.lock
  xcm/pallet-xcm/src/mock.rs
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-builder/src/barriers.rs
  xcm/xcm-builder/src/currency_adapter.rs
  xcm/xcm-builder/src/mock.rs
  xcm/xcm-builder/src/tests.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-builder/tests/scenarios.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3618 Make xcm-simulator async with more tests
  xcm/xcm-simulator/example/src/lib.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3601 Impl WeightTrader for tuple
  xcm/xcm-builder/src/tests.rs
  xcm/xcm-executor/src/traits/weight.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3645 v0.9.9-rc2
  runtime/kusama/src/weights/pallet_balances.rs
  runtime/kusama/src/weights/pallet_bounties.rs
  runtime/kusama/src/weights/pallet_collective.rs
  runtime/kusama/src/weights/pallet_democracy.rs
  runtime/kusama/src/weights/pallet_gilt.rs
  runtime/kusama/src/weights/pallet_identity.rs
  runtime/kusama/src/weights/pallet_im_online.rs
  runtime/kusama/src/weights/pallet_indices.rs
  runtime/kusama/src/weights/pallet_membership.rs
  runtime/kusama/src/weights/pallet_multisig.rs
  runtime/kusama/src/weights/pallet_proxy.rs
  runtime/kusama/src/weights/pallet_scheduler.rs
  runtime/kusama/src/weights/pallet_session.rs
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/kusama/src/weights/pallet_timestamp.rs
  runtime/kusama/src/weights/pallet_tips.rs
  runtime/kusama/src/weights/pallet_treasury.rs
  runtime/kusama/src/weights/pallet_utility.rs
  runtime/kusama/src/weights/pallet_vesting.rs
  runtime/kusama/src/weights/runtime_common_auctions.rs
  runtime/kusama/src/weights/runtime_common_claims.rs
  runtime/kusama/src/weights/runtime_common_crowdloan.rs
  runtime/kusama/src/weights/runtime_common_paras_registrar.rs
  runtime/kusama/src/weights/runtime_common_slots.rs
  runtime/polkadot/src/weights/pallet_balances.rs
  runtime/polkadot/src/weights/pallet_bounties.rs
  runtime/polkadot/src/weights/pallet_collective.rs
  runtime/polkadot/src/weights/pallet_democracy.rs
  runtime/polkadot/src/weights/pallet_elections_phragmen.rs
  runtime/polkadot/src/weights/pallet_identity.rs
  runtime/polkadot/src/weights/pallet_im_online.rs
  runtime/polkadot/src/weights/pallet_indices.rs
  runtime/polkadot/src/weights/pallet_membership.rs
  runtime/polkadot/src/weights/pallet_multisig.rs
  runtime/polkadot/src/weights/pallet_proxy.rs
  runtime/polkadot/src/weights/pallet_scheduler.rs
  runtime/polkadot/src/weights/pallet_session.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/polkadot/src/weights/pallet_timestamp.rs
  runtime/polkadot/src/weights/pallet_tips.rs
  runtime/polkadot/src/weights/pallet_treasury.rs
  runtime/polkadot/src/weights/pallet_utility.rs
  runtime/polkadot/src/weights/pallet_vesting.rs
  runtime/polkadot/src/weights/runtime_common_claims.rs
  runtime/westend/src/weights/pallet_balances.rs
  runtime/westend/src/weights/pallet_identity.rs
  runtime/westend/src/weights/pallet_im_online.rs
  runtime/westend/src/weights/pallet_indices.rs
  runtime/westend/src/weights/pallet_multisig.rs
  runtime/westend/src/weights/pallet_proxy.rs
  runtime/westend/src/weights/pallet_scheduler.rs
  runtime/westend/src/weights/pallet_session.rs
  runtime/westend/src/weights/pallet_staking.rs
  runtime/westend/src/weights/pallet_timestamp.rs
  runtime/westend/src/weights/pallet_utility.rs
  runtime/westend/src/weights/pallet_vesting.rs
  runtime/westend/src/weights/runtime_common_auctions.rs
  runtime/westend/src/weights/runtime_common_crowdloan.rs
  runtime/westend/src/weights/runtime_common_paras_registrar.rs
  runtime/westend/src/weights/runtime_common_slots.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3657 Fix xcm tests
  xcm/xcm-builder/src/tests.rs
  xcm/xcm-builder/tests/scenarios.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3615 Companion PR for 'Make choosing an executor an explicit part of service construction' (#9525)
  Cargo.lock
  bridges/bin/millau/node/src/service.rs
  bridges/bin/rialto/node/src/service.rs
  cli/src/command.rs
  node/client/src/lib.rs
  node/service/src/lib.rs
  node/test/client/src/lib.rs
  node/test/polkadot-simnet/common/src/lib.rs
  node/test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌

#3635 Use proc macros to generate conversion functions for MultiLocation
  Cargo.lock
  Cargo.toml
  xcm/Cargo.toml
  xcm/procedural/Cargo.toml
  xcm/procedural/src/lib.rs
  xcm/procedural/src/v0.rs
  xcm/procedural/src/v0/multilocation.rs
  xcm/procedural/src/v1.rs
  xcm/procedural/src/v1/multilocation.rs
  xcm/src/v0/multi_location.rs
  xcm/src/v1/multilocation.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3662 Companion for https://github.com/paritytech/substrate/pull/9569
  Cargo.lock
  runtime/kusama/src/weights/pallet_election_provider_multi_phase.rs
  runtime/polkadot/src/weights/pallet_election_provider_multi_phase.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/weights/pallet_election_provider_multi_phase.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3600 Companion for #9517 (Custom BenchmarkError)
  Cargo.lock
  runtime/common/src/claims.rs
  runtime/kusama/src/weights/pallet_elections_phragmen.rs
  runtime/polkadot/src/weights/pallet_elections_phragmen.rs
Labels: B0-silent, C1-low 📌, D2-notlive 💤

#3661 Provide dummy dispute coordinator by default.
  Cargo.toml
  cli/Cargo.toml
  node/core/dispute-coordinator/Cargo.toml
  node/core/dispute-coordinator/src/dummy.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/real/backend.rs
  node/core/dispute-coordinator/src/real/db/mod.rs
  node/core/dispute-coordinator/src/real/db/v1.rs
  node/core/dispute-coordinator/src/real/mod.rs
  node/core/dispute-coordinator/src/real/tests.rs
  node/service/Cargo.toml
Labels: A0-pleasereview, B1-releasenotes, C3-medium 📣, A1-needsburnin

#3650 Better logs
  node/core/approval-voting/src/lib.rs
  node/network/availability-recovery/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3665 Replace `()` filter with `Nothing`
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3603 Introduce metrics into PVF validation host
  Cargo.lock
  node/core/candidate-validation/src/lib.rs
  node/core/pvf/Cargo.toml
  node/core/pvf/src/execute/queue.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/lib.rs
  node/core/pvf/src/metrics.rs
  node/core/pvf/src/prepare/pool.rs
  node/core/pvf/src/prepare/queue.rs
  node/core/pvf/tests/it/main.rs
  node/malus/Cargo.toml
  node/malus/src/variant-a.rs
  node/service/src/overseer.rs
Labels: A3-inprogress, B0-silent, C1-low 📌, D3-trivial 🧸

#3672 demote warnings due to disconnected dispute coordinator
  node/core/approval-voting/src/lib.rs
  node/core/backing/src/lib.rs
  node/network/dispute-distribution/src/receiver/error.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌

#3676 Bypass chain-selection subsystem until disputes are enabled.
  node/service/src/relay_chain_selection.rs
  node/service/src/tests.rs
Labels: A0-pleasereview, B1-releasenotes, C3-medium 📣, A1-needsburnin

#3684 properly gate sanity check
  node/service/src/relay_chain_selection.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3691 Release v0.9.9
  node/service/src/relay_chain_selection.rs
  node/service/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3690 Improve MultiLocation conversion functions in xcm-procedural
  xcm/procedural/src/v0/multilocation.rs
  xcm/procedural/src/v1/multilocation.rs
  xcm/src/v0/multi_location.rs
  xcm/src/v1/multilocation.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3685 remove dead_code from chain selection test
  node/service/src/lib.rs
  node/service/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3693 XCM: Introduce versioning to dispatchables' params
  bridges/primitives/chain-rococo/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/tests.rs
  xcm/src/lib.rs
  xcm/xcm-executor/integration-tests/src/lib.rs
  xcm/xcm-simulator/example/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#3407 substrate #9202 companion: Multiple vesting schedules
  Cargo.lock
  runtime/common/src/claims.rs
  runtime/common/src/purchase.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_vesting.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_vesting.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/pallet_vesting.rs
Labels: A0-pleasereview, B1-releasenotes, C3-medium 📣, D3-trivial 🧸

#3681 Fill up request slots via `launch_parallel_requests`
  node/network/availability-recovery/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, A1-needsburnin

#3626 backing-availability-audit: Move ErasureChunk Proof to BoundedVec
  Cargo.lock
  erasure-coding/src/lib.rs
  node/core/av-store/src/tests.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/tests.rs
  node/network/availability-distribution/src/tests/mock.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  node/network/protocol/src/request_response/v1.rs
  node/primitives/Cargo.toml
  node/primitives/src/lib.rs
Labels: F1-security, A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3727 XCM: Allow reclaim of assets dropped from holding
  runtime/common/src/claims.rs
  runtime/kusama/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/xcm_config.rs
  runtime/westend/src/lib.rs
  xcm/pallet-xcm/Cargo.toml
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/pallet-xcm/src/tests.rs
  xcm/src/lib.rs
  xcm/src/v2/mod.rs
  xcm/src/v2/traits.rs
  xcm/xcm-builder/src/barriers.rs
  xcm/xcm-builder/src/mock.rs
  xcm/xcm-builder/src/tests.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-executor/src/assets.rs
  xcm/xcm-executor/src/config.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/drop_assets.rs
  xcm/xcm-executor/src/traits/mod.rs
  xcm/xcm-executor/src/traits/should_execute.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#3730 Return a Result in invert_location
  runtime/test-runtime/src/xcm_config.rs
  scripts/gitlab/lingua.dic
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/tests.rs
  xcm/src/v2/traits.rs
  xcm/xcm-builder/src/location_conversion.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/conversion.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3517 Companion for Generate storage info for pallet authority_discovery #9428
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/session_info.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#3658 Removed unneeded deps
  Cargo.lock
  node/client/Cargo.toml
  node/core/approval-voting/Cargo.toml
  node/core/dispute-coordinator/Cargo.toml
  node/metered-channel/Cargo.toml
  node/metrics/Cargo.toml
  node/network/availability-distribution/Cargo.toml
  node/network/dispute-distribution/Cargo.toml
  node/network/gossip-support/Cargo.toml
  node/overseer/Cargo.toml
  node/overseer/all-subsystems-gen/Cargo.toml
  node/primitives/Cargo.toml
  node/subsystem-test-helpers/Cargo.toml
  node/subsystem-types/Cargo.toml
  node/subsystem-util/Cargo.toml
  node/test/polkadot-simnet/common/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/parachains/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/westend/Cargo.toml
  scripts/gitlab/lingua.dic
  utils/staking-miner/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-simulator/example/Cargo.toml
Labels: A0-pleasereview, B1-releasenotes, C3-medium 📣, D3-trivial 🧸

#3683 New Proxy for Auctions + Crowdloans + Registrar + Slots
  runtime/kusama/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️
