Repository paritytech/polkadot, pull requests merged in 2021-07, with the labels that each got.

#3392 Fix busy loops.
  node/network/availability-recovery/src/lib.rs
  node/network/collator-protocol/src/validator_side/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3387 Bump version, specs & substrate in prep for v0.9.8
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/client/Cargo.toml
  node/malus/Cargo.toml
  node/service/Cargo.toml
  node/test/client/Cargo.toml
  node/test/service/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/halt/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/slot_range_helper/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  statement-table/Cargo.toml
  xcm/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3140 Companion for Substrate#8953
  Cargo.lock
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/lib.rs
  primitives/src/v1/mod.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, A1-needsburnin, A7-companion, B0-silent, C1-low 📌, D3-trivial 🧸

#3141 Staking Miner
  Cargo.lock
  Cargo.toml
  node/service/src/chain_spec.rs
  runtime/common/src/elections.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
  utils/staking-miner/.gitignore
  utils/staking-miner/Cargo.toml
  utils/staking-miner/src/dry_run.rs
  utils/staking-miner/src/emergency_solution.rs
  utils/staking-miner/src/main.rs
  utils/staking-miner/src/monitor.rs
  utils/staking-miner/src/prelude.rs
  utils/staking-miner/src/rpc_helpers.rs
  utils/staking-miner/src/signer.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium 📣, D2-notlive 💤

#3397 cleanup stream polls
  node/core/provisioner/src/lib.rs
  node/metered-channel/src/bounded.rs
  node/network/bridge/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3269 XCM `canonicalize` + `prepend_with` fix
  xcm/src/v0/junction.rs
  xcm/src/v0/multi_location.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#3351 make it easier to dbg stalls
  node/core/parachains-inherent/src/lib.rs
  node/overseer/src/lib.rs
  node/overseer/src/tests.rs
  node/service/src/grandpa_support.rs
  node/service/src/relay_chain_selection.rs
  node/subsystem-test-helpers/src/lib.rs
  node/test/service/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3411 Enable logging in the puppet worker
  Cargo.lock
  node/core/pvf/Cargo.toml
  node/core/pvf/src/lib.rs
  node/core/pvf/src/testing.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3405 parachain origin to frame v2
  runtime/parachains/src/origin.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3408 Warn on low connectivity.
  node/network/gossip-support/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3402 bump a bunch of deps in parity-common
  Cargo.lock
  cli/browser-demo/index.html
  cli/src/browser.rs
  core-primitives/Cargo.toml
  node/core/approval-voting/Cargo.toml
  node/core/av-store/Cargo.toml
  node/core/chain-selection/Cargo.toml
  node/core/dispute-coordinator/Cargo.toml
  node/core/runtime-api/Cargo.toml
  node/malus/Cargo.toml
  node/service/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  xcm/pallet-xcm/Cargo.toml
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low 📌, D3-trivial 🧸

#3412 Use MaxEncodedLen trait from new parity-scale-codec v2.2
  Cargo.lock
  bridges/primitives/chain-millau/Cargo.toml
  bridges/primitives/chain-millau/src/millau_hash.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low 📌, D3-trivial 🧸

#3353 Add XCM Tracing
  Cargo.lock
  xcm/Cargo.toml
  xcm/pallet-xcm/Cargo.toml
  xcm/pallet-xcm/src/lib.rs
  xcm/src/v0/traits.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/conversion.rs
  xcm/xcm-executor/src/traits/filter_asset_location.rs
  xcm/xcm-executor/src/traits/matches_fungible.rs
  xcm/xcm-executor/src/traits/matches_fungibles.rs
  xcm/xcm-executor/src/traits/should_execute.rs
  xcm/xcm-executor/src/traits/transact_asset.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#3403 paras.rs to FRAME V2
  node/service/src/chain_spec.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/paras_registrar.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/scheduler.rs
  runtime/parachains/src/util.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3377 Enable over-bridge-messaging in Rococo/Wococo runtime
  Cargo.lock
  node/service/src/chain_spec.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/bridge_messages.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D2-notlive 💤

#3328 Chain Selection: Follow-ups
  Cargo.lock
  node/core/approval-voting/src/approval_db/v1/mod.rs
  node/core/approval-voting/src/approval_db/v1/tests.rs
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  node/core/chain-selection/Cargo.toml
  node/core/chain-selection/src/db_backend/mod.rs
  node/core/chain-selection/src/db_backend/v1.rs
  node/core/chain-selection/src/lib.rs
  node/core/chain-selection/src/tests.rs
  node/core/chain-selection/src/tree.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3416 parchain initializer.rs to FrameV2
  runtime/kusama/src/lib.rs
  runtime/parachains/src/initializer.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3258 Companion for #9100 (Paged keys rpc for child storage.)
  Cargo.lock
  node/client/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3418 PVF: unresponsive worker doesn't mean the candidate is bad
  node/core/pvf/src/prepare/pool.rs
  node/core/pvf/src/prepare/worker.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3430 Bump BEEFY
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3424 Companion for #9090 (include storage info)
  Cargo.lock
  bridges/bin/rialto/runtime/src/lib.rs
  node/core/pvf/src/executor_intf.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3442 bump parity-ws
  Cargo.lock
Labels: A2-insubstantial, B1-releasenotes, C3-medium 📣

#3419 Seun txpool refactor
  Cargo.lock
  rpc/Cargo.toml
  utils/staking-miner/Cargo.toml
  utils/staking-miner/src/monitor.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3366 Approval voting overlay db
  node/core/approval-voting/src/approval_db/v1/mod.rs
  node/core/approval-voting/src/approval_db/v1/tests.rs
  node/core/approval-voting/src/backend.rs
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/ops.rs
  node/core/approval-voting/src/persisted_entries.rs
  node/core/approval-voting/src/tests.rs
  node/subsystem/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, F4-tests, F6-refactor

#3391 Approval voting full subsystem tests
  Cargo.lock
  node/core/approval-voting/Cargo.toml
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/old_tests.rs
  node/core/approval-voting/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, F4-tests

#3401 Guide updates for disputes.
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
  roadmap/implementers-guide/src/node/disputes/dispute-distribution.md
  roadmap/implementers-guide/src/node/disputes/dispute-participation.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3452 thiserror annotations + spelling
  .config/lingua.dic
  node/core/approval-voting/src/criteria.rs
  node/core/chain-selection/src/backend.rs
  node/network/availability-distribution/src/error.rs
  node/network/collator-protocol/src/error.rs
  node/network/dispute-distribution/src/error.rs
  node/network/dispute-distribution/src/metrics.rs
  node/network/dispute-distribution/src/receiver/error.rs
  node/network/dispute-distribution/src/sender/error.rs
  node/network/dispute-distribution/src/sender/mod.rs
  node/network/dispute-distribution/src/sender/send_task.rs
  node/network/statement-distribution/src/error.rs
  node/subsystem-util/src/error_handling.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3443 Companion for `substrate/pull/9286`
  Cargo.lock
  node/overseer/overseer-gen/Cargo.toml
  node/overseer/overseer-gen/src/lib.rs
  runtime/common/src/elections.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_election_provider_multi_phase.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_election_provider_multi_phase.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/pallet_election_provider_multi_phase.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3348 Wire up candidate backing, approval-voting to disputes
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/old_tests.rs
  node/core/approval-voting/src/persisted_entries.rs
  node/core/approval-voting/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/backing/src/tests.rs
  node/core/dispute-coordinator/src/db/v1.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/tests.rs
  node/core/provisioner/src/lib.rs
  node/overseer/src/lib.rs
  node/primitives/src/disputes/mod.rs
  node/subsystem-types/src/messages.rs
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
  roadmap/implementers-guide/src/node/utility/provisioner.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3446 DoS protection on the collator protocol
  Cargo.lock
  node/network/collator-protocol/Cargo.toml
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3457 more fine grained runtime api caching + a fix for av-store
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/core/runtime-api/src/cache.rs
  node/core/runtime-api/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3420 Companion for #9276: Remove `Filter` impl on `()`
  Cargo.lock
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/lib.rs
  bridges/modules/currency-exchange/src/lib.rs
  bridges/modules/dispatch/src/lib.rs
  bridges/modules/ethereum/src/mock.rs
  bridges/modules/grandpa/src/mock.rs
  bridges/modules/messages/src/mock.rs
  bridges/modules/shift-session-manager/src/lib.rs
  runtime/common/src/auctions.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/impls.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/lib.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots.rs
  runtime/parachains/src/mock.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, A7-companion, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#3459 Dispute Coordinator: Batch queries
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/tests.rs
  node/core/provisioner/src/lib.rs
  node/network/dispute-distribution/src/lib.rs
  node/network/dispute-distribution/src/sender/mod.rs
  node/network/dispute-distribution/src/tests/mod.rs
  node/subsystem-types/src/messages.rs
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, F6-refactor

#3460 Small tweaks to staking miner
  utils/staking-miner/src/main.rs
  utils/staking-miner/src/monitor.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#3462 Dispute coordinator overlay
  node/core/dispute-coordinator/src/backend.rs
  node/core/dispute-coordinator/src/db/v1.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, F6-refactor

#3359 Companion for substrate#9197
  Cargo.lock
  runtime/common/src/impls.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#2609 Introduce test runner biolerplate
  Cargo.lock
  Cargo.toml
  node/test/polkadot-simnet/common/Cargo.toml
  node/test/polkadot-simnet/common/src/lib.rs
  node/test/polkadot-simnet/node/Cargo.toml
  node/test/polkadot-simnet/node/src/main.rs
  node/test/polkadot-simnet/test/Cargo.toml
  node/test/polkadot-simnet/test/src/main.rs
  node/test/service/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3350 Companion for upgrade of `pallet-mmr` to pallet macro
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3466 Upgrade staking-miner to use jsonrpsee v0.3
  Cargo.lock
  utils/staking-miner/Cargo.toml
  utils/staking-miner/src/main.rs
  utils/staking-miner/src/monitor.rs
  utils/staking-miner/src/rpc_helpers.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#3474 Bump BEEFY
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3479 overseer gen minor
  node/overseer/Cargo.toml
  node/overseer/overseer-gen/proc-macro/src/impl_misc.rs
  node/overseer/overseer-gen/proc-macro/src/impl_overseer.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, F6-refactor

#3423 ci: use srtool-actions to build runtimes
  .github/workflows/publish-draft-release.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3476 more verbose asserts in simnet tests
  node/test/polkadot-simnet/common/src/lib.rs
  node/test/polkadot-simnet/test/src/main.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3480 Update BEEFY+MMR integration.
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/mmr.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#3486 added pallet-proxy in rococo feature dependencies
  runtime/rococo/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#3483 Remove the Kubernetes Helm chart
  scripts/kubernetes/Chart.yaml
  scripts/kubernetes/README.md
  scripts/kubernetes/templates/poddisruptionbudget.yaml
  scripts/kubernetes/templates/service.yaml
  scripts/kubernetes/templates/serviceaccount.yaml
  scripts/kubernetes/templates/statefulset.yaml
  scripts/kubernetes/values.yaml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#2947 Disputes runtime
  Cargo.lock
  primitives/src/v1/mod.rs
  roadmap/implementers-guide/src/runtime/disputes.md
  roadmap/implementers-guide/src/types/disputes.md
  runtime/kusama/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras_inherent.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#3491 add rustfmt toml
  rustfmt.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3493 dependabot: ignore another git dep
  .github/dependabot.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3494 Bump BEEFY
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3477 Companion for substrate #9315
  Cargo.lock
  node/test/polkadot-simnet/common/src/lib.rs
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low 📌

#3498 Dispute vote filtering for block authors
  primitives/src/v1/mod.rs
  roadmap/implementers-guide/src/runtime/disputes.md
  runtime/parachains/src/disputes.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D9-needsaudit 👮

#3509 Add `wococo-local` chain spec
  cli/src/command.rs
  node/service/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3510 Use correct syntax for bridge CODEOWNERS
  .github/CODEOWNERS
Labels: A2-insubstantial, B0-silent, C1-low 📌

#3481 Dispute coordinator - Recover disputes on startup
  Cargo.lock
  node/core/dispute-coordinator/Cargo.toml
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/tests.rs
Labels: A5-grumble, B0-silent, C1-low 📌, F6-refactor

#3440 Parachains inclusion.rs to Frame V2
  runtime/kusama/src/lib.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras_inherent.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3426 parachain dmp.rs to Frame V2
  runtime/common/src/xcm_sender.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/dmp.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3507 Improve test in bridge
  bridges/modules/dispatch/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3218 Update slots pallet to FRAME v2
  runtime/common/src/integration_tests.rs
  runtime/common/src/slots.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸, E1-runtimemigration, E5-breaksapi

#3475 Parachains hrmp.rs to Frame V2
  runtime/kusama/src/lib.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, E1-runtimemigration, E5-breaksapi

#3425 Parachains shared.rs to Frame V2
  runtime/common/src/integration_tests.rs
  runtime/common/src/paras_registrar.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/paras_inherent.rs
  runtime/parachains/src/reward_points.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/scheduler.rs
  runtime/parachains/src/session_info.rs
  runtime/parachains/src/shared.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, E5-breaksapi

#3465 Reduce staking miner reward (companion `substrate/pull/9395`)
  Cargo.lock
  runtime/common/src/elections.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#3345 Fix TransactAsset Implementation
  xcm/src/v0/traits.rs
  xcm/xcm-builder/src/currency_adapter.rs
  xcm/xcm-executor/src/traits/matches_fungibles.rs
  xcm/xcm-executor/src/traits/transact_asset.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3519 Do not leak active head data in statement distribution
  node/network/statement-distribution/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, F2-bug, F7-footprint

#3478 enable disputes
  Cargo.lock
  node/core/chain-selection/src/lib.rs
  node/malus/src/variant-a.rs
  node/overseer/Cargo.toml
  node/overseer/examples/minimal-example.rs
  node/overseer/overseer-gen/examples/dummy.rs
  node/overseer/src/lib.rs
  node/overseer/src/subsystems.rs
  node/overseer/src/tests.rs
  node/service/Cargo.toml
  node/service/src/grandpa_support.rs
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/service/src/parachains_db/mod.rs
  node/service/src/parachains_db/upgrade.rs
  node/service/src/relay_chain_selection.rs
  node/subsystem-test-helpers/src/lib.rs
  node/test/service/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, E2-databasemigration

#3484 integrate dispute finality
  Cargo.lock
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/old_tests.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/tests.rs
  node/service/Cargo.toml
  node/service/src/grandpa_support.rs
  node/service/src/lib.rs
  node/service/src/relay_chain_selection.rs
  node/service/src/tests.rs
  node/subsystem-types/src/messages.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3525 change ActiveLeaves to contain at most one activated
  Cargo.lock
  node/core/av-store/src/tests.rs
  node/network/availability-distribution/Cargo.toml
  node/network/availability-distribution/src/tests/state.rs
  node/network/availability-recovery/Cargo.toml
  node/network/availability-recovery/src/tests.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/tests.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/dispute-distribution/src/tests/mod.rs
  node/network/statement-distribution/src/tests.rs
  node/overseer/src/lib.rs
  node/overseer/src/tests.rs
  node/subsystem-types/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3526 Companion for Substrate#9165
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#3528 Parachains ump.rs to FrameV2
  runtime/kusama/src/lib.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/paras_inherent.rs
  runtime/parachains/src/ump.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#3516 Parachains configuration.rs FrameV2
  node/service/src/chain_spec.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/xcm_sender.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/inclusion.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/scheduler.rs
  runtime/parachains/src/session_info.rs
  runtime/parachains/src/ump.rs
  runtime/parachains/src/util.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3456 Companion for substrate #9319
  Cargo.lock
  bridges/bin/millau/node/src/service.rs
  bridges/bin/rialto/node/src/service.rs
  erasure-coding/src/lib.rs
  node/client/Cargo.toml
  node/service/src/lib.rs
  scripts/gitlab/lingua.dic
Labels: A2-insubstantial, A7-companion, B0-silent, C1-low 📌, D3-trivial 🧸

#3521 Parachains session_info.rs to FrameV2
  runtime/kusama/src/lib.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/session_info.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#3529 Parachains scheduler.rs to FrameV2
  runtime/kusama/src/lib.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras_inherent.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/scheduler.rs
  runtime/parachains/src/session_info.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸
