Repository paritytech/polkadot, pull requests merged in 2022-06, with the labels that each got.

#5270 Cleanup macro magic
  Cargo.lock
  node/client/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5622 Add release branch check and refactoring
  .github/workflows/release-01_branch-check.yml
  .github/workflows/release-10_candidate.yml
  .github/workflows/release-20_extrinsic-ordering-check-from-bin.yml
  .github/workflows/release-30_publish-draft-release.yml
  .github/workflows/release-50_publish-docker-release.yml
  .github/workflows/release-51_publish-docker-manual.yml
  .github/workflows/release-99_bot.yml
  scripts/ci/github/check-rel-br
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5646 add missing absolute path specifier
  node/orchestra/proc-macro/src/impl_orchestra.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5634 Changed Bonding & SlashDefer Duration in Westend
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#5594 Fix a storage leak in parachains db
  node/core/dispute-coordinator/src/backend.rs
  node/core/dispute-coordinator/src/db/v1.rs
  node/core/dispute-coordinator/src/error.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/metrics.rs
  node/core/dispute-coordinator/src/tests.rs
  node/service/src/parachains_db/mod.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#5633 Companion for paritytech/substrate#11584
  Cargo.lock
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/lib.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5661 Enable nomination pool slashing on Kusama and westend
  runtime/kusama/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#5670 add weights for pool::chill
  Cargo.lock
  runtime/kusama/src/weights/pallet_nomination_pools.rs
  runtime/westend/src/weights/pallet_nomination_pools.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4783 secondary filtering
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/disputes/tests.rs
Labels: A3-inprogress, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#5619 Companion PR for Substrate 11537
  Cargo.lock
  node/service/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#5676 Companion for #11661
  Cargo.lock
  rpc/Cargo.toml
  utils/staking-miner/Cargo.toml
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌

#5581 Companion to combine iteratons and tolerance in sp-npos-elections API #11498
  Cargo.lock
  runtime/parachains/src/disputes.rs
  utils/staking-miner/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5677 Companion for substrate#11618
  Cargo.lock
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto-parachain/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5682 update substrate
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5683 bump spec_version to 9250
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5597 Allow relay chain council to send XCMs
  runtime/kusama/src/xcm_config.rs
  runtime/polkadot/src/xcm_config.rs
Labels: A0-pleasereview, B1-releasenotes, C3-medium 📣, D3-trivial 🧸

#5671 Companion for paritytech/substrate#11631
  Cargo.lock
  runtime/parachains/Cargo.toml
  runtime/parachains/src/origin.rs
  runtime/westend/src/xcm_config.rs
  xcm/Cargo.toml
  xcm/pallet-xcm/src/lib.rs
  xcm/src/v0/junction.rs
  xcm/src/v1/junction.rs
  xcm/src/v1/multilocation.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#5605 Remove Kusama Nomination Pools Init
  runtime/kusama/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5685 Get rid of unnecessary clone.
  node/core/dispute-coordinator/src/initialized.rs
  primitives/src/v2/mod.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5690 bump transaction version (polkadot & kusama)
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#5695 remove stale migrations
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A8-backport, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5694 remove stale migrations
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5699 Remove futures 0.1
  Cargo.lock
  node/test/service/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#5701 Companion: Bump syn
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#5703 bump substrate
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5521 Let PR titles spread accross multiple lines in the release notes
  scripts/ci/changelog/templates/change.md.tera
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5691 Zombienet re-enable upgrade test
  .gitlab-ci.yml
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌

#5710 Add publish docker staking-miner
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5706 Update metric before bailing out
  node/network/gossip-support/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5516 Rococo: add new pallet-beefy-mmr API (companion for substrate#11406)
  Cargo.lock
  runtime/rococo/src/lib.rs
Labels: A2-insubstantial, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#5708 pass $COMPANION_OVERRIDES to check_dependent_project
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5722 pvf: unignore `terminates_on_timeout` test
  node/core/pvf/tests/it/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5712 pvf: ensure enough stack space
  Cargo.lock
  node/core/pvf/Cargo.toml
  node/core/pvf/src/error.rs
  node/core/pvf/src/execute/worker.rs
  node/core/pvf/src/executor_intf.rs
  node/core/pvf/src/prepare/worker.rs
  node/core/pvf/src/testing.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, A1-needsburnin, D3-trivial 🧸

#5707 Bump `wasmtime` to 0.38.0 and `zstd` to 0.11.2 (companion for substrate#11720)
  Cargo.lock
  node/primitives/Cargo.toml
Labels: A0-pleasereview, F7-optimisation, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#5577 Fix 5560: add support for a new `staking-miner info` command
  utils/staking-miner/Cargo.toml
  utils/staking-miner/README.md
  utils/staking-miner/src/dry_run.rs
  utils/staking-miner/src/main.rs
  utils/staking-miner/src/opts.rs
  utils/staking-miner/src/runtime_versions.rs
  utils/staking-miner/tests/cli.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D2-notlive 💤

#5715 Add checklist item
  .github/ISSUE_TEMPLATE/release.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5733 Add release-engineering to CI files' reviewers
  .github/pr-custom-review.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5716 Fix confusing metric naming
  node/network/gossip-support/src/metrics.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌

#5731 Update dependencies (companion for substrate#11722)
  Cargo.lock
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#5734 staking-miner: CLI flag delay solution x secs
  utils/staking-miner/src/monitor.rs
  utils/staking-miner/src/opts.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌

#5738 Alter minimum weight to fee ratio
  runtime/common/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️
