Repository paritytech/polkadot, pull requests merged in 2022-04, with the labels that each got.

#5228 CI: Require Kusama benchmark to pass
  .gitlab-ci.yml
Labels: A8-mergeoncegreen, A0-pleasereview, B0-silent, C1-low 📌

#5224 Integrate `benchmark-block`
  Cargo.lock
  cli/Cargo.toml
  cli/src/cli.rs
  cli/src/command.rs
  tests/benchmark_block_works.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#4719 Refactor beefy-mmr implementation
  Cargo.lock
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5137 Integrate `benchmark-overhead` command
  Cargo.lock
  cli/src/cli.rs
  cli/src/command.rs
  node/client/Cargo.toml
  node/client/src/lib.rs
  node/core/parachains-inherent/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  tests/benchmark_overhead_works.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#5231 Zombienet: Increase peer connections timeout check
  zombienet_tests/functional/0001-parachains-pvf.feature
  zombienet_tests/functional/0002-parachains-disputes.feature
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5216 [ci] update block- and extrinsic base weights
  scripts/run_benches_for_runtime.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5232 Companion for #10808 (Transactional Layer Limit)
  Cargo.lock
  runtime/parachains/src/paras_inherent/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5239 [ci] add update_rococo_weights job
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5180 Trie State migration rpc
  Cargo.lock
  node/service/src/lib.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#5113 Update Rococo chainspec to v2_1
  node/service/res/rococo.json
  node/service/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5242 rococo: update weights
  runtime/rococo/constants/src/weights/block_weights.rs
  runtime/rococo/constants/src/weights/extrinsic_weights.rs
  runtime/rococo/src/weights/frame_system.rs
  runtime/rococo/src/weights/pallet_balances.rs
  runtime/rococo/src/weights/pallet_collective.rs
  runtime/rococo/src/weights/pallet_im_online.rs
  runtime/rococo/src/weights/pallet_indices.rs
  runtime/rococo/src/weights/pallet_membership.rs
  runtime/rococo/src/weights/pallet_multisig.rs
  runtime/rococo/src/weights/pallet_proxy.rs
  runtime/rococo/src/weights/pallet_timestamp.rs
  runtime/rococo/src/weights/pallet_utility.rs
  runtime/rococo/src/weights/runtime_common_auctions.rs
  runtime/rococo/src/weights/runtime_common_crowdloan.rs
  runtime/rococo/src/weights/runtime_common_paras_registrar.rs
  runtime/rococo/src/weights/runtime_common_slots.rs
  runtime/rococo/src/weights/runtime_parachains_configuration.rs
  runtime/rococo/src/weights/runtime_parachains_disputes.rs
  runtime/rococo/src/weights/runtime_parachains_hrmp.rs
  runtime/rococo/src/weights/runtime_parachains_initializer.rs
  runtime/rococo/src/weights/runtime_parachains_paras.rs
  runtime/rococo/src/weights/runtime_parachains_ump.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5259 Add epoch index to well known keys
  primitives/src/v2/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5264 companion for #11173
  Cargo.lock
  utils/staking-miner/Cargo.toml
  utils/staking-miner/src/rpc.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌

#5272 CI Fix paths to vault secrets
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5028 Replace TransactionByteFee with LengthToFee
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#5253 create .github/pr-custom-review.yml
  .github/pr-custom-review.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#5247 Co #11164: Sub-commands for `benchmark`
  .gitlab-ci.yml
  Cargo.lock
  cli/src/cli.rs
  cli/src/command.rs
  cli/src/error.rs
  tests/benchmark_block_works.rs
  tests/benchmark_overhead_works.rs
  tests/benchmark_storage_works.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸, D2-breaksapi

#5279 fix .github/pr-custom-review.yml
  .github/pr-custom-review.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#5283 Improve error handling in approval voting block import
  Cargo.lock
  node/core/approval-voting/Cargo.toml
  node/core/approval-voting/src/import.rs
  node/subsystem-types/src/errors.rs
Labels: A0-pleasereview, F8-enhancement, B0-silent, C1-low 📌, D3-trivial 🧸

#5287 Remove Travis CI
  .travis.yml
  ci/script.sh
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5289 [ci] point benchmark script to sub-commands (#5247)
  scripts/run_benches_for_runtime.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5286 Session is actually ancient not unknown.
  node/core/approval-voting/src/import.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5291 bump spec_version to 9190
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5292 [ci] fix pallet benchmark script (#5247)
  scripts/run_benches_for_runtime.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5280 Create .github/workflows/pr-custom-review.yml
  .github/workflows/pr-custom-review.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#5297 pvf: fix the deadlock when any of the channels get at capacity
  node/core/pvf/src/host.rs
  node/core/pvf/tests/it/adder.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5282 Prepare for rust 1.60
  .gitlab-ci.yml
  Cargo.lock
  node/overseer/overseer-gen/Cargo.toml
  node/overseer/overseer-gen/src/tests.rs
  node/overseer/overseer-gen/tests/ui/err-01-duplicate-consumer.stderr
  scripts/update-rust-stable.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5313 CI: rename ambiguous jobs
  .github/workflows/pr-custom-review.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5194 remove old pallet migrations
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/migration.rs
  runtime/parachains/src/configuration/tests.rs
  runtime/parachains/src/session_info.rs
  runtime/parachains/src/session_info/migration.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5276 Add mmr_root() to pallet-mmr API to expose root from state (companion for substrate#11183)
  Cargo.lock
  bridges/bin/millau/runtime/Cargo.toml
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto/node/Cargo.toml
  bridges/bin/rialto/runtime/Cargo.toml
  bridges/bin/rialto/runtime/src/lib.rs
  node/client/Cargo.toml
  node/client/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#4442 Add XCM Benchmarks to Kusama
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/xcm/mod.rs
  runtime/kusama/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  runtime/kusama/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  runtime/kusama/src/xcm_config.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#5241 Companion for Adding benchmarking for new `frame_election_provider_support` #11149
  Cargo.lock
  runtime/common/src/elections.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/frame_election_provider_support.rs
  runtime/kusama/src/weights/mod.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/frame_election_provider_support.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/frame_election_provider_support.rs
  runtime/westend/src/weights/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5326 Co #11198: Expose `benchmark machine` command
  Cargo.lock
  cli/src/command.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D2-notlive 💤

#4807 Make debug builds more useful & testing faster.
  Cargo.toml
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#5342 remove FixCouncilDeposit migration
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5323 dispute-coordinator: Cleanup + Bug fixes
  Cargo.lock
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/backing/src/tests.rs
  node/core/dispute-coordinator/Cargo.toml
  node/core/dispute-coordinator/src/error.rs
  node/core/dispute-coordinator/src/real/initialized.rs
  node/core/dispute-coordinator/src/real/mod.rs
  node/core/dispute-coordinator/src/real/ordering/mod.rs
  node/core/dispute-coordinator/src/real/participation/mod.rs
  node/core/dispute-coordinator/src/real/participation/queues/mod.rs
  node/core/dispute-coordinator/src/real/participation/queues/tests.rs
  node/core/dispute-coordinator/src/real/participation/tests.rs
  node/core/dispute-coordinator/src/real/scraping/mod.rs
  node/core/dispute-coordinator/src/real/scraping/tests.rs
  node/core/dispute-coordinator/src/real/tests.rs
  node/network/dispute-distribution/src/receiver/mod.rs
  node/network/dispute-distribution/src/tests/mod.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/runtime/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5254 flatten dispute-coordinator 'real' module.
  node/core/dispute-coordinator/src/backend.rs
  node/core/dispute-coordinator/src/db/mod.rs
  node/core/dispute-coordinator/src/db/v1.rs
  node/core/dispute-coordinator/src/error.rs
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/participation/mod.rs
  node/core/dispute-coordinator/src/participation/queues/mod.rs
  node/core/dispute-coordinator/src/participation/queues/tests.rs
  node/core/dispute-coordinator/src/participation/tests.rs
  node/core/dispute-coordinator/src/real/mod.rs
  node/core/dispute-coordinator/src/scraping/mod.rs
  node/core/dispute-coordinator/src/scraping/tests.rs
  node/core/dispute-coordinator/src/spam_slots.rs
  node/core/dispute-coordinator/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5164 Reduce network bandwidth, improve parablock times: optimize approval-distribution
  Cargo.lock
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/network/approval-distribution/Cargo.toml
  node/network/approval-distribution/src/lib.rs
  node/network/approval-distribution/src/metrics.rs
  node/network/approval-distribution/src/tests.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/lib.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/gossip-support/Cargo.toml
  node/network/gossip-support/src/lib.rs
  node/network/gossip-support/src/tests.rs
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/tests.rs
  node/primitives/src/approval.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-types/src/messages/network_bridge_event.rs
  roadmap/implementers-guide/src/node/approval/approval-distribution.md
  roadmap/implementers-guide/src/types/network.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C3-medium 📣, D9-needsaudit 👮

#5341 Remove FixCouncilDeposit migration
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5324 Companion to Split `SolutionImprovementThresholds` into two types
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#5309 Companion to Substrate #11002
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#5328 Use EXTRA_DEPENDENCIES for pipeline-scripts
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#5084 Prepare for network protocol version upgrades
  Cargo.lock
  node/network/approval-distribution/src/lib.rs
  node/network/approval-distribution/src/tests.rs
  node/network/availability-distribution/src/pov_requester/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/tests.rs
  node/network/availability-distribution/src/tests/state.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bitfield-distribution/src/tests.rs
  node/network/bridge/Cargo.toml
  node/network/bridge/src/lib.rs
  node/network/bridge/src/network.rs
  node/network/bridge/src/tests.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests.rs
  node/network/dispute-distribution/src/sender/send_task.rs
  node/network/dispute-distribution/src/tests/mod.rs
  node/network/gossip-support/src/lib.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/lib.rs
  node/network/protocol/src/peer_set.rs
  node/network/protocol/src/request_response/mod.rs
  node/network/protocol/src/request_response/outgoing.rs
  node/network/protocol/src/request_response/v1.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/requester.rs
  node/network/statement-distribution/src/tests.rs
  node/overseer/src/lib.rs
  node/overseer/src/tests.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-types/src/messages/network_bridge_event.rs
  roadmap/implementers-guide/src/node/approval/approval-distribution.md
  roadmap/implementers-guide/src/node/availability/availability-recovery.md
  roadmap/implementers-guide/src/node/backing/statement-distribution.md
  roadmap/implementers-guide/src/node/collators/collator-protocol.md
  roadmap/implementers-guide/src/node/subsystems-and-jobs.md
  roadmap/implementers-guide/src/node/utility/network-bridge.md
  roadmap/implementers-guide/src/types/network.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  runtime/parachains/src/inclusion/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#5345 Add some additional logging to availability recovery subsystem
  node/network/availability-recovery/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5306 Companion to Proportional Slashing: Substrate #10982
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#5365 Extract peers grid topology related code to a separate unit
  Cargo.lock
  node/network/approval-distribution/src/lib.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/grid_topology.rs
  node/network/protocol/src/lib.rs
  scripts/gitlab/lingua.dic
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5375 Fix priority thresholds
  scripts/changelog/templates/change.md.tera
  scripts/changelog/templates/high_priority.md.tera
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#5374 Remove SlotsCrowdloanIndexMigration & InjectValidatorsIntoVoterList
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5376 Fix priority thresholds (backport #5375)
  scripts/changelog/templates/change.md.tera
  scripts/changelog/templates/high_priority.md.tera
Labels: A8-backport, A0-pleasereview, B0-silent, C1-low 📌

#5380 Update Substrate master
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#5383 Update Substrate
  Cargo.lock
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#5201 fast-runtime tweak
  node/metrics/src/lib.rs
  runtime/kusama/constants/src/lib.rs
  runtime/polkadot/constants/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5379 Remove SlotsCrowdloanIndexMigration & InjectValidatorsIntoVoterList (#5374)
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5369 polkadot-like testnets should be 10 decimal places
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  node/test/service/src/chain_spec.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#5391 metrics separation
  node/collation-generation/src/lib.rs
  node/collation-generation/src/metrics.rs
  node/core/backing/src/lib.rs
  node/core/backing/src/metrics.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/bitfield-signing/src/metrics.rs
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/metrics.rs
  node/core/chain-api/src/lib.rs
  node/core/chain-api/src/metrics.rs
  node/core/runtime-api/src/lib.rs
  node/core/runtime-api/src/metrics.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌

#5370 Companion to `chain-info` Subcommand: #11250
  Cargo.lock
  cli/src/cli.rs
  cli/src/command.rs
Labels: A2-insubstantial, B0-silent, A7-companion, C1-low 📌

#5393 Update `tracing-log` to 0.1.3 (Companion for Substrate#11264)
  Cargo.lock
Labels: A0-pleasereview, F7-optimisation, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#5356 Skip pr-custom-review if pull request is in Draft
  .github/workflows/pr-custom-review.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#5366 Companion for Recovery Pallet benchmarking #11176
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5331 service: use deny-list instead of allow-list for BEEFY
  cli/src/command.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#5392 Update the usage of check_dependent_project
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5386 Co #11270: Update benchmark machine command
  Cargo.lock
  cli/src/command.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5352 Companion for Remove Approval feature in Treasury Pallet (#11243)
  Cargo.lock
  runtime/kusama/src/weights/pallet_treasury.rs
  runtime/polkadot/src/weights/pallet_treasury.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5404 Reduce log severity in the collator protocol
  node/network/collator-protocol/src/collator_side/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5402 Migrate to the new runtime-version macro
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5377 backing: refactor off of jobs system
  Cargo.lock
  node/core/backing/Cargo.toml
  node/core/backing/src/error.rs
  node/core/backing/src/lib.rs
  node/core/backing/src/tests.rs
  node/service/src/overseer.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5407 Update Rococo chainspec to v2_2
  node/service/res/rococo.json
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5412 Quick'n dirty Versi chainspec config.
  cli/src/command.rs
  node/service/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5405 add nomination pools to westend runtime
  Cargo.lock
  node/service/src/chain_spec.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/pallet_nomination_pools.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#5419 break provisioner/candidate-backing cycle
  node/core/backing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸
