Repository paritytech/polkadot, pull requests merged in 2022-08, with the labels that each got.

#5836 Remove already executed calls to nompools MigrateToV2 migration
  runtime/kusama/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5845 Use Saturating Math in XCM
  xcm/pallet-xcm/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5847 Add release-v* rule to common-refs
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5848 Co #11952: Remove `remove_member_wrong_refund` from `phragmen` weights
  Cargo.lock
  runtime/kusama/src/weights/pallet_elections_phragmen.rs
  runtime/polkadot/src/weights/pallet_elections_phragmen.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5846 Companion for #11939
  .gitlab-ci.yml
  Cargo.lock
  rpc/Cargo.toml
  utils/staking-miner/Cargo.toml
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌

#5853 Run benchmarks with `--steps=2`
  .gitlab-ci.yml
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#5840 zombienet: BEEFY and MMR test
  .gitlab-ci.yml
  zombienet_tests/functional/0003-beefy-and-mmr.feature
  zombienet_tests/functional/0003-beefy-and-mmr.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5856 [Zombienet] update the image to the version 1.2.51 globally
  .gitlab-ci.yml
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌

#5849 Update RequestResponseConfig interface to match substrate
  Cargo.lock
  node/network/protocol/src/request_response/mod.rs
Labels: A8-mergeoncegreen, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#5861 Update yamux to fix a potential crash
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5863 Renaming CLI prunning and keep-blocks flags
  Cargo.lock
  node/test/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5841 Trivial networking changes for Substrate PR #11940
  Cargo.lock
  node/core/approval-voting/src/tests.rs
  node/network/bridge/Cargo.toml
  node/network/bridge/src/network.rs
  node/network/bridge/src/rx/tests.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/test/service/Cargo.toml
  node/test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌

#5865 add unit tests to run runtime migrations
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#5857 Zombienet: test disputes with malus garbage candidates
  .gitlab-ci.yml
  zombienet_tests/functional/0003-parachains-garbage-candidate.feature
  zombienet_tests/functional/0003-parachains-garbage-candidate.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5858 [ci] Run check-runtime only for PRs
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5870 Change request-response protocol names to include genesis hash & fork id
  Cargo.lock
  node/network/availability-distribution/src/tests/mod.rs
  node/network/availability-recovery/src/tests.rs
  node/network/bridge/src/network.rs
  node/network/bridge/src/rx/tests.rs
  node/network/bridge/src/tx/mod.rs
  node/network/bridge/src/tx/tests.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/dispute-distribution/src/tests/mod.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/request_response/incoming/mod.rs
  node/network/protocol/src/request_response/mod.rs
  node/network/statement-distribution/src/tests.rs
  node/service/src/lib.rs
  node/service/src/overseer.rs
  roadmap/implementers-guide/src/node/disputes/dispute-distribution.md
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌

#5582 Add nomination pools to Polkadot runtime
  Cargo.lock
  node/service/src/chain_spec.rs
  runtime/common/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_nomination_pools.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#5815 Incorporate changes from substrate PR #11908
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#5874 [ci] Improve cancel-pipeline job
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5871 Transaction payment runtime apis: query call info and fee details
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D5-nicetohaveaudit ⚠️

#5785 Reduce dispute coordinator load
  Cargo.lock
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/backing/src/tests.rs
  node/core/dispute-coordinator/Cargo.toml
  node/core/dispute-coordinator/src/db/v1.rs
  node/core/dispute-coordinator/src/error.rs
  node/core/dispute-coordinator/src/import.rs
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/metrics.rs
  node/core/dispute-coordinator/src/spam_slots.rs
  node/core/dispute-coordinator/src/tests.rs
  node/core/parachains-inherent/src/lib.rs
  node/core/provisioner/src/error.rs
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/tests.rs
  node/network/approval-distribution/src/lib.rs
  node/network/dispute-distribution/src/receiver/mod.rs
  node/network/dispute-distribution/src/sender/mod.rs
  node/network/dispute-distribution/src/tests/mod.rs
  node/overseer/src/lib.rs
  node/primitives/src/disputes/mod.rs
  node/subsystem-types/src/messages.rs
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  roadmap/implementers-guide/src/node/backing/candidate-backing.md
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
  roadmap/implementers-guide/src/node/disputes/dispute-distribution.md
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D5-nicetohaveaudit ⚠️, D3-trivial 🧸

#5888 Don't request votes if there is nothing to request.
  node/core/provisioner/src/lib.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5883 Break cycle collator-procol - backing
  node/core/backing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5892 Governance 2 (Part 1, Non-Controversial Changes)
  runtime/common/src/auctions.rs
  runtime/common/src/slots/mod.rs
  runtime/kusama/src/governance/mod.rs
  runtime/kusama/src/governance/old.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/tests.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/xcm-builder/src/origin_conversion.rs
  xcm/xcm-executor/src/traits/weight.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5891 [ci] Add check-runtime-migration job
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5899 update Cargo.loc to fix build issue
  Cargo.lock
Labels: A0-pleasereview, F9-release, B0-silent, C1-low 📌

#5897 Companion for new Trie cache
  Cargo.lock
  erasure-coding/Cargo.toml
  erasure-coding/src/lib.rs
  node/test/service/src/lib.rs
  runtime/common/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5916 ci Pin gha versions
  .github/workflows/auto-label-prs.yml
  .github/workflows/release-10_candidate.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5913 Companion to Substrate PR 12006
  Cargo.lock
  node/network/bridge/src/network.rs
Labels: B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#5906 Fix output file for updating weights in run_benches_for_runtime.sh
  scripts/ci/run_benches_for_runtime.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5920 Clean up MigrateToV10
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A8-backport, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5914 chore: bump zombienet version
  .gitlab-ci.yml
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌

#5925 Send back empty votes + log in approval-voting in case candidate entry is missing.
  node/core/approval-voting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5921 Clean up MigrateToV10
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5931 Fix wrong logic.
  node/network/collator-protocol/src/validator_side/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5934 Update Substrate to make companion check happy
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5904 use generated preimage weight
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5924 Companion for 12095
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D2-notlive 💤

#5941 Fix some typos in dispute-coordinator
  node/core/dispute-coordinator/src/participation/mod.rs
  node/core/dispute-coordinator/src/scraping/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5876 Change validation & collation protocol names to include genesis hash & fork id
  node/network/approval-distribution/src/tests.rs
  node/network/bitfield-distribution/src/tests.rs
  node/network/bridge/src/lib.rs
  node/network/bridge/src/metrics.rs
  node/network/bridge/src/network.rs
  node/network/bridge/src/rx/mod.rs
  node/network/bridge/src/rx/tests.rs
  node/network/bridge/src/tx/mod.rs
  node/network/bridge/src/tx/tests.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/collator-protocol/src/validator_side/tests.rs
  node/network/protocol/src/lib.rs
  node/network/protocol/src/peer_set.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/tests.rs
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/subsystem-types/src/messages/network_bridge_event.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, T2-Parachains-Protocol

#5942 fix cargo check -p polkadot-node-core-provisioner --all-features
  node/core/provisioner/src/onchain_disputes.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌
