Repository paritytech/polkadot, pull requests merged in 2022-11, with the labels that each got.

#6151 PVF timeouts follow-up
  node/core/pvf/src/artifacts.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/metrics.rs
  node/core/pvf/src/prepare/pool.rs
  node/core/pvf/src/prepare/queue.rs
  node/core/pvf/src/prepare/worker.rs
  node/core/pvf/src/pvf.rs
  node/primitives/src/lib.rs
  roadmap/implementers-guide/src/glossary.md
  roadmap/implementers-guide/src/pvf-prechecking.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6223 BlockId removal: refactor: BlockBackend::block_body
  Cargo.lock
  node/client/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6198 Replace parachain/parathread boolean by enum
  Cargo.lock
  node/test/service/src/lib.rs
  runtime/common/src/paras_registrar.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/builder.rs
  runtime/parachains/src/hrmp/benchmarking.rs
  runtime/parachains/src/hrmp/tests.rs
  runtime/parachains/src/inclusion/tests.rs
  runtime/parachains/src/initializer/tests.rs
  runtime/parachains/src/paras/benchmarking/pvf_check.rs
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras/tests.rs
  runtime/parachains/src/scheduler/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6229 BlockId removal: refactor: Backend::justifications
  Cargo.lock
  node/client/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6225 backing: introduce `CanSecond` request for advertisements filtering
  node/core/backing/src/lib.rs
  node/core/backing/src/tests/mod.rs
  node/core/backing/src/tests/prospective_parachains.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/validator_side/collation.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests/mod.rs
  node/network/collator-protocol/src/validator_side/tests/prospective_parachains.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-util/src/backing_implicit_view.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6233 BlockId removal: refactor: Backend::block_indexed_body
  Cargo.lock
  node/client/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6178 Xcm-Simulator Docs
  xcm/xcm-simulator/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#6206 clean up executed runtime migrations
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6238 Co #12085: Update `k256`
  Cargo.lock
  xcm/pallet-xcm/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#6242 remove unused deps for polkadot-primitives
  Cargo.lock
  primitives/Cargo.toml
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#6243 Pipeline with ci image with rust 1.65
  node/core/runtime-api/src/tests.rs
Labels: A3-inprogress, B0-silent, C1-low 📌

#6246 BlockId removal: &Hash to Hash
  Cargo.lock
  node/client/src/lib.rs
  xcm/xcm-executor/integration-tests/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6230 Increase max rewardable nominators
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#5872 Update polkadot inflation to take into account auctions
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/impls.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/kusama/src/tests.rs
  runtime/polkadot/src/lib.rs
Labels: A3-inprogress, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#6216 Add a `last change` footer to the implementers guide
  roadmap/implementers-guide/README.md
  roadmap/implementers-guide/book.toml
  roadmap/implementers-guide/last-changed.css
  scripts/ci/gitlab/pipeline/build.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6213 Retry failed PVF prepare jobs
  node/core/pvf/src/artifacts.rs
  node/core/pvf/src/host.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6253 companion for fast unstake batching
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#6106 Make rolling session more resilient in case of long finality stalls
  Cargo.lock
  node/core/approval-voting/src/approval_db/v1/mod.rs
  node/core/approval-voting/src/approval_db/v1/tests.rs
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  node/core/dispute-coordinator/src/db/v1.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/tests.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/parachains_db/mod.rs
  node/service/src/parachains_db/upgrade.rs
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/rolling_session_window.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️, E2-databasemigration

#6235 Retry failed PVF execution (AmbiguousWorkerDeath)
  Cargo.lock
  node/core/candidate-validation/Cargo.toml
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/tests.rs
  node/core/pvf/src/execute/queue.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6157 [Companion] Bound Election and Staking by MaxActiveValidators
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  utils/staking-miner/src/emergency_solution.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6226 Companion for substrate#12560
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#6167 Companion for substrate#12530: Consolidate and deduplicate MMR API methods
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D2-notlive 💤, D2-breaksapi

#5424 Add a few staking params to fast-runtime build
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#6127 State trie migration rococo runtime changes.
  Cargo.lock
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#6239 Brad implementers guide revisions 2
  roadmap/implementers-guide/src/node/disputes/README.md
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6130 Update disputes prioritisation in `dispute-coordinator`
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/metrics.rs
  node/core/dispute-coordinator/src/scraping/candidates.rs
  node/core/dispute-coordinator/src/scraping/mod.rs
  node/core/dispute-coordinator/src/scraping/tests.rs
  node/core/dispute-coordinator/src/tests.rs
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, T2-Parachains-Protocol

#6266 approval-voting: remove redundant validation check
  node/core/approval-voting/src/lib.rs
  node/core/candidate-validation/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6200 Remove fill_block
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#6279 fix a compilation warning
  Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#6258 Implement `StagingValidityConstraints` Runtime API method
  node/core/prospective-parachains/src/fragment_tree.rs
  node/subsystem-util/src/inclusion_emulator/staging.rs
  primitives/src/vstaging/mod.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/runtime_api_impl/vstaging.rs
  runtime/parachains/src/shared.rs
  runtime/parachains/src/shared/tests.rs
  runtime/parachains/src/ump.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#6270 Only report concluded if there is an actual dispute.
  node/core/dispute-coordinator/src/import.rs
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/tests.rs
  node/primitives/src/disputes/message.rs
  node/primitives/src/disputes/status.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6281 [ci] fix buildah image
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6291 Fixes "for loop over an `Option`" warnings
  node/core/approval-voting/src/lib.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/chain-selection/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/network/availability-recovery/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/rx/mod.rs
  node/network/statement-distribution/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6290 companion for #12599
  Cargo.lock
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌

#6300 [ci] Improve pipeline stopper
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6294 Provisioner should ignore unconfirmed disputes
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/tests.rs
  node/core/provisioner/src/disputes/prioritized_selection/mod.rs
  node/core/provisioner/src/disputes/prioritized_selection/tests.rs
  node/core/provisioner/src/disputes/random_selection/mod.rs
  node/network/dispute-distribution/src/sender/mod.rs
  node/network/dispute-distribution/src/tests/mod.rs
  node/subsystem-types/src/messages.rs
Labels: A0-pleasereview, F3-annoyance, B0-silent, C1-low 📌, T2-Parachains-Protocol

#6305 network-bridge: fix subsystem task name
  node/network/bridge/src/rx/mod.rs
  node/network/bridge/src/tx/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6275 Change best effort queue behaviour in `dispute-coordinator`
  node/core/dispute-coordinator/src/participation/queues/mod.rs
  node/core/dispute-coordinator/src/participation/queues/tests.rs
  node/core/dispute-coordinator/src/participation/tests.rs
  node/core/dispute-coordinator/src/tests.rs
  node/network/availability-distribution/src/tests/state.rs
  node/subsystem-test-helpers/src/lib.rs
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, T2-Parachains-Protocol

#6306 [ci] fix build implementers guide
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6268 Remove the `wasmtime` feature flag (companion for substrate#12684)
  Cargo.lock
  cli/Cargo.toml
  node/test/service/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6311 Add `starts_with` to v0 and v1 MultiLocation
  xcm/src/v0/multi_location.rs
  xcm/src/v1/multilocation.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#6318 Extend lower bound of `manage_lease_period_start` from `runtime_common::slots`
  runtime/common/src/slots/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6319 Update async-trait version to v0.1.58
  Cargo.lock
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#6293 Add PVF module documentation
  node/core/pvf/src/executor_intf.rs
  node/core/pvf/src/lib.rs
  node/core/pvf/src/priority.rs
  roadmap/implementers-guide/README.md
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/glossary.md
  roadmap/implementers-guide/src/node/utility/candidate-validation.md
  roadmap/implementers-guide/src/node/utility/pvf-prechecker.md
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/chain.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  roadmap/implementers-guide/src/types/pvf-prechecking.md
  scripts/ci/gitlab/lingua.dic
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6315 Rate limit improvements
  node/network/dispute-distribution/src/receiver/mod.rs
  node/network/dispute-distribution/src/sender/mod.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6335 [ci] fix build-implementers-guide
  scripts/ci/gitlab/pipeline/build.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6342 minor: ig: Fix description of execution retry delay
  roadmap/implementers-guide/src/node/utility/candidate-validation.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6343 Add support for outbound only configs on request/response protocols
  node/network/protocol/src/request_response/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6351 update to substrate master
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#6348 Add more granularity to prometheus histogram buckets
  node/core/av-store/src/metrics.rs
  node/core/bitfield-signing/src/metrics.rs
  node/network/approval-distribution/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6346 Provide some more granular metrics for polkadot_pvf_execution_time
  node/core/pvf/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6357 [ci] fix implementer guide job
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6364 remove executed migrations (0.9.33)
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A8-backport, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6321 Companion for: pallet-mmr: move offchain logic to client-side gadget
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#6326 Add Collectives as Trusted Teleporter
  runtime/polkadot/src/xcm_config.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#6369 Companion for: MMR: move RPC code from frame/ to client/
  Cargo.lock
  rpc/Cargo.toml
  rpc/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D2-notlive 💤

#6366 Support OpenGov Calls in Proxy Definitions
  runtime/kusama/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#6282 Use CPU clock timeout for PVF jobs
  Cargo.lock
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/tests.rs
  node/core/pvf/Cargo.toml
  node/core/pvf/src/artifacts.rs
  node/core/pvf/src/error.rs
  node/core/pvf/src/execute/mod.rs
  node/core/pvf/src/execute/queue.rs
  node/core/pvf/src/execute/worker.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/prepare/queue.rs
  node/core/pvf/src/prepare/worker.rs
  node/core/pvf/src/worker_common.rs
  node/core/pvf/tests/it/adder.rs
  node/core/pvf/tests/it/main.rs
  roadmap/implementers-guide/src/node/utility/candidate-validation.md
  rpc/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6309 guide: remove refences to outdated secondary checkers
  node/primitives/src/lib.rs
  roadmap/implementers-guide/src/glossary.md
  roadmap/implementers-guide/src/node/availability/README.md
  roadmap/implementers-guide/src/protocol-overview.md
  roadmap/implementers-guide/src/runtime/README.md
  roadmap/implementers-guide/src/types/approval.md
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
  runtime/parachains/src/paras/mod.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#6287 Prepare the Runtime for asynchronous backing upgrade
  node/core/backing/src/lib.rs
  node/core/backing/src/tests/mod.rs
  node/core/backing/src/tests/prospective_parachains.rs
  node/core/prospective-parachains/src/lib.rs
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/tests.rs
  node/core/runtime-api/src/cache.rs
  node/core/runtime-api/src/lib.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/collator_side/tests/mod.rs
  node/network/collator-protocol/src/collator_side/tests/prospective_parachains.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side/collation.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests/mod.rs
  node/network/collator-protocol/src/validator_side/tests/prospective_parachains.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-types/src/runtime_client.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/runtime/mod.rs
  primitives/src/runtime_api.rs
  primitives/src/vstaging/mod.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/migration.rs
  runtime/parachains/src/configuration/tests.rs
  runtime/parachains/src/inclusion/tests.rs
  runtime/parachains/src/paras_inherent/mod.rs
  runtime/parachains/src/runtime_api_impl/vstaging.rs
  runtime/parachains/src/shared.rs
  runtime/parachains/src/shared/tests.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️, E1-runtimemigration
