Repository paritytech/polkadot, pull requests merged in 2022-01, with the labels that each got.

#4647 derive Copy and Clone for Upgrade signals (#4637)
  primitives/src/v1/mod.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4646 chore: fix copy&paste and tidy comments
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/paras.rs
  runtime/parachains/src/scheduler.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4636 paras: split tests
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4645 Set CurrentCodeHash before running some dispatchable benchmarks
  runtime/parachains/src/paras/benchmarking.rs
  runtime/westend/src/weights/runtime_parachains_paras.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4570 Update RELEASE.md to reflect reality
  RELEASE.md
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4654 Update remote ext test default uri
  utils/remote-ext-tests/bags-list/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4642 Don't change rep on timeout in collator protocol.
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests.rs
  node/network/protocol/src/request_response/outgoing.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4640 collator-protocol: short-term fixes for connectivity
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/collator-protocol/src/lib.rs
  node/network/protocol/src/peer_set.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4658 lower debug level for testnet build
  Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4653 Fully enable bags-list pallet in polkadot runtime
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/pallet_staking.rs
  utils/remote-ext-tests/bags-list/src/voter_bags.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#4659 Bump serde_json from 1.0.73 to 1.0.74
  Cargo.lock
  node/test/service/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4602 Parachain runtime metrics followup
  node/metrics/src/lib.rs
  node/metrics/src/runtime/mod.rs
  node/metrics/src/runtime/parachain.rs
  primitives/src/v1/metrics.rs
  primitives/src/v1/mod.rs
  runtime/metrics/src/with_runtime_metrics.rs
  runtime/metrics/src/without_runtime_metrics.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/metrics.rs
  runtime/parachains/src/paras_inherent/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#4519 Polkadot companion for Substrate#10463
  Cargo.lock
  node/service/src/chain_spec.rs
  node/service/src/lib.rs
  node/test/service/src/chain_spec.rs
Labels: B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#4662 configuration: Update upgrade validation delay doc
  runtime/parachains/src/configuration.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4663 [ci] .gitlab-ci.yml chores
  .gitlab-ci.yml
  scripts/dockerfiles/malus_injected.Dockerfile
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4638 Companion for Substrate#10568 - Add new BEEFY RPC
  Cargo.lock
  node/service/src/lib.rs
  rpc/src/lib.rs
Labels: B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#4668 zombinet: bump collator image
  .gitlab-ci.yml
Labels: A3-inprogress, A2-insubstantial, B0-silent, C1-low 📌

#4669 Better error for spurious cache misses.
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/requester/session_cache.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4655 Fix locked deposit of council voters
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#4656 Fix locked deposits of Nicks pallet
  runtime/kusama/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#4377 [zombinet] initial implementation of zombienet backchannel
  Cargo.lock
  Cargo.toml
  node/zombienet-backchannel/Cargo.toml
  node/zombienet-backchannel/src/errors.rs
  node/zombienet-backchannel/src/lib.rs
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌

#4671 Fix command to check substrate base ref
  RELEASE.md
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4643 pvf-precheck: PVF pre-checker subsystem
  Cargo.lock
  Cargo.toml
  node/core/pvf-checker/Cargo.toml
  node/core/pvf-checker/src/interest_view.rs
  node/core/pvf-checker/src/lib.rs
  node/core/pvf-checker/src/runtime_api.rs
  node/core/pvf-checker/src/tests.rs
  node/network/bridge/src/tests.rs
  node/overseer/src/dummy.rs
  node/overseer/src/lib.rs
  node/overseer/src/tests.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/subsystem-types/src/messages.rs
  scripts/gitlab/lingua.dic
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#4673 paras: fix weight computation
  runtime/parachains/src/paras/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4639 Remove sleep from tests
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  node/metrics/Cargo.toml
  node/metrics/src/lib.rs
  node/metrics/src/tests.rs
  node/test/service/Cargo.toml
  node/test/service/src/lib.rs
  node/test/service/tests/build-blocks.rs
  node/test/service/tests/call-function.rs
  parachain/test-parachains/adder/collator/tests/integration.rs
  runtime/test-runtime/Cargo.toml
  scripts/gitlab/test_linux_stable.sh
  tests/common.rs
  tests/purge_chain_works.rs
  tests/running_the_node_and_interrupt.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4661 Small mostly doc improvements
  node/core/chain-selection/src/lib.rs
  node/core/dispute-coordinator/src/real/mod.rs
  node/service/src/relay_chain_selection.rs
  node/subsystem-types/src/messages.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4680 Companion for substrate#10503
  Cargo.lock
  Cargo.toml
  node/test/polkadot-simnet/common/Cargo.toml
  node/test/polkadot-simnet/common/src/lib.rs
  node/test/polkadot-simnet/node/Cargo.toml
  node/test/polkadot-simnet/node/src/main.rs
  node/test/polkadot-simnet/test/Cargo.toml
  node/test/polkadot-simnet/test/src/main.rs
Labels: B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#4666 CI: remove rococo from CI
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4644 Move XCM runtime configurations into their own files
  runtime/kusama/src/lib.rs
  runtime/kusama/src/xcm_config.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/xcm_config.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/xcm_config.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/tests.rs
  runtime/westend/src/xcm_config.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4652 Switch types to use `RuntimeDebug` instead of gated `Debug`
  parachain/src/primitives.rs
  primitives/src/v0.rs
  primitives/src/v1/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4688 Delete Process.json
  Process.json
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4694 staking miner: use config for emergency solution
  utils/staking-miner/src/emergency_solution.rs
  utils/staking-miner/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4696 Companion for substrate#10620
  Cargo.lock
  runtime/parachains/src/builder.rs
  runtime/parachains/src/disputes.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4703 Update test commands according to current process
  README.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4704 approval-voting: add more logs
  node/core/approval-voting/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4692 Fix Migrations for the upcoming release
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4702 Add some docs to prevent a time loop.
  node/network/availability-recovery/src/lib.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4705 approval-voting: query finalized block on startup and increase look back
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  node/service/src/relay_chain_selection.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4579 cargo: sync workspace members with dependencies
  Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4685 impl guide: Describe the PVF check subsystem
  roadmap/implementers-guide/src/node/utility/pvf-prechecker.md
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4699 Add node authority status metric
  node/network/gossip-support/src/lib.rs
  node/network/gossip-support/src/metrics.rs
  node/network/gossip-support/src/tests.rs
  node/service/src/overseer.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4683 paras: Add runtime events for PVF pre-checking
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#4332 Add `fast-runtime` Cargo Feature for Quick Test Runs
  Cargo.toml
  cli/Cargo.toml
  node/service/Cargo.toml
  runtime/common/src/lib.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/constants/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/constants/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D2-notlive 💤

#4722 Report the actual missing session.
  node/subsystem-util/src/rolling_session_window.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4724 spellcheck fixes
  runtime/metrics/src/with_runtime_metrics.rs
  runtime/metrics/src/without_runtime_metrics.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4726 backport 4706
  node/core/runtime-api/src/cache.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4723 refactor runtime cache for SessionInfo
  node/core/runtime-api/src/cache.rs
  node/core/runtime-api/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4728 Change EraIndex import path: companion #10671
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4684 paras: do not allow PVF vote submission if disabled
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4731 make xcm_config public
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4736 Check that `try-runtime` compiles in CI
  .gitlab-ci.yml
  scripts/gitlab/check_no_default_features.sh
  scripts/gitlab/check_runtime_benchmarks.sh
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4741 pvf-checker-subsystem: metrics
  node/core/pvf-checker/src/interest_view.rs
  node/core/pvf-checker/src/lib.rs
  node/core/pvf-checker/src/metrics.rs
  node/core/pvf-checker/src/tests.rs
  node/service/src/overseer.rs
Labels: A3-inprogress, B0-silent, C1-low 📌, D3-trivial 🧸

#4747 Bump substrate.
  Cargo.lock
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4739 Mainnets have upper bound on treasury bond required (companion for #10689)
  Cargo.lock
  runtime/common/src/impls.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, B0-silent, C1-low 📌, D3-trivial 🧸

#4564 Create benchmarks for XCM instructions introduced in v3
  runtime/westend/src/weights/xcm/mod.rs
  runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  xcm/src/v3/mod.rs
  xcm/src/v3/traits.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4660 [Zombienet] add dummy upgrade test
  .gitlab-ci.yml
  zombienet_tests/parachains/0002-parachains-upgrade-smoke-test.feature
  zombienet_tests/parachains/0002-parachains-upgrade-smoke-test.toml
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌

#4657 [runtime] follow up relay chain cleanups
  Cargo.lock
  node/core/provisioner/src/lib.rs
  primitives/src/v1/mod.rs
  primitives/src/v1/signed.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/builder.rs
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/inclusion/mod.rs
  runtime/parachains/src/inclusion/tests.rs
  runtime/parachains/src/paras_inherent/misc.rs
  runtime/parachains/src/paras_inherent/mod.rs
  runtime/parachains/src/paras_inherent/tests.rs
  runtime/parachains/src/paras_inherent/weights.rs
  utils/staking-miner/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D9-needsaudit 👮, A1-needsburnin

#4746 co #10662: Require `MaxEncodedLen` per default
  Cargo.lock
  bridges/modules/grandpa/src/lib.rs
  bridges/modules/messages/src/lib.rs
  runtime/common/src/assigned_slots.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/dmp.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/inclusion/mod.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras_inherent/mod.rs
  runtime/parachains/src/scheduler.rs
  runtime/parachains/src/session_info.rs
  runtime/parachains/src/shared.rs
  runtime/parachains/src/ump.rs
  runtime/rococo/src/validator_manager.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/fuzzer/src/parachain.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#4712 Remove `Default` bound on `AccountId` types under the xcm directory
  bridges/bin/rialto-parachain/runtime/src/lib.rs
  xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  xcm/xcm-builder/src/currency_adapter.rs
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/location_conversion.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/fuzzer/src/parachain.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#4732 XCM v3: Introduce querier field into `QueryReponse`
  runtime/test-runtime/src/lib.rs
  scripts/gitlab/lingua.dic
  xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  xcm/pallet-xcm-benchmarks/src/mock.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/pallet-xcm/src/tests.rs
  xcm/src/v1/multilocation.rs
  xcm/src/v2/mod.rs
  xcm/src/v3/mod.rs
  xcm/src/v3/traits.rs
  xcm/xcm-builder/src/barriers.rs
  xcm/xcm-builder/src/mock.rs
  xcm/xcm-builder/src/tests.rs
  xcm/xcm-builder/tests/scenarios.rs
  xcm/xcm-executor/integration-tests/src/lib.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/on_response.rs
  xcm/xcm-simulator/example/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#3876 HRMP benchmarks
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/runtime_parachains_hrmp.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/hrmp/benchmarking.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras/mod.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/runtime_parachains_hrmp.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/weights/mod.rs
  runtime/rococo/src/weights/runtime_parachains_hrmp.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/runtime_parachains_hrmp.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️, E6-transactionversion

#4762 polkadot-test-service: Enable wasmtime feature
  node/test/service/Cargo.toml
  node/test/service/src/chain_spec.rs
  node/test/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4760 Use `define_benchmarks!`
  bridges/bin/millau/runtime/src/lib.rs
  bridges/bin/rialto-parachain/runtime/src/lib.rs
  bridges/bin/rialto/runtime/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: F6-refactor, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4765 Companion for Substrate#10655
  Cargo.lock
  bridges/modules/dispatch/src/lib.rs
  bridges/primitives/polkadot-core/src/lib.rs
  bridges/primitives/runtime/src/chain.rs
  parachain/src/primitives.rs
  runtime/common/src/impls.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4491 New changelog scripts
  .github/workflows/publish-draft-release.yml
  scripts/changelog/.gitignore
  scripts/changelog/Gemfile
  scripts/changelog/Gemfile.lock
  scripts/changelog/README.md
  scripts/changelog/bin/changelog
  scripts/changelog/digests/.gitignore
  scripts/changelog/digests/.gitkeep
  scripts/changelog/lib/changelog.rb
  scripts/changelog/templates/change.md.tera
  scripts/changelog/templates/changes.md.tera
  scripts/changelog/templates/changes_client.md.tera
  scripts/changelog/templates/changes_misc.md.tera
  scripts/changelog/templates/changes_runtime.md.tera
  scripts/changelog/templates/compiler.md.tera
  scripts/changelog/templates/debug.md.tera
  scripts/changelog/templates/docker_image.md.tera
  scripts/changelog/templates/global_priority.md.tera
  scripts/changelog/templates/high_priority.md.tera
  scripts/changelog/templates/host_functions.md.tera
  scripts/changelog/templates/migrations.md.tera
  scripts/changelog/templates/pre_release.md.tera
  scripts/changelog/templates/runtime.md.tera
  scripts/changelog/templates/runtimes.md.tera
  scripts/changelog/templates/template.md.tera
  scripts/changelog/test/test_basic.rb
  scripts/github/lib.rb
Labels: A3-inprogress, A2-insubstantial, B0-silent, C1-low 📌

#4775 [ci] pipeline chores
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4779 [ci] remove publish-s3-release
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4709 Companion for Use proper bounded vector type for nominations #10601
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4596 availability-distribution: look for leaf ancestors within the same session
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/requester/mod.rs
  node/network/availability-distribution/src/requester/tests.rs
  node/subsystem-types/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4785 log concluded disputes
  node/core/dispute-coordinator/src/real/initialized.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4787 Fix tests
  bridges/modules/messages/src/lib.rs
  node/network/availability-distribution/src/requester/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4752 `relay chain selection` and `dispute-coordinator` fixes and improvements
  node/core/dispute-coordinator/src/real/initialized.rs
  node/core/dispute-coordinator/src/real/mod.rs
  node/core/dispute-coordinator/src/real/ordering/mod.rs
  node/service/src/relay_chain_selection.rs
  node/subsystem-util/src/rolling_session_window.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4735 Refactor and fix usage of `get_session_index()` and `get_session_info_by_index()`
  node/network/availability-distribution/src/requester/mod.rs
  node/network/availability-distribution/src/requester/session_cache.rs
  node/network/availability-distribution/src/requester/tests.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/dispute-distribution/src/sender/mod.rs
  node/network/dispute-distribution/src/sender/send_task.rs
  node/network/statement-distribution/src/lib.rs
  node/subsystem-types/src/lib.rs
  node/subsystem-util/src/rolling_session_window.rs
  node/subsystem-util/src/runtime/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4757 Companion for better way to resolve `Phase::Emergency` via governance #10663
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4795 Fix incomplete sorting.
  runtime/parachains/src/disputes.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D1-audited 👍

#4800 wrong if-case - backport of #4798 into v0.9.16
  runtime/parachains/src/inclusion/mod.rs
  runtime/parachains/src/inclusion/tests.rs
  runtime/parachains/src/paras_inherent/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#4727 Refactor check_validation_outputs
  runtime/parachains/src/inclusion/mod.rs
  runtime/parachains/src/paras_inherent/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4806 Rk fix sorting 0.9.16
  runtime/parachains/src/disputes.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4801 Refactor check validation outputs - Backport of #4727 into v0.9.16
  runtime/parachains/src/inclusion/mod.rs
  runtime/parachains/src/paras_inherent/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4798 wrong if-case
  runtime/parachains/src/inclusion/mod.rs
  runtime/parachains/src/inclusion/tests.rs
  runtime/parachains/src/paras_inherent/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#4777 Add baseline benchmarks
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/frame_benchmarking_baseline.rs
  runtime/kusama/src/weights/pallet_balances.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/frame_benchmarking_baseline.rs
  runtime/polkadot/src/weights/pallet_balances.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4818 Update PVF metric histogram buckets
  node/core/pvf/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌
