Repository paritytech/polkadot, pull requests merged in 2022-10, with the labels that each got.

#6088 Fix: minor typo
  README.md
Labels: A2-insubstantial, B0-silent, C1-low 📌

#6061 Companion for pallet-mmr: generate historical proofs
  Cargo.lock
  node/service/src/chain_spec.rs
  runtime/common/src/impls.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/lib.rs
  runtime/common/src/paras_registrar.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/ump.rs
  runtime/parachains/src/ump/benchmarking.rs
  runtime/parachains/src/ump/tests.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  scripts/ci/gitlab/pipeline/zombienet.yml
  xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  xcm/pallet-xcm-benchmarks/src/generic/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6086 Remove orchestra and metered channel
  Cargo.lock
  Cargo.toml
  node/metered-channel/Cargo.toml
  node/metered-channel/src/bounded.rs
  node/metered-channel/src/lib.rs
  node/metered-channel/src/oneshot.rs
  node/metered-channel/src/tests.rs
  node/metered-channel/src/unbounded.rs
  node/metrics/Cargo.toml
  node/orchestra/Cargo.toml
  node/orchestra/README.md
  node/orchestra/adr/01-adr.md
  node/orchestra/examples/duo.rs
  node/orchestra/examples/misc.rs
  node/orchestra/examples/solo.rs
  node/orchestra/proc-macro/Cargo.toml
  node/orchestra/proc-macro/build.rs
  node/orchestra/proc-macro/src/graph.rs
  node/orchestra/proc-macro/src/impl_builder.rs
  node/orchestra/proc-macro/src/impl_channels_out.rs
  node/orchestra/proc-macro/src/impl_message_wrapper.rs
  node/orchestra/proc-macro/src/impl_orchestra.rs
  node/orchestra/proc-macro/src/impl_subsystem_ctx_sender.rs
  node/orchestra/proc-macro/src/lib.rs
  node/orchestra/proc-macro/src/orchestra.rs
  node/orchestra/proc-macro/src/parse/mod.rs
  node/orchestra/proc-macro/src/parse/parse_orchestra_attr.rs
  node/orchestra/proc-macro/src/parse/parse_orchestra_struct.rs
  node/orchestra/proc-macro/src/parse/parse_subsystem_attr.rs
  node/orchestra/proc-macro/src/parse/tests.rs
  node/orchestra/proc-macro/src/subsystem.rs
  node/orchestra/proc-macro/src/tests.rs
  node/orchestra/src/lib.rs
  node/orchestra/src/tests.rs
  node/orchestra/tests/ui/err-01-duplicate-consumer.rs
  node/orchestra/tests/ui/err-01-duplicate-consumer.stderr
  node/orchestra/tests/ui/err-02-enum.rs
  node/orchestra/tests/ui/err-02-enum.stderr
  node/orchestra/tests/ui/err-03-subsys-twice.rs
  node/orchestra/tests/ui/err-03-subsys-twice.stderr
  node/orchestra/tests/ui/err-04-missing-error.rs
  node/orchestra/tests/ui/err-04-missing-error.stderr
  node/orchestra/tests/ui/err-05-missing-field.rs
  node/orchestra/tests/ui/err-05-missing-field.stderr
  node/orchestra/tests/ui/err-06-missing-subsystem.rs
  node/orchestra/tests/ui/err-06-missing-subsystem.stderr
  node/orchestra/tests/ui/err-07-missing-spawner.rs
  node/orchestra/tests/ui/err-07-missing-spawner.stderr
  node/orchestra/tests/ui/err-08-duplicate-subsystem.rs
  node/orchestra/tests/ui/err-08-duplicate-subsystem.stderr
  node/orchestra/tests/ui/err-09-uninit_generic_baggage.rs
  node/orchestra/tests/ui/err-09-uninit_generic_baggage.stderr
  node/orchestra/tests/ui/ok-01-wip.rs
  node/overseer/Cargo.toml
  node/subsystem-types/Cargo.toml
  node/subsystem-util/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5205 Governance v2 (Kusama only)
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/constants/src/lib.rs
  runtime/kusama/src/governance/fellowship.rs
  runtime/kusama/src/governance/mod.rs
  runtime/kusama/src/governance/old.rs
  runtime/kusama/src/governance/origins.rs
  runtime/kusama/src/governance/tracks.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_collective_council.rs
  runtime/kusama/src/weights/pallet_collective_technical_committee.rs
  runtime/kusama/src/weights/pallet_conviction_voting.rs
  runtime/kusama/src/weights/pallet_ranked_collective.rs
  runtime/kusama/src/weights/pallet_referenda_fellowship_referenda.rs
  runtime/kusama/src/weights/pallet_referenda_referenda.rs
  runtime/kusama/src/weights/pallet_whitelist.rs
  xcm/pallet-xcm-benchmarks/Cargo.toml
  xcm/pallet-xcm-benchmarks/src/fungible/mod.rs
  xcm/pallet-xcm-benchmarks/src/generic/mod.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#6068 Use active_leaves instead of known_leaves
  node/core/parachains-inherent/src/lib.rs
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6098 Companion for BEEFY: Simplify hashing for pallet-beefy-mmr
  Cargo.lock
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6054 Keep sessions in window for the full unfinalized chain
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/tests.rs
  node/core/dispute-coordinator/src/tests.rs
  node/subsystem-util/src/rolling_session_window.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#5894 Batch vote import in dispute-distribution
  Cargo.lock
  Cargo.toml
  node/network/dispute-distribution/Cargo.toml
  node/network/dispute-distribution/src/lib.rs
  node/network/dispute-distribution/src/metrics.rs
  node/network/dispute-distribution/src/receiver/batches/batch.rs
  node/network/dispute-distribution/src/receiver/batches/mod.rs
  node/network/dispute-distribution/src/receiver/batches/waiting_queue.rs
  node/network/dispute-distribution/src/receiver/error.rs
  node/network/dispute-distribution/src/receiver/mod.rs
  node/network/dispute-distribution/src/receiver/peer_queues.rs
  node/network/dispute-distribution/src/sender/mod.rs
  node/network/dispute-distribution/src/sender/send_task.rs
  node/network/dispute-distribution/src/tests/mock.rs
  node/network/dispute-distribution/src/tests/mod.rs
  node/network/protocol/src/request_response/mod.rs
  roadmap/implementers-guide/src/node/disputes/dispute-distribution.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D9-needsaudit 👮, T2-Parachains-Protocol

#6105 Add unknown words
  scripts/ci/gitlab/lingua.dic
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6022 Buffered connection management for collator-protocol
  Cargo.lock
  node/network/collator-protocol/Cargo.toml
  node/network/collator-protocol/src/collator_side/metrics.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/collator-protocol/src/collator_side/validators_buffer.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, T2-Parachains-Protocol

#6091 Properly migrate weights to v2
  runtime/kusama/src/lib.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/migration.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/tests.rs
  xcm/xcm-executor/integration-tests/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#6110 Pass through `runtime-benchmarks` feature
  cli/Cargo.toml
  node/test/performance-test/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5729 Companion for #11649: Bound uses of `Call`
  Cargo.lock
  runtime/kusama/src/governance/fellowship.rs
  runtime/kusama/src/governance/mod.rs
  runtime/kusama/src/governance/old.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_democracy.rs
  runtime/kusama/src/weights/pallet_preimage.rs
  runtime/kusama/src/weights/pallet_scheduler.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_democracy.rs
  runtime/polkadot/src/weights/pallet_preimage.rs
  runtime/polkadot/src/weights/pallet_scheduler.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/weights/pallet_democracy.rs
  runtime/rococo/src/weights/pallet_preimage.rs
  runtime/rococo/src/weights/pallet_scheduler.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/pallet_preimage.rs
  runtime/westend/src/weights/pallet_scheduler.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#6111 update kvdb & co
  Cargo.lock
  Cargo.toml
  core-primitives/Cargo.toml
  node/core/approval-voting/Cargo.toml
  node/core/av-store/Cargo.toml
  node/core/av-store/src/lib.rs
  node/core/chain-selection/Cargo.toml
  node/core/chain-selection/src/db_backend/v1.rs
  node/core/dispute-coordinator/Cargo.toml
  node/core/runtime-api/Cargo.toml
  node/malus/Cargo.toml
  node/overseer/Cargo.toml
  node/service/Cargo.toml
  node/service/src/parachains_db/upgrade.rs
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/database.rs
  parachain/Cargo.toml
  primitives/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, E3-dependencies

#6109 Dump more info for `unexpected metric type`
  node/metrics/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6112 service: use MmrRootProvider as custom BEEFY payload provider (companion for 12428)
  Cargo.lock
  node/service/src/lib.rs
Labels: B0-silent, A7-companion, C1-low 📌

#6021 Maximum value for `MultiplierUpdate`
  Cargo.lock
  runtime/common/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, A9-companion-backlog, C1-low 📌, D3-trivial 🧸

#6118 Companion for upgrading pin-project
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5929 Companion for 12109
  Cargo.lock
  runtime/common/src/claims.rs
  runtime/common/src/purchase.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#6029 Add event to asset claim
  xcm/pallet-xcm/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6131 Fix flaky test
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests.rs
  node/subsystem-test-helpers/src/lib.rs
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6119 ci/guide: install mdbook-graphviz
  scripts/ci/gitlab/pipeline/build.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#6117 Companion for paritytech/substrate#12441
  Cargo.lock
  node/network/protocol/src/peer_set.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#6124 Update tests for Rust 1.64
  node/gum/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6058 Companion for #12328
  Cargo.lock
  utils/staking-miner/src/monitor.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌

#6135 Expose node subcommands in Malus CLI
  cli/src/cli.rs
  node/malus/src/malus.rs
  node/malus/src/variants/dispute_valid_candidates.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5451 Manual Para Lock
  runtime/common/src/paras_registrar.rs
  runtime/kusama/src/weights/runtime_common_paras_registrar.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/paras/mod.rs
  runtime/polkadot/src/weights/runtime_common_paras_registrar.rs
  runtime/rococo/src/weights/runtime_common_paras_registrar.rs
  runtime/westend/src/weights/runtime_common_paras_registrar.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D1-audited 👍

#5740 collator-protocol: asynchronous backing changes
  node/collation-generation/src/lib.rs
  node/network/collator-protocol/src/collator_side/collation.rs
  node/network/collator-protocol/src/collator_side/metrics.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/collator_side/tests/mod.rs
  node/network/collator-protocol/src/collator_side/tests/prospective_parachains.rs
  node/network/collator-protocol/src/collator_side/validators_buffer.rs
  node/network/collator-protocol/src/error.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side/collation.rs
  node/network/collator-protocol/src/validator_side/metrics.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests/mod.rs
  node/network/collator-protocol/src/validator_side/tests/prospective_parachains.rs
  node/network/protocol/src/lib.rs
  node/network/protocol/src/request_response/mod.rs
  node/network/protocol/src/request_response/outgoing.rs
  node/network/protocol/src/request_response/vstaging.rs
  node/overseer/src/lib.rs
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-util/src/backing_implicit_view.rs
  scripts/ci/gitlab/lingua.dic
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6140 refactor grid topology to expose more info to subsystems
  Cargo.lock
  node/network/approval-distribution/src/lib.rs
  node/network/approval-distribution/src/tests.rs
  node/network/bitfield-distribution/Cargo.toml
  node/network/bitfield-distribution/src/lib.rs
  node/network/bitfield-distribution/src/tests.rs
  node/network/bridge/src/rx/mod.rs
  node/network/gossip-support/src/lib.rs
  node/network/gossip-support/src/tests.rs
  node/network/protocol/src/grid_topology.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/tests.rs
  node/overseer/src/tests.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-types/src/messages/network_bridge_event.rs
  roadmap/implementers-guide/src/types/network.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6100 Malus: add disputed block percentage
  Cargo.lock
  node/malus/Cargo.toml
  node/malus/src/malus.rs
  node/malus/src/variants/back_garbage_candidate.rs
  node/malus/src/variants/common.rs
  node/malus/src/variants/dispute_valid_candidates.rs
  node/malus/src/variants/mod.rs
  node/malus/src/variants/suggest_garbage_candidate.rs
Labels: A0-pleasereview, F8-enhancement, B0-silent, C1-low 📌, T1-Parachains-Engineering

#6139 Separate preparation timeouts for PVF prechecking and execution
  node/core/pvf/src/host.rs
  node/core/pvf/src/metrics.rs
  node/core/pvf/src/prepare/pool.rs
  node/core/pvf/src/prepare/queue.rs
  node/core/pvf/src/prepare/worker.rs
  roadmap/implementers-guide/src/pvf-prechecking.md
  scripts/ci/gitlab/lingua.dic
  zombienet_tests/functional/0001-parachains-pvf.zndsl
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6072 pallet-mmr: RPC and Runtime APIs work with block numbers
  Cargo.lock
  node/client/src/lib.rs
  rpc/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D2-notlive 💤

#6148 lingua.dic is not managed by CI team
  .github/CODEOWNERS
Labels: A2-insubstantial, B0-silent, C1-low 📌

#6142 bump zombienet version
  .gitlab-ci.yml
  node/malus/integrationtests/0001-dispute-valid-block.zndsl
  scripts/ci/gitlab/pipeline/zombienet.yml
  zombienet_tests/misc/0001-paritydb.zndsl
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌

#6146 First Round of Implementers Guide Fixes
  roadmap/implementers-guide/src/disputes-flow.md
  roadmap/implementers-guide/src/protocol-chain-selection.md
  roadmap/implementers-guide/src/runtime/configuration.md
  roadmap/implementers-guide/src/runtime/paras.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6145 Re-export `pub` stuff from universal_exports.rs + removed unecessary clone
  xcm/src/v3/traits.rs
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-executor/src/traits/export.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6149 BlockId removal refactor: Backend::state_at
  Cargo.lock
  xcm/xcm-executor/integration-tests/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6153 Fix fuzzing builds xcm-fuzz and erasure-coding fuzzer
  Cargo.lock
  erasure-coding/fuzzer/Cargo.toml
  erasure-coding/fuzzer/src/round_trip.rs
  xcm/xcm-simulator/fuzzer/Cargo.toml
  xcm/xcm-simulator/fuzzer/src/fuzz.rs
Labels: B0-silent, C1-low 📌

#6155 Add `force_open_hrmp_channel` Call
  runtime/kusama/src/weights/runtime_parachains_hrmp.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/hrmp/benchmarking.rs
  runtime/parachains/src/hrmp/tests.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/runtime_parachains_hrmp.rs
  runtime/rococo/src/weights/runtime_parachains_hrmp.rs
  runtime/westend/src/weights/runtime_parachains_hrmp.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#6128 Update clap to version 4
  Cargo.lock
  cli/Cargo.toml
  cli/src/cli.rs
  node/malus/Cargo.toml
  node/malus/src/malus.rs
  node/malus/src/variants/common.rs
  node/malus/src/variants/dispute_valid_candidates.rs
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/adder/collator/src/cli.rs
  parachain/test-parachains/undying/collator/Cargo.toml
  parachain/test-parachains/undying/collator/src/cli.rs
  utils/generate-bags/Cargo.toml
  utils/generate-bags/src/main.rs
  utils/remote-ext-tests/bags-list/Cargo.toml
  utils/remote-ext-tests/bags-list/src/main.rs
  utils/staking-miner/Cargo.toml
  utils/staking-miner/src/opts.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6081 availability-recovery: use `IfDisconnected::TryConnect` for chunks
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#6160 BlockId removal: refactor: StorageProvider
  Cargo.lock
  node/client/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6164 Bump substrate
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6162 companion for #12212
  Cargo.lock
  Cargo.toml
  tests/common.rs
  utils/staking-miner/src/main.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌

#6158 validator assignment fixes for backing and collator protocol
  node/core/backing/src/lib.rs
  node/core/backing/src/tests/prospective_parachains.rs
  node/network/collator-protocol/src/validator_side/collation.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests/prospective_parachains.rs
  node/network/statement-distribution/src/legacy_v1/mod.rs
Labels: A0-pleasereview

#6115 Companion for EPM duplicate submissions
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
  utils/staking-miner/src/main.rs
  utils/staking-miner/src/monitor.rs
  utils/staking-miner/src/opts.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, E1-runtimemigration

#6171 bump transaction_version (0.9.31)
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#6170 try and fix build
  Cargo.lock
  cli/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#6150 Use a more typesafe approach for managing indexed data
  node/core/approval-voting/src/criteria.rs
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  node/core/dispute-coordinator/src/import.rs
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/tests.rs
  node/core/runtime-api/src/tests.rs
  node/network/availability-distribution/src/tests/mock.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/dispute-distribution/src/sender/mod.rs
  node/network/dispute-distribution/src/tests/mock.rs
  node/network/gossip-support/src/tests.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/tests.rs
  node/primitives/src/disputes/message.rs
  node/subsystem-util/src/rolling_session_window.rs
  node/subsystem-util/src/runtime/mod.rs
  primitives/src/v2/mod.rs
  runtime/parachains/src/builder.rs
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/disputes/slashing.rs
  runtime/parachains/src/disputes/slashing/benchmarking.rs
  runtime/parachains/src/session_info.rs
  runtime/parachains/src/session_info/tests.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#6181 Add missing prerequisite in README for implementers guide
  roadmap/implementers-guide/README.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6179 Refactor prospective parachains mode request
  node/core/backing/src/error.rs
  node/core/backing/src/lib.rs
  node/core/prospective-parachains/src/error.rs
  node/core/prospective-parachains/src/lib.rs
  node/core/provisioner/src/error.rs
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/tests.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/error.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side/collation.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/runtime/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6185 backing: don't send backed candidate to provisioner if async backing is enabled
  node/core/backing/src/lib.rs
  node/core/backing/src/tests/prospective_parachains.rs
Labels: A0-pleasereview

#6172 Companion for #12457 (Bounded Multisig)
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6180 Make some fixes to logging in PVF subsystem
  node/core/pvf/src/execute/queue.rs
  node/core/pvf/src/executor_intf.rs
  node/core/pvf/src/worker_common.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6188 Co #12558: Update `pallet-multisig` benches
  Cargo.lock
  runtime/kusama/src/weights/pallet_multisig.rs
  runtime/parachains/src/mock.rs
  runtime/polkadot/src/weights/pallet_multisig.rs
  runtime/rococo/src/weights/pallet_multisig.rs
  runtime/westend/src/weights/pallet_multisig.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#6197 Update impl guide README
  roadmap/implementers-guide/README.md
Labels: A2-insubstantial, B0-silent, C1-low 📌

#6205 clean up executed runtime migrations (0.9.31)
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6199 [Companion] StakingInterface adjustments
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6209 Companion for update `wasm-opt`
  Cargo.lock
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#6214 Make ValidateUnsigned available on all chains for paras.
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6215 [ZombieNet] fix upgrade node test, use latest as base image
  scripts/ci/gitlab/pipeline/zombienet.yml
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌

#6219 Check if approval voting db is empty on startup
  node/core/approval-voting/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌
