Repository paritytech/polkadot, pull requests merged in 2022-07, with the labels that each got.

#5744 fix(staking miner): query latest state when comparing to already submitted solutions
  utils/staking-miner/src/main.rs
  utils/staking-miner/src/monitor.rs
  utils/staking-miner/src/rpc.rs
Labels: B0-silent, C1-low 📌

#5742 Limit stagnant checks to a certain amount of entries
  node/core/chain-selection/src/backend.rs
  node/core/chain-selection/src/db_backend/v1.rs
  node/core/chain-selection/src/lib.rs
  node/core/chain-selection/src/tests.rs
  node/core/chain-selection/src/tree.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5751 Fix regexp to find the repo name
  .github/workflows/release-01_branch-check.yml
  scripts/ci/github/check-rel-br
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5718 [Zombienet] test deregister validator
  .gitlab-ci.yml
  zombienet_tests/smoke/0003-deregister-register-validator-smoke.feature
  zombienet_tests/smoke/0003-deregister-register-validator-smoke.toml
  zombienet_tests/smoke/0003-deregister-register-validator.js
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌

#5756 Several small fixes to the templates of the release notes
  scripts/ci/changelog/templates/changes_misc.md.tera
  scripts/ci/changelog/templates/global_priority.md.tera
  scripts/ci/changelog/templates/high_priority.md.tera
  scripts/ci/changelog/templates/host_functions.md.tera
  scripts/ci/changelog/templates/migrations-db.md.tera
  scripts/ci/changelog/templates/migrations-runtime.md.tera
  scripts/ci/changelog/templates/runtime.md.tera
  scripts/ci/changelog/templates/runtimes.md.tera
  scripts/ci/changelog/templates/template.md.tera
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5749 Rename `extra_constant`
  runtime/common/src/auctions.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5764 Update release-99_bot.yml
  .github/workflows/release-99_bot.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5761 Implement prune only stagnant check mode
  node/core/chain-selection/src/lib.rs
  node/core/chain-selection/src/tests.rs
  node/core/chain-selection/src/tree.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5557 Integrate prospective parachains subsystem into backing: Part 1
  node/core/backing/src/error.rs
  node/core/backing/src/lib.rs
  node/core/backing/src/tests/mod.rs
  node/core/backing/src/tests/prospective_parachains.rs
  node/core/prospective-parachains/src/fragment_tree.rs
  node/core/prospective-parachains/src/lib.rs
  node/malus/src/variants/suggest_garbage_candidate.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests.rs
  node/network/statement-distribution/src/error.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/tests.rs
  node/overseer/src/lib.rs
  node/primitives/src/disputes/mod.rs
  node/primitives/src/lib.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-util/src/backing_implicit_view.rs
  node/subsystem-util/src/lib.rs
  primitives/src/v2/signed.rs
  runtime/parachains/src/runtime_api_impl/vstaging.rs
  statement-table/src/generic.rs
  statement-table/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#5773 Fix disable-runtime-api feature flag
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#5778 backing: track occupied depths per parachain
  node/core/backing/src/lib.rs
  node/core/backing/src/tests/mod.rs
  node/core/backing/src/tests/prospective_parachains.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5757 companion for new pools reward scheme
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#5781 Fix Core Version display in the release notes
  scripts/ci/changelog/templates/runtime.md.tera
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5766 Fix Typo
  runtime/common/src/auctions.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5787 Fix test `full_block_council_election_cost`
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview

#5310 Zombienet: paritydb test
  .gitlab-ci.yml
  zombienet_tests/misc/0001-check_paritydb.sh
  zombienet_tests/misc/0001-paritydb.feature
  zombienet_tests/misc/0001-paritydb.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5780 `staking-miner`: Add handling of `SIGTERM`, `SIGKILL`, `SIGQUIT` and `SIGINT`
  Cargo.lock
  utils/staking-miner/Cargo.toml
  utils/staking-miner/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5620 Co #11456: Expose `benchmark extrinsic` command
  Cargo.lock
  cli/Cargo.toml
  cli/src/command.rs
  node/client/src/benchmarking.rs
  node/client/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  tests/benchmark_block_works.rs
  tests/benchmark_overhead_works.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#5790 add `Extrinsic Ordering` check that runs against a local reference node
  .github/workflows/release-21_extrinsic-ordering-check-from-two.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5782 Introduce async runtime calling trait for runtime-api subsystem
  Cargo.lock
  node/core/approval-voting/Cargo.toml
  node/core/approval-voting/src/tests.rs
  node/core/runtime-api/Cargo.toml
  node/core/runtime-api/src/lib.rs
  node/core/runtime-api/src/tests.rs
  node/overseer/Cargo.toml
  node/overseer/examples/minimal-example.rs
  node/overseer/src/lib.rs
  node/overseer/src/tests.rs
  node/subsystem-test-helpers/src/lib.rs
  node/subsystem-types/Cargo.toml
  node/subsystem-types/src/lib.rs
  node/subsystem-types/src/runtime_client.rs
  rustfmt.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5792 allow re-use and avoid compiling kusama parachain code
  cli/Cargo.toml
  cli/src/command.rs
  cli/src/lib.rs
  node/test/performance-test/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5791 Fix benchmarking tests
  Cargo.lock
  tests/benchmark_block.rs
  tests/benchmark_extrinsic.rs
  tests/benchmark_overhead.rs
  tests/common.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5794 Cleanup light client leftovers
  Cargo.lock
  cli/src/command.rs
  parachain/test-parachains/adder/collator/src/main.rs
  parachain/test-parachains/undying/collator/src/main.rs
Labels: A8-mergeoncegreen, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#5798 Westend xcm: collectives parachain is trusted teleporter
  runtime/westend/src/xcm_config.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium 📣

#5806 [ci] publish parachain-implementers-guide
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5770 malus: add `finality_delay` cli flag
  cli/src/command.rs
  node/malus/src/malus.rs
  node/service/src/lib.rs
  node/test/service/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
  parachain/test-parachains/undying/collator/src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5812 Add missing trigger wildcards for some CI workflows
  .github/workflows/release-01_branch-check.yml
  .github/workflows/release-10_candidate.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5814 Bump substrate
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5816 Bump strum to 0.24.1
  Cargo.lock
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#5811 Prepare for rust 1.62.1
  .gitlab-ci.yml
  node/orchestra/tests/ui/err-01-duplicate-consumer.stderr
  node/orchestra/tests/ui/err-02-enum.stderr
  node/orchestra/tests/ui/err-03-subsys-twice.stderr
  node/orchestra/tests/ui/err-04-missing-error.stderr
  node/orchestra/tests/ui/err-05-missing-field.stderr
  node/orchestra/tests/ui/err-06-missing-subsystem.stderr
  node/orchestra/tests/ui/err-07-missing-spawner.stderr
  node/orchestra/tests/ui/err-08-duplicate-subsystem.stderr
  node/orchestra/tests/ui/err-09-uninit_generic_baggage.stderr
  node/orchestra/tests/ui/ok-01-wip.rs
  scripts/update-rust-stable.sh
Labels: A3-inprogress, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5817 add migration for staking v10
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#5818 [ci] Return production image
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5784 Companion for #11831
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#5797 Parachains db column "migration"
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/parachains_db/mod.rs
  node/service/src/parachains_db/upgrade.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5822 [ci] Add timeout to update-weights jobs
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5825 Fix GH workflow
  .github/workflows/release-21_extrinsic-ordering-check-from-two.yml
Labels: A8-backport, A0-pleasereview, B0-silent, C1-low 📌

#5830 bump transaction_version for rococo (#5760)
  runtime/rococo/src/lib.rs
Labels: A8-backport, A0-pleasereview, B0-silent, C1-low 📌

#5831 Backport of #5822: [ci] Add timeout to benchmark jobs (#5822)
  .gitlab-ci.yml
Labels: A8-backport, A0-pleasereview, B0-silent, C1-low 📌

#5829 bump transaction_version for rococo (#5760)
  runtime/rococo/src/lib.rs
Labels: A8-backport, A0-pleasereview, B0-silent, C1-low 📌

#5832 Update substrate deps
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌, E3-dependencies

#5837 Remove already executed calls to nompools MigrateToV2 migration
  runtime/kusama/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A8-backport, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5750 Remove Useless Inherent Data Provider
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5702 Companion for substrate#11523
  Cargo.lock
  runtime/parachains/src/dmp/tests.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#5838 Remove Unused Trait Bound
  runtime/common/src/impls.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5796 companion for #11821: node/service: add BEEFY to block import
  Cargo.lock
  node/service/src/lib.rs
Labels: B0-silent, A7-companion, C1-low 📌
