Repository paritytech/polkadot, pull requests merged in 2022-12, with the labels that each got.

#6354 Kusama: approve/reject treasury prop by treasurer
  runtime/kusama/src/governance/mod.rs
  runtime/kusama/src/governance/origins.rs
  runtime/kusama/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#6304 Create thread_local in XCM executor to limit recursion depth
  Cargo.lock
  runtime/test-runtime/src/lib.rs
  runtime/test-runtime/src/xcm_config.rs
  xcm/src/v3/traits.rs
  xcm/xcm-executor/Cargo.toml
  xcm/xcm-executor/integration-tests/src/lib.rs
  xcm/xcm-executor/src/lib.rs
Labels: A0-pleasereview

#6298 Add upper limit on the number of overweight messages in the queue
  runtime/kusama/src/lib.rs
  runtime/parachains/src/ump.rs
  runtime/parachains/src/ump/migration.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview

#6280 Introduce whitelist for Transact and limit UMP processing to 10 messages per block
  runtime/kusama/src/xcm_config.rs
  runtime/parachains/src/ump.rs
  runtime/polkadot/src/xcm_config.rs
  runtime/rococo/src/xcm_config.rs
  runtime/test-runtime/src/xcm_config.rs
  runtime/westend/src/xcm_config.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/xcm-builder/src/tests/mock.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-executor/src/config.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
  xcm/xcm-simulator/fuzzer/src/parachain.rs
  xcm/xcm-simulator/fuzzer/src/relay_chain.rs
Labels: A0-pleasereview

#6359 Add buckets on lower end of distribution to network bridge latency metrics
  node/network/statement-distribution/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6328 Reduce provisioner work
  Cargo.lock
  node/client/Cargo.toml
  node/client/src/benchmarking.rs
  node/core/parachains-inherent/Cargo.toml
  node/core/parachains-inherent/src/lib.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6383 update deprecated alias `--all`
  README.md
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#6262 Upgrade tokio to 1.22.0
  Cargo.lock
  Cargo.toml
  node/jaeger/Cargo.toml
  node/jaeger/src/lib.rs
  node/metrics/Cargo.toml
  node/test/service/Cargo.toml
  node/zombienet-backchannel/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/undying/collator/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/westend/Cargo.toml
  utils/remote-ext-tests/bags-list/Cargo.toml
  utils/staking-miner/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6393 Tweak some NIS params
  runtime/kusama/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#6390 Allow Root with gov2 Origins
  runtime/kusama/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#6394 Bump Substrate
  Cargo.lock
Labels: A3-inprogress, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#6397 crowdloan: Fix migration.
  runtime/common/src/crowdloan/migration.rs
  runtime/common/src/crowdloan/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6385 Companion of Substrate PR 12837
  .github/dependabot.yml
  Cargo.lock
  node/client/Cargo.toml
  node/service/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  utils/staking-miner/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#6392 Companion: kusama whitelist pallet preimage dep upgrade
  runtime/kusama/src/governance/mod.rs
  runtime/kusama/src/weights/pallet_whitelist.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6374 Companion for paritytech/substrate#12795
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  core-primitives/Cargo.toml
  core-primitives/src/lib.rs
  node/core/approval-voting/Cargo.toml
  node/core/av-store/Cargo.toml
  node/core/chain-selection/Cargo.toml
  node/core/dispute-coordinator/Cargo.toml
  node/malus/Cargo.toml
  node/overseer/Cargo.toml
  node/overseer/src/lib.rs
  node/overseer/src/memory_stats.rs
  node/overseer/src/metrics.rs
  node/service/Cargo.toml
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/database.rs
  parachain/Cargo.toml
  parachain/src/primitives.rs
  primitives/Cargo.toml
  primitives/src/v2/mod.rs
  src/main.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6381 Let the PVF host kill the worker on timeout
  node/core/pvf/src/execute/worker.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/prepare/pool.rs
  node/core/pvf/src/prepare/worker.rs
  node/core/pvf/src/worker_common.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6382 Make sure to preserve backing votes
  node/core/dispute-coordinator/src/import.rs
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/scraping/mod.rs
  node/core/dispute-coordinator/src/scraping/tests.rs
  node/core/dispute-coordinator/src/tests.rs
  node/core/provisioner/src/disputes/prioritized_selection/mod.rs
  node/core/provisioner/src/disputes/prioritized_selection/tests.rs
  node/network/dispute-distribution/src/sender/mod.rs
  node/primitives/src/disputes/mod.rs
  node/primitives/src/lib.rs
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6395 Refactoring to condense disputes tests
  node/core/dispute-coordinator/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6407 async-backing: Use real prospective parachains subsystem
  Cargo.lock
  node/core/prospective-parachains/src/lib.rs
  node/service/Cargo.toml
  node/service/src/overseer.rs
Labels: A0-pleasereview

#6107 [ci] Adjust check-runtime-migration job
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/check.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌, E1-runtimemigration

#6376 Feature gate test `benchmark_storage_works`
  tests/benchmark_storage_works.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6406 Companion for paritytech/substrate#12868
  Cargo.lock
  runtime/common/src/lib.rs
  runtime/kusama/constants/src/weights/block_weights.rs
  runtime/kusama/constants/src/weights/extrinsic_weights.rs
  runtime/kusama/constants/src/weights/paritydb_weights.rs
  runtime/kusama/constants/src/weights/rocksdb_weights.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/migration.rs
  runtime/polkadot/constants/src/weights/block_weights.rs
  runtime/polkadot/constants/src/weights/extrinsic_weights.rs
  runtime/polkadot/constants/src/weights/paritydb_weights.rs
  runtime/polkadot/constants/src/weights/rocksdb_weights.rs
  runtime/rococo/constants/src/weights/block_weights.rs
  runtime/rococo/constants/src/weights/extrinsic_weights.rs
  runtime/rococo/constants/src/weights/paritydb_weights.rs
  runtime/rococo/constants/src/weights/rocksdb_weights.rs
  runtime/test-runtime/constants/src/weights/block_weights.rs
  runtime/test-runtime/constants/src/weights/extrinsic_weights.rs
  runtime/test-runtime/constants/src/weights/paritydb_weights.rs
  runtime/test-runtime/constants/src/weights/rocksdb_weights.rs
  runtime/westend/constants/src/weights/block_weights.rs
  runtime/westend/constants/src/weights/extrinsic_weights.rs
  runtime/westend/constants/src/weights/paritydb_weights.rs
  runtime/westend/constants/src/weights/rocksdb_weights.rs
  xcm/xcm-builder/src/tests.rs
  xcm/xcm-builder/src/weight.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/fuzzer/src/parachain.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#6416 OpenGov: Tweak parameters further
  runtime/kusama/src/governance/mod.rs
  runtime/kusama/src/governance/tracks.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#6339 companion for #12663 jsonrpsee v0.16
  Cargo.lock
  rpc/Cargo.toml
  utils/staking-miner/Cargo.toml
Labels: A0-pleasereview, B1-releasenotes, A7-companion, C1-low 📌, D3-trivial 🧸

#6424 companion slash chilling update
  Cargo.lock
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/westend/src/weights/pallet_staking.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#6421 Swap HRMP Error Responses
  runtime/parachains/src/hrmp.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6425 [ci] fix check-transaction-versions
  scripts/ci/gitlab/pipeline/build.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6401 approval-distribution: batched approval/assignment sending
  node/network/approval-distribution/src/lib.rs
  node/network/approval-distribution/src/tests.rs
  node/network/protocol/src/peer_set.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#6408 Small nits for xcm-v3
  runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  xcm/pallet-xcm-benchmarks/src/generic/mod.rs
  xcm/xcm-builder/src/tests/bridging/mod.rs
  xcm/xcm-builder/src/universal_exports.rs
Labels: A0-pleasereview

#6434 add westend bootnode
  node/service/chain-specs/westend.json
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#6433 [ci] add job switcher
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/build.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6187 companion for try-runtime revamp
  Cargo.lock
  cli/Cargo.toml
  cli/src/command.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
  utils/staking-miner/src/main.rs
Labels: A0-please_review, B0-silent, C1-low 📌, D3-trivial 🧸, D2-notlive 💤

#6440 Fix wrong rate limit + add a few logs.
  node/core/approval-voting/src/lib.rs
  node/core/dispute-coordinator/src/initialized.rs
  node/network/dispute-distribution/src/sender/mod.rs
  node/network/dispute-distribution/src/sender/send_task.rs
Labels: A0-please_review, B1-releasenotes, D3-trivial 🧸, C7-high ❗️

#6451 Make sure errors get logged
  node/overseer/src/lib.rs
  node/overseer/src/tests.rs
  node/service/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6455 Adding some more logs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/bridge/src/network.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#6448 Add benchmarks for XCM pallet version migration
  runtime/kusama/src/weights/pallet_xcm.rs
  runtime/polkadot/src/weights/pallet_xcm.rs
  runtime/rococo/src/weights/pallet_xcm.rs
  runtime/westend/src/weights/pallet_xcm.rs
  xcm/pallet-xcm/src/benchmarking.rs
  xcm/pallet-xcm/src/lib.rs
Labels: A0-pleasereview

#6413 [bump] orchestra v0.0.4
  Cargo.lock
  node/overseer/Cargo.toml
  node/overseer/src/dummy.rs
  node/overseer/src/lib.rs
  node/subsystem-types/Cargo.toml
  node/subsystem-types/src/messages.rs
  node/subsystem/src/lib.rs
Labels: B0-silent, C1-low 📌

#6449 Use explicit call indices
  Cargo.lock
  runtime/common/src/assigned_slots.rs
  runtime/common/src/auctions.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan/mod.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/paras_sudo_wrapper.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots/mod.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/disputes/slashing.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras_inherent/mod.rs
  runtime/parachains/src/ump.rs
  runtime/rococo/src/validator_manager.rs
  runtime/test-runtime/src/lib.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/mock.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6457 Update Substrate to make companions work
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#6418 BlockId removal: refactor: HeaderBackend::header
  Cargo.lock
  cli/src/command.rs
  node/client/src/lib.rs
  node/core/chain-api/src/lib.rs
  node/core/chain-api/src/tests.rs
  node/core/parachains-inherent/Cargo.toml
  node/core/parachains-inherent/src/lib.rs
  node/service/src/grandpa_support.rs
  node/service/src/lib.rs
  node/test/client/src/block_builder.rs
Labels: A0-please_review, B0-silent, C1-low 📌, D3-trivial 🧸

#6384 PVF preparation: do not conflate errors
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/tests.rs
  node/core/pvf/src/error.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/prepare/pool.rs
  node/core/pvf/src/prepare/queue.rs
  node/core/pvf/src/prepare/worker.rs
  node/core/pvf/src/worker_common.rs
Labels: A0-please_review, B0-silent, C1-low 📌, D3-trivial 🧸

#6445 [ci] New try-runtime command
  scripts/ci/gitlab/pipeline/check.yml
Labels: A3-in_progress, B0-silent, C1-low 📌, E1-database_migration

#6273 Kusama origins as xcm multi_location
  runtime/kusama/src/lib.rs
  runtime/kusama/src/xcm_config.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/src/v0/junction.rs
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/origin_conversion.rs
Labels: A0-please_review, B1-releasenotes, C3-medium 📣, D9-needsaudit 👮

#6459 BlockId removal: refactor: HeaderBackend::status
  Cargo.lock
  node/client/src/lib.rs
  node/core/chain-api/src/tests.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6464 cargo update -p libp2p-yamux
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#6468 fix dependabot labels
  .github/dependabot.yml
Labels: B0-silent, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6469 CI: fix runtime-migration label detection
  scripts/ci/gitlab/pipeline/check.yml
Labels: B0-silent, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6470 Fix comments
  runtime/rococo/src/weights/xcm/mod.rs
Labels: A0-pleasereview

#6444 [Companion] Allow StakingAdmin to set min_commission
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/pallet_staking.rs
Labels: A0-please_review, B1-releasenotes, C3-medium 📣, D3-trivial 🧸

#6460 Note that backing votes are always supplied in provisioner dispute set
  node/core/provisioner/src/disputes/prioritized_selection/mod.rs
Labels: B0-silent, C1-low 📌, A0-pleasereview

#6481 Runtime diagnostics for leaked messages in unbounded channels (part 2)
  Cargo.lock
Labels: A0-please_review, B0-silent, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6329 Update disputes subsytems section.
  roadmap/implementers-guide/src/node/disputes/README.md
Labels: A2-insubstantial, A0-please_review, B0-silent, C1-low 📌, D3-trivial 🧸

#6303 Update dispute participation on active leaves update
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/participation/mod.rs
  node/core/dispute-coordinator/src/participation/queues/mod.rs
  node/core/dispute-coordinator/src/scraping/mod.rs
  node/core/dispute-coordinator/src/tests.rs
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
Labels: A0-please_review, B0-silent, C1-low 📌
