Repository paritytech/polkadot, pull requests merged in 2022-02, with the labels that each got.

#4824 Update Crowdloan Account to FundIndex
  runtime/common/src/crowdloan.rs
  runtime/common/src/integration_tests.rs
Labels: A0-pleasereview

#4826 [ci] Fix docker credentials
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4830 reduce conservative upper bound
  node/core/provisioner/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4833 feat(cicd): expire artifacts after 7 days
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4831 Bump transaction_version for polkadot, kusama, & westend
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#4828 Bump substrate
  Cargo.lock
Labels: A3-inprogress, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4836 Same than #4832 but signed
  .gitlab-ci.yml
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#4821 Add tests to ensure session is set correctly in `OnChainScrapingVotes`
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/paras_inherent/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4834 [chore] runtime split tests
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/tests.rs
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/disputes/tests.rs
  runtime/parachains/src/dmp.rs
  runtime/parachains/src/dmp/tests.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/hrmp/tests.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/initializer/tests.rs
  runtime/parachains/src/scheduler.rs
  runtime/parachains/src/scheduler/tests.rs
  runtime/parachains/src/session_info.rs
  runtime/parachains/src/session_info/tests.rs
  runtime/parachains/src/shared.rs
  runtime/parachains/src/shared/tests.rs
  runtime/parachains/src/ump.rs
  runtime/parachains/src/ump/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4843 [ci] revert #4779
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4844 Add a few items to the release checklist and move the doc away
  .github/ISSUE_TEMPLATE/release.md
  doc/release-checklist.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4840 allow overseer to be enabled anyways
  node/service/src/lib.rs
  node/test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4716 staking miner: spawn separate task for each block
  Cargo.lock
  utils/staking-miner/Cargo.toml
  utils/staking-miner/README.md
  utils/staking-miner/src/main.rs
  utils/staking-miner/src/monitor.rs
  utils/staking-miner/src/rpc_helpers.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4855 [ci] Fix scheduled pipeline
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4858 Forward `enable_overseer_always`
  cli/src/command.rs
  node/service/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4825 collation-generation: Support compressed PoVs directly
  node/collation-generation/src/lib.rs
  node/collation-generation/src/tests.rs
  node/primitives/src/lib.rs
  parachain/test-parachains/adder/collator/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4854 Ignore redundant dispute messages
  node/core/dispute-coordinator/src/real/initialized.rs
  node/core/dispute-coordinator/src/real/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#4857 rm unused deps
  Cargo.lock
  parachain/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4873 remove upgrade test
  .gitlab-ci.yml
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌

#4877 Remove `node-primitives`
  Cargo.lock
  Cargo.toml
  tests/common.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4859 Zombienet: add disputes test
  .gitlab-ci.yml
  zombienet_tests/functional/0002-parachains-disputes.feature
  zombienet_tests/functional/0002-parachains-disputes.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4753 Create a more rigid overseer builder pattern that fails at compile time
  bridges/bin/rialto/node/src/overseer.rs
  node/overseer/overseer-gen/README.md
  node/overseer/overseer-gen/examples/dummy.rs
  node/overseer/overseer-gen/proc-macro/src/impl_builder.rs
  node/overseer/overseer-gen/proc-macro/src/parse_struct.rs
  node/overseer/overseer-gen/src/tests.rs
  node/overseer/overseer-gen/tests/ui/err-01-duplicate-consumer.stderr
  node/overseer/overseer-gen/tests/ui/err-05-missing-field.rs
  node/overseer/overseer-gen/tests/ui/err-05-missing-field.stderr
  node/overseer/overseer-gen/tests/ui/err-06-missing-subsystem.rs
  node/overseer/overseer-gen/tests/ui/err-06-missing-subsystem.stderr
  node/overseer/overseer-gen/tests/ui/err-07-missing-spawner.rs
  node/overseer/overseer-gen/tests/ui/err-07-missing-spawner.stderr
  node/overseer/overseer-gen/tests/ui/err-08-duplicate-subsystem.rs
  node/overseer/overseer-gen/tests/ui/err-08-duplicate-subsystem.stderr
  node/overseer/overseer-gen/tests/ui/err-09-uninit_generic_baggage.rs
  node/overseer/overseer-gen/tests/ui/err-09-uninit_generic_baggage.stderr
  node/overseer/overseer-gen/tests/ui/ok-01-wip.rs
  node/overseer/src/dummy.rs
  node/service/src/overseer.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4881 Companion to Substrate #10786
  Cargo.lock
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/westend/src/weights/pallet_staking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4901 Zombienet: increase smoke test log verbosity
  zombienet_tests/parachains/0001-parachains-smoke-test.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4909 collator-protocol: fix wrong warning
  node/network/collator-protocol/src/collator_side/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4905 statement-distribution: add more specific rep change reasons
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4896 Baseline weights for `force_apply_min_commission`
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/westend/src/weights/pallet_staking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4851 Add proxy type for Kappa Sigma Mu
  runtime/kusama/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#4848 Remove stale migrations post 9.16 release
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4920 Companion for `Remove u32_trait`
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4918 Companion for #10832
  Cargo.lock
  rpc/src/lib.rs
Labels: A2-insubstantial, B0-silent, A7-companion, C1-low 📌

#4907 update digest to v0.10.2
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4928 Companion CI: Make sure to pass the update crates properly
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#4927 Companion for refactor election score #10834
  Cargo.lock
  utils/staking-miner/src/dry_run.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌

#4932 corrected parachain code validation events description
  runtime/parachains/src/paras/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4845 Better spam slots handling
  node/core/dispute-coordinator/src/real/initialized.rs
  node/core/dispute-coordinator/src/real/spam_slots.rs
  node/core/dispute-coordinator/src/real/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#4914 Revert "collator-protocol: short-term fixes for connectivity (#4640)"
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/collator-protocol/src/lib.rs
Labels: A1-onice, B1-releasenotes, C1-low 📌

#4790 inclusion emulator logic for asynchronous backing
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/inclusion_emulator/mod.rs
  node/subsystem-util/src/inclusion_emulator/staging.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/runtime/mod.rs
  primitives/src/lib.rs
  primitives/src/v2/mod.rs
  primitives/src/vstaging/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#4955 bump transaction_version
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4956 bump transaction_version
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4965 Bump `tokio` to 1.17.0
  Cargo.lock
  Cargo.toml
  node/metrics/Cargo.toml
  node/test/service/Cargo.toml
  node/zombienet-backchannel/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  utils/remote-ext-tests/bags-list/Cargo.toml
  utils/staking-miner/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4871 add pyroscope
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/cli.rs
  cli/src/command.rs
  cli/src/error.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4934 paras: `initialize_para_now` and `ParachainsCache`
  runtime/parachains/src/hrmp/benchmarking.rs
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4970 feat: decrese the validity for biggest artifacts
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4908 approval-distribution: a fix for out-of-view messages
  node/network/approval-distribution/src/lib.rs
  roadmap/implementers-guide/src/node/approval/approval-distribution.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4957 Use only fresh DisputeStatement-s for dispute spam detection (#4921)
  node/core/dispute-coordinator/src/real/initialized.rs
Labels: B0-silent, C1-low 📌

#4940 Companion for substrate#10878
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#4974 introduce expander
  Cargo.lock
  node/overseer/Cargo.toml
  node/overseer/overseer-gen/Cargo.toml
  node/overseer/overseer-gen/README.md
  node/overseer/overseer-gen/proc-macro/Cargo.toml
  node/overseer/overseer-gen/proc-macro/build.rs
  node/overseer/overseer-gen/proc-macro/src/lib.rs
Labels: F6-refactor, A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4980 Fix docker release workflow
  .github/workflows/publish-docker-release.yml
  scripts/dockerfiles/polkadot_injected_release.Dockerfile
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4981 Add manual dispatch trigger for docker builds
  .github/workflows/publish-docker-manual.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4988 Try to fix disputes test
  node/malus/Cargo.toml
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#4989 do not allow zombienet tests to fail
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4448 fatality based errors
  Cargo.lock
  node/core/dispute-coordinator/Cargo.toml
  node/core/dispute-coordinator/src/dummy.rs
  node/core/dispute-coordinator/src/error.rs
  node/core/dispute-coordinator/src/real/db/v1.rs
  node/core/dispute-coordinator/src/real/initialized.rs
  node/core/dispute-coordinator/src/real/mod.rs
  node/core/dispute-coordinator/src/real/ordering/mod.rs
  node/core/dispute-coordinator/src/real/participation/mod.rs
  node/core/dispute-coordinator/src/real/participation/queues/mod.rs
  node/core/dispute-coordinator/src/real/participation/queues/tests.rs
  node/core/dispute-coordinator/src/real/spam_slots.rs
  node/core/parachains-inherent/src/lib.rs
  node/network/availability-distribution/Cargo.toml
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/pov_requester/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/requester/mod.rs
  node/network/availability-distribution/src/requester/session_cache.rs
  node/network/availability-distribution/src/responder.rs
  node/network/availability-recovery/Cargo.toml
  node/network/availability-recovery/src/lib.rs
  node/network/collator-protocol/Cargo.toml
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/error.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/dispute-distribution/Cargo.toml
  node/network/dispute-distribution/src/error.rs
  node/network/dispute-distribution/src/lib.rs
  node/network/dispute-distribution/src/receiver/error.rs
  node/network/dispute-distribution/src/receiver/mod.rs
  node/network/dispute-distribution/src/sender/error.rs
  node/network/dispute-distribution/src/sender/mod.rs
  node/network/dispute-distribution/src/sender/send_task.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/request_response/incoming/error.rs
  node/network/protocol/src/request_response/incoming/mod.rs
  node/network/protocol/src/request_response/outgoing.rs
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/error.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/responder.rs
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/runtime/error.rs
  node/subsystem-util/src/runtime/mod.rs
  tests/common.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, A1-needsburnin

#4982 Co #10897: Storage benchmarking
  Cargo.lock
  cli/src/cli.rs
  cli/src/command.rs
Labels: A0-pleasereview, B1-releasenotes, A7-companion, C1-low 📌

#4972 Add metrics for out of view statement distribution errors
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/metrics.rs
  node/network/statement-distribution/src/requester.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#3889 Add benchmarking for parachain runtime `ump` pallet
  bridges/bin/rialto/node/src/chain_spec.rs
  node/service/src/chain_spec.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/runtime_parachains_ump.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/ump.rs
  runtime/parachains/src/ump/benchmarking.rs
  runtime/parachains/src/ump/tests.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/weights/mod.rs
  runtime/rococo/src/weights/runtime_parachains_ump.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/runtime_parachains_ump.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
  xcm/xcm-simulator/fuzzer/src/relay_chain.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4861 [WIP] Companion PR for sr25519 fallible constructor
  Cargo.lock
  runtime/common/src/purchase.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#5005 Fix master build
  parachain/test-parachains/undying/Cargo.toml
  parachain/test-parachains/undying/collator/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌
