Repository paritytech/polkadot, pull requests merged in 2022-09, with the labels that each got.

#5950 Don't store available data on disputes
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/participation/mod.rs
  node/core/dispute-coordinator/src/participation/queues/mod.rs
  node/core/dispute-coordinator/src/participation/queues/tests.rs
  node/core/dispute-coordinator/src/participation/tests.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#5907 companion `try-state`
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  utils/remote-ext-tests/bags-list/src/main.rs
  xcm/pallet-xcm/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#5936 [Feature] Make XCM benchmarks more reusable and remove a redundant bench
  xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5957 candidate-validation: info logs on failure
  node/core/candidate-validation/src/lib.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#5959 Reflect benchmarking fn signature change
  Cargo.lock
  cli/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5963 Use custom type for ProtocolName
  Cargo.lock
  node/network/bridge/src/network.rs
  node/network/bridge/src/rx/tests.rs
  node/network/bridge/src/tx/tests.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/protocol/src/peer_set.rs
  node/network/protocol/src/request_response/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5967 Doc comments for metrics in provisioner
  node/core/provisioner/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸, T2-Parachains-Protocol

#5951 Double approval checking timeout.
  node/primitives/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5842 Companion - Read babe config parameters from runtime
  Cargo.lock
  node/core/runtime-api/src/tests.rs
  node/service/src/lib.rs
  rpc/src/lib.rs
  runtime/kusama/constants/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/constants/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/constants/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/constants/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/constants/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#5968 Companion for: `try-runtime`::`follow-chain` - keep connection
  Cargo.lock
  tests/common.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5955 [Companion] Metadata delete on dissolve_pool
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#5711 provisioner: async backing changes
  node/core/provisioner/src/error.rs
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/tests.rs
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5971 Companion for paritytech/substrate#12183
  Cargo.lock
  runtime/kusama/constants/src/weights/block_weights.rs
  runtime/kusama/constants/src/weights/extrinsic_weights.rs
  runtime/kusama/constants/src/weights/paritydb_weights.rs
  runtime/kusama/constants/src/weights/rocksdb_weights.rs
  runtime/kusama/src/tests.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras_inherent/mod.rs
  runtime/parachains/src/paras_inherent/tests.rs
  runtime/parachains/src/ump.rs
  runtime/polkadot/constants/src/weights/block_weights.rs
  runtime/polkadot/constants/src/weights/extrinsic_weights.rs
  runtime/polkadot/constants/src/weights/paritydb_weights.rs
  runtime/polkadot/constants/src/weights/rocksdb_weights.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/constants/src/weights/block_weights.rs
  runtime/rococo/constants/src/weights/extrinsic_weights.rs
  runtime/rococo/constants/src/weights/paritydb_weights.rs
  runtime/rococo/constants/src/weights/rocksdb_weights.rs
  runtime/test-runtime/constants/src/weights/block_weights.rs
  runtime/test-runtime/constants/src/weights/extrinsic_weights.rs
  runtime/test-runtime/constants/src/weights/paritydb_weights.rs
  runtime/test-runtime/constants/src/weights/rocksdb_weights.rs
  runtime/westend/constants/src/weights/block_weights.rs
  runtime/westend/constants/src/weights/extrinsic_weights.rs
  runtime/westend/constants/src/weights/paritydb_weights.rs
  runtime/westend/constants/src/weights/rocksdb_weights.rs
  runtime/westend/src/tests.rs
  xcm/pallet-xcm/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#5966 Service: Use weak dependency features
  node/service/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#5981 Update Substrate
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5617 Update Rococo to mirror Kusama
  Cargo.lock
  node/service/src/chain_spec.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/xcm_config.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/constants/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/weights/frame_benchmarking_baseline.rs
  runtime/rococo/src/weights/mod.rs
  runtime/rococo/src/weights/pallet_bounties.rs
  runtime/rococo/src/weights/pallet_child_bounties.rs
  runtime/rococo/src/weights/pallet_collective_council.rs
  runtime/rococo/src/weights/pallet_collective_technical_committee.rs
  runtime/rococo/src/weights/pallet_democracy.rs
  runtime/rococo/src/weights/pallet_elections_phragmen.rs
  runtime/rococo/src/weights/pallet_gilt.rs
  runtime/rococo/src/weights/pallet_identity.rs
  runtime/rococo/src/weights/pallet_preimage.rs
  runtime/rococo/src/weights/pallet_scheduler.rs
  runtime/rococo/src/weights/pallet_session.rs
  runtime/rococo/src/weights/pallet_tips.rs
  runtime/rococo/src/weights/pallet_treasury.rs
  runtime/rococo/src/weights/pallet_vesting.rs
  runtime/rococo/src/weights/runtime_common_claims.rs
  runtime/rococo/src/weights/xcm/mod.rs
  runtime/rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  runtime/rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  runtime/rococo/src/xcm_config.rs
  scripts/ci/gitlab/lingua.dic
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#5977 pvf-checker: enable subsystem on all chains
  node/service/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#5862 disputes rewards
  runtime/kusama/src/lib.rs
  runtime/parachains/src/reward_points.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️, T2-Parachains-Protocol

#5855 zombienet: add BEEFY justifications import test
  zombienet_tests/functional/0003-beefy-and-mmr.feature
  zombienet_tests/functional/0003-beefy-and-mmr.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5969 remove stale polkadot call filter
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5991 Network bridge changes for asynchronous backing + update subsystems to handle versioned packets
  Cargo.lock
  node/core/backing/src/tests/mod.rs
  node/network/approval-distribution/src/lib.rs
  node/network/approval-distribution/src/tests.rs
  node/network/bitfield-distribution/Cargo.toml
  node/network/bitfield-distribution/src/lib.rs
  node/network/bitfield-distribution/src/tests.rs
  node/network/bridge/src/network.rs
  node/network/bridge/src/rx/mod.rs
  node/network/bridge/src/rx/tests.rs
  node/network/bridge/src/tx/mod.rs
  node/network/bridge/src/tx/tests.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/gossip-support/src/lib.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/lib.rs
  node/network/protocol/src/peer_set.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#5985 Update Westend Trusted Teleporters
  runtime/westend/src/xcm_config.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#5994 Update cid to 0.8.6
  Cargo.lock
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌

#5986 Remove CanAuthorWith trait
  Cargo.lock
  node/service/src/lib.rs
  node/test/service/src/lib.rs
Labels: A3-inprogress, B0-silent, C1-low 📌, D3-trivial 🧸

#5987 Companion for paritytech/substrate#12219
  Cargo.lock
  runtime/common/src/auctions.rs
  runtime/common/src/claims.rs
  runtime/common/src/impls.rs
  runtime/common/src/lib.rs
  runtime/kusama/src/tests.rs
  runtime/polkadot/src/lib.rs
  xcm/pallet-xcm-benchmarks/src/generic/mod.rs
  xcm/xcm-builder/src/mock.rs
  xcm/xcm-builder/src/weight.rs
  xcm/xcm-executor/src/config.rs
  xcm/xcm-executor/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#5983 Co #11976: Enable rust features
  Cargo.lock
  cli/src/command.rs
  node/service/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/westend/Cargo.toml
  xcm/pallet-xcm-benchmarks/Cargo.toml
Labels: A8-mergeoncegreen, B0-silent, C1-low 📌, D3-trivial 🧸

#6014 remove max_pov_size requirement from prospective pvd request
  node/core/prospective-parachains/src/lib.rs
  node/subsystem-types/src/messages.rs
Labels: A0-pleasereview

#6016 node/core/pvf: strip some deps
  Cargo.lock
  node/core/pvf/Cargo.toml
  node/core/pvf/src/metrics.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#6019 Bump blake2 from 0.10.2 to 0.10.4
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5930 [Substrate Companion] Part 1: add TargetList for validator ranking
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#5984 Use correct file header for `benchmark overhead`
  scripts/ci/run_benches_for_runtime.sh
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#6024 gossip-support: disconnect when we're no longer in other's reserved set
  node/network/gossip-support/src/lib.rs
  node/network/gossip-support/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5567 Improved dispute votes import in provisioner
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  node/core/dispute-coordinator/src/db/v1.rs
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/status.rs
  node/core/dispute-coordinator/src/tests.rs
  node/core/provisioner/Cargo.toml
  node/core/provisioner/src/disputes/mod.rs
  node/core/provisioner/src/disputes/prioritized_selection/mod.rs
  node/core/provisioner/src/disputes/prioritized_selection/tests.rs
  node/core/provisioner/src/disputes/random_selection/mod.rs
  node/core/provisioner/src/error.rs
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/metrics.rs
  node/core/provisioner/src/onchain_disputes.rs
  node/core/provisioner/src/tests.rs
  node/core/runtime-api/src/cache.rs
  node/core/runtime-api/src/lib.rs
  node/core/runtime-api/src/tests.rs
  node/network/approval-distribution/Cargo.toml
  node/network/approval-distribution/src/tests.rs
  node/primitives/src/disputes/mod.rs
  node/primitives/src/disputes/status.rs
  node/primitives/src/lib.rs
  node/service/Cargo.toml
  node/subsystem-types/src/messages.rs
  node/subsystem-types/src/runtime_client.rs
  primitives/src/lib.rs
  primitives/src/runtime_api.rs
  primitives/src/vstaging/mod.rs
  primitives/test-helpers/Cargo.toml
  primitives/test-helpers/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/runtime_api_impl/mod.rs
  runtime/parachains/src/runtime_api_impl/vstaging.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D9-needsaudit 👮

#6028 [ci] Revert cancel-pipeline job
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5970 [Zombienet] add upgrade test
  .gitlab-ci.yml
  zombienet_tests/misc/0002-download-polkadot-from-pr.sh
  zombienet_tests/misc/0002-upgrade-node.feature
  zombienet_tests/misc/0002-upgrade-node.toml
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌

#6020 Rename Origin
  Cargo.lock
  runtime/common/src/assigned_slots.rs
  runtime/common/src/auctions.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan/mod.rs
  runtime/common/src/impls.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots/mod.rs
  runtime/kusama/src/governance/old.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/xcm_config.rs
  runtime/parachains/src/configuration/tests.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/hrmp/benchmarking.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras/tests.rs
  runtime/parachains/src/session_info/tests.rs
  runtime/parachains/src/ump.rs
  runtime/parachains/src/ump/tests.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/xcm_config.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/validator_manager.rs
  runtime/rococo/src/xcm_config.rs
  runtime/test-runtime/src/lib.rs
  runtime/test-runtime/src/xcm_config.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/xcm_config.rs
  xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  xcm/pallet-xcm-benchmarks/src/generic/mod.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/pallet-xcm/src/tests.rs
  xcm/xcm-builder/src/mock.rs
  xcm/xcm-builder/src/origin_conversion.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-executor/src/config.rs
  xcm/xcm-simulator/example/src/lib.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
  xcm/xcm-simulator/fuzzer/src/parachain.rs
  xcm/xcm-simulator/fuzzer/src/relay_chain.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸

#6034 Change visibility of `open_database` for use in cumulus
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6038 Companion for #12283 (Anon -> Pure Proxy)
  Cargo.lock
  runtime/kusama/src/weights/pallet_proxy.rs
  runtime/polkadot/src/weights/pallet_proxy.rs
  runtime/rococo/src/weights/pallet_proxy.rs
  runtime/westend/src/weights/pallet_proxy.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#6037 Increase BlockHashCount parameter
  runtime/common/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#6026 Extract legacy statement distribution to its own module
  node/core/backing/src/lib.rs
  node/core/backing/src/tests/mod.rs
  node/core/backing/src/tests/prospective_parachains.rs
  node/network/bridge/src/rx/tests.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/protocol/src/lib.rs
  node/network/statement-distribution/src/legacy_v1/mod.rs
  node/network/statement-distribution/src/legacy_v1/requester.rs
  node/network/statement-distribution/src/legacy_v1/responder.rs
  node/network/statement-distribution/src/legacy_v1/tests.rs
  node/network/statement-distribution/src/lib.rs
  node/overseer/src/tests.rs
  node/primitives/src/lib.rs
  node/subsystem-types/src/messages.rs
  roadmap/implementers-guide/src/node/backing/candidate-backing.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-pleasereview

#6006 Some more information on disputes for the guide
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5997 Companion - Independence of Slot-based algorithms from Timestamp
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5992 Companion for substrate#11983.
  Cargo.lock
  node/test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6031 [ci] Split gitlab-ci config to separate files
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/check.yml
  scripts/ci/gitlab/pipeline/publish.yml
  scripts/ci/gitlab/pipeline/short-benchmarks.yml
  scripts/ci/gitlab/pipeline/test.yml
  scripts/ci/gitlab/pipeline/weights.yml
  scripts/ci/gitlab/pipeline/zombienet.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5973 Companion for paritytech/substrate#12264
  .gitlab-ci.yml
  Cargo.lock
  node/network/protocol/Cargo.toml
  node/network/protocol/src/peer_set.rs
  node/service/src/lib.rs
  node/test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#6032 paras: unblock offboarding when pvf-check concludes
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#6051 [orchestra] fix: require the initialization with `F: FnOnce` to be `Send`
  node/orchestra/examples/solo.rs
  node/orchestra/proc-macro/src/impl_builder.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#6004 staking miner: CLI make request and connection timeout configurable
  utils/staking-miner/src/main.rs
  utils/staking-miner/src/opts.rs
  utils/staking-miner/src/rpc.rs
Labels: B0-silent, C1-low 📌

#6059 make spellcheck green again
  node/core/provisioner/src/disputes/mod.rs
  node/core/provisioner/src/disputes/prioritized_selection/mod.rs
  node/core/provisioner/src/disputes/random_selection/mod.rs
  node/primitives/src/disputes/status.rs
  node/subsystem-types/src/messages.rs
  primitives/src/runtime_api.rs
  runtime/parachains/src/runtime_api_impl/mod.rs
Labels: A3-inprogress, A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#6056 Remove executed runtime migrations (nompools MigrateToV3, InitiateNominationPools)
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6050 add fast-unstsake pallet to all runtimes
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_fast_unstake.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_fast_unstake.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/pallet_fast_unstake.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#6055 Fix tests
  node/core/backing/src/lib.rs
  node/core/backing/src/tests/prospective_parachains.rs
  node/core/provisioner/src/lib.rs
Labels: A0-pleasereview

#6073 Rename zombienet extension
  node/malus/README.md
  node/malus/integrationtests/0001-dispute-valid-block.zndsl
  scripts/ci/gitlab/pipeline/zombienet.yml
  zombienet_tests/README.md
  zombienet_tests/functional/0001-parachains-pvf.zndsl
  zombienet_tests/functional/0002-parachains-disputes.zndsl
  zombienet_tests/functional/0003-beefy-and-mmr.zndsl
  zombienet_tests/functional/0003-parachains-garbage-candidate.zndsl
  zombienet_tests/misc/0001-paritydb.zndsl
  zombienet_tests/misc/0002-download-polkadot-from-pr.sh
  zombienet_tests/misc/0002-upgrade-node.zndsl
  zombienet_tests/smoke/0001-parachains-smoke-test.zndsl
  zombienet_tests/smoke/0002-parachains-upgrade-smoke-test.zndsl
  zombienet_tests/smoke/0003-deregister-register-validator-smoke.zndsl
Labels: A0-pleasereview, B0-silent, C1-low 📌

#6062 [zombienet] add nominators
  .gitlab-ci.yml
  runtime/kusama/src/lib.rs
  zombienet_tests/functional/0004-slashing.toml
Labels: F4-tests, A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#6078 Validate chunks from disk in availability-recovery
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6080 Demote warning
  node/core/provisioner/src/lib.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#6084 Log `para_id` when fetching PoV
  node/core/backing/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/pov_requester/mod.rs
  node/subsystem-types/src/messages.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#6075 [Migration] Refund stored multisig calls
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, D9-needsaudit 👮
