Repository paritytech/polkadot, pull requests merged in 2022-03, with the labels that each got.

#4993 add disputes pallet to Polkadot
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/runtime_parachains_disputes.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#5003 dispute-distribution: downgrade a warn
  node/network/dispute-distribution/src/receiver/error.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4975 Update dispute-coordinator documentation
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
Labels: B0-silent, C1-low 📌

#4823 Add MaxUnlockingChunks to staking configs; Companion to #10670
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5015 ci: Add rococo to release pipeline
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/publish-draft-release.yml
  scripts/changelog/bin/changelog
  scripts/github/generate_release_text.rb
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌

#4786 Runtime changes for Asynchronous Backing
  roadmap/implementers-guide/src/runtime/dmp.md
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/parainherent.md
  roadmap/implementers-guide/src/runtime/paras.md
  roadmap/implementers-guide/src/runtime/scheduler.md
  roadmap/implementers-guide/src/runtime/shared.md
  runtime/kusama/src/weights/runtime_parachains_paras.rs
  runtime/parachains/src/dmp.rs
  runtime/parachains/src/dmp/tests.rs
  runtime/parachains/src/inclusion/mod.rs
  runtime/parachains/src/inclusion/tests.rs
  runtime/parachains/src/paras/benchmarking.rs
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras/tests.rs
  runtime/parachains/src/paras_inherent/mod.rs
  runtime/parachains/src/paras_inherent/tests.rs
  runtime/parachains/src/runtime_api_impl/v1.rs
  runtime/parachains/src/scheduler.rs
  runtime/parachains/src/scheduler/migration.rs
  runtime/parachains/src/scheduler/tests.rs
  runtime/parachains/src/shared.rs
  runtime/polkadot/src/weights/runtime_parachains_paras.rs
  runtime/rococo/src/weights/runtime_parachains_paras.rs
  runtime/westend/src/weights/runtime_parachains_paras.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D1-audited 👍

#4995 Remove balancing iterations from OCW miners
  runtime/common/src/elections.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
  utils/staking-miner/src/dry_run.rs
  utils/staking-miner/src/main.rs
  utils/staking-miner/src/signer.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D9-needsaudit 👮

#5018 Revise how staking configurations are set
  Cargo.lock
  runtime/kusama/src/weights/pallet_staking.rs
  runtime/polkadot/src/weights/pallet_staking.rs
  runtime/westend/src/weights/pallet_staking.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#4838 paritydb support for parachains db.
  Cargo.lock
  node/core/approval-voting/src/approval_db/v1/mod.rs
  node/core/approval-voting/src/approval_db/v1/tests.rs
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/core/chain-selection/src/db_backend/v1.rs
  node/core/chain-selection/src/lib.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/real/db/v1.rs
  node/core/dispute-coordinator/src/real/mod.rs
  node/core/dispute-coordinator/src/real/tests.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/service/src/parachains_db/mod.rs
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/database.rs
  node/subsystem-util/src/lib.rs
  tests/purge_chain_works.rs
Labels: B1-releasenotes, C1-low 📌

#5025 Fix fast-runtime
  runtime/polkadot/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#5024 [staking miner]: add CLI tests + fix `--version`
  Cargo.lock
  utils/staking-miner/Cargo.toml
  utils/staking-miner/src/main.rs
  utils/staking-miner/tests/cli.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4819 staking miner: Check the queue one last time before submission
  utils/staking-miner/Cargo.toml
  utils/staking-miner/src/main.rs
  utils/staking-miner/src/monitor.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4837 Companion PR for storage changes
  Cargo.lock
  node/test/service/src/lib.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#5032 Add UmpSink Config
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#5033 Companion for Substrate#10915
  Cargo.lock
  bridges/fuzz/storage-proof/src/main.rs
  bridges/primitives/runtime/src/storage_proof.rs
  bridges/relays/client-substrate/src/client.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#5041 [ci] fix test-node-metrics dependency
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4923 Add missing XCM benchmarks for ReserveAssetDeposited
  file_header.txt
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/xcm/mod.rs
  runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  xcm/pallet-xcm-benchmarks/src/fungible/benchmarking.rs
  xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  xcm/pallet-xcm-benchmarks/src/fungible/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5016 Improve parachain liveness by reducing required number of backing votes
  node/core/backing/src/lib.rs
  node/core/backing/src/tests.rs
  runtime/parachains/src/inclusion/mod.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, D3-trivial 🧸

#4756 XCM v3: Context & ID hash
  Cargo.lock
  bridges/bin/rialto-parachain/runtime/src/lib.rs
  runtime/common/src/xcm_sender.rs
  runtime/parachains/src/ump.rs
  runtime/test-runtime/src/xcm_config.rs
  runtime/westend/src/weights/xcm/mod.rs
  runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  xcm/Cargo.toml
  xcm/pallet-xcm-benchmarks/Cargo.toml
  xcm/pallet-xcm-benchmarks/src/fungible/benchmarking.rs
  xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  xcm/pallet-xcm-benchmarks/src/lib.rs
  xcm/pallet-xcm-benchmarks/src/mock.rs
  xcm/pallet-xcm/Cargo.toml
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/pallet-xcm/src/tests.rs
  xcm/src/v3/mod.rs
  xcm/src/v3/traits.rs
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-builder/src/currency_adapter.rs
  xcm/xcm-builder/src/fungibles_adapter.rs
  xcm/xcm-builder/src/nonfungibles_adapter.rs
  xcm/xcm-builder/src/test_utils.rs
  xcm/xcm-builder/src/tests/assets.rs
  xcm/xcm-builder/src/tests/basic.rs
  xcm/xcm-builder/src/tests/bridging/local_para_para.rs
  xcm/xcm-builder/src/tests/bridging/local_relay_relay.rs
  xcm/xcm-builder/src/tests/bridging/mod.rs
  xcm/xcm-builder/src/tests/bridging/paid_remote_relay_relay.rs
  xcm/xcm-builder/src/tests/bridging/remote_para_para.rs
  xcm/xcm-builder/src/tests/bridging/remote_para_para_via_relay.rs
  xcm/xcm-builder/src/tests/bridging/remote_relay_relay.rs
  xcm/xcm-builder/src/tests/expecting.rs
  xcm/xcm-builder/src/tests/locking.rs
  xcm/xcm-builder/src/tests/mock.rs
  xcm/xcm-builder/src/tests/origins.rs
  xcm/xcm-builder/src/tests/querying.rs
  xcm/xcm-builder/src/tests/transacting.rs
  xcm/xcm-builder/src/tests/version_subscriptions.rs
  xcm/xcm-builder/src/tests/weight.rs
  xcm/xcm-builder/src/universal_exports.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-builder/tests/scenarios.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/drop_assets.rs
  xcm/xcm-executor/src/traits/export.rs
  xcm/xcm-executor/src/traits/on_response.rs
  xcm/xcm-executor/src/traits/transact_asset.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/fuzzer/src/parachain.rs
  xcm/xcm-simulator/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5063 chore: make debug log less noisy
  node/core/bitfield-signing/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5068 bump transaction_version
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5065 Use updated bags list: Companion to #10997
  Cargo.lock
  bridges/bin/rialto-parachain/runtime/src/lib.rs
  runtime/common/src/elections.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/xcm_config.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/xcm_config.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#5074 bump transaction_version
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5077 [ci] fix test-node-metrics dependency (#5041)
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5066 [ci] cancel pipeline if test-linux-stable fail
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5067 update mick jaeger and add some sanity unit tests
  Cargo.lock
  node/jaeger/Cargo.toml
  node/jaeger/src/lib.rs
  node/jaeger/src/spans.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5030 Add babe randomness to well known keys
  primitives/src/v2/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5071 Check signatures as "Compact" in statement distribution
  node/network/protocol/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/tests.rs
  primitives/src/v2/mod.rs
  primitives/src/v2/signed.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#4850 availability-distribution: fix session index lookup for activated leaves
  node/network/availability-distribution/src/requester/mod.rs
  node/network/availability-distribution/src/requester/session_cache.rs
  node/network/availability-distribution/src/tests/state.rs
Labels: F2-bug, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5064 Runtime dependent weights
  Cargo.lock
  node/test/service/Cargo.toml
  node/test/service/src/lib.rs
  runtime/common/src/elections.rs
  runtime/common/src/lib.rs
  runtime/kusama/constants/src/lib.rs
  runtime/kusama/constants/src/weights/block_weights.rs
  runtime/kusama/constants/src/weights/extrinsic_weights.rs
  runtime/kusama/constants/src/weights/mod.rs
  runtime/kusama/constants/src/weights/paritydb_weights.rs
  runtime/kusama/constants/src/weights/rocksdb_weights.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/tests.rs
  runtime/polkadot/constants/src/lib.rs
  runtime/polkadot/constants/src/weights/block_weights.rs
  runtime/polkadot/constants/src/weights/extrinsic_weights.rs
  runtime/polkadot/constants/src/weights/mod.rs
  runtime/polkadot/constants/src/weights/paritydb_weights.rs
  runtime/polkadot/constants/src/weights/rocksdb_weights.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/constants/src/lib.rs
  runtime/rococo/constants/src/weights/block_weights.rs
  runtime/rococo/constants/src/weights/extrinsic_weights.rs
  runtime/rococo/constants/src/weights/mod.rs
  runtime/rococo/constants/src/weights/paritydb_weights.rs
  runtime/rococo/constants/src/weights/rocksdb_weights.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/constants/src/lib.rs
  runtime/test-runtime/constants/src/weights/block_weights.rs
  runtime/test-runtime/constants/src/weights/extrinsic_weights.rs
  runtime/test-runtime/constants/src/weights/mod.rs
  runtime/test-runtime/constants/src/weights/paritydb_weights.rs
  runtime/test-runtime/constants/src/weights/rocksdb_weights.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/constants/src/lib.rs
  runtime/westend/constants/src/weights/block_weights.rs
  runtime/westend/constants/src/weights/extrinsic_weights.rs
  runtime/westend/constants/src/weights/mod.rs
  runtime/westend/constants/src/weights/paritydb_weights.rs
  runtime/westend/constants/src/weights/rocksdb_weights.rs
  runtime/westend/src/lib.rs
Labels: F6-refactor, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5092 Remove InvertLocation trait
  bridges/bin/rialto-parachain/runtime/src/lib.rs
  runtime/kusama/src/xcm_config.rs
  runtime/polkadot/src/xcm_config.rs
  runtime/rococo/src/xcm_config.rs
  runtime/test-runtime/src/lib.rs
  runtime/test-runtime/src/xcm_config.rs
  runtime/westend/src/xcm_config.rs
  xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/src/v3/junctions.rs
  xcm/src/v3/multiasset.rs
  xcm/src/v3/multilocation.rs
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/location_conversion.rs
  xcm/xcm-builder/src/test_utils.rs
  xcm/xcm-builder/src/tests/mock.rs
  xcm/xcm-builder/src/universal_exports.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-executor/src/assets.rs
  xcm/xcm-executor/src/config.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/conversion.rs
  xcm/xcm-executor/src/traits/mod.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
  xcm/xcm-simulator/fuzzer/src/parachain.rs
  xcm/xcm-simulator/fuzzer/src/relay_chain.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5091 Parachain runtime dependent weights
  Cargo.lock
  node/test/service/Cargo.toml
  node/test/service/src/lib.rs
  runtime/common/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/tests.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: F6-refactor, A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5094 Remove XCMv1
  xcm/pallet-xcm/src/tests.rs
  xcm/procedural/src/lib.rs
  xcm/procedural/src/v1.rs
  xcm/procedural/src/v1/multilocation.rs
  xcm/procedural/src/v2.rs
  xcm/procedural/src/v3.rs
  xcm/src/lib.rs
  xcm/src/v1/mod.rs
  xcm/src/v1/order.rs
  xcm/src/v1/traits.rs
  xcm/src/v2/junction.rs
  xcm/src/v2/mod.rs
  xcm/src/v2/multiasset.rs
  xcm/src/v2/multilocation.rs
  xcm/src/v3/junction.rs
  xcm/src/v3/multilocation.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5036 derive serialize/deserialize for xcm primitives
  Cargo.lock
  xcm/Cargo.toml
  xcm/src/v2/junction.rs
  xcm/src/v2/mod.rs
  xcm/src/v2/multiasset.rs
  xcm/src/v2/multilocation.rs
  xcm/src/v3/junction.rs
  xcm/src/v3/junctions.rs
  xcm/src/v3/multiasset.rs
  xcm/src/v3/multilocation.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5080 Zombienet: add cpu/mem resource requests
  .gitlab-ci.yml
  zombienet_tests/functional/0001-parachains-pvf.toml
  zombienet_tests/functional/0002-parachains-disputes.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5100 ci: use production profile for benchmarks
  .gitlab-ci.yml
  scripts/run_benches_for_runtime.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5102 ci: use production profile for all benchmarks (follow-up for #5100)
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5103 update ump for weights sink_process_upward_message -> process_upward_message
  runtime/kusama/src/weights/runtime_parachains_ump.rs
  runtime/parachains/src/ump.rs
  runtime/westend/src/weights/runtime_parachains_ump.rs
Labels: A0-pleasereview

#5110 Some small log improvements
  node/core/av-store/src/lib.rs
  node/core/provisioner/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5082 Rococo to use BABE randomness, Westend & Rococo runtime synchronization in file format
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5115 Rococo rm uneeded migrations, as network reset to "2.1"
  runtime/rococo/README.md
  runtime/rococo/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5108 Add metrics timer for the `PerRequest` structure lifetime
  node/network/collator-protocol/src/validator_side/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5101 StatementDistributionMessage::get_metadata is a footgun and should be removed
  node/network/protocol/src/lib.rs
  node/network/statement-distribution/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5126 [ci] scripts: don't rebuild for every pallet benchmark
  .gitlab-ci.yml
  scripts/run_benches_for_runtime.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5124 observability: add two more timers
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5123 Add more info to logs.
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5133 make more subsystems blocking, fix blocking subsystem spawning
  node/overseer/overseer-gen/proc-macro/src/impl_builder.rs
  node/overseer/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5129 Collator protocol debug
  node/network/collator-protocol/src/validator_side/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#4863 Add Child Bounties to Polkadot and Kusama
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_child_bounties.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_child_bounties.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸

#5132 strengthen signals-received atomics
  node/overseer/overseer-gen/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5125 Additional tracing in provisioner
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5112 Companion to Moving `NposSolution` to frame #11031
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5142 provisioner logs minor janitor duties
  node/core/provisioner/src/lib.rs
  node/overseer/overseer-gen/proc-macro/src/impl_dispatch.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5144 Sligth improvements to the collator side metrics and logs
  node/network/collator-protocol/src/collator_side/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5139 Fix Benchmark Regressions in Polkadot Parachain Auction System
  runtime/common/src/auctions.rs
  runtime/common/src/crowdloan/mod.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/slots.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5143 Logs for large messages + metrics on size.
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/metrics.rs
  node/network/statement-distribution/src/requester.rs
  node/network/statement-distribution/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5147 bitfield dist logging cleanup and enhancements
  Cargo.lock
  node/network/bitfield-distribution/Cargo.toml
  node/network/bitfield-distribution/src/lib.rs
  node/network/bitfield-distribution/src/metrics.rs
  node/network/bitfield-distribution/src/tests.rs
  node/overseer/src/lib.rs
  node/subsystem-util/src/tests.rs
Labels: A8-mergeoncegreen, A0-pleasereview, B0-silent, C1-low 📌

#5151 fix freshness calculations in statement distribution
  node/network/statement-distribution/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5157 Don't wait for dispute coordinator
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/backing/src/tests.rs
  node/core/dispute-coordinator/src/error.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#5154 Some improvements in the statement-distribution histograms
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5150 have some lenience on outdated messages in statement distribution
  node/network/statement-distribution/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C3-medium 📣, D3-trivial 🧸

#5160 add a metric for report events in network bridge
  node/network/bridge/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5136 Companion for #10956
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5122 `AliasOrigin` instruction stub
  runtime/westend/src/weights/xcm/mod.rs
  xcm/src/v3/mod.rs
  xcm/src/v3/traits.rs
  xcm/xcm-executor/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, D3-trivial 🧸

#5161 approval dist imrpo
  node/network/approval-distribution/src/lib.rs
  node/network/approval-distribution/src/metrics.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5167 miniscule: fix edition fmt
  node/gum/proc-macro/src/lib.rs
  node/overseer/overseer-gen/proc-macro/src/lib.rs
  scripts/gitlab/spellcheck.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5163 update remaining weights (follow-up #5138 & #5098)
  runtime/kusama/src/weights/pallet_child_bounties.rs
  runtime/kusama/src/weights/runtime_common_crowdloan.rs
  runtime/polkadot/src/weights/pallet_child_bounties.rs
  runtime/polkadot/src/weights/runtime_common_auctions.rs
  runtime/polkadot/src/weights/runtime_common_crowdloan.rs
  runtime/polkadot/src/weights/runtime_common_slots.rs
  runtime/westend/src/weights/runtime_common_crowdloan.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5155 Fix changelog
  .github/workflows/publish-draft-release.yml
  scripts/changelog/README.md
  scripts/changelog/bin/changelog
  scripts/changelog/templates/global_priority.md.tera
  scripts/changelog/templates/migrations-db.md.tera
  scripts/changelog/templates/migrations-runtime.md.tera
  scripts/changelog/templates/migrations.md.tera
  scripts/changelog/templates/template.md.tera
Labels: A3-inprogress, A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#5175 Companion to #11081, upgrade paritydb version.
  Cargo.lock
  node/service/Cargo.toml
  node/subsystem-util/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, D2-notlive 💤

#5000 lower kusama staking limits
  runtime/kusama/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#5179 [ci] don't exclude frame_system from weights benchmarks
  scripts/run_benches_for_runtime.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5145 Companion to Implementing MaxEncodedLen for generate_solution_type #11032
  Cargo.lock
  node/core/pvf/tests/it/main.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#5159 Extract MAX_FINALITY_LAG constant from relay_chain_selection
  node/core/approval-voting/src/import.rs
  node/core/dispute-coordinator/src/real/initialized.rs
  node/primitives/src/lib.rs
  node/service/src/relay_chain_selection.rs
Labels: B0-silent, C1-low 📌

#5088 companion for validator self-vote in bags
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮, E1-runtimemigration

#4809 Update docs and enable DOT-over-XCM
  runtime/kusama/src/xcm_config.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/xcm_config.rs
  xcm/pallet-xcm/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, D9-needsaudit 👮

#5188 [ci] Add short benchmarks to the pipeline
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4862 Companion for paritytech/substrate#10242
  Cargo.lock
  runtime/common/src/elections.rs
Labels: A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#5200 [ci] Run short benchmarks only in PR pipelines
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#4938 paras: `include_pvf_check_statement` rt bench
  Cargo.lock
  runtime/kusama/src/weights/runtime_parachains_paras.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/paras/benchmarking.rs
  runtime/parachains/src/paras/benchmarking/pvf_check.rs
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras/tests.rs
  runtime/parachains/src/shared.rs
  runtime/polkadot/src/weights/runtime_parachains_paras.rs
  runtime/rococo/src/weights/runtime_parachains_paras.rs
  runtime/westend/src/weights/runtime_parachains_paras.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5197 Companion for Substrate#11107
  Cargo.lock
  cli/src/command.rs
  node/core/pvf/src/executor_intf.rs
Labels: F2-bug, A0-pleasereview, B0-silent, A7-companion, C1-low 📌, D3-trivial 🧸

#5177 Try to fix out of view statements
  Cargo.lock
  node/network/approval-distribution/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/tests.rs
  node/service/src/overseer.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/tests.rs
  primitives/test-helpers/Cargo.toml
  primitives/test-helpers/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5199 remove the dummy overseer implementation
  node/core/dispute-coordinator/src/dummy.rs
  node/core/dispute-coordinator/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#5183 Companion for Update Bounty Deposit (#11014)
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸, D2-breaksapi

#5093 Adding `Fallback` on election failure
  Cargo.lock
  runtime/common/src/elections.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#5189 Fix build script for the builder image
  scripts/dockerfiles/polkadot/build.sh
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#5207 [ci] Require short-benches check to pass
  .gitlab-ci.yml
Labels: A4-awaitingci, A0-pleasereview, B0-silent, C1-low 📌

#4549 Implement transfer_asset on CurrencyAdapter
  xcm/xcm-builder/src/currency_adapter.rs
  xcm/xcm-builder/src/fungibles_adapter.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-builder/tests/scenarios.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/transact_asset.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5202 Update Block- and Extrinsic base weights
  runtime/kusama/constants/src/lib.rs
  runtime/kusama/constants/src/weights/block_weights.rs
  runtime/kusama/constants/src/weights/extrinsic_weights.rs
  runtime/kusama/constants/src/weights/mod.rs
  runtime/polkadot/constants/src/lib.rs
  runtime/polkadot/constants/src/weights/block_weights.rs
  runtime/polkadot/constants/src/weights/extrinsic_weights.rs
  runtime/polkadot/constants/src/weights/mod.rs
  runtime/rococo/constants/src/lib.rs
  runtime/rococo/constants/src/weights/block_weights.rs
  runtime/rococo/constants/src/weights/extrinsic_weights.rs
  runtime/rococo/constants/src/weights/mod.rs
  runtime/westend/constants/src/lib.rs
  runtime/westend/constants/src/weights/block_weights.rs
  runtime/westend/constants/src/weights/extrinsic_weights.rs
  runtime/westend/constants/src/weights/mod.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5173 Migrate Slot Depositors in Crowdloan Migration
  runtime/common/src/crowdloan/migration.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium 📣, D5-nicetohaveaudit ⚠️, E1-runtimemigration

#5220 Update storage weights
  runtime/polkadot/constants/src/weights/paritydb_weights.rs
  runtime/polkadot/constants/src/weights/rocksdb_weights.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸

#5209 Companion for bags-list iter-from interface
  Cargo.lock
  runtime/common/src/elections.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#5229 fix approval-voting force-approve
  node/core/approval-voting/src/import.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, D3-trivial 🧸
