Repository paritytech/polkadot, pull requests merged in 2023-02, with the labels that each got.

#6249 Some late short-term fixes for dispute slashing
  runtime/parachains/src/builder.rs
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/disputes/slashing.rs
  runtime/parachains/src/disputes/slashing/benchmarking.rs
  runtime/parachains/src/disputes/tests.rs
  runtime/parachains/src/mock.rs
  zombienet_tests/functional/0002-parachains-disputes.zndsl
  zombienet_tests/functional/0003-parachains-garbage-candidate.zndsl
Labels: A0-please_review, B0-silent, C1-low, D9-needsaudit 👮

#6663 Fix XCM bench for new substrate refs
  Cargo.lock
  runtime/test-runtime/Cargo.toml
  xcm/pallet-xcm/Cargo.toml
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/fuzzer/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low

#6528 [Substrate companion] Update beefy-merkle-tree dep to merkle-tree
  Cargo.lock
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
Labels: B0-silent, A4-companion, C1-low, D3-trivial 🧸

#6665 kusama: allow root to cancel/kill referendums
  runtime/kusama/src/governance/mod.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, T1-runtime, B1-note_worthy

#6623 Companion for substrate #13215 - Add new BEEFY api to runtimes
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, B0-silent, A4-companion, C1-low, D3-trivial 🧸

#6609 Add a CI check ensuring the code has license headers
  .github/workflows/check-licenses.yml
  erasure-coding/benches/scaling_with_validators.rs
  erasure-coding/fuzzer/src/reconstruct.rs
  erasure-coding/fuzzer/src/round_trip.rs
  node/core/chain-api/src/tests.rs
  node/core/dispute-coordinator/src/scraping/candidates.rs
  node/core/provisioner/src/tests.rs
  node/network/bridge/src/errors.rs
  node/network/protocol/src/reputation.rs
  runtime/kusama/src/weights/xcm/mod.rs
  runtime/rococo/src/weights/xcm/mod.rs
  runtime/westend/src/weights/xcm/mod.rs
  statement-table/src/lib.rs
  utils/staking-miner/tests/cli.rs
  xcm/pallet-xcm-benchmarks/src/generic/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6666 Bump parity-scale-codec to 3.3.0
  Cargo.lock
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/collation-generation/Cargo.toml
  node/core/approval-voting/Cargo.toml
  node/core/av-store/Cargo.toml
  node/core/candidate-validation/Cargo.toml
  node/core/chain-api/Cargo.toml
  node/core/chain-selection/Cargo.toml
  node/core/dispute-coordinator/Cargo.toml
  node/core/pvf/Cargo.toml
  node/jaeger/Cargo.toml
  node/metrics/Cargo.toml
  node/network/availability-distribution/Cargo.toml
  node/network/availability-recovery/Cargo.toml
  node/network/bridge/Cargo.toml
  node/network/collator-protocol/Cargo.toml
  node/network/dispute-distribution/Cargo.toml
  node/network/protocol/Cargo.toml
  node/network/statement-distribution/Cargo.toml
  node/primitives/Cargo.toml
  node/subsystem-util/Cargo.toml
  node/test/client/Cargo.toml
  node/zombienet-backchannel/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/undying/Cargo.toml
  parachain/test-parachains/undying/collator/Cargo.toml
  primitives/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/slot_range_helper/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/metrics/Cargo.toml
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  statement-table/Cargo.toml
  utils/staking-miner/Cargo.toml
  xcm/Cargo.toml
  xcm/pallet-xcm-benchmarks/Cargo.toml
  xcm/pallet-xcm/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
  xcm/xcm-simulator/Cargo.toml
  xcm/xcm-simulator/example/Cargo.toml
  xcm/xcm-simulator/fuzzer/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6565 pvf: Log memory metrics from preparation
  Cargo.lock
  node/core/pvf/Cargo.toml
  node/core/pvf/src/host.rs
  node/core/pvf/src/metrics.rs
  node/core/pvf/src/prepare/memory_stats.rs
  node/core/pvf/src/prepare/mod.rs
  node/core/pvf/src/prepare/pool.rs
  node/core/pvf/src/prepare/queue.rs
  node/core/pvf/src/prepare/worker.rs
  node/overseer/src/memory_stats.rs
  node/overseer/src/metrics.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6674 Fix dependabot labels
  .github/dependabot.yml
Labels: B0-silent, C1-low, D3-trivial 🧸

#6640 Disable `hostperfcheck` by default
  Cargo.toml
  cli/Cargo.toml
  cli/src/command.rs
  cli/src/error.rs
  node/service/src/lib.rs
  node/test/performance-test/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6661 Companion for substrate#13160
  Cargo.lock
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6638 Weights for new referenda/democracy extrinsics
  Cargo.lock
  runtime/kusama/src/weights/pallet_democracy.rs
  runtime/kusama/src/weights/pallet_referenda_fellowship_referenda.rs
  runtime/kusama/src/weights/pallet_referenda_referenda.rs
  runtime/polkadot/src/weights/pallet_democracy.rs
  runtime/rococo/src/weights/pallet_democracy.rs
Labels: A3-in_progress, B0-silent, C1-low, D3-trivial 🧸

#6680 companion substrate#13305
  Cargo.lock
  runtime/kusama/src/governance/old.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#6636 Remove BoundedVec half-impls in xcm
  Cargo.lock
  node/zombienet-backchannel/Cargo.toml
  xcm/Cargo.toml
  xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  xcm/pallet-xcm/Cargo.toml
  xcm/pallet-xcm/src/benchmarking.rs
  xcm/src/v2/junction.rs
  xcm/src/v2/mod.rs
  xcm/src/v3/mod.rs
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-builder/src/tests/transacting.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-executor/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6675 Introduce jemalloc-allocator feature flag
  Cargo.lock
  Cargo.toml
  node/core/pvf/Cargo.toml
  node/core/pvf/src/prepare/memory_stats.rs
  node/core/pvf/src/prepare/worker.rs
  node/overseer/Cargo.toml
  node/overseer/src/lib.rs
  node/overseer/src/memory_stats.rs
  node/overseer/src/metrics.rs
  src/main.rs
Labels: A0-please_review, C1-low, T0-node, B1-note_worthy

#6692 New template to generate a full pr list
  scripts/ci/changelog/README.md
  scripts/ci/changelog/templates/full_pr_list.md.tera
Labels: B0-silent, C1-low, T8-release

#6691 av-store: skip processing finalized blocks while major syncing
  Cargo.lock
  node/core/av-store/Cargo.toml
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/service/src/overseer.rs
Labels: A0-please_review, B0-silent, C1-low, T4-parachains_engineering, T0-node

#6695 edit xcm simulator test code
  xcm/xcm-simulator/example/src/lib.rs
Labels: B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview

#6690 fix: runtime benchmark feature
  runtime/test-runtime/Cargo.toml
  xcm/pallet-xcm/Cargo.toml
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/fuzzer/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6620 Companion for substrate #13159
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/kusama/src/governance/old.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6716 v3::Junction supports small (32-byte max) "vecs".
  xcm/src/v2/junction.rs
  xcm/src/v3/junction.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️, T6-XCM

#6693 Refactor PVF preparation memory stats
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/tests.rs
  node/core/pvf/src/artifacts.rs
  node/core/pvf/src/error.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/lib.rs
  node/core/pvf/src/metrics.rs
  node/core/pvf/src/prepare/memory_stats.rs
  node/core/pvf/src/prepare/mod.rs
  node/core/pvf/src/prepare/queue.rs
  node/core/pvf/src/prepare/worker.rs
Labels: I8-refactor, A0-please_review, I4-annoyance, B0-silent, C1-low, D3-trivial 🧸, T4-parachains_engineering

#6334 add warp sync params to enable parachain warp sync
  Cargo.lock
  node/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#6161 Executor Environment parameterization
  Cargo.lock
  erasure-coding/benches/scaling_with_validators.rs
  node/core/candidate-validation/Cargo.toml
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/tests.rs
  node/core/dispute-coordinator/src/tests.rs
  node/core/pvf-checker/src/lib.rs
  node/core/pvf/Cargo.toml
  node/core/pvf/src/artifacts.rs
  node/core/pvf/src/execute/queue.rs
  node/core/pvf/src/execute/worker.rs
  node/core/pvf/src/executor_intf.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/lib.rs
  node/core/pvf/src/prepare/pool.rs
  node/core/pvf/src/prepare/queue.rs
  node/core/pvf/src/prepare/worker.rs
  node/core/pvf/src/pvf.rs
  node/core/pvf/src/testing.rs
  node/core/pvf/src/worker_common.rs
  node/core/pvf/tests/it/adder.rs
  node/core/pvf/tests/it/main.rs
  node/core/runtime-api/src/cache.rs
  node/core/runtime-api/src/lib.rs
  node/malus/src/variants/suggest_garbage_candidate.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-types/src/runtime_client.rs
  node/subsystem-util/src/lib.rs
  node/test/performance-test/Cargo.toml
  node/test/performance-test/src/lib.rs
  primitives/src/runtime_api.rs
  primitives/src/v2/mod.rs
  primitives/src/vstaging/executor_params.rs
  primitives/src/vstaging/mod.rs
  runtime/common/src/xcm_sender.rs
  runtime/parachains/src/disputes/migration.rs
  runtime/parachains/src/runtime_api_impl/vstaging.rs
  runtime/parachains/src/session_info.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, C3-medium, D9-needsaudit 👮, E0-runtime_migration, E1-database_migration, E4-node_first_update, T1-runtime, B1-note_worthy

#6718 Move Fellowship to Collectives
  Cargo.lock
  runtime/polkadot/Cargo.toml
  runtime/polkadot/constants/src/lib.rs
  runtime/polkadot/src/governance/fellowship.rs
  runtime/polkadot/src/governance/mod.rs
  runtime/polkadot/src/governance/origins.rs
  runtime/polkadot/src/governance/tracks.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/mod.rs
  runtime/polkadot/src/weights/pallet_ranked_collective.rs
  runtime/polkadot/src/weights/pallet_referenda_fellowship_referenda.rs
  runtime/polkadot/src/xcm_config.rs
Labels: A3-in_progress

#6715 Async Backing: Integrate `vstaging` of statement distribution into `lib.rs`
  node/network/statement-distribution/src/legacy_v1/mod.rs
  node/network/statement-distribution/src/legacy_v1/responder.rs
  node/network/statement-distribution/src/legacy_v1/tests.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/vstaging/mod.rs
  node/network/statement-distribution/src/vstaging/statement_store.rs
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/subsystem-util/src/inclusion_emulator/staging.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview

#6673 Async backing statement distribution: grid tests
  node/network/statement-distribution/src/vstaging/grid.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6707 Add more tests in `requests.rs`
  node/network/statement-distribution/src/vstaging/requests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview

#6658 Async backing statement distribution: `Candidates` tests
  Cargo.lock
  node/core/prospective-parachains/src/tests.rs
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/vstaging/candidates.rs
  primitives/test-helpers/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6702 Update release-related templates for the new changelogerator output format
  scripts/ci/changelog/Gemfile
  scripts/ci/changelog/Gemfile.lock
  scripts/ci/changelog/bin/changelog
  scripts/ci/changelog/templates/change.md.tera
  scripts/ci/changelog/templates/changes_api.md.tera
  scripts/ci/changelog/templates/changes_client.md.tera
  scripts/ci/changelog/templates/changes_misc.md.tera
  scripts/ci/changelog/templates/changes_runtime.md.tera
  scripts/ci/changelog/templates/debug.md.tera
  scripts/ci/changelog/templates/high_priority.md.tera
  scripts/ci/changelog/templates/host_functions.md.tera
  scripts/ci/changelog/templates/migrations-db.md.tera
  scripts/ci/changelog/templates/migrations-runtime.md.tera
Labels: A2-insubstantial, B0-silent, C1-low, D2-notlive 💤

#6706 Companion for substrate #12910: BEEFY metrics
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low

#6731 Backport release notes fix #6702
  scripts/ci/changelog/Gemfile
  scripts/ci/changelog/Gemfile.lock
  scripts/ci/changelog/bin/changelog
  scripts/ci/changelog/templates/change.md.tera
  scripts/ci/changelog/templates/changes_api.md.tera
  scripts/ci/changelog/templates/changes_client.md.tera
  scripts/ci/changelog/templates/changes_misc.md.tera
  scripts/ci/changelog/templates/changes_runtime.md.tera
  scripts/ci/changelog/templates/debug.md.tera
  scripts/ci/changelog/templates/high_priority.md.tera
  scripts/ci/changelog/templates/host_functions.md.tera
  scripts/ci/changelog/templates/migrations-db.md.tera
  scripts/ci/changelog/templates/migrations-runtime.md.tera
Labels: B0-silent, C1-low, A6-backport, T8-release

#6603 Use a `BoundedVec` in `ValidationResult`
  Cargo.lock
  node/collation-generation/src/tests.rs
  node/core/backing/src/tests.rs
  node/core/candidate-validation/src/tests.rs
  node/malus/src/variants/common.rs
  node/primitives/Cargo.toml
  node/primitives/src/lib.rs
  parachain/Cargo.toml
  parachain/src/primitives.rs
  parachain/test-parachains/adder/collator/src/lib.rs
  parachain/test-parachains/adder/src/wasm_validation.rs
  parachain/test-parachains/undying/collator/src/lib.rs
  parachain/test-parachains/undying/src/wasm_validation.rs
  primitives/src/v2/mod.rs
  primitives/test-helpers/src/lib.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/builder.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/hrmp/tests.rs
  runtime/parachains/src/ump.rs
  runtime/parachains/src/ump/benchmarking.rs
  runtime/parachains/src/ump/tests.rs
  xcm/Cargo.toml
  xcm/pallet-xcm/Cargo.toml
  xcm/xcm-builder/src/tests/querying.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6728 Change `MaxMemorySize` to `MaxMemoryPages`
  node/core/pvf/src/executor_intf.rs
  primitives/src/vstaging/executor_params.rs
Labels: B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview

#6732 Fix a metric description
  node/core/provisioner/src/metrics.rs
Labels: B0-silent, C1-low, T4-parachains_engineering, A0-pleasereview

#6729 Add OpenGov Calls to Proxy Definitions
  runtime/polkadot/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6704 Do not call longest chain by default
  node/service/src/relay_chain_selection.rs
  node/service/src/tests.rs
Labels: B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview

#6593 Companion for substrate #13121 - BEEFY Equivocations support
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, B0-silent, A4-companion, C1-low, D3-trivial 🧸

#6720 Async Backing: Fix clippy errors in statement distribution branch
  node/network/statement-distribution/src/legacy_v1/mod.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/vstaging/candidates.rs
  node/network/statement-distribution/src/vstaging/grid.rs
  node/network/statement-distribution/src/vstaging/mod.rs
  node/network/statement-distribution/src/vstaging/requests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview

#6744 Retire `OldV1SessionInfo`
  node/core/runtime-api/src/lib.rs
  node/subsystem-types/src/runtime_client.rs
  primitives/src/lib.rs
  primitives/src/runtime_api.rs
  primitives/src/v2/mod.rs
Labels: A0-please_review, B0-silent, D3-trivial 🧸

#6742 Use PVF code paired with executor params wherever possible
  node/core/candidate-validation/src/lib.rs
  node/core/pvf/src/executor_intf.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/lib.rs
  node/core/pvf/src/prepare/pool.rs
  node/core/pvf/src/prepare/queue.rs
  node/core/pvf/src/prepare/worker.rs
  node/core/pvf/src/pvf.rs
  node/core/pvf/src/testing.rs
  node/core/pvf/tests/it/main.rs
  node/test/performance-test/src/lib.rs
Labels: B0-silent, C1-low

#6747 Fix auction bench
  Cargo.lock
  cli/src/command.rs
  node/service/src/lib.rs
  runtime/common/src/auctions.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#6721 `BlockId` removal: refactor of runtime API
  Cargo.lock
  node/subsystem-types/src/runtime_client.rs
  node/test/client/src/block_builder.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#6743 Companion for Substrate#13411: frame/beefy: prune entries in set id session mapping
  Cargo.lock
  runtime/rococo/src/lib.rs
Labels: A0-please_review, B0-silent, A4-companion, C1-low, D3-trivial 🧸

#6683 Companion PR for PR#13119
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, T2-API, B1-note_worthy

#6734 `BlockId` removal: `BlockBuilderProvider::new_block_at`
  Cargo.lock
  node/test/client/src/block_builder.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#6750 Companion for Substrate #13410: Introduce EnsureOrigin to democracy.propose
  Cargo.lock
  runtime/kusama/src/governance/old.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6653 Companion for substrate#13284
  Cargo.lock
  node/client/src/lib.rs
Labels: I8-refactor, I9-footprint, A0-please_review, I10-optimisation, B0-silent, C1-low, D3-trivial 🧸

#6753 polkadot companion #12608 (Pools claim permissions)
  .cargo/config.toml
  Cargo.lock
  runtime/kusama/src/weights/pallet_nomination_pools.rs
  runtime/polkadot/src/weights/pallet_nomination_pools.rs
  runtime/westend/src/weights/pallet_nomination_pools.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6737 Remove state migration from westend runtime.
  Cargo.lock
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6763 clean up executed migrations
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#6752 Corrected weight trader comment
  xcm/xcm-builder/src/weight.rs
Labels: B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview

#6190 Improve XCM fuzzer
  Cargo.lock
  xcm/xcm-simulator/fuzzer/.gitignore
  xcm/xcm-simulator/fuzzer/Cargo.toml
  xcm/xcm-simulator/fuzzer/README.md
  xcm/xcm-simulator/fuzzer/src/fuzz.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#6730 Companion for Substrate#12520
  Cargo.lock
  node/core/pvf/src/executor_intf.rs
Labels: B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview

#6757 Explicitly Handling ProvisionableData Cases
  node/core/backing/src/lib.rs
  node/core/provisioner/src/lib.rs
  roadmap/implementers-guide/src/protocol-disputes.md
Labels: A0-please_review, B0-silent, C1-low

#6787 XCM: Ensure max_weight is assigned properly in AllowTopPaidExecutionFrom
  xcm/xcm-builder/src/barriers.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6783 Automatically format ci pipeline specs with prettier
  .gitattributes
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/check.yml
  scripts/ci/gitlab/pipeline/publish.yml
  scripts/ci/gitlab/pipeline/short-benchmarks.yml
  scripts/ci/gitlab/pipeline/test.yml
  scripts/ci/gitlab/pipeline/weights.yml
  scripts/ci/gitlab/pipeline/zombienet.yml
  scripts/ci/gitlab/prettier.sh
Labels: A2-insubstantial, B0-silent, C1-low

#6776 [Companion] GRANDPA crate renaming
  Cargo.lock
  node/client/Cargo.toml
  node/client/src/lib.rs
  node/service/Cargo.toml
  node/test/service/Cargo.toml
  rpc/Cargo.toml
  rpc/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low

#6795 Use `BTreeSet` as the internal type of `ParachainsCache`
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras/tests.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#6786 XCM: Limit the max number of assets weighable in MultiAssets
  runtime/kusama/src/weights/xcm/mod.rs
  runtime/kusama/src/xcm_config.rs
  runtime/rococo/src/weights/xcm/mod.rs
  runtime/westend/src/weights/xcm/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T6-XCM

#6799 [Companion] BEEFY crates renaming
  Cargo.lock
  node/client/Cargo.toml
  node/client/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
Labels: B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview
