Repository paritytech/polkadot, pull requests merged in 2023-07, with the labels that each got.

#7449 Allow Root to initiate auctions
  runtime/polkadot/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6871 Whitelist from benchmarking XCM storage keys read each block
  runtime/kusama/src/lib.rs
  runtime/kusama/src/tests.rs
  runtime/kusama/src/weights/pallet_xcm.rs
  runtime/parachains/src/configuration.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_xcm.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/weights/pallet_xcm.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/tests.rs
  runtime/westend/src/weights/pallet_xcm.rs
  xcm/pallet-xcm/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7438 [xcm] BridgeBlobDispatcher - prepend bridge instance discriminator.
  xcm/xcm-builder/src/tests/bridging/local_para_para.rs
  xcm/xcm-builder/src/tests/bridging/local_relay_relay.rs
  xcm/xcm-builder/src/tests/bridging/paid_remote_relay_relay.rs
  xcm/xcm-builder/src/tests/bridging/remote_para_para.rs
  xcm/xcm-builder/src/tests/bridging/remote_para_para_via_relay.rs
  xcm/xcm-builder/src/tests/bridging/remote_relay_relay.rs
  xcm/xcm-builder/src/universal_exports.rs
Labels: A0-please_review, B0-silent, C1-low, D9-needsaudit 👮

#7451 Do not depend on native runtimes for `RuntimeApi`
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/command.rs
  cli/src/lib.rs
  node/client/Cargo.toml
  node/client/src/benchmarking.rs
  node/client/src/lib.rs
  node/service/Cargo.toml
  node/service/src/benchmarking.rs
  node/service/src/chain_spec.rs
  node/service/src/fake_runtime_api.rs
  node/service/src/lib.rs
  node/test/client/Cargo.toml
  node/test/client/src/block_builder.rs
  node/test/client/src/lib.rs
  node/test/service/Cargo.toml
  node/test/service/src/lib.rs
  tests/purge_chain_works.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, T0-node, B1-note_worthy

#7417 availability-recovery: move cpu burners in blocking tasks
  node/core/approval-voting/src/lib.rs
  node/core/dispute-coordinator/src/participation/mod.rs
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/tests.rs
  node/subsystem-types/src/errors.rs
Labels: A0-please_review, B0-silent, C1-low

#7453 Update pr-custom-review.yml 3 Core-devs to approve
  .github/pr-custom-review.yml
Labels: B0-silent

#7015 Kusama state version switch and migration.
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, E0-runtime_migration, E1-database_migration, T1-runtime, B1-note_worthy

#7460 zombienet-backchannel: /s/openssl/rustls/
  Cargo.lock
  node/zombienet-backchannel/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7448 Add Nomination Pools and Voters List to Staking Proxy
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, T1-runtime, B1-note_worthy

#7459 Companion for Substrate#14511
  Cargo.lock
  cli/src/command.rs
  node/service/src/benchmarking.rs
  node/service/src/chain_spec.rs
  node/service/src/lib.rs
  parachain/test-parachains/adder/collator/src/cli.rs
  parachain/test-parachains/undying/collator/src/cli.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7303 PVF: add landlock sandboxing
  Cargo.lock
  node/core/pvf/common/Cargo.toml
  node/core/pvf/common/src/worker/mod.rs
  node/core/pvf/common/src/worker/security.rs
  node/core/pvf/execute-worker/src/lib.rs
  node/core/pvf/prepare-worker/src/lib.rs
  node/core/pvf/src/host.rs
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/utility/candidate-validation.md
  roadmap/implementers-guide/src/node/utility/pvf-host-and-workers.md
Labels: A0-please_review, C1-low, D3-trivial 🧸, T0-node, B1-note_worthy

#7390 Run timeout-based tests only in CI
  Cargo.lock
  Cargo.toml
  node/core/pvf/Cargo.toml
  node/core/pvf/tests/it/main.rs
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, B0-silent, C1-low

#7469 backing: Remove redundant erasure encoding
  Cargo.lock
  node/core/av-store/Cargo.toml
  node/core/av-store/src/lib.rs
  node/core/av-store/src/tests.rs
  node/core/backing/src/error.rs
  node/core/backing/src/lib.rs
  node/subsystem-types/src/messages.rs
  roadmap/implementers-guide/src/node/utility/availability-store.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-please_review, B0-silent, C1-low

#7475 Companion #14527
  .cargo/config.toml
  Cargo.lock
  runtime/common/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/governance/old.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#7466 Enable missing features
  runtime/test-runtime/constants/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#7470 paras: Prune upgrade cooldowns
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7405 Update collation generation for asynchronous backing
  Cargo.lock
  node/collation-generation/Cargo.toml
  node/collation-generation/src/lib.rs
  node/collation-generation/src/metrics.rs
  node/collation-generation/src/tests.rs
  node/overseer/src/tests.rs
  node/primitives/src/lib.rs
  node/subsystem-types/src/messages.rs
  node/test/service/src/lib.rs
  parachain/src/primitives.rs
  parachain/test-parachains/adder/collator/src/main.rs
  parachain/test-parachains/undying/collator/src/main.rs
  roadmap/implementers-guide/src/node/collators/collation-generation.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️, T0-node

#7396 configuration: drop `pvf_checking_enabled` parameter
  runtime/kusama/src/lib.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/migration.rs
  runtime/parachains/src/configuration/migration/v6.rs
  runtime/parachains/src/configuration/migration/v7.rs
  runtime/parachains/src/configuration/tests.rs
  runtime/parachains/src/hrmp/tests.rs
  runtime/parachains/src/paras/benchmarking/pvf_check.rs
  runtime/parachains/src/paras/tests.rs
  runtime/parachains/src/scheduler/tests.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, E0-runtime_migration

#7443 Companion for removal of execution strategies
  Cargo.lock
  node/core/runtime-api/Cargo.toml
  node/core/runtime-api/src/tests.rs
  node/malus/src/variants/back_garbage_candidate.rs
  node/malus/src/variants/dispute_valid_candidates.rs
  node/malus/src/variants/suggest_garbage_candidate.rs
  node/metrics/Cargo.toml
  node/metrics/src/tests.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/subsystem-types/Cargo.toml
  node/subsystem-types/src/lib.rs
  node/subsystem-types/src/runtime_client.rs
  node/test/client/src/lib.rs
  node/test/service/src/lib.rs
  rpc/src/lib.rs
  scripts/ci/gitlab/pipeline/short-benchmarks.yml
  scripts/ci/run_benches_for_runtime.sh
  tests/benchmark_block.rs
  xcm/xcm-executor/integration-tests/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7489 configuration: optionally read pending configs in migration
  runtime/parachains/src/configuration/migration/v7.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, E0-runtime_migration

#7397 `GenesisBuild<T,I>` deprecated. `BuildGenesisConfig` added
  Cargo.lock
  node/service/src/chain_spec.rs
  node/test/service/src/chain_spec.rs
  runtime/common/src/assigned_slots.rs
  runtime/common/src/auctions.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan/mod.rs
  runtime/common/src/impls.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots/mod.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras/mod.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-simulator/example/src/lib.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
  xcm/xcm-simulator/fuzzer/src/fuzz.rs
  xcm/xcm-simulator/fuzzer/src/parachain.rs
  xcm/xcm-simulator/fuzzer/src/relay_chain.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#7431 Moves `Block` to `frame_system` instead of `construct_runtime` and removes `Header` and `BlockNumber`
  Cargo.lock
  roadmap/implementers-guide/src/runtime/configuration.md
  roadmap/implementers-guide/src/runtime/paras.md
  runtime/common/src/assigned_slots.rs
  runtime/common/src/auctions.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan/mod.rs
  runtime/common/src/impls.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/mock.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots/mod.rs
  runtime/common/src/xcm_sender.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/builder.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/disputes/slashing.rs
  runtime/parachains/src/disputes/slashing/benchmarking.rs
  runtime/parachains/src/disputes/tests.rs
  runtime/parachains/src/dmp.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/inclusion/mod.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras/benchmarking.rs
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras_inherent/mod.rs
  runtime/parachains/src/runtime_api_impl/v5.rs
  runtime/parachains/src/scheduler.rs
  runtime/parachains/src/session_info.rs
  runtime/parachains/src/shared.rs
  runtime/parachains/src/util.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
  xcm/xcm-simulator/fuzzer/src/parachain.rs
  xcm/xcm-simulator/fuzzer/src/relay_chain.rs
Labels: A4-companion, C1-low, D3-trivial 🧸, T1-runtime, B1-note_worthy

#7374 Replace Index for Nonce
  Cargo.lock
  runtime/common/src/assigned_slots.rs
  runtime/common/src/auctions.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan/mod.rs
  runtime/common/src/impls.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots/mod.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  utils/staking-miner/src/main.rs
  utils/staking-miner/src/prelude.rs
  utils/staking-miner/src/signer.rs
  xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
  xcm/xcm-simulator/fuzzer/src/parachain.rs
  xcm/xcm-simulator/fuzzer/src/relay_chain.rs
Labels: A0-please_review, B0-silent, A4-companion, C1-low, D3-trivial 🧸

#7477 Put HRMP Channel Management on General Admin Track
  runtime/kusama/src/governance/origins.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/mock.rs
  runtime/polkadot/src/governance/origins.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, T1-runtime, B1-note_worthy

#7410 Alert on frequent network errors
  Cargo.lock
  node/gum/Cargo.toml
  node/gum/proc-macro/src/lib.rs
  node/gum/proc-macro/src/types.rs
  node/gum/src/lib.rs
  node/gum/src/tests.rs
  node/network/availability-distribution/src/error.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/statement-distribution/src/error.rs
  node/network/statement-distribution/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low

#7478 [Do not merge] migration to ci-unified image
  .gitlab-ci.yml
Labels: A0-please_review, B0-silent, C1-low

#7484 companion for substrate#14423
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-please_review, B0-silent, A4-companion, C1-low

#7509 `chain-spec`: `polkadot_staging_testnet` config removed
  cli/src/command.rs
  node/service/src/chain_spec.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#7511 Move `CI_IMAGE` to external snippet via !reference
  .gitlab-ci.yml
Labels: A0-please_review, B0-silent, C1-low

#7432 Companion for substrate#14471
  Cargo.lock
  runtime/common/src/integration_tests.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/xcm-builder/src/process_xcm_message.rs
Labels: A0-please_review, B0-silent, A4-companion, C1-low, D1-audited 👍

#7512 Disable `spellcheck` CI job
  scripts/ci/gitlab/pipeline/check.yml
Labels: A0-please_review, B0-silent, C1-low

#7513 remove staging APIs from Rococo & Westend
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#7516 Bump `HostConfig` storage version to 7
  runtime/parachains/src/configuration.rs
Labels: A0-please_review, B0-silent, C1-low

#7495 Remove Executed Migrations
  runtime/common/src/lib.rs
  runtime/common/src/session/migration.rs
  runtime/common/src/session/mod.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/tests.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/migration.rs
  runtime/parachains/src/configuration/migration/v5.rs
  runtime/parachains/src/configuration/migration/v6.rs
  runtime/parachains/src/configuration/migration_ump.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, E0-runtime_migration

#7486 paras: count upgrade delay from inclusion
  runtime/parachains/src/inclusion/mod.rs
  runtime/parachains/src/inclusion/tests.rs
  runtime/parachains/src/paras/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D9-needsaudit 👮

#7515 send network messages on main protocol name
  node/network/bridge/src/network.rs
Labels: A0-please_review, B0-silent, C1-low, T0-node

#7521 add missing syscalls
  scripts/packaging/polkadot.service
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#7525 [Backport] add missing syscalls (#7521)
  scripts/packaging/polkadot.service
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, A6-backport

#7524 More PoV size metrics
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/metrics.rs
Labels: A0-please_review, B0-silent, C1-low

#7532 misc async backing improvements for allowed ancestry blocks
  node/core/prospective-parachains/src/tests.rs
  runtime/parachains/src/shared.rs
  runtime/parachains/src/shared/tests.rs
Labels: I3-bug, A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6227 Add `NetworkBridgeEvent::UpdatedAuthorityIds`
  Cargo.lock
  node/network/approval-distribution/src/lib.rs
  node/network/bitfield-distribution/src/lib.rs
  node/network/bridge/src/rx/mod.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/gossip-support/Cargo.toml
  node/network/gossip-support/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-types/src/messages/network_bridge_event.rs
Labels: B0-silent, C1-low

#7527 provisioner: request candidate receipt by relay parent
  node/core/backing/src/lib.rs
  node/core/backing/src/tests/mod.rs
  node/core/prospective-parachains/src/fragment_tree.rs
  node/core/prospective-parachains/src/lib.rs
  node/core/prospective-parachains/src/tests.rs
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/tests.rs
  node/overseer/src/tests.rs
  node/subsystem-types/src/messages.rs
  roadmap/implementers-guide/src/node/backing/prospective-parachains.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: I3-bug, A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7372 add tests to worker common thread
  node/core/pvf/common/src/worker/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7537 add missing feature flag
  xcm/xcm-executor/Cargo.toml
Labels: B0-silent, C1-low

#7528 Overcharging on `limited_teleport_assets`
  xcm/pallet-xcm/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, T1-runtime, B1-note_worthy

#7422 ci: always run runtime migration checks
  scripts/ci/gitlab/pipeline/check.yml
Labels: A0-please_review, B0-silent, C1-low

#7530 ParachainsInherent: apply weight limit only in `ProvideInherent`
  runtime/parachains/src/paras_inherent/mod.rs
  runtime/parachains/src/paras_inherent/tests.rs
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, B0-silent, C1-low

#7472 [Substrate companion] update libp2p to 0.52.0
  Cargo.lock
  node/core/approval-voting/Cargo.toml
  node/core/dispute-coordinator/Cargo.toml
  node/core/runtime-api/Cargo.toml
  node/gum/proc-macro/Cargo.toml
  node/network/availability-distribution/Cargo.toml
  node/network/availability-recovery/Cargo.toml
  node/network/bridge/src/validator_discovery.rs
  node/network/dispute-distribution/Cargo.toml
  node/network/gossip-support/src/tests.rs
  node/overseer/Cargo.toml
  node/service/Cargo.toml
  node/subsystem-types/Cargo.toml
  node/subsystem-util/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/constants/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/polkadot/constants/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/rococo/constants/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/test-runtime/constants/Cargo.toml
  runtime/westend/Cargo.toml
  runtime/westend/constants/Cargo.toml
  xcm/procedural/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7465 change HashFor to HashingFor
  Cargo.lock
  node/service/src/lib.rs
  rpc/src/lib.rs
Labels: B0-silent, A4-companion, C1-low, D3-trivial 🧸

#7551 Publish docker image description
  scripts/ci/dockerfiles/polkadot_Dockerfile.README.md
  scripts/ci/dockerfiles/staking-miner/staking-miner_Dockerfile.README.md
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#7552 Fix description filename
  scripts/ci/dockerfiles/polkadot_Dockerfile.README.md
  scripts/ci/dockerfiles/staking-miner/staking-miner_Dockerfile.README.md
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#7514 revert to old `handle_new_activations` logic in some cases
  node/collation-generation/src/lib.rs
  node/collation-generation/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️, T0-node

#7553 Fix ci syntax
  scripts/ci/dockerfiles/polkadot_Dockerfile.README.md
  scripts/ci/dockerfiles/staking-miner/staking-miner_Dockerfile.README.md
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#7143 Fix matrix rooms
  .github/workflows/burnin-label-notification.yml
  .github/workflows/release-10_candidate.yml
  .github/workflows/release-30_publish-draft-release.yml
  .github/workflows/release-99_bot.yml
  scripts/ci/common/lib.sh
Labels: A2-insubstantial, A0-please_review, B0-silent

#7558 Fix publish dockerhub description ci jobs
  scripts/ci/dockerfiles/polkadot_Dockerfile.README.md
  scripts/ci/dockerfiles/staking-miner/staking-miner_Dockerfile.README.md
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#7559 implementers-guide: drop WIP label in pre-checking section
  roadmap/implementers-guide/src/pvf-prechecking.md
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7529 Omnibus asynchronous backing bugfix PR
  node/core/backing/src/lib.rs
  node/core/backing/src/tests/mod.rs
  node/core/prospective-parachains/src/lib.rs
  node/core/prospective-parachains/src/tests.rs
  node/network/statement-distribution/src/vstaging/grid.rs
  node/network/statement-distribution/src/vstaging/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️
