Repository paritytech/polkadot, pull requests merged in 2023-04, with the labels that each got.

#6994 Update Substrate to fix Substrate companions
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#6993 Cache `SessionInfo` on new activated leaf in `dispute-distribution`
  node/network/dispute-distribution/src/sender/mod.rs
  node/network/dispute-distribution/src/tests/mod.rs
Labels: A0-please_review, B0-silent, C1-low, T5-parachains_protocol

#6986 Added `origin` to config for `universal_origin` benchmark
  runtime/kusama/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  xcm/pallet-xcm-benchmarks/src/generic/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T6-XCM

#6999 Substrate companion: Remove deprecated batch verification
  Cargo.lock
  node/core/pvf/src/executor_intf.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6990 PR review rules, include all rs files except weights
  .github/pr-custom-review.yml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6998 Companion for paritytech/substrate#13811
  Cargo.lock
  node/core/pvf/src/executor_intf.rs
  runtime/rococo/src/validator_manager.rs
  runtime/test-runtime/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T7-substrate

#7003 Co #13699: Remove old calls
  Cargo.lock
  runtime/polkadot/src/xcm_config.rs
  runtime/rococo/src/xcm_config.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7008 Expose WASM bulk memory extension in execution environment parameters
  node/core/pvf/src/executor_intf.rs
  primitives/src/v4/executor_params.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T4-parachains_engineering

#7012 PVF: Minor refactor in workers code
  node/core/pvf/src/error.rs
  node/core/pvf/src/execute/worker.rs
  node/core/pvf/src/lib.rs
  node/core/pvf/src/prepare/worker.rs
  node/core/pvf/src/worker_common.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T4-parachains_engineering

#7013 Onchain scraper in `dispute-coordinator` will scrape `SCRAPED_FINALIZED_BLOCKS_COUNT` blocks before finality
  node/core/dispute-coordinator/src/scraping/mod.rs
  node/core/dispute-coordinator/src/scraping/tests.rs
  node/primitives/src/lib.rs
Labels: A0-please_review, B0-silent, T5-parachains_protocol

#6963 scheduler: update storage migration
  runtime/kusama/src/lib.rs
  runtime/parachains/src/scheduler.rs
  runtime/parachains/src/scheduler/migration.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, E0-runtime_migration

#7025 Statement Distribution Guide Edits
  node/core/prospective-parachains/Cargo.toml
  node/subsystem-util/src/inclusion_emulator/staging.rs
  roadmap/implementers-guide/src/node/backing/statement-distribution.md
Labels: A0-please_review, B0-silent, C1-low

#7052 apply clippy 1.68 suggestions
  node/core/approval-voting/src/approval_db/v1/tests.rs
  node/core/approval-voting/src/criteria.rs
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/ops.rs
  node/core/approval-voting/src/tests.rs
  node/core/dispute-coordinator/src/import.rs
Labels: A0-please_review, B0-silent, C1-low

#7050 use stable rust toolchain in ci
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A2-insubstantial, B0-silent, C1-low

#7057 Invoke cargo build commands with `--locked`
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/check.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A2-insubstantial, B0-silent, C1-low

#7049 [Deps] bump scale-info to be in line with cumulus
  Cargo.lock
  core-primitives/Cargo.toml
  parachain/Cargo.toml
  primitives/Cargo.toml
  runtime/common/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  xcm/Cargo.toml
  xcm/pallet-xcm-benchmarks/Cargo.toml
  xcm/pallet-xcm/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-simulator/example/Cargo.toml
  xcm/xcm-simulator/fuzzer/Cargo.toml
Labels: B0-silent, C1-low, D3-trivial 🧸, E2-dependencies

#7017 Use RuntimeHoldReason for the NIS pallet HoldReason
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/tests.rs
  runtime/rococo/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7038 `approval distribution`: trigger assignment/votes resend based on approval checking lag
  node/network/approval-distribution/src/lib.rs
  node/network/approval-distribution/src/tests.rs
  node/service/src/lib.rs
  node/service/src/relay_chain_selection.rs
  node/service/src/tests.rs
  node/subsystem-types/src/messages.rs
Labels: A0-please_review, B0-silent, C1-low

#7055 sc_executor: Use new_with_wasm_executor instead of deprecated new method
  Cargo.lock
  node/service/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6996 [CI] Add weights verification jobs
  .github/workflows/check-weights.yml
  scripts/ci/github/check_weights_swc.sh
  scripts/ci/github/verify_updated_weights.sh
Labels: A0-please_review, B0-silent, C1-low

#7078 Fix try-runtime CI
  scripts/ci/gitlab/pipeline/check.yml
Labels: A0-please_review, B0-silent, C1-low

#6934 Enable changing executor params through governance
  primitives/src/v4/executor_params.rs
  primitives/src/v4/mod.rs
  runtime/kusama/src/weights/runtime_parachains_configuration.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/benchmarking.rs
  runtime/parachains/src/configuration/migration.rs
  runtime/parachains/src/configuration/tests.rs
  runtime/parachains/src/session_info.rs
  runtime/polkadot/src/weights/runtime_parachains_configuration.rs
  runtime/rococo/src/weights/runtime_parachains_configuration.rs
  runtime/westend/src/weights/runtime_parachains_configuration.rs
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, T1-runtime, B1-note_worthy

#7086 Use `MaybeUninit` when calling `getrusage` (musl compatibility)
  node/core/pvf/src/prepare/memory_stats.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7083 sync versions with current release
  Cargo.lock
  Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸, T8-release

#7088 [XCM - UnpaidRemoteExporter] Remove unreachable code
  xcm/xcm-builder/src/universal_exports.rs
Labels: A0-please_review, B0-silent

#7059 companion for substrate#13883
  Cargo.lock
  node/service/src/lib.rs
  rpc/src/lib.rs
Labels: A0-please_review, B0-silent, A4-companion, C1-low

#7040 Switch to DNS name based bootnodes for Rococo
  node/service/chain-specs/rococo.json
Labels: A0-please_review, C1-low, T0-node, B1-note_worthy

#7063 Companion for Substrate #13889
  Cargo.lock
  node/core/approval-voting/src/criteria.rs
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/tests.rs
  node/network/approval-distribution/src/tests.rs
  node/primitives/Cargo.toml
  node/primitives/src/approval.rs
  node/service/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6983 Companion for substrate#13771
  Cargo.lock
  runtime/polkadot/src/governance/old.rs
  runtime/rococo/src/lib.rs
Labels: A0-please_review, B0-silent, D3-trivial 🧸

#6551 pvf: Update docs for PVF artifacts
  node/core/pvf/src/artifacts.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6843 XCM: Properly set the pricing for the DMP router
  runtime/common/src/xcm_sender.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/kusama/src/xcm_config.rs
  runtime/parachains/src/dmp.rs
  runtime/parachains/src/dmp/tests.rs
  runtime/parachains/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/xcm_config.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/xcm_config.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/xcm_config.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/tests.rs
  xcm/src/v3/mod.rs
Labels: A0-please_review, C1-low, D1-audited 👍, T1-runtime, B1-note_worthy

#7011 PVF: Don't dispute on missing artifact
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/tests.rs
  node/core/pvf/src/execute/mod.rs
  node/core/pvf/src/execute/queue.rs
  node/core/pvf/src/execute/worker.rs
  node/core/pvf/src/host.rs
  node/core/pvf/tests/it/main.rs
  roadmap/implementers-guide/src/node/utility/candidate-validation.md
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T4-parachains_engineering

#7080 update safe call filter
  runtime/kusama/src/xcm_config.rs
  runtime/polkadot/src/xcm_config.rs
Labels: A0-please_review, B0-silent, C3-medium, D3-trivial 🧸

#7081 Reduce base proof size weight component to zero
  runtime/kusama/src/xcm_config.rs
  runtime/polkadot/src/xcm_config.rs
  xcm/src/v3/mod.rs
Labels: A0-please_review, B0-silent, C3-medium, D3-trivial 🧸

#7113 update rocksdb to 0.20.1
  Cargo.lock
  node/service/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, E2-dependencies

#7115 Revert default proof size back to 64 KB
  runtime/kusama/src/xcm_config.rs
  xcm/src/v3/mod.rs
Labels: A0-please_review, B0-silent, C3-medium, D3-trivial 🧸

#6968 Rework `dispute-coordinator` to use `RuntimeInfo` for obtaining session information instead of `RollingSessionWindow`
  node/core/dispute-coordinator/src/error.rs
  node/core/dispute-coordinator/src/import.rs
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, T5-parachains_protocol

#6662 XCM: Remote account converter
  xcm/xcm-builder/src/location_conversion.rs
Labels: A0-please_review, C1-low, D9-needsaudit 👮, T1-runtime, B1-note_worthy

#6991 Bump assigned_slots params
  runtime/rococo/src/lib.rs
Labels: B0-silent, D3-trivial 🧸

#7126 Fix rolling session window
  node/subsystem-util/src/rolling_session_window.rs
Labels: A0-please_review, B0-silent, C1-low

#7125 Fix stalling dispute coordinator.
  node/core/dispute-coordinator/src/initialized.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7114 Offences Migration v1: Removes `ReportsByKindIndex`
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  scripts/ci/gitlab/pipeline/check.yml
Labels: A0-please_review, D9-needsaudit 👮, E0-runtime_migration, C7-high, T1-runtime, B1-note_worthy

#6952 malus: dont panic on missing validation data
  node/malus/Cargo.toml
  node/malus/src/variants/suggest_garbage_candidate.rs
Labels: A0-please_review, B0-silent, C1-low

#7132 Clears Old Storage for Session pallet
  runtime/common/src/lib.rs
  runtime/common/src/session/migration.rs
  runtime/common/src/session/mod.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, E0-runtime_migration, T1-runtime

#7098 XCM: Implement a blocking barrier
  runtime/kusama/src/weights/pallet_xcm.rs
  runtime/polkadot/src/weights/pallet_xcm.rs
  runtime/rococo/src/weights/pallet_xcm.rs
  runtime/westend/src/weights/pallet_xcm.rs
  xcm/pallet-xcm/src/benchmarking.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/src/lib.rs
  xcm/src/v3/matcher.rs
  xcm/src/v3/mod.rs
  xcm/xcm-builder/src/barriers.rs
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/matcher.rs
  xcm/xcm-builder/src/tests/barriers.rs
  xcm/xcm-builder/src/tests/mock.rs
  xcm/xcm-builder/src/tests/mod.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-executor/src/traits/mod.rs
  xcm/xcm-executor/src/traits/should_execute.rs
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, T1-runtime, B1-note_worthy

#7141 ci: update check-runtime-migration fixme issues
  scripts/ci/gitlab/pipeline/check.yml
Labels: A2-insubstantial, B0-silent, C1-low

#7131 Add option to skip av-store requests in availability-recovery-subsystem
  node/network/availability-recovery/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T4-parachains_engineering
