Repository paritytech/polkadot, pull requests merged in 2023-03, with the labels that each got.

#6314 Add async-backing zombienet tests
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/zombienet.yml
  zombienet_tests/async_backing/001-async-backing-compatibility.toml
  zombienet_tests/async_backing/001-async-backing-compatibility.zndsl
  zombienet_tests/async_backing/002-async-backing-runtime-upgrade.toml
  zombienet_tests/async_backing/002-async-backing-runtime-upgrade.zndsl
  zombienet_tests/async_backing/003-async-backing-collator-mix.toml
  zombienet_tests/async_backing/003-async-backing-collator-mix.zndsl
  zombienet_tests/async_backing/README.md
Labels: I5-tests, A0-please_review, B0-silent, C1-low

#6738 Async backing: impl guide for statement distribution
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/backing/statement-distribution-legacy.md
  roadmap/implementers-guide/src/node/backing/statement-distribution.md
Labels: I7-documentation, A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6800 (companion) Bump `crossbeam-utils` 0.8.9 -> 0.8.14
  Cargo.lock
Labels: A0-please_review, B0-silent, A4-companion, C1-low, D3-trivial 🧸

#6806 changelog: fix migration listing
  scripts/ci/changelog/templates/migrations-db.md.tera
  scripts/ci/changelog/templates/migrations-runtime.md.tera
Labels: A0-please_review, B0-silent, C1-low, T8-release

#6808 Get rid of unnecessary cloning and work.
  node/core/dispute-coordinator/src/initialized.rs
Labels: A0-please_review, B0-silent, C1-low

#6739 [XCM] Multiple `FungiblesAdapter`s support + `WeightTrader::buy_weight` more accurate error
  xcm/xcm-builder/src/asset_conversion.rs
  xcm/xcm-builder/src/currency_adapter.rs
  xcm/xcm-executor/src/traits/token_matching.rs
  xcm/xcm-executor/src/traits/weight.rs
  xcm/xcm-simulator/example/src/parachain.rs
Labels: A0-please_review, B0-silent, C1-low, T6-XCM

#6809 Companion for substrate#13509: bump API versions of {Beefy,Mmr}Api
  Cargo.lock
  runtime/rococo/src/lib.rs
Labels: A0-please_review, B0-silent, A4-companion, C1-low, D2-notlive 💤

#6815 Forgotten re-export for `MatchedConvertedConcreteId`
  xcm/xcm-builder/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, T6-XCM

#6814 Removing Outdated References to Misbehavior Arbitration Subsystem
  node/subsystem-types/src/messages.rs
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/node/backing/statement-distribution.md
  roadmap/implementers-guide/src/node/utility/misbehavior-arbitration.md
  roadmap/implementers-guide/src/node/utility/provisioner.md
  roadmap/implementers-guide/src/types/overseer-protocol.md
Labels: A0-please_review, B0-silent, C1-low

#6816 Bump parity-db
  Cargo.lock
  node/service/Cargo.toml
  node/subsystem-util/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low

#6818 Freeze note on `SessionInfo`.
  primitives/src/v2/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview

#5999 Asynchronous backing statement distribution: Take III
  Cargo.lock
  node/core/backing/src/lib.rs
  node/core/backing/src/tests/prospective_parachains.rs
  node/core/prospective-parachains/src/fragment_tree.rs
  node/core/prospective-parachains/src/lib.rs
  node/core/prospective-parachains/src/tests.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/lib.rs
  node/network/protocol/src/request_response/mod.rs
  node/network/protocol/src/request_response/outgoing.rs
  node/network/protocol/src/request_response/vstaging.rs
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/error.rs
  node/network/statement-distribution/src/legacy_v1/mod.rs
  node/network/statement-distribution/src/legacy_v1/responder.rs
  node/network/statement-distribution/src/legacy_v1/tests.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/vstaging/candidates.rs
  node/network/statement-distribution/src/vstaging/cluster.rs
  node/network/statement-distribution/src/vstaging/grid.rs
  node/network/statement-distribution/src/vstaging/groups.rs
  node/network/statement-distribution/src/vstaging/mod.rs
  node/network/statement-distribution/src/vstaging/requests.rs
  node/network/statement-distribution/src/vstaging/statement_store.rs
  node/network/statement-distribution/src/vstaging/tests/cluster.rs
  node/network/statement-distribution/src/vstaging/tests/grid.rs
  node/network/statement-distribution/src/vstaging/tests/mod.rs
  node/network/statement-distribution/src/vstaging/tests/requests.rs
  node/overseer/src/lib.rs
  node/primitives/src/lib.rs
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-util/src/lib.rs
  primitives/src/v2/mod.rs
  primitives/test-helpers/src/lib.rs
  runtime/parachains/src/inclusion/mod.rs
Labels: A0-please_review, B0-silent, D2-notlive 💤, A0-pleasereview

#6756 Introduce XCM matcher for writing barriers
  xcm/src/lib.rs
  xcm/src/v3/matcher.rs
  xcm/src/v3/mod.rs
  xcm/src/v3/traits.rs
  xcm/xcm-builder/src/barriers.rs
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, T1-runtime, B1-note_worthy

#6820 Change handle_import_statements to FatalResult
  node/core/dispute-coordinator/src/backend.rs
  node/core/dispute-coordinator/src/db/v1.rs
  node/core/dispute-coordinator/src/initialized.rs
Labels: A0-please_review, B0-silent, C1-low

#6775 Additional tracing in `provisioner`, `vote_selection` and `dispute-coordinator`
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/scraping/mod.rs
  node/core/provisioner/src/disputes/prioritized_selection/mod.rs
  node/core/provisioner/src/lib.rs
  node/core/provisioner/src/metrics.rs
Labels: B0-silent, C1-low, A0-pleasereview

#6826 Decrease expected peer count in zombinenet tests
  zombienet_tests/functional/0001-parachains-pvf.zndsl
  zombienet_tests/functional/0002-parachains-disputes.zndsl
  zombienet_tests/misc/0001-paritydb.zndsl
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6788 Polkadot XCM Body constants
  runtime/polkadot/constants/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6727 Don't send `ActiveLeaves` from leaves in db on startup in Overseer
  node/overseer/src/dummy.rs
  node/overseer/src/lib.rs
  node/overseer/src/tests.rs
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/subsystem-test-helpers/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, T4-parachains_engineering

#6804 changelog: update template for new label behavior (E3/E4)
  scripts/ci/changelog/templates/host_functions.md.tera
Labels: A0-please_review, B0-silent, C1-low, T8-release

#6829 Bump `blake2b_simd` to 1.0.1
  Cargo.lock
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6773 bump `zombienet` version to v1.3.37
  .gitlab-ci.yml
  zombienet_tests/functional/0001-parachains-pvf.zndsl
  zombienet_tests/functional/0002-parachains-disputes.zndsl
  zombienet_tests/functional/0003-beefy-and-mmr.zndsl
  zombienet_tests/functional/0003-parachains-garbage-candidate.zndsl
  zombienet_tests/misc/0001-paritydb.zndsl
  zombienet_tests/misc/0002-upgrade-node.zndsl
  zombienet_tests/smoke/0001-parachains-smoke-test.zndsl
  zombienet_tests/smoke/0002-parachains-upgrade-smoke-test.zndsl
  zombienet_tests/smoke/0003-deregister-register-validator-smoke.zndsl
Labels: A0-please_review, B0-silent, C1-low, A0-pleasereview

#6837 Remove hardcoded paths from `dispute-valid-block` zombienet test for malus
  node/malus/integrationtests/0001-dispute-valid-block.toml
Labels: B0-silent, C1-low, T4-parachains_engineering, A0-pleasereview

#6784 Companion for Substrate #13425
  Cargo.lock
  runtime/common/src/integration_tests.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, D3-trivial 🧸

#6839 Correct xcm comment
  xcm/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6823 Move PVF timeouts to executor environment parameters
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/backing/src/tests.rs
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/tests.rs
  node/core/dispute-coordinator/src/participation/mod.rs
  node/core/dispute-coordinator/src/participation/tests.rs
  node/core/pvf/src/execute/queue.rs
  node/core/pvf/src/executor_intf.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/lib.rs
  node/core/pvf/src/metrics.rs
  node/core/pvf/src/prepare/pool.rs
  node/core/pvf/src/prepare/queue.rs
  node/core/pvf/src/prepare/worker.rs
  node/core/pvf/src/pvf.rs
  node/core/pvf/tests/it/main.rs
  node/overseer/examples/minimal-example.rs
  node/overseer/src/tests.rs
  node/primitives/src/lib.rs
  node/subsystem-types/src/messages.rs
  primitives/src/lib.rs
  primitives/src/v2/mod.rs
  primitives/src/vstaging/executor_params.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️, T4-parachains_engineering

#6852 Update `wasmtime` to 6.0.1 (0.9.39 branch)
  Cargo.lock
Labels: I2-security, A0-please_review, D3-trivial 🧸, C9-critical, T0-node, B1-note_worthy

#6851 Update `wasmtime` to 6.0.1 / `substrate` to 48e7cb147cb9a27125fd2e82edbcf4d0ed5927c4
  Cargo.lock
Labels: I2-security, A0-please_review, D3-trivial 🧸, C9-critical, T0-node, B1-note_worthy

#6755 Async Backing: Statement Distribution Tests
  node/network/protocol/src/lib.rs
  node/network/statement-distribution/src/vstaging/grid.rs
  node/network/statement-distribution/src/vstaging/mod.rs
  node/network/statement-distribution/src/vstaging/tests/cluster.rs
  node/network/statement-distribution/src/vstaging/tests/grid.rs
  node/network/statement-distribution/src/vstaging/tests/mod.rs
  node/network/statement-distribution/src/vstaging/tests/requests.rs
  node/subsystem-types/src/messages.rs
Labels: A3-in_progress, B0-silent, C1-low, D3-trivial 🧸

#6838 Adding Dispute Participation Metrics
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/metrics.rs
  node/core/dispute-coordinator/src/participation/mod.rs
  node/core/dispute-coordinator/src/participation/queues/mod.rs
  node/core/dispute-coordinator/src/participation/queues/tests.rs
  node/core/dispute-coordinator/src/participation/tests.rs
Labels: A0-please_review, B0-silent, C1-low

#6845 Companion for Substrate #13564
  Cargo.lock
  runtime/rococo/src/lib.rs
Labels: A0-please_review, B0-silent, D3-trivial 🧸

#6835 Remove use of Store trait
  Cargo.lock
  primitives/src/v2/mod.rs
  runtime/common/src/assigned_slots.rs
  runtime/common/src/auctions.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan/mod.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/paras_sudo_wrapper.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots/mod.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/migration.rs
  runtime/parachains/src/configuration/tests.rs
  runtime/parachains/src/dmp.rs
  runtime/parachains/src/dmp/tests.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/hrmp/tests.rs
  runtime/parachains/src/inclusion/mod.rs
  runtime/parachains/src/initializer.rs
  runtime/parachains/src/initializer/tests.rs
  runtime/parachains/src/origin.rs
  runtime/parachains/src/paras/benchmarking.rs
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras/tests.rs
  runtime/parachains/src/paras_inherent/mod.rs
  runtime/parachains/src/scheduler.rs
  runtime/parachains/src/scheduler/tests.rs
  runtime/parachains/src/session_info.rs
  runtime/parachains/src/shared.rs
  runtime/parachains/src/ump.rs
  runtime/parachains/src/ump/tests.rs
  runtime/test-runtime/src/lib.rs
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/migration.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/fuzzer/src/parachain.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#6870 Delete unused `Cargo.lock`
  utils/staking-miner/Cargo.lock
Labels: A2-insubstantial, A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6854 Update orchestra to the recent version
  Cargo.lock
  node/core/pvf/Cargo.toml
  node/metrics/Cargo.toml
  node/overseer/Cargo.toml
  node/overseer/src/lib.rs
  node/overseer/src/tests.rs
  node/subsystem-types/Cargo.toml
  node/subsystem-util/Cargo.toml
Labels: U2-some_time_soon, B0-silent, C1-low, T4-parachains_engineering, A1-needs_burnin, A0-pleasereview

#6869 Companion for paritytech/substrate#13592
  Cargo.lock
  node/network/bridge/Cargo.toml
  node/network/bridge/src/network.rs
  node/network/protocol/Cargo.toml
  node/network/protocol/src/peer_set.rs
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/test/service/Cargo.toml
  node/test/service/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6873 PVF: Document that preparation cannot lead to disputes
  node/core/candidate-validation/src/lib.rs
  node/core/pvf/src/error.rs
  roadmap/implementers-guide/src/node/utility/pvf-prechecker.md
  roadmap/implementers-guide/src/pvf-prechecking.md
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6877 Polkadot: add Council to SpendOrigin
  runtime/polkadot/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6842 companion for #13555
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, A4-companion, C1-low, D3-trivial 🧸

#6264 polkadot companion: #13128 (Pools commission)
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_nomination_pools.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_nomination_pools.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/pallet_nomination_pools.rs
Labels: A0-please_review, C1-low, D9-needsaudit 👮, E0-runtime_migration, T1-runtime, B1-note_worthy

#6885 Release parachain host API v4
  node/core/candidate-validation/src/lib.rs
  node/core/pvf/src/artifacts.rs
  node/core/pvf/src/execute/queue.rs
  node/core/pvf/src/execute/worker.rs
  node/core/pvf/src/executor_intf.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/pvf.rs
  node/core/pvf/src/testing.rs
  node/core/pvf/tests/it/main.rs
  node/core/runtime-api/src/cache.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-types/src/runtime_client.rs
  node/subsystem-util/src/lib.rs
  node/test/performance-test/src/lib.rs
  primitives/src/lib.rs
  primitives/src/runtime_api.rs
  primitives/src/v4/executor_params.rs
  primitives/src/v4/metrics.rs
  primitives/src/v4/mod.rs
  primitives/src/v4/signed.rs
  primitives/src/vstaging/mod.rs
  runtime/kusama/src/lib.rs
  runtime/parachains/src/runtime_api_impl/mod.rs
  runtime/parachains/src/runtime_api_impl/v4.rs
  runtime/parachains/src/runtime_api_impl/vstaging.rs
  runtime/parachains/src/session_info.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, T2-API, B1-note_worthy

#6890 timestamp ci job logs
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, B0-silent, C1-low

#6655 Companion for #13287
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, T1-runtime, B1-note_worthy

#6882 Issue 4393: Correcting Unnecessary Use of Arc
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/participation/queues/mod.rs
  node/core/dispute-coordinator/src/participation/queues/tests.rs
  node/core/dispute-coordinator/src/participation/tests.rs
Labels: A0-please_review, B0-silent, C1-low

#6855 XCM tweaks for OpenGov
  runtime/polkadot/constants/src/lib.rs
  runtime/polkadot/src/xcm_config.rs
Labels: A0-please_review

#6884 remove duplicated arm and fix version index
  Cargo.lock
  xcm/Cargo.toml
  xcm/src/lib.rs
  xcm/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#6880 Testing Reversion Speed on Dispute Concluded Against
  node/core/chain-selection/src/tree.rs
  node/core/dispute-coordinator/src/initialized.rs
Labels: A0-please_review, B0-silent, C1-low

#6896 parachains-runtime: Less cloning!
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/disputes/tests.rs
  runtime/parachains/src/paras_inherent/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6898 Fix approval voting test
  node/core/approval-voting/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low

#6892 [Companion #13615] Keystore overhaul
  Cargo.lock
  node/core/approval-voting/src/criteria.rs
  node/core/approval-voting/src/tests.rs
  node/core/backing/src/lib.rs
  node/core/backing/src/tests.rs
  node/core/bitfield-signing/src/lib.rs
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/tests.rs
  node/core/provisioner/src/tests.rs
  node/core/pvf-checker/src/lib.rs
  node/core/pvf-checker/src/tests.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/tests/mod.rs
  node/network/availability-distribution/src/tests/state.rs
  node/network/bitfield-distribution/src/tests.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests.rs
  node/network/dispute-distribution/src/lib.rs
  node/network/dispute-distribution/src/tests/mock.rs
  node/network/dispute-distribution/src/tests/mod.rs
  node/network/gossip-support/src/lib.rs
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/tests.rs
  node/primitives/src/disputes/mod.rs
  node/service/src/lib.rs
  node/subsystem-test-helpers/src/mock.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/runtime/mod.rs
  primitives/src/v4/signed.rs
  roadmap/implementers-guide/src/node/approval/approval-voting.md
  rpc/src/lib.rs
  runtime/common/src/crowdloan/mod.rs
  runtime/common/src/integration_tests.rs
  runtime/parachains/src/inclusion/tests.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras/tests.rs
  runtime/parachains/src/paras_inherent/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6907 changelog: template fixup
  scripts/ci/changelog/templates/host_functions.md.tera
Labels: A2-insubstantial, B0-silent, C1-low, A6-backport, T8-release

#6780 Deprecate Currency: Companion for #12951
  Cargo.lock
  node/test/service/src/lib.rs
  node/test/service/tests/call-function.rs
  runtime/common/src/assigned_slots.rs
  runtime/common/src/auctions.rs
  runtime/common/src/claims.rs
  runtime/common/src/crowdloan/mod.rs
  runtime/common/src/impls.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/purchase.rs
  runtime/common/src/slots/mod.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_balances.rs
  runtime/kusama/src/weights/pallet_balances_nis_counterpart_balances.rs
  runtime/parachains/src/hrmp/benchmarking.rs
  runtime/parachains/src/mock.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_balances.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/weights/pallet_balances.rs
  runtime/rococo/src/weights/pallet_balances_nis_counterpart_balances.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/pallet_balances.rs
  xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/xcm-builder/src/fungibles_adapter.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
  xcm/xcm-simulator/fuzzer/src/parachain.rs
  xcm/xcm-simulator/fuzzer/src/relay_chain.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#6916 Revert orchestra update
  Cargo.lock
  node/core/pvf/Cargo.toml
  node/metrics/Cargo.toml
  node/overseer/Cargo.toml
  node/overseer/src/lib.rs
  node/overseer/src/tests.rs
  node/subsystem-types/Cargo.toml
  node/subsystem-util/Cargo.toml
Labels: A0-please_review, U1-asap, B0-silent, C1-low

#6913 [Companion #13634] keystore overhaul (iter2)
  Cargo.lock
  node/service/src/lib.rs
  node/test/service/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6901 Handling timers for repeat dispute participation requests
  node/core/dispute-coordinator/src/participation/queues/mod.rs
  node/core/dispute-coordinator/src/participation/queues/tests.rs
Labels: A0-please_review, B0-silent, C1-low

#6921 Bump parity-db
  Cargo.lock
  node/service/Cargo.toml
  node/subsystem-util/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6915 introduce well known key for fetching committed para head
  primitives/src/v4/mod.rs
  runtime/parachains/src/paras/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#5974 kusama: enable dispute slashes
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/runtime_parachains_disputes_slashing.rs
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, T1-runtime, B1-note_worthy

#6924 Companion for #13624
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#6931 runtime/inclusion: fix availability_threshold
  primitives/src/v4/mod.rs
  runtime/parachains/src/inclusion/mod.rs
  runtime/parachains/src/inclusion/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6932 move back to ci-linux@production image
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-silent, C1-low

#6945 Bump parity-scale-codec to v 3.4.0
  Cargo.lock
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/collation-generation/Cargo.toml
  node/core/approval-voting/Cargo.toml
  node/core/av-store/Cargo.toml
  node/core/candidate-validation/Cargo.toml
  node/core/chain-api/Cargo.toml
  node/core/chain-selection/Cargo.toml
  node/core/dispute-coordinator/Cargo.toml
  node/core/pvf/Cargo.toml
  node/jaeger/Cargo.toml
  node/metrics/Cargo.toml
  node/network/availability-distribution/Cargo.toml
  node/network/availability-recovery/Cargo.toml
  node/network/bridge/Cargo.toml
  node/network/collator-protocol/Cargo.toml
  node/network/dispute-distribution/Cargo.toml
  node/network/protocol/Cargo.toml
  node/network/statement-distribution/Cargo.toml
  node/primitives/Cargo.toml
  node/subsystem-util/Cargo.toml
  node/test/client/Cargo.toml
  node/zombienet-backchannel/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/undying/Cargo.toml
  parachain/test-parachains/undying/collator/Cargo.toml
  primitives/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/slot_range_helper/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/metrics/Cargo.toml
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  statement-table/Cargo.toml
  utils/staking-miner/Cargo.toml
  xcm/Cargo.toml
  xcm/pallet-xcm-benchmarks/Cargo.toml
  xcm/pallet-xcm/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
  xcm/xcm-simulator/Cargo.toml
  xcm/xcm-simulator/example/Cargo.toml
  xcm/xcm-simulator/fuzzer/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6937 inherent disputes: remove per block initializer and disputes timeout event
  roadmap/implementers-guide/src/disputes-flow.md
  roadmap/implementers-guide/src/protocol-disputes.md
  roadmap/implementers-guide/src/runtime/disputes.md
  roadmap/implementers-guide/src/types/runtime.md
  runtime/kusama/src/lib.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/migration.rs
  runtime/parachains/src/configuration/tests.rs
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/disputes/tests.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, E0-runtime_migration, T1-runtime, B1-note_worthy

#6944 Companion for #13683
  Cargo.lock
  node/core/backing/src/tests.rs
  node/core/dispute-coordinator/src/tests.rs
  node/core/provisioner/src/tests.rs
  node/core/pvf-checker/src/tests.rs
  node/network/bitfield-distribution/src/tests.rs
  node/network/dispute-distribution/src/tests/mock.rs
  node/network/gossip-support/src/lib.rs
  node/network/statement-distribution/src/tests.rs
  node/primitives/src/disputes/mod.rs
  node/subsystem-test-helpers/src/mock.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/runtime/mod.rs
  primitives/src/v4/signed.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6905 Subsystem channel tweaks
  Cargo.lock
  node/network/bridge/src/rx/mod.rs
  node/overseer/Cargo.toml
  node/overseer/src/lib.rs
  node/subsystem-types/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low

#6957 Nomination Pools migration v5: RewardPool fix
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/parachains/src/configuration/migration.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, B0-silent, D9-needsaudit 👮, E0-runtime_migration, C9-critical

#6846 Proxy for Nomination Pools
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: C1-low, D3-trivial 🧸, T1-runtime, B1-note_worthy

#6935 Histogram support in runtime metrics
  Cargo.lock
  node/metrics/src/runtime/mod.rs
  node/metrics/src/runtime/parachain.rs
  primitives/src/v4/metrics.rs
  runtime/metrics/Cargo.toml
  runtime/metrics/src/with_runtime_metrics.rs
  runtime/metrics/src/without_runtime_metrics.rs
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/metrics.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T4-parachains_engineering

#6961 configuration: backport async backing parameters from the feature branch
  primitives/src/vstaging/mod.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/migration.rs
  runtime/parachains/src/configuration/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, E0-runtime_migration

#6861 Check spawned worker version vs node version before PVF preparation
  Cargo.lock
  cli/src/cli.rs
  cli/src/command.rs
  node/core/pvf/Cargo.toml
  node/core/pvf/build.rs
  node/core/pvf/src/execute/worker.rs
  node/core/pvf/src/lib.rs
  node/core/pvf/src/prepare/worker.rs
  node/core/pvf/src/testing.rs
  node/core/pvf/src/worker_common.rs
  node/core/pvf/tests/it/worker_common.rs
  node/malus/src/malus.rs
Labels: A0-please_review, B0-silent, C1-low, T4-parachains_engineering

#6980 Tighter bound on asset types teleported so that weight is cheaper
  xcm/pallet-xcm/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, T1-runtime, B1-note_worthy

#6981 Use `SIGTERM` instead of `SIGKILL` on PVF worker version mismatch
  node/core/pvf/src/worker_common.rs
Labels: A0-please_review, B0-silent, C1-low, T4-parachains_engineering

#6974 Drop timers for new requests of active participations
  node/core/dispute-coordinator/src/participation/mod.rs
  node/core/dispute-coordinator/src/participation/queues/mod.rs
Labels: A0-please_review, B0-silent, C1-low

#6903 Add crowdloan to SafeCallFilter
  runtime/kusama/src/xcm_config.rs
  runtime/polkadot/src/xcm_config.rs
  runtime/rococo/src/xcm_config.rs
  runtime/westend/src/xcm_config.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6802 approval-voting: simplify v2 assignments
  Cargo.lock
  node/core/approval-voting/src/approval_db/v1/mod.rs
  node/core/approval-voting/src/criteria.rs
  node/core/approval-voting/src/lib.rs
  node/core/approval-voting/src/persisted_entries.rs
  node/network/approval-distribution/Cargo.toml
  node/network/approval-distribution/src/lib.rs
  node/network/bridge/src/rx/mod.rs
  node/network/protocol/src/lib.rs
  node/primitives/Cargo.toml
  node/primitives/src/approval.rs
  node/service/src/parachains_db/upgrade.rs
  node/subsystem-types/Cargo.toml
  node/subsystem-types/src/messages.rs
  roadmap/implementers-guide/src/node/approval/approval-voting.md
Labels: A0-please_review, B0-silent, C1-low

#6989 Avoid redundant clone.
  runtime/parachains/src/paras_inherent/mod.rs
Labels: A2-insubstantial, A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6458 Consolidate subsystem spans so they are all children of the leaf-activated root span
  Cargo.lock
  node/core/approval-voting/src/import.rs
  node/core/approval-voting/src/lib.rs
  node/jaeger/src/spans.rs
  node/network/approval-distribution/Cargo.toml
  node/network/approval-distribution/src/lib.rs
  node/network/availability-distribution/src/lib.rs
  node/network/availability-distribution/src/pov_requester/mod.rs
  node/network/availability-distribution/src/requester/fetch_task/mod.rs
  node/network/availability-distribution/src/requester/mod.rs
  node/network/availability-distribution/src/requester/tests.rs
  node/network/availability-distribution/src/responder.rs
Labels: B0-silent, C1-low
