Repository paritytech/polkadot, pull requests merged in 2023-08, with the labels that each got.

#7566 PVF: Fix external workers being required for non-collator full nodes
  cli/src/cli.rs
  node/service/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7563 ` XcmContext` to `buy_weight / refund_weight`
  runtime/test-runtime/src/xcm_config.rs
  xcm/xcm-builder/src/tests/weight.rs
  xcm/xcm-builder/src/weight.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-executor/src/traits/weight.rs
Labels: A0-please_review, B0-silent, C1-low, T6-XCM

#7369 Take into account size as well in weight limiting.
  Cargo.lock
  node/core/provisioner/Cargo.toml
  node/core/provisioner/src/disputes/mod.rs
  node/core/provisioner/src/disputes/random_selection/mod.rs
  node/core/provisioner/src/lib.rs
  primitives/src/v5/mod.rs
  runtime/kusama/src/weights/runtime_parachains_paras_inherent.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/paras_inherent/mod.rs
  runtime/parachains/src/paras_inherent/tests.rs
  runtime/parachains/src/paras_inherent/weights.rs
  runtime/polkadot/src/weights/runtime_parachains_paras_inherent.rs
  runtime/westend/src/weights/runtime_parachains_paras_inherent.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#7572 Companion for Substrate#14373
  Cargo.lock
  node/service/src/chain_spec.rs
  node/service/src/fake_runtime_api.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/xcm_config.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7517 [xcm] `GlobalConsensusConvertsFor` for remote relay chain (based on pevious GlobalConsensusParachainConvertsFor)
  xcm/src/v3/multiasset.rs
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/location_conversion.rs
Labels: A0-please_review, B0-silent, C1-low

#7550 Fix flaky reputation change test
  node/network/bitfield-distribution/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low

#7235 Remove xcm on_runtime_upgrade pallet hook
  xcm/pallet-xcm/src/lib.rs
  xcm/pallet-xcm/src/migration.rs
  xcm/pallet-xcm/src/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, E0-runtime_migration

#7587 PVF: Add missing crate descriptions
  node/core/candidate-validation/Cargo.toml
  node/core/pvf-checker/Cargo.toml
  node/core/pvf/Cargo.toml
  node/core/pvf/common/Cargo.toml
  node/core/pvf/common/src/lib.rs
  node/core/pvf/execute-worker/Cargo.toml
  node/core/pvf/execute-worker/src/lib.rs
  node/core/pvf/prepare-worker/Cargo.toml
  node/core/pvf/prepare-worker/src/lib.rs
  node/core/pvf/src/lib.rs
Labels: I7-documentation, A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7589 update weight file template
  xcm/pallet-xcm-benchmarks/template.hbs
Labels: A0-please_review, B0-silent, C1-low

#7547 Companion for #14412
  Cargo.lock
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7540 Remove unused code in runtime/polkadot/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#6807 Companion for substrate#12970
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, C3-medium, D1-audited 👍, T1-runtime, B1-note_worthy

#7491 Add counter for unapproved candidates
  node/core/approval-voting/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low

#7556 Publish RC container images
  .github/workflows/check-licenses.yml
  .github/workflows/release-40_publish-rc-image.yml
  .github/workflows/release-50_publish-docker-release.yml
  .github/workflows/release-51_publish-docker-manual.yml
  .gitignore
  .gitlab-ci.yml
  doc/docker.md
  scripts/ci/common/lib.sh
  scripts/ci/dockerfiles/adder-collator/build-injected.sh
  scripts/ci/dockerfiles/adder-collator/test-build.sh
  scripts/ci/dockerfiles/binary_injected.Dockerfile
  scripts/ci/dockerfiles/build-injected.sh
  scripts/ci/dockerfiles/collator_injected.Dockerfile
  scripts/ci/dockerfiles/entrypoint.sh
  scripts/ci/dockerfiles/malus/build-injected.sh
  scripts/ci/dockerfiles/malus/test-build.sh
  scripts/ci/dockerfiles/malus_injected.Dockerfile
  scripts/ci/dockerfiles/polkadot/README.md
  scripts/ci/dockerfiles/polkadot/build-injected.sh
  scripts/ci/dockerfiles/polkadot/build.sh
  scripts/ci/dockerfiles/polkadot/docker-compose.yml
  scripts/ci/dockerfiles/polkadot/polkadot_Dockerfile.README.md
  scripts/ci/dockerfiles/polkadot/polkadot_builder.Dockerfile
  scripts/ci/dockerfiles/polkadot/polkadot_injected_debian.Dockerfile
  scripts/ci/dockerfiles/polkadot/test-build.sh
  scripts/ci/dockerfiles/polkadot_injected_debug.Dockerfile
  scripts/ci/dockerfiles/staking-miner/README.md
  scripts/ci/dockerfiles/staking-miner/build-injected.sh
  scripts/ci/dockerfiles/staking-miner/build.sh
  scripts/ci/dockerfiles/staking-miner/staking-miner_builder.Dockerfile
  scripts/ci/dockerfiles/staking-miner/staking-miner_injected.Dockerfile
  scripts/ci/dockerfiles/staking-miner/test-build.sh
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/publish.yml
  utils/staking-miner/README.md
Labels: B0-silent, T8-release

#7600 companion for 14754: cli: move no-beefy flag to sc-cli
  Cargo.lock
  cli/src/cli.rs
  cli/src/command.rs
  node/service/src/lib.rs
  node/test/service/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
  parachain/test-parachains/undying/collator/src/main.rs
Labels: A0-please_review, B0-silent, A4-companion, C1-low

#7538 pvf: use test-utils feature to export test only
  Cargo.lock
  Cargo.toml
  node/core/pvf/Cargo.toml
  node/core/pvf/common/Cargo.toml
  node/core/pvf/common/src/lib.rs
  node/core/pvf/common/src/pvf.rs
  node/core/pvf/src/lib.rs
  node/core/pvf/src/testing.rs
  node/core/pvf/tests/it/worker_common.rs
  node/malus/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/undying/collator/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, E5-needs_cumulus_pr

#7607 RC container image fixes
  .github/workflows/release-40_publish-rc-image.yml
  scripts/ci/common/lib.sh
Labels: A0-please_review, B0-silent, C1-low

#7610 Fix the user used to login to Docker hub
  .github/workflows/release-40_publish-rc-image.yml
  scripts/ci/common/lib.sh
Labels: A0-please_review, B0-silent, C1-low

#7612 Remove ParityDb migration tests
  node/service/src/parachains_db/upgrade.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7601 Disable validation/collation protocols for normal full nodes
  node/service/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7608 PVF workers: some fixes for cargo run and cargo install
  README.md
  node/service/src/lib.rs
  parachain/test-parachains/adder/collator/README.md
  utils/staking-miner/README.md
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7614 [async backing branch] fix zombienet tests
  zombienet_tests/async_backing/002-async-backing-runtime-upgrade.toml
  zombienet_tests/async_backing/003-async-backing-collator-mix.zndsl
Labels: A0-please_review, B0-silent, C1-low

#7593 XCM: Rename Instruction instructions to Command instructions
  xcm/src/v2/mod.rs
  xcm/src/v3/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7617 Remove superflous parameter `overseer_enable_anyways` and make parachain node type more explicit
  cli/src/command.rs
  node/core/approval-voting/src/lib.rs
  node/core/pvf/execute-worker/src/lib.rs
  node/network/approval-distribution/src/lib.rs
  node/network/approval-distribution/src/tests.rs
  node/network/collator-protocol/src/lib.rs
  node/network/gossip-support/src/lib.rs
  node/network/statement-distribution/src/responder.rs
  node/service/src/lib.rs
  node/service/src/overseer.rs
  node/test/service/src/lib.rs
  parachain/test-parachains/adder/collator/src/main.rs
  parachain/test-parachains/undying/collator/src/main.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/paras_inherent/mod.rs
  runtime/parachains/src/runtime_api_impl/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#7217 Change the Config of the MaxRococoNum Slot from a Constant to a Storage function
  node/service/src/chain_spec.rs
  runtime/common/Cargo.toml
  runtime/common/src/assigned_slots/benchmarking.rs
  runtime/common/src/assigned_slots/migration.rs
  runtime/common/src/assigned_slots/mod.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
  runtime/rococo/src/weights/mod.rs
  runtime/rococo/src/weights/runtime_common_assigned_slots.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/mod.rs
  runtime/westend/src/weights/runtime_common_assigned_slots.rs
Labels: A3-in_progress, A0-please_review, C1-low, D3-trivial 🧸, E0-runtime_migration, T1-runtime, B1-note_worthy

#7618 attempt to fix zombienet disputes
  node/malus/integrationtests/0001-dispute-valid-block.zndsl
  node/malus/src/variants/common.rs
  parachain/test-parachains/undying/collator/src/lib.rs
  zombienet_tests/functional/0002-parachains-disputes.zndsl
  zombienet_tests/functional/0003-parachains-garbage-candidate.zndsl
  zombienet_tests/functional/0004-parachains-disputes-past-session.zndsl
  zombienet_tests/misc/0001-paritydb.zndsl
Labels: B0-silent, C1-low, D3-trivial 🧸, T0-node

#7625 Fix clippy warnings
  node/collation-generation/src/tests.rs
  node/core/av-store/src/tests.rs
  node/core/backing/src/tests.rs
  node/core/chain-selection/src/tests.rs
  node/core/dispute-coordinator/src/participation/queues/tests.rs
  node/core/dispute-coordinator/src/tests.rs
  node/core/provisioner/src/disputes/prioritized_selection/tests.rs
  node/core/pvf-checker/src/tests.rs
  node/core/pvf/tests/it/adder.rs
  node/core/runtime-api/src/tests.rs
  node/malus/src/variants/back_garbage_candidate.rs
  node/malus/src/variants/common.rs
  node/malus/src/variants/dispute_valid_candidates.rs
  node/malus/src/variants/suggest_garbage_candidate.rs
  node/network/approval-distribution/src/tests.rs
  node/network/availability-distribution/src/tests/state.rs
  node/network/availability-recovery/src/tests.rs
  node/network/bitfield-distribution/src/tests.rs
  node/network/bridge/src/rx/tests.rs
  node/network/bridge/src/tx/tests.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/collator-protocol/src/validator_side/tests.rs
  node/network/dispute-distribution/src/tests/mock.rs
  node/network/gossip-support/src/tests.rs
  node/network/statement-distribution/src/tests.rs
  node/service/src/tests.rs
  node/test/service/src/lib.rs
  runtime/common/src/auctions.rs
  runtime/common/src/crowdloan/mod.rs
  runtime/common/src/xcm_sender.rs
  runtime/parachains/src/builder.rs
  runtime/parachains/src/disputes/tests.rs
  runtime/parachains/src/inclusion/tests.rs
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras/tests.rs
  runtime/parachains/src/paras_inherent/tests.rs
  runtime/parachains/src/scheduler/tests.rs
  runtime/parachains/src/session_info/tests.rs
  runtime/parachains/src/ump_tests.rs
  scripts/ci/gitlab/pipeline/test.yml
  statement-table/src/generic.rs
  xcm/pallet-xcm/src/tests.rs
  xcm/xcm-builder/src/asset_conversion.rs
  xcm/xcm-builder/src/tests/assets.rs
  xcm/xcm-builder/src/tests/bridging/mod.rs
  xcm/xcm-builder/src/tests/bridging/paid_remote_relay_relay.rs
  xcm/xcm-builder/src/tests/mock.rs
  xcm/xcm-builder/src/tests/transacting.rs
  xcm/xcm-builder/src/tests/version_subscriptions.rs
  xcm/xcm-simulator/fuzzer/src/parachain.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7595 [Polkadot] 28 days as conviction voting period
  Cargo.toml
  runtime/polkadot/src/governance/mod.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, T1-runtime, B1-note_worthy

#7631 bump zombienet to `v1.3.65`
  .gitlab-ci.yml
  parachain/test-parachains/adder/collator/src/main.rs
  parachain/test-parachains/undying/collator/src/main.rs
  scripts/ci/gitlab/pipeline/zombienet.yml
Labels: A0-please_review, B0-silent, C1-low

#7599 cli: remove deprecated try-runtime subcommand (also companion for #14731)
  Cargo.lock
  cli/src/cli.rs
  cli/src/command.rs
  scripts/ci/gitlab/pipeline/check.yml
Labels: A0-please_review, C1-low, T0-node, B1-note_worthy

#7301 Polkadot gets topic-based message IDs
  runtime/polkadot/src/xcm_config.rs
  xcm/src/v3/junction.rs
Labels: A0-please_review, C1-low, D1-audited 👍, T1-runtime, B1-note_worthy

#7536 Companion for Substrate#14612
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/lib.rs
  utils/staking-miner/Cargo.toml
  utils/staking-miner/src/dry_run.rs
  utils/staking-miner/src/emergency_solution.rs
  utils/staking-miner/src/main.rs
  utils/staking-miner/src/monitor.rs
  utils/staking-miner/src/prelude.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7633 XCM: Replace council XCM origin with general admin
  runtime/kusama/src/xcm_config.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/xcm_config.rs
  runtime/rococo/src/xcm_config.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7314 migration: unlock/unreserve Gov v1 balances and remove kvs
  node/service/src/chain_spec.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/governance/mod.rs
  runtime/polkadot/src/governance/old.rs
  runtime/polkadot/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, E0-runtime_migration, T1-runtime, B1-note_worthy

#7636 protobuf is required dep for build
  README.md
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#7645 Fix cargo.toml
  Cargo.lock
  node/core/prospective-parachains/Cargo.toml
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/legacy_v1/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7638 scheduler migration minor fixes
  runtime/parachains/src/scheduler/migration.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#7330 PVF worker: Prevent access to env vars
  node/core/pvf/common/src/worker/mod.rs
  roadmap/implementers-guide/src/node/utility/pvf-host-and-workers.md
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T4-parachains_engineering

#7649 PVF worker: random fixes
  node/core/pvf/common/src/worker/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7591 Add BEEFY capabilities to Westend and Kusama
  Cargo.lock
  cli/src/command.rs
  node/service/src/chain_spec.rs
  node/service/src/lib.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/kusama/src/tests.rs
  runtime/parachains/src/disputes/slashing/benchmarking.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  runtime/westend/src/tests.rs
  scripts/prepare-test-net.sh
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, T0-node, B1-note_worthy

#7641 Bound number of assets which can be withdrawn to pay for execution.
  xcm/xcm-builder/src/barriers.rs
Labels: A0-please_review, B0-silent, C1-low, D9-needsaudit 👮, T1-runtime

#7652 Fix xcm-builder mock
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-builder/src/tests/pay/mock.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#7626 Companion: restructure macro related exports
  Cargo.lock
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
  xcm/xcm-executor/integration-tests/Cargo.toml
  xcm/xcm-executor/integration-tests/src/lib.rs
  xcm/xcm-simulator/example/src/lib.rs
Labels: A2-insubstantial, A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7659 primitives: make async backing params accessible for parachains
  primitives/src/v5/mod.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7661 cli: disallow BEEFY and warp sync together
  cli/src/command.rs
Labels: A0-please_review, C1-low, T0-node, B1-note_worthy

#7654 update readme: archived repo
  README.md
Labels: A2-insubstantial, B0-silent, C1-low, D2-notlive 💤
