Repository paritytech/polkadot, pull requests merged in 2023-01, with the labels that each got.

#6477 BlockId removal: refactor: BlockBackend::block|block_status
  Cargo.lock
  node/client/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6465 Deploy scheduler agenda cleanup migration
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸, E0-runtime_migration, A0-pleasereview

#6365 Migrate Staking pallet to v13
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️, E0-runtime_migration

#6498 Co #13045: Selectable on-runtime-upgrade checks
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6501 Add `try-runtime` to Rococo runtime
  Cargo.lock
  runtime/rococo/Cargo.toml
  runtime/rococo/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low 📌, D3-trivial 🧸, T4-parachains_engineering, A0-pleasereview

#6503 Fix `polkadot-runtime-constants` std build
  runtime/kusama/constants/Cargo.toml
  runtime/polkadot/constants/Cargo.toml
  runtime/rococo/constants/Cargo.toml
  runtime/westend/constants/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low 📌, D3-trivial 🧸

#6494 Issue 6274: keeping all backing votes in provisioner vote set
  node/core/provisioner/src/disputes/prioritized_selection/mod.rs
  roadmap/implementers-guide/src/node/utility/provisioner.md
Labels: B0-silent, C1-low 📌, A0-pleasereview

#6504 Log PVF retries
  node/core/candidate-validation/src/lib.rs
  node/core/pvf/src/host.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6286 Specify Ethereum networks by their chain id
  xcm/src/v3/junction.rs
Labels: A0-please_review, B0-silent, C1-low 📌, D3-trivial 🧸

#6500 upgrade libp2p to 0.50.0
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#6509 [ci] Remove check-transaction-versions job
  scripts/ci/gitlab/pipeline/build.yml
Labels: B0-silent, C1-low 📌, A0-pleasereview

#6085 Unlimited Proof size per block
  runtime/common/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️

#6484 Use `polkadot-node-metrics` where possible
  Cargo.lock
  node/core/candidate-validation/Cargo.toml
  node/core/candidate-validation/src/metrics.rs
  node/core/chain-api/Cargo.toml
  node/core/chain-api/src/metrics.rs
  node/core/runtime-api/Cargo.toml
  node/core/runtime-api/src/metrics.rs
  node/network/approval-distribution/Cargo.toml
  node/network/approval-distribution/src/metrics.rs
  node/network/bridge/Cargo.toml
  node/network/bridge/src/metrics.rs
Labels: A0-please_review, B0-silent, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6345 disputes pallet: Remove spam slots
  roadmap/implementers-guide/src/runtime/disputes.md
  runtime/kusama/src/lib.rs
  runtime/parachains/src/builder.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/configuration/migration.rs
  runtime/parachains/src/configuration/tests.rs
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/disputes/migration.rs
  runtime/parachains/src/disputes/tests.rs
  runtime/parachains/src/paras_inherent/mod.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: I7-refactor, A0-please_review, B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️, T5-parachains_protocol

#6525 Remove unused code in subsystem message implementations
  node/subsystem-types/src/messages.rs
Labels: A0-please_review, B0-silent, C1-low 📌, A0-pleasereview

#6524 Fix flaky test in `dispute-coordinator`
  node/core/dispute-coordinator/src/tests.rs
Labels: I5-tests, A0-please_review, B0-silent, C1-low 📌, T4-parachains_engineering

#6520 Guide changes 3
  roadmap/implementers-guide/src/node/collators/collation-generation.md
  roadmap/implementers-guide/src/node/utility/chain-selection.md
Labels: B0-silent, C1-low 📌, A0-pleasereview

#6419 Replace async-std with tokio in PVF subsystem
  Cargo.lock
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/tests.rs
  node/core/pvf/Cargo.toml
  node/core/pvf/src/artifacts.rs
  node/core/pvf/src/error.rs
  node/core/pvf/src/execute/queue.rs
  node/core/pvf/src/execute/worker.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/lib.rs
  node/core/pvf/src/prepare/pool.rs
  node/core/pvf/src/prepare/queue.rs
  node/core/pvf/src/prepare/worker.rs
  node/core/pvf/src/worker_common.rs
  node/core/pvf/tests/it/adder.rs
  node/core/pvf/tests/it/main.rs
  node/core/pvf/tests/it/worker_common.rs
  node/primitives/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low 📌, D3-trivial 🧸

#6489 Fix cycle dispute-coordinator <-> dispute-distribution
  Cargo.lock
  node/core/dispute-coordinator/Cargo.toml
  node/core/dispute-coordinator/src/import.rs
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/lib.rs
  node/core/dispute-coordinator/src/tests.rs
  node/network/dispute-distribution/src/lib.rs
  node/network/dispute-distribution/src/sender/mod.rs
  node/network/dispute-distribution/src/sender/send_task.rs
  node/network/dispute-distribution/src/tests/mod.rs
  node/primitives/src/disputes/message.rs
  node/subsystem-util/Cargo.toml
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/nesting_sender.rs
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
  roadmap/implementers-guide/src/node/disputes/dispute-distribution.md
Labels: B0-silent, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6532 Update the GHA srtool-actions to the latest version
  .github/workflows/release-30_publish-draft-release.yml
Labels: A2-insubstantial, A0-please_review, B0-silent, C1-low 📌, T8-release, A0-pleasereview

#6533 Minor fixes
  node/core/pvf/src/execute/worker.rs
  node/network/dispute-distribution/src/lib.rs
  node/subsystem-util/src/nesting_sender.rs
Labels: A0-please_review, B0-silent, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6522 Trigger update-node-template when a final release tag is created
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#6539 ci: mark update-weights non-interruptible
  scripts/ci/gitlab/pipeline/weights.yml
Labels: A0-please_review, B0-silent, C1-low 📌, A0-pleasereview

#6471 Improve inactive fund tracking
  runtime/common/src/crowdloan/migration.rs
  runtime/common/src/crowdloan/mod.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸, E0-runtime_migration, A0-pleasereview

#6531 Add a paragraph about slashing in runtime disputes section from the guide
  roadmap/implementers-guide/src/runtime/disputes.md
Labels: I6-documentation, B0-silent, C1-low 📌, T5-parachains_protocol, A0-pleasereview

#6336 Westend state trie to version 1
  Cargo.lock
  runtime/westend/Cargo.toml
  runtime/westend/src/lib.rs
Labels: A0-please_review, B1-releasenotes, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️, E0-runtime_migration, E1-database_migration, T0-node, T1-runtime

#6541 Handle substrate-node-template and substrate-parachain-template
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, D2-notlive 💤

#6537 pvf: Fix missing execution request when retrying preparation
  node/core/pvf/src/host.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6492 pre-checking: Reject failed PVFs
  node/collation-generation/src/lib.rs
  node/core/candidate-validation/src/lib.rs
  node/core/pvf-checker/src/lib.rs
  node/core/pvf-checker/src/tests.rs
  node/core/pvf/src/execute/queue.rs
  node/core/pvf/src/host.rs
  roadmap/implementers-guide/src/node/utility/pvf-prechecker.md
  roadmap/implementers-guide/src/pvf-prechecking.md
  runtime/parachains/src/paras/benchmarking/pvf_check.rs
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/paras/tests.rs
Labels: B1-releasenotes, C1-low 📌, D5-nicetohaveaudit ⚠️, A0-pleasereview

#6554 Fix set-output deprecation
  .github/workflows/release-10_candidate.yml
  .github/workflows/release-30_publish-draft-release.yml
Labels: B0-silent, C1-low 📌, A0-pleasereview

#6308 add erasure-coding benches
  Cargo.lock
  erasure-coding/Cargo.toml
  erasure-coding/benches/README.md
  erasure-coding/benches/scaling_with_validators.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#6562 CI: Code mark to request a pipeline failure
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, B0-silent, C1-low 📌, A0-pleasereview

#6566 Add runtime-benchmarks feature to test client and test service
  node/test/client/Cargo.toml
  node/test/service/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6490 Enable treasury.spend by Root origin for Polkadot network before Gov2
  runtime/polkadot/src/lib.rs
Labels: B7-runtimenoteworthy, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6569 Co #12928: NIS should retain funds in reserve
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_nis.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/weights/pallet_nis.rs
Labels: B7-runtimenoteworthy, A4-companion, C1-low 📌, D2-notlive 💤, A0-pleasereview

#6573 Allow AuctionAdmin to use Scheduler
  runtime/kusama/src/lib.rs
Labels: A0-please_review, B7-runtimenoteworthy, C1-low 📌, D5-nicetohaveaudit ⚠️

#6570 Companion for substrate#13154
  Cargo.lock
  node/client/src/lib.rs
Labels: B0-silent, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6579 Added `HaulBlobError` to pub re-exports
  xcm/xcm-builder/src/lib.rs
Labels: B0-silent, C1-low 📌

#6512 Issue 4804: Notify chain selection of concluded disputes directly
  node/core/chain-selection/src/lib.rs
  node/core/chain-selection/src/tests.rs
  node/core/chain-selection/src/tree.rs
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/scraping/candidates.rs
  node/core/dispute-coordinator/src/scraping/mod.rs
  node/core/dispute-coordinator/src/scraping/tests.rs
  node/core/dispute-coordinator/src/tests.rs
  node/overseer/src/lib.rs
  node/subsystem-types/src/messages.rs
  roadmap/implementers-guide/src/node/disputes/dispute-coordinator.md
  roadmap/implementers-guide/src/node/utility/chain-selection.md
Labels: B0-silent, C1-low 📌, A0-pleasereview

#6578 XCM: `ExpectTransactStatus` instruction
  runtime/kusama/src/weights/xcm/mod.rs
  runtime/kusama/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  runtime/rococo/src/weights/xcm/mod.rs
  runtime/rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  runtime/westend/src/weights/xcm/mod.rs
  runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  xcm/src/v3/mod.rs
  xcm/xcm-builder/src/tests/transacting.rs
  xcm/xcm-executor/src/lib.rs
Labels: B0-silent, C1-low 📌, D5-nicetohaveaudit ⚠️, A0-pleasereview

#6577 construct mmr leaf prior to session pallet hook
  runtime/rococo/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low 📌, D3-trivial 🧸

#6582 Companion for Substrate #13157
  Cargo.lock
Labels: B0-silent, C1-low 📌, D3-trivial 🧸, A0-pleasereview

#6583 Companion for substrate: Make DispatchError impl MEL
  Cargo.lock
Labels: B0-silent, A4-companion, C1-low 📌

#6585 Update changelog templates to use new labels
  scripts/ci/changelog/README.md
  scripts/ci/changelog/templates/change.md.tera
  scripts/ci/changelog/templates/changes_client.md.tera
  scripts/ci/changelog/templates/changes_misc.md.tera
  scripts/ci/changelog/templates/changes_runtime.md.tera
  scripts/ci/changelog/templates/high_priority.md.tera
Labels: A0-please_review, B0-silent, C1-low 📌, A0-pleasereview

#6556 sync versions with release branch (0.9.37)
  Cargo.lock
  Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low 📌, D3-trivial 🧸, A6-backport, A0-pleasereview

#6597 Disallow decoding of phantom asset
  xcm/src/v3/multiasset.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, C1-low 📌

#6595 docs: remove references to rpm
  .gitignore
  Cargo.toml
  README.md
Labels: A0-please_review, B0-silent, C1-low, A0-pleasereview

#6269 Warn validators with slow hardware
  Cargo.lock
  cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, C1-low 📌

#6103 Fix some unjustified disputes
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/tests.rs
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/participation/mod.rs
  node/malus/src/variants/common.rs
  node/primitives/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6606 XCM: Add HRMP to SafeCallFilter
  runtime/kusama/src/xcm_config.rs
  runtime/polkadot/src/xcm_config.rs
  runtime/rococo/src/xcm_config.rs
  runtime/westend/src/xcm_config.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6616 libc crate update
  Cargo.lock
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6617 Bump parity-db
  Cargo.lock
  node/service/Cargo.toml
  node/subsystem-util/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#6605 Backport `HypotheticalFrontier` into the feature branch
  node/core/prospective-parachains/src/fragment_tree.rs
  node/core/prospective-parachains/src/lib.rs
  node/network/approval-distribution/src/tests.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-util/src/inclusion_emulator/staging.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6447 Resolve todo about legacy leaf activation
  node/network/statement-distribution/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6622 nix upgrade to 0.26.1
  Cargo.lock
  Cargo.toml
  node/metrics/Cargo.toml
Labels: B0-silent, C1-low, D3-trivial 🧸

#6621 Fix async backing statement distribution tests
  node/network/statement-distribution/src/vstaging/grid.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6633 Metrics: add PoV size and validation code size in `candidate-validation`
  node/core/candidate-validation/src/lib.rs
  node/core/candidate-validation/src/metrics.rs
Labels: A0-please_review, B0-silent, C1-low

#6587 Enable `try-runtime` flag in CI
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤

#6635 Fix XCM transact bench
  xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#6630 clear migrations included in 0.9.37
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A2-insubstantial, A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6521 Remove `HypotheticalDepthRequest` in favor of `HypotheticalFrontierRequest`
  node/core/backing/src/lib.rs
  node/core/backing/src/tests/prospective_parachains.rs
  node/core/prospective-parachains/src/fragment_tree.rs
  node/core/prospective-parachains/src/lib.rs
  node/subsystem-types/src/messages.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6634 Async Backing: Send Statement Distribution "Backed" messages
  node/core/backing/src/lib.rs
  node/core/backing/src/tests/mod.rs
  node/core/backing/src/tests/prospective_parachains.rs
  node/network/statement-distribution/src/lib.rs
  node/subsystem-types/src/messages.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, A0-pleasereview

#6552 Co reducing fast-unstake bench time and more
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/try_runtime.rs
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_fast_unstake.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_fast_unstake.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/pallet_fast_unstake.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#6536 13110 Companion: Add WeightToFee and LengthToFee Runtime API
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, T1-runtime, T2-API, B1-note_worthy

#6619 Storage monitor added to polkadot node
  Cargo.lock
  cli/Cargo.toml
  cli/src/cli.rs
  cli/src/command.rs
  cli/src/error.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6588 Make zombienet tests native friendly
  zombienet_tests/.set_env
  zombienet_tests/README.md
  zombienet_tests/functional/0001-parachains-pvf.zndsl
  zombienet_tests/functional/0003-parachains-garbage-candidate.toml
  zombienet_tests/misc/0001-paritydb.toml
  zombienet_tests/smoke/0001-parachains-smoke-test.toml
  zombienet_tests/smoke/0003-deregister-register-validator-smoke.toml
Labels: A0-please_review, I4-annoyance, B0-silent, C1-low, T4-parachains_engineering

#6615 Companion: Remove `uncles` related code
  Cargo.lock
  runtime/common/src/impls.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6598 Update benchmark's successful origin api
  runtime/common/src/auctions.rs
  runtime/common/src/slots/mod.rs
  xcm/pallet-xcm/src/benchmarking.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6482 Resolve some todos in async backing statement-distribution branch
  node/core/backing/src/lib.rs
  node/network/statement-distribution/src/vstaging/cluster.rs
  node/network/statement-distribution/src/vstaging/groups.rs
  node/network/statement-distribution/src/vstaging/mod.rs
  node/network/statement-distribution/src/vstaging/requests.rs
  node/primitives/src/lib.rs
  runtime/parachains/src/inclusion/mod.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6626 companion for substrate #13237
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/test-runtime/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, A4-companion, C1-low, D3-trivial 🧸

#6641 ignore fast-unstake remote test
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤

#6361 inclusion-emulator: mirror advancement rule check
  node/core/prospective-parachains/src/fragment_tree.rs
  node/subsystem-util/src/inclusion_emulator/staging.rs
  primitives/src/vstaging/mod.rs
  runtime/parachains/src/runtime_api_impl/vstaging.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#6649 prospective-parachains: introduce `backed_in_path_only` flag for advertisements
  node/core/backing/src/lib.rs
  node/core/backing/src/tests/prospective_parachains.rs
  node/core/prospective-parachains/src/fragment_tree.rs
  node/core/prospective-parachains/src/lib.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-util/src/inclusion_emulator/staging.rs
Labels: A0-please_review, B0-silent, D3-trivial 🧸
