Repository paritytech/polkadot, pull requests merged in 2023-06, with the labels that each got.

#7318 rococo-runtime: use mmr-specific Hash
  runtime/rococo/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7312 Serialize/Deserialize trait implemented in no-std for numerous types
  Cargo.lock
  parachain/Cargo.toml
  parachain/src/primitives.rs
  primitives/Cargo.toml
  primitives/src/v4/executor_params.rs
  primitives/src/v4/mod.rs
  primitives/src/vstaging/mod.rs
  runtime/common/Cargo.toml
  runtime/common/src/claims.rs
  runtime/parachains/Cargo.toml
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/paras/mod.rs
  xcm/Cargo.toml
  xcm/src/v3/junction.rs
  xcm/src/v3/junctions.rs
  xcm/src/v3/multilocation.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7321 XCM: Utility struct for AccountId conversion
  xcm/xcm-builder/src/location_conversion.rs
  xcm/xcm-builder/src/pay.rs
Labels: A0-please_review, B0-silent, C1-low, D2-notlive 💤, T1-runtime

#7320 Fix XCM benchmark template
  runtime/kusama/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  runtime/kusama/src/xcm_config.rs
  runtime/rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  xcm/pallet-xcm-benchmarks/template.hbs
Labels: A3-in_progress, B0-silent, C1-low, D3-trivial 🧸

#7246 PVF: Instantiate wasm in pre-checking
  Cargo.lock
  node/core/candidate-validation/src/lib.rs
  node/core/pvf/common/Cargo.toml
  node/core/pvf/common/src/error.rs
  node/core/pvf/common/src/executor_intf.rs
  node/core/pvf/common/src/prepare.rs
  node/core/pvf/common/src/pvf.rs
  node/core/pvf/execute-worker/Cargo.toml
  node/core/pvf/execute-worker/src/executor_intf.rs
  node/core/pvf/execute-worker/src/lib.rs
  node/core/pvf/prepare-worker/src/lib.rs
  node/core/pvf/src/host.rs
  node/core/pvf/src/lib.rs
  node/core/pvf/tests/it/main.rs
  roadmap/implementers-guide/src/glossary.md
  roadmap/implementers-guide/src/pvf-prechecking.md
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T4-parachains_engineering

#7287 Renaming Parathread Mentions
  node/core/provisioner/src/lib.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/statement-distribution/src/vstaging/mod.rs
  primitives/src/v4/mod.rs
  roadmap/implementers-guide/src/SUMMARY.md
  roadmap/implementers-guide/src/glossary.md
  roadmap/implementers-guide/src/node/utility/provisioner.md
  roadmap/implementers-guide/src/pvf-prechecking.md
  roadmap/implementers-guide/src/runtime-api/availability-cores.md
  roadmap/implementers-guide/src/runtime/README.md
  roadmap/implementers-guide/src/runtime/configuration.md
  roadmap/implementers-guide/src/runtime/disputes.md
  roadmap/implementers-guide/src/runtime/dmp.md
  roadmap/implementers-guide/src/runtime/hrmp.md
  roadmap/implementers-guide/src/runtime/inclusion.md
  roadmap/implementers-guide/src/runtime/initializer.md
  roadmap/implementers-guide/src/runtime/paras.md
  roadmap/implementers-guide/src/runtime/scheduler.md
  roadmap/implementers-guide/src/runtime/shared.md
  roadmap/implementers-guide/src/types/candidate.md
  roadmap/implementers-guide/src/types/runtime.md
  roadmap/parachains.md
  runtime/common/src/assigned_slots.rs
  runtime/common/src/integration_tests.rs
  runtime/common/src/mock.rs
  runtime/common/src/paras_registrar.rs
  runtime/common/src/paras_sudo_wrapper.rs
  runtime/common/src/slots/mod.rs
  runtime/common/src/traits.rs
  runtime/parachains/src/configuration.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/inclusion/mod.rs
  runtime/parachains/src/lib.rs
  runtime/parachains/src/paras/mod.rs
  runtime/parachains/src/scheduler.rs
  runtime/parachains/src/scheduler/tests.rs
  runtime/polkadot/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7327 PayOverXcm: DescendOrigin before UnpaidExecution
  xcm/xcm-builder/src/pay.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7245 Implement AliasOrigin processing in XCVM
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  runtime/kusama/src/xcm_config.rs
  runtime/polkadot/src/xcm_config.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  runtime/rococo/src/xcm_config.rs
  runtime/test-runtime/src/xcm_config.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  runtime/westend/src/xcm_config.rs
  xcm/pallet-xcm-benchmarks/Cargo.toml
  xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
  xcm/pallet-xcm-benchmarks/src/generic/mock.rs
  xcm/pallet-xcm-benchmarks/src/generic/mod.rs
  xcm/pallet-xcm/src/mock.rs
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/origin_aliases.rs
  xcm/xcm-builder/src/tests/aliases.rs
  xcm/xcm-builder/src/tests/mock.rs
  xcm/xcm-builder/src/tests/mod.rs
  xcm/xcm-builder/tests/mock/mod.rs
  xcm/xcm-executor/src/config.rs
  xcm/xcm-executor/src/lib.rs
  xcm/xcm-simulator/example/src/parachain.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
  xcm/xcm-simulator/fuzzer/src/parachain.rs
  xcm/xcm-simulator/fuzzer/src/relay_chain.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, T1-runtime, B1-note_worthy

#6811 dispute-coordinator: past session dispute slashing
  node/core/dispute-coordinator/src/initialized.rs
  node/core/dispute-coordinator/src/scraping/mod.rs
  node/core/dispute-coordinator/src/scraping/tests.rs
  node/core/dispute-coordinator/src/tests.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/runtime/mod.rs
  primitives/src/vstaging/slashing.rs
  runtime/parachains/src/disputes/slashing.rs
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/zombienet.yml
  zombienet_tests/functional/0004-parachains-disputes-past-session.toml
  zombienet_tests/functional/0004-parachains-disputes-past-session.zndsl
Labels: B0-silent, C1-low, D3-trivial 🧸, T5-parachains_protocol, T0-node

#7333 Fix feature
  xcm/Cargo.toml
Labels: A2-insubstantial, A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7317 approval-distribution: Add approvals/assignments spans on all paths
  node/jaeger/src/spans.rs
  node/network/approval-distribution/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, T4-parachains_engineering

#7340 Fix migrations
  runtime/parachains/src/configuration/migration/v5.rs
  runtime/parachains/src/configuration/migration/v6.rs
  runtime/parachains/src/configuration/migration_ump.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, E0-runtime_migration, T1-runtime, B1-note_worthy

#7335 metrics: Increase the resolution of histogram metrics
  node/network/approval-distribution/src/metrics.rs
  node/overseer/src/metrics.rs
Labels: A0-please_review, B0-silent, C1-low, T4-parachains_engineering

#7339 para scheduler: fix division
  runtime/parachains/src/scheduler.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T1-runtime

#7347 fix nightly warnings
  node/service/src/lib.rs
  runtime/common/src/paras_registrar.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7358 sync master with 0.9.43
  Cargo.lock
  Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: B0-silent, C1-low, D3-trivial 🧸, A6-backport, T8-release

#7137 Unify code paths of create_inherent and enter
  node/metrics/src/runtime/parachain.rs
  primitives/src/v5/metrics.rs
  roadmap/implementers-guide/src/runtime/parainherent.md
  runtime/kusama/src/weights/runtime_parachains_paras_inherent.rs
  runtime/parachains/src/disputes.rs
  runtime/parachains/src/disputes/tests.rs
  runtime/parachains/src/inclusion/mod.rs
  runtime/parachains/src/inclusion/tests.rs
  runtime/parachains/src/metrics.rs
  runtime/parachains/src/paras_inherent/mod.rs
  runtime/parachains/src/paras_inherent/tests.rs
  runtime/polkadot/src/weights/runtime_parachains_paras_inherent.rs
  runtime/westend/src/weights/runtime_parachains_paras_inherent.rs
Labels: A0-please_review, B0-silent, C1-low, D5-nicetohaveaudit ⚠️

#7360 Patch CI for split out worker binaries
  scripts/ci/dockerfiles/polkadot_injected_debug.Dockerfile
  scripts/ci/gitlab/pipeline/build.yml
Labels: A0-please_review, B0-silent

#7365 Hotfix for #7360
  scripts/ci/gitlab/pipeline/build.yml
Labels: A0-please_review, B0-silent

#7368 Metrics: provisioner bitfields histogram bucket adjustment
  node/core/provisioner/src/metrics.rs
Labels: A0-please_review, B0-silent, C1-low

#7309 [frame/im-online] remove network state from heartbeats
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/kusama/src/weights/pallet_im_online.rs
  runtime/polkadot/src/lib.rs
  runtime/polkadot/src/weights/pallet_im_online.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/weights/pallet_im_online.rs
  runtime/westend/src/lib.rs
  runtime/westend/src/weights/pallet_im_online.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, T1-runtime, B1-note_worthy

#7214 Delay reputation updates
  Cargo.lock
  node/network/approval-distribution/Cargo.toml
  node/network/approval-distribution/src/lib.rs
  node/network/approval-distribution/src/tests.rs
  node/network/bitfield-distribution/Cargo.toml
  node/network/bitfield-distribution/src/lib.rs
  node/network/bitfield-distribution/src/tests.rs
  node/network/bridge/src/network.rs
  node/network/bridge/src/rx/mod.rs
  node/network/bridge/src/rx/tests.rs
  node/network/bridge/src/tx/mod.rs
  node/network/bridge/src/tx/tests.rs
  node/network/bridge/src/validator_discovery.rs
  node/network/collator-protocol/src/collator_side/mod.rs
  node/network/collator-protocol/src/collator_side/tests.rs
  node/network/collator-protocol/src/lib.rs
  node/network/collator-protocol/src/validator_side/mod.rs
  node/network/collator-protocol/src/validator_side/tests.rs
  node/network/protocol/src/reputation.rs
  node/network/protocol/src/request_response/incoming/mod.rs
  node/network/statement-distribution/Cargo.toml
  node/network/statement-distribution/src/lib.rs
  node/network/statement-distribution/src/tests.rs
  node/overseer/src/tests.rs
  node/subsystem-types/src/messages.rs
  node/subsystem-util/src/lib.rs
  node/subsystem-util/src/reputation.rs
Labels: B0-silent, C1-low, T4-parachains_engineering

#7376 [XCM] Make NetworkId and Junction versioned
  xcm/src/lib.rs
  xcm/src/v2/mod.rs
  xcm/src/v3/junction.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7375 Wait peers to connect before doing anything else
  node/network/bridge/src/rx/tests.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T4-parachains_engineering

#7386 docs: update references to NetworkConfiguration::extra_sets
  node/network/bridge/src/lib.rs
  node/network/bridge/src/rx/mod.rs
  node/network/bridge/src/tx/mod.rs
Labels: A2-insubstantial, B0-silent, C1-low

#7288 Companion for Soft deprecate GenesisConfig
  Cargo.lock
  node/service/src/chain_spec.rs
  node/test/service/src/chain_spec.rs
  xcm/pallet-xcm-benchmarks/src/fungible/mock.rs
  xcm/pallet-xcm-benchmarks/src/generic/mock.rs
Labels: A3-in_progress, B0-silent, A4-companion, C1-low, D3-trivial 🧸

#7356 Runtime: Kusama gets Society v2
  Cargo.lock
  parachain/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/kusama/src/past_payouts.rs
  runtime/kusama/src/weights/mod.rs
  runtime/kusama/src/weights/pallet_society.rs
  runtime/kusama/src/xcm_config.rs
  runtime/rococo/src/lib.rs
  runtime/rococo/src/xcm_config.rs
  xcm/Cargo.toml
  xcm/pallet-xcm/Cargo.toml
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, E0-runtime_migration, T1-runtime, B1-note_worthy

#7395 Fixed a link issue.
  runtime/common/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-notlive 💤

#7399 fix dependency for "cli" feature in polkadot-cli
  cli/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, T0-node

#7359 Clarification on the use of vstaging
  primitives/src/runtime_api.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7382 Bump `parity-scale-codec` to 3.6.1
  Cargo.lock
  core-primitives/Cargo.toml
  erasure-coding/Cargo.toml
  node/collation-generation/Cargo.toml
  node/core/approval-voting/Cargo.toml
  node/core/av-store/Cargo.toml
  node/core/candidate-validation/Cargo.toml
  node/core/chain-api/Cargo.toml
  node/core/chain-selection/Cargo.toml
  node/core/dispute-coordinator/Cargo.toml
  node/core/pvf/Cargo.toml
  node/core/pvf/common/Cargo.toml
  node/core/pvf/execute-worker/Cargo.toml
  node/core/pvf/prepare-worker/Cargo.toml
  node/jaeger/Cargo.toml
  node/metrics/Cargo.toml
  node/network/availability-distribution/Cargo.toml
  node/network/availability-recovery/Cargo.toml
  node/network/bridge/Cargo.toml
  node/network/collator-protocol/Cargo.toml
  node/network/dispute-distribution/Cargo.toml
  node/network/protocol/Cargo.toml
  node/network/statement-distribution/Cargo.toml
  node/primitives/Cargo.toml
  node/subsystem-util/Cargo.toml
  node/test/client/Cargo.toml
  node/zombienet-backchannel/Cargo.toml
  parachain/Cargo.toml
  parachain/test-parachains/Cargo.toml
  parachain/test-parachains/adder/Cargo.toml
  parachain/test-parachains/adder/collator/Cargo.toml
  parachain/test-parachains/undying/Cargo.toml
  parachain/test-parachains/undying/collator/Cargo.toml
  primitives/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/slot_range_helper/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/metrics/Cargo.toml
  runtime/parachains/Cargo.toml
  runtime/polkadot/Cargo.toml
  runtime/rococo/Cargo.toml
  runtime/test-runtime/Cargo.toml
  runtime/westend/Cargo.toml
  statement-table/Cargo.toml
  utils/staking-miner/Cargo.toml
  xcm/Cargo.toml
  xcm/pallet-xcm-benchmarks/Cargo.toml
  xcm/pallet-xcm/Cargo.toml
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-executor/Cargo.toml
  xcm/xcm-simulator/Cargo.toml
  xcm/xcm-simulator/example/Cargo.toml
  xcm/xcm-simulator/fuzzer/Cargo.toml
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7409 availability recovery: measure re-encoding time
  node/network/availability-recovery/src/lib.rs
  node/network/availability-recovery/src/metrics.rs
Labels: A0-please_review, B0-silent, C1-low

#7389 Clear Existing HRMP Channel Request When Force Opening
  runtime/kusama/src/weights/runtime_parachains_hrmp.rs
  runtime/parachains/src/hrmp.rs
  runtime/parachains/src/hrmp/benchmarking.rs
  runtime/parachains/src/hrmp/tests.rs
  runtime/polkadot/src/weights/runtime_parachains_hrmp.rs
  runtime/rococo/src/weights/runtime_parachains_hrmp.rs
  runtime/westend/src/weights/runtime_parachains_hrmp.rs
Labels: A0-please_review, C1-low, D3-trivial 🧸, T1-runtime, B1-note_worthy

#7398 fixed one member of two teams prs counting individually
  .github/pr-custom-review.yml
Labels: B0-silent

#7420 Disable flaky test
  node/network/bitfield-distribution/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low, D2-notlive 💤

#7404 Warn if participated in the losing side of a dispute
  node/core/dispute-coordinator/src/initialized.rs
  zombienet_tests/functional/0002-parachains-disputes.zndsl
  zombienet_tests/functional/0003-parachains-garbage-candidate.zndsl
Labels: A0-please_review, B0-silent, C1-low

#7415 Remove `Unwrappable`
  xcm/src/v3/mod.rs
  xcm/src/v3/traits.rs
  xcm/xcm-executor/src/traits/export.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7387 add pallet_im_online::migration to Unreleased migrations
  runtime/kusama/src/lib.rs
  runtime/parachains/src/configuration/migration_ump.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸, E0-runtime_migration

#7429 Companion for substrate #14464
  Cargo.lock
  primitives/Cargo.toml
  runtime/parachains/Cargo.toml
Labels: A0-please_review, B0-silent, D3-trivial 🧸, E2-dependencies, T0-node

#7433 Co #14318: `pallet-message-queue`: add queue pausing
  Cargo.lock
  runtime/kusama/src/lib.rs
  runtime/parachains/src/mock.rs
  runtime/parachains/src/ump_tests.rs
  runtime/polkadot/src/lib.rs
  runtime/rococo/src/lib.rs
  runtime/westend/src/lib.rs
  xcm/xcm-simulator/example/src/relay_chain.rs
  xcm/xcm-simulator/fuzzer/src/relay_chain.rs
Labels: A0-please_review, B0-silent, A4-companion, C1-low, D3-trivial 🧸

#7165 Introduce Tinkernet multisig XCM configs to Kusama/Rococo through xcm-builder
  Cargo.lock
  runtime/kusama/src/xcm_config.rs
  runtime/rococo/src/xcm_config.rs
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/location_conversion.rs
  xcm/xcm-builder/src/origin_conversion.rs
Labels: A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, T1-runtime, B1-note_worthy

#7434 Companion for Substrate#14474
  Cargo.lock
  Cargo.toml
  cli/src/command.rs
  node/test/client/src/lib.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸

#7446 Revert "Introduce Tinkernet multisig XCM configs to Kusama/Rococo through xcm-builder"
  Cargo.lock
  runtime/kusama/src/xcm_config.rs
  runtime/rococo/src/xcm_config.rs
  xcm/xcm-builder/Cargo.toml
  xcm/xcm-builder/src/lib.rs
  xcm/xcm-builder/src/location_conversion.rs
  xcm/xcm-builder/src/origin_conversion.rs
Labels: A0-please_review, B0-silent, C1-low, D3-trivial 🧸
